# Banking sector：Forecast-to-Policy A0--A9 最优策略消融实验（方案二：手动日期 + pred.csv 修正版）

本 notebook 用于从 `D:/paper/onging/ablation` 中读取 `A0--A9_seed*_pred.csv`，自动把 `0,1,...,14` 列映射为 `bankclose.csv` 的 15 只股票代码，并生成和 Healthcare 组一致的 `Best policy` 表格。

In [1]:
# ===============================
# 0. Basic imports and global paths
# ===============================

import os
import random
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ==============================================================
# FinRL 0.3.4 compatibility imports
# ==============================================================
try:
    from finrl.preprocessing.preprocessors import FeatureEngineer
    print("FeatureEngineer import: finrl.preprocessing.preprocessors")
except Exception as e:
    raise ImportError(
        "当前环境无法导入 finrl.preprocessing.preprocessors.FeatureEngineer。\n"
        "请确认 Jupyter kernel 是包含 finrl==0.3.4 的环境。"
    ) from e

try:
    from finrl.preprocessing.preprocessors import data_split as _finrl_data_split
    print("data_split import: finrl.preprocessing.preprocessors")
except Exception:
    _finrl_data_split = None
    print("data_split import: custom fallback data_split")

try:
    from finrl.model.models import DRLAgent
    print("DRLAgent import: finrl.model.models")
except Exception as e:
    raise ImportError(
        "当前环境无法导入 finrl.model.models.DRLAgent。\n"
        "这通常说明 Jupyter kernel 不是你的 FinRL 环境，或 FinRL 安装不完整。"
    ) from e

# Gym / Stable-Baselines3 imports
import gym
from gym import spaces
from gym.utils import seeding
from stable_baselines3.common.vec_env import DummyVecEnv


def _first_existing_path(candidates, description):
    """Return the first existing path; if none exists, return the first candidate and print warning."""
    candidates = [Path(p) for p in candidates]
    for p in candidates:
        if p.exists():
            print(f"[OK] {description}: {p}")
            return p
    print(f"[WARN] 未找到 {description}，先使用默认路径: {candidates[0]}")
    return candidates[0]

# -------------------------------
# Project paths
# -------------------------------
PROJECT_ROOT = Path(r"D:/paper/onging")

# 关键修正：预测消融结果目录，不再读取 D:/paper/onging/ablation
PRED_ABLATION_DIR = PROJECT_ROOT / "ablation"

# 输出目录放在 ablation 下，避免覆盖 bank 组
GENERATED_FINRL_DIR = PRED_ABLATION_DIR / "finrl_csv_bank_best_policy"
RL_ABLATION_DIR = PRED_ABLATION_DIR / "rl_bank_best_policy"

PRED_ABLATION_DIR.mkdir(parents=True, exist_ok=True)
GENERATED_FINRL_DIR.mkdir(parents=True, exist_ok=True)
RL_ABLATION_DIR.mkdir(parents=True, exist_ok=True)

# Banking sector 的原始 FinRL 长表数据（按存在顺序自动选择）
BASE_FULL_MGT_CSV = _first_existing_path(
    [
        PROJECT_ROOT / "data" / "graph" / "banktrademergeGNNtr20241231.CSV",
        PROJECT_ROOT / "data" / "graph" / "banktrademergeGNNtr20241231.csv",
        PROJECT_ROOT / "data" / "graph" / "mergebanktrade20241231.csv",
        PROJECT_ROOT / "data" / "graph" / "banktrade20241231.csv",
        PROJECT_ROOT / "data" / "bank" / "banktrade20241231.csv",
    ],
    "BASE_FULL_MGT_CSV"
)

# close matrix 仅在没有 *_pred_raw.csv、需要从归一化 *_pred.csv 反归一化时使用
BANK_CLOSE_CSV = _first_existing_path(
    [
        PROJECT_ROOT / "data" / "bank" / "bankclose.csv",
        PROJECT_ROOT / "data" / "graph" / "bankclose.csv",
        PROJECT_ROOT / "data" / "bankclose.csv",
    ],
    "BANK_CLOSE_CSV"
)

# 与 bank 组 A0--A9 编号保持一致
ALL_VARIANTS = [
    "A0_Full_MGT",
    "A1_Transformer_only",
    "A2_MGNN_only",
    "A3_SH_only",
    "A4_QA_only",
    "A5_KD_only",
    "A6_SH_QA",
    "A7_SH_KD",
    "A8_QA_KD",
    "A9_Fixed_fusion",
]

DISPLAY_NAMES = {
    "A0_Full_MGT": "A0 Full MGT",
    "A1_Transformer_only": "A1 Transformer-only",
    "A2_MGNN_only": "A2 MGNN-only",
    "A3_SH_only": "A3 SH-only",
    "A4_QA_only": "A4 QA-only",
    "A5_KD_only": "A5 KD-only",
    "A6_SH_QA": "A6 SH+QA",
    "A7_SH_KD": "A7 SH+KD",
    "A8_QA_KD": "A8 QA+KD",
    "A9_Fixed_fusion": "A9 Fixed-fusion",
}

print("\n========== PATH CHECK ==========")
print("PRED_ABLATION_DIR =", PRED_ABLATION_DIR, "| exists=", PRED_ABLATION_DIR.exists())
print("GENERATED_FINRL_DIR =", GENERATED_FINRL_DIR)
print("RL_ABLATION_DIR =", RL_ABLATION_DIR)
print("BASE_FULL_MGT_CSV =", BASE_FULL_MGT_CSV, "| exists=", BASE_FULL_MGT_CSV.exists())
print("BANK_CLOSE_CSV =", BANK_CLOSE_CSV, "| exists=", BANK_CLOSE_CSV.exists())

FeatureEngineer import: finrl.preprocessing.preprocessors
data_split import: custom fallback data_split
DRLAgent import: finrl.model.models
[OK] BASE_FULL_MGT_CSV: D:\paper\onging\data\graph\banktrademergeGNNtr20241231.CSV
[OK] BANK_CLOSE_CSV: D:\paper\onging\data\bank\bankclose.csv

========== PATH CHECK ==========
PRED_ABLATION_DIR = D:\paper\onging\ablation | exists= True
GENERATED_FINRL_DIR = D:\paper\onging\ablation\finrl_csv_bank_best_policy
RL_ABLATION_DIR = D:\paper\onging\ablation\rl_bank_best_policy
BASE_FULL_MGT_CSV = D:\paper\onging\data\graph\banktrademergeGNNtr20241231.CSV | exists= True
BANK_CLOSE_CSV = D:\paper\onging\data\bank\bankclose.csv | exists= True

## 1. 与预测消融 notebook 对应的银行组输入文件配置

下面的 `RL_ABLATION_INPUTS` 与 A0--A9 消融编号一一对应。

程序会优先从银行组预测消融输出目录读取并生成 FinRL 长表 CSV，例如：

```text
D:/paper/onging/ablation/finrl_csv_bank_best_policy/banktrademergeGNNtr20241231_A0_Full_MGT.CSV
D:/paper/onging/ablation/finrl_csv_bank_best_policy/banktrademergeGNNtr20241231_A1_Transformer_only.CSV
...
```

如果某个版本没有生成，程序会自动跳过；如果 A0 没生成，则回退到原始银行组 Full MGT 文件。

In [2]:
# ===============================
# 1. Ablation input mapping
# ===============================

# 每个版本对应的自动生成 FinRL 长表 CSV。
# 这些 CSV 会由 D:/paper/onging/ablation/A*_seed*_pred_raw.csv 自动生成。
def generated_finrl_csv_path(tag: str) -> Path:
    return GENERATED_FINRL_DIR / f"banktrademergeGNNtr20241231_{tag}.CSV"


def resolve_variant_csv(tag: str) -> Path:
    """优先使用自动生成的 A0-A9 长表 CSV；若 A0 没有生成，则回退到原始 Full MGT 文件。"""
    gen_path = generated_finrl_csv_path(tag)
    if gen_path.exists():
        return gen_path
    if tag == "A0_Full_MGT" and BASE_FULL_MGT_CSV.exists():
        return BASE_FULL_MGT_CSV
    return gen_path


RL_ABLATION_INPUTS = {tag: resolve_variant_csv(tag) for tag in ALL_VARIANTS}

print("Initial ablation CSV mapping:")
for tag, path in RL_ABLATION_INPUTS.items():
    print(f"{tag:28s} -> {path} | exists={Path(path).exists()}")

Initial ablation CSV mapping:
A0_Full_MGT                  -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A0_Full_MGT.CSV | exists=True
A1_Transformer_only          -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A1_Transformer_only.CSV | exists=True
A2_MGNN_only                 -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A2_MGNN_only.CSV | exists=True
A3_SH_only                   -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A3_SH_only.CSV | exists=True
A4_QA_only                   -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A4_QA_only.CSV | exists=True
A5_KD_only                   -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A5_KD_only.CSV | exists=True
A6_SH_QA                     -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A6_SH_QA.CSV | exists=True
A7_SH_KD                     -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A7_SH_KD.CSV | exists=True
A8_QA_KD                     -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A8_QA_KD.CSV | exists=True
A9_Fixed_fusion              -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV | exists=True

## 2. 实验设置

本 notebook 用于生成与 Healthcare innovation sector 表格一致的 Bank sector forecast-to-policy 消融实验结果：

- A0--A9 每个预测状态变体；
- PPO、A2C、SAC、TD3、DDPG 五个 downstream RL policy；
- 每个变体按 Final account value 选择 best policy；
- 输出 `Method, Best policy, CR, AR, SR, MDD, Calmar, Sortino, Final value` 的论文表格。

默认 `SEEDS = [1]`，与当前 Healthcare 表格保持一致；如需多随机种子，可改成 `[1, 2, 3]`。

In [3]:
# ===============================
# 2. Experiment settings
# ===============================

# 训练开始日期固定；训练结束、交易开始和交易结束默认由 pred_raw 文件自动识别。
TRAIN_START = "2018-01-02"
TRAIN_END = "2021-12-31"   # 方案二：手动设置。预测文件是 2022 测试集时，训练截止到 2021 年末。
TRADE_START = "2022-01-04" # 方案二：手动设置预测/交易开始日期。
TRADE_END = "2022-12-30"   # 方案二：手动设置预测/交易结束日期。
AUTO_DETECT_TRADE_RANGE_FROM_PRED = False

INITIAL_AMOUNT = 1_000_000
TRANSACTION_COST_PCT = 0.0001
REWARD_SCALING = 1e-1
LOOKBACK = 252

TECH_INDICATOR_LIST = ["macd", "rsi_30", "cci_30", "dx_30"]

# 与 bank 组保持一致的输出：默认先跑客观基准，并可选择是否跑五个 RL agents。
RUN_OBJECTIVE_BASELINES = True
RUN_RL_AGENTS = True   # 如果只想快速生成和 bank 当前汇总类似的基准表，可改成 False
AGENTS_FOR_ABLATION = ["a2c", "ppo", "sac", "td3", "ddpg"]

# 调试阶段用 [1]；论文最终如果需要多次重复，可改成 [1, 2, 3]
SEEDS = [1]

# 自动从 D:/paper/onging/ablation/A*_seed*_pred_raw.csv 生成 A0-A9 FinRL 长表 CSV
AUTO_GENERATE_VARIANT_FINRL_CSVS = True

# 关键修正：优先使用反归一化后的 pred_raw 文件；若不存在，再回退到 pred.csv 并用 close matrix 反归一化。
PRED_FILE_KIND = "pred"  # 方案二：当前 bank 组只有 *_pred.csv，无 date 列；强制读取 pred 并反归一化。

# 多个预测 seed 如何合并："mean" 表示对 seed1/2/3 预测取平均；也可以改成 1、2、3。
PRED_SEED_MODE = "mean"

VARIANTS_TO_RUN = ALL_VARIANTS.copy()

# 训练步数。调试时可以适当降低；正式实验建议保持和 bank 组一致。
TOTAL_TIMESTEPS = {
    "a2c": 40000,
    "ppo": 40000,
    "sac": 60000,
    "td3": 30000,
    "ddpg": 50000,
}

MODEL_PARAMS = {
    "a2c": {"n_steps": 10, "ent_coef": 0.005, "learning_rate": 0.0004},
    "ppo": {"n_steps": 2048, "ent_coef": 0.005, "learning_rate": 0.001, "batch_size": 128},
    "sac": {"batch_size": 128, "buffer_size": 1_000_000, "learning_rate": 0.0001,
            "learning_starts": 100, "ent_coef": "auto_0.1"},
    "td3": {"batch_size": 100, "buffer_size": 1_000_000, "learning_rate": 0.001},
    "ddpg": {},
}


def set_global_seed(seed: int = 1):
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)


set_global_seed(1)

print("RUN_OBJECTIVE_BASELINES =", RUN_OBJECTIVE_BASELINES)
print("RUN_RL_AGENTS =", RUN_RL_AGENTS)
print("PRED_FILE_KIND =", PRED_FILE_KIND)
print("PRED_SEED_MODE =", PRED_SEED_MODE)
print("AUTO_DETECT_TRADE_RANGE_FROM_PRED =", AUTO_DETECT_TRADE_RANGE_FROM_PRED)
print("TRAIN_END =", TRAIN_END)
print("TRADE_START =", TRADE_START)
print("TRADE_END =", TRADE_END)

RUN_OBJECTIVE_BASELINES = True
RUN_RL_AGENTS = True
PRED_FILE_KIND = pred
PRED_SEED_MODE = mean
AUTO_DETECT_TRADE_RANGE_FROM_PRED = False
TRAIN_END = 2021-12-31
TRADE_START = 2022-01-04
TRADE_END = 2022-12-30

## 3. 数据读取与协方差状态构造

这部分替代原 notebook 中重复的 `FeatureEngineer` 和重复的 covariance 代码。

修正点：

1. 不再重复调用 `fe.preprocess_data(df)`；
2. 如果技术指标已经存在，则不重复生成；
3. 每次重新计算 `cov_list`，避免从 CSV 读取后变成字符串；
4. 训练集和交易集都会重新设置整数 day index，保证环境中的 `df.loc[self.day, :]` 正常工作。

In [4]:
# ===============================
# 3. Data preprocessing
# ===============================

def _reset_day_index(df: pd.DataFrame) -> pd.DataFrame:
    df = df.sort_values(["date", "tic"]).copy()
    df.index = pd.factorize(df["date"])[0]
    return df


def _check_required_columns(df: pd.DataFrame, csv_path: Path):
    required = {"date", "tic", "close"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"{csv_path} 缺少必要字段: {missing}")


def load_finrl_data(csv_path, lookback=252, tech_indicator_list=None):
    """
    读取 FinRL 长表 CSV，并生成技术指标和 rolling covariance state。

    输入 CSV 至少应包含:
    date, tic, open, high, low, close, volume
    """
    csv_path = Path(csv_path)
    if not csv_path.exists():
        raise FileNotFoundError(f"找不到数据文件: {csv_path}")

    df = pd.read_csv(csv_path)
    _check_required_columns(df, csv_path)

    df["date"] = pd.to_datetime(df["date"]).dt.strftime("%Y-%m-%d")
    df["tic"] = df["tic"].astype(str)
    df = df.sort_values(["date", "tic"]).reset_index(drop=True)

    if tech_indicator_list is None:
        tech_indicator_list = TECH_INDICATOR_LIST

    missing_tech = [c for c in tech_indicator_list if c not in df.columns]
    if missing_tech:
        print(f"[{csv_path.name}] Missing technical indicators {missing_tech}; running FeatureEngineer...")
        fe = FeatureEngineer(
            use_technical_indicator=True,
            use_turbulence=False,
            user_defined_feature=False
        )
        df = fe.preprocess_data(df)
        df["date"] = pd.to_datetime(df["date"]).dt.strftime("%Y-%m-%d")
        df["tic"] = df["tic"].astype(str)
    else:
        print(f"[{csv_path.name}] Technical indicators already exist; skip FeatureEngineer.")

    # 避免从 CSV 读取旧 cov_list/return_list 后变成字符串
    for col in ["cov_list", "return_list"]:
        if col in df.columns:
            df = df.drop(columns=[col])

    df = df.sort_values(["date", "tic"], ignore_index=True)
    df.index = pd.factorize(df["date"])[0]

    unique_dates = df["date"].unique()
    if len(unique_dates) <= lookback:
        raise ValueError(f"数据交易日数量 {len(unique_dates)} 小于等于 lookback={lookback}，无法构造协方差状态。")

    cov_list = []
    return_list = []

    for i in range(lookback, len(unique_dates)):
        data_lookback = df.loc[i - lookback:i, :]
        price_lookback = data_lookback.pivot_table(index="date", columns="tic", values="close")
        return_lookback = price_lookback.pct_change().dropna()

        return_list.append(return_lookback)
        cov_list.append(return_lookback.cov().values)

    df_cov = pd.DataFrame({
        "date": unique_dates[lookback:],
        "cov_list": cov_list,
        "return_list": return_list
    })

    df = df.reset_index(drop=True)
    df = df.merge(df_cov, on="date", how="inner")
    df = df.sort_values(["date", "tic"]).reset_index(drop=True)

    return df


def _slice_by_date_inclusive(df: pd.DataFrame, start: str, end: str) -> pd.DataFrame:
    if start is None or end is None:
        raise ValueError("TRAIN/TRADE 日期尚未设置。请先运行自动读取 pred_raw 的 cell。")
    out = df[(df["date"] >= start) & (df["date"] <= end)].copy()
    out = out.sort_values(["date", "tic"]).copy()
    out.index = pd.factorize(out["date"])[0]
    return out


def make_train_trade(df: pd.DataFrame):
    """使用显式日期切片，避免 FinRL data_split 的开闭区间差异导致少一天。"""
    train = _slice_by_date_inclusive(df, TRAIN_START, TRAIN_END)
    trade = _slice_by_date_inclusive(df, TRADE_START, TRADE_END)

    train = _reset_day_index(train)
    trade = _reset_day_index(trade)

    print(f"train dates: {train['date'].min()} -> {train['date'].max()} | rows={len(train)}")
    print(f"trade dates: {trade['date'].min()} -> {trade['date'].max()} | rows={len(trade)}")

    return train, trade

## 3.1 从 `D:/paper/onging/ablation` 自动读取 A0--A9 预测结果

本单元是本次修正的核心。

原代码读取不到数据的主要原因通常是：

1. 读取目录仍然是 `D:/paper/onging/ablation`，而你的 banking sector 预测结果实际在 `D:/paper/onging/ablation`；
2. 原代码查找 `*_pred.csv`，但你的可用于回测的真实价格预测文件是 `*_pred_raw.csv`；
3. 预测文件中第一列是 `date`，原代码直接 `astype(float)` 会把日期字符串也转成数值，导致报错；
4. 原代码手动指定 2023--2024 交易区间，而当前预测文件可能是 2022 测试集，导致行数和日期数量不一致。

下面代码会自动处理这些问题。

In [5]:
# ===============================
# 3.1 Auto-generate FinRL CSVs from prediction ablation outputs
# ===============================

from sklearn.preprocessing import MinMaxScaler


def load_close_matrix_and_scaler(required_columns=None):
    """读取 close 矩阵并复现 MinMaxScaler(feature_range=(-1, 1)).

    方案二关键修正：
    1) 如果 pred.csv 的列名是 0,1,...,14，不再把它们当作股票代码；
    2) close matrix 的列顺序作为真实股票顺序；
    3) 当 required_columns 是数字序列时，自动按 close matrix 顺序映射。
    """
    if BANK_CLOSE_CSV.exists():
        close_raw = pd.read_csv(BANK_CLOSE_CSV)
        source = BANK_CLOSE_CSV

        # 兼容两种格式：
        # A. 第一列为 date/index，后面是 ticker；
        # B. 已经是纯数值矩阵，列名是 ticker。
        possible_date_cols = [c for c in close_raw.columns if str(c).strip().lower() in {"date", "datetime", "trade_date", "time"}]
        unnamed_cols = [c for c in close_raw.columns if str(c).lower().startswith("unnamed")]

        if possible_date_cols:
            date_col = possible_date_cols[0]
            close = close_raw.copy()
            close[date_col] = pd.to_datetime(close[date_col]).dt.strftime("%Y-%m-%d")
            close = close.set_index(date_col)
        elif unnamed_cols:
            idx_col = unnamed_cols[0]
            close = close_raw.copy()
            close[idx_col] = pd.to_datetime(close[idx_col], errors="coerce").dt.strftime("%Y-%m-%d")
            close = close.set_index(idx_col)
        else:
            # 默认第一列是日期/索引
            first_col = close_raw.columns[0]
            maybe_date = pd.to_datetime(close_raw[first_col], errors="coerce")
            if maybe_date.notna().mean() > 0.8:
                close = close_raw.copy()
                close[first_col] = maybe_date.dt.strftime("%Y-%m-%d")
                close = close.set_index(first_col)
            else:
                close = pd.read_csv(BANK_CLOSE_CSV, index_col=0)
    else:
        if not BASE_FULL_MGT_CSV.exists():
            raise FileNotFoundError(
                f"既找不到 BANK_CLOSE_CSV: {BANK_CLOSE_CSV}，也找不到 BASE_FULL_MGT_CSV: {BASE_FULL_MGT_CSV}"
            )
        base = pd.read_csv(BASE_FULL_MGT_CSV)
        required = {"date", "tic", "close"}
        missing = required - set(base.columns)
        if missing:
            raise ValueError(f"{BASE_FULL_MGT_CSV} 缺少用于生成 close 矩阵的字段: {missing}")
        base["date"] = pd.to_datetime(base["date"]).dt.strftime("%Y-%m-%d")
        base["tic"] = base["tic"].astype(str)
        close = base.pivot_table(index="date", columns="tic", values="close", aggfunc="last")
        source = BASE_FULL_MGT_CSV
        print(f"[INFO] 未找到 {BANK_CLOSE_CSV.name}，已从 {BASE_FULL_MGT_CSV.name} 自动生成 close matrix。")

    close.index = pd.to_datetime(close.index, errors="coerce").strftime("%Y-%m-%d")
    close.columns = close.columns.astype(str)
    close = close.sort_index()
    close = close.apply(pd.to_numeric, errors="coerce").dropna(how="all").ffill().bfill()

    if required_columns is not None:
        required_columns = [str(c) for c in required_columns]
        # 如果 required_columns 是 0,1,2,... 这种数字列名，说明 pred.csv 没有股票代码列名。
        # 此时不要检查缺失股票代码，而是按 close matrix 的列顺序直接使用。
        is_numeric_position_cols = False
        try:
            ints = [int(c) for c in required_columns]
            is_numeric_position_cols = (sorted(ints) == list(range(len(required_columns))))
        except Exception:
            is_numeric_position_cols = False

        if is_numeric_position_cols:
            if len(required_columns) != close.shape[1]:
                raise ValueError(
                    f"pred.csv 数字列数量与 close matrix 股票数量不一致：pred={len(required_columns)}, close={close.shape[1]}"
                )
            # 不重排，直接使用 close 原有股票顺序。
            pass
        else:
            missing_cols = [c for c in required_columns if c not in close.columns]
            if missing_cols:
                raise ValueError(f"close matrix 缺少预测文件中的股票列: {missing_cols[:10]}")
            close = close[required_columns]

    scaler = MinMaxScaler(feature_range=(-1, 1))
    scaler.fit(close.values)
    print(f"Close matrix source = {source}; shape = {close.shape}")
    return close, scaler

def list_prediction_files():
    """列出 ablation 目录中可用的 A0--A9 预测文件，便于检查命名。"""
    rows = []
    for tag in ALL_VARIANTS:
        raw_files = sorted(PRED_ABLATION_DIR.glob(f"{tag}_seed*_pred_raw.csv"))
        scaled_files = sorted(PRED_ABLATION_DIR.glob(f"{tag}_seed*_pred.csv"))
        true_raw_files = sorted(PRED_ABLATION_DIR.glob(f"{tag}_seed*_true_raw.csv"))
        rows.append({
            "variant": tag,
            "pred_raw_count": len(raw_files),
            "pred_count": len(scaled_files),
            "true_raw_count": len(true_raw_files),
            "pred_raw_files": ", ".join([p.name for p in raw_files[:3]]),
        })
    out = pd.DataFrame(rows)
    display(out)
    return out


prediction_file_check = list_prediction_files()


def _drop_unnamed_columns(df: pd.DataFrame) -> pd.DataFrame:
    unnamed = [c for c in df.columns if str(c).lower().startswith("unnamed")]
    if unnamed:
        df = df.drop(columns=unnamed)
    return df


def _detect_date_column(df: pd.DataFrame):
    for c in df.columns:
        if str(c).strip().lower() in {"date", "datetime", "trade_date", "time"}:
            return c
    return None


def find_prediction_files(tag: str):
    """按图片命名规则查找预测文件。优先 *_pred_raw.csv。"""
    if PRED_FILE_KIND in ["auto", "pred_raw"]:
        raw_files = sorted(PRED_ABLATION_DIR.glob(f"{tag}_seed*_pred_raw.csv"))
        if raw_files:
            return raw_files, "pred_raw"
        if PRED_FILE_KIND == "pred_raw":
            return [], "pred_raw"

    scaled_files = sorted(PRED_ABLATION_DIR.glob(f"{tag}_seed*_pred.csv"))
    return scaled_files, "pred"


def read_single_prediction_file(file_path: Path, file_kind: str):
    """
    读取一个 prediction matrix，返回 wide DataFrame(index=date if available, columns=tickers).

    方案二关键修正：
    - 当前 bank 组只有 *_pred.csv，没有 date 列；
    - pred.csv 的列名常为 0,1,2,...,14；
    - 读取后用 bankclose.csv 的 15 个股票代码替换这些数字列名；
    - 再使用同一个 MinMaxScaler 反归一化到真实价格尺度。
    """
    df = pd.read_csv(file_path)
    df = _drop_unnamed_columns(df)

    date_col = _detect_date_column(df)
    if date_col is not None:
        dates = pd.to_datetime(df[date_col]).dt.strftime("%Y-%m-%d")
        values = df.drop(columns=[date_col]).copy()
    else:
        dates = None
        values = df.copy()

    original_cols = values.columns.astype(str).tolist()
    values = values.apply(pd.to_numeric, errors="coerce")
    if values.isna().any().any():
        bad_cols = values.columns[values.isna().any()].tolist()[:10]
        raise ValueError(f"{file_path.name} 中存在无法转成数值的预测列: {bad_cols}")

    if file_kind == "pred":
        # 归一化预测值需要反归一化。
        # 不要求 pred.csv 的列名一定是股票代码；如果是 0..14，自动按 close matrix 的股票顺序映射。
        close_df, scaler = load_close_matrix_and_scaler(required_columns=original_cols)

        if values.shape[1] != close_df.shape[1]:
            raise ValueError(
                f"{file_path.name} 的列数与 close matrix 不一致："
                f"pred columns={values.shape[1]}, close columns={close_df.shape[1]}"
            )

        real_values = scaler.inverse_transform(values.values)
        values = pd.DataFrame(real_values, columns=close_df.columns.astype(str).tolist())
    else:
        # pred_raw 本身已经是真实价格尺度。
        # 如果列名是 0..14，也按 close matrix 映射成真实股票代码。
        cols = [str(c) for c in original_cols]
        try:
            ints = [int(c) for c in cols]
            is_numeric_position_cols = (sorted(ints) == list(range(len(cols))))
        except Exception:
            is_numeric_position_cols = False
        if is_numeric_position_cols:
            close_df, _ = load_close_matrix_and_scaler(required_columns=cols)
            if values.shape[1] != close_df.shape[1]:
                raise ValueError(
                    f"{file_path.name} 的列数与 close matrix 不一致："
                    f"pred columns={values.shape[1]}, close columns={close_df.shape[1]}"
                )
            values.columns = close_df.columns.astype(str).tolist()
        else:
            values.columns = cols

    if dates is not None:
        values.index = dates
        values.index.name = "date"

    return values

def _select_files_by_seed(files, seed_mode):
    if seed_mode == "mean":
        return files
    seed = int(seed_mode)
    selected = [p for p in files if f"_seed{seed}_" in p.name]
    if not selected:
        raise FileNotFoundError(f"找不到 seed={seed} 对应预测文件。候选文件: {[p.name for p in files]}")
    return selected


def read_prediction_wide(tag: str, seed_mode="mean"):
    """读取某个 A0--A9 版本的预测矩阵。多个 seed 默认取平均。"""
    files, file_kind = find_prediction_files(tag)
    if not files:
        raise FileNotFoundError(
            f"找不到 {tag}_seed*_pred_raw.csv 或 {tag}_seed*_pred.csv。\n"
            f"当前读取目录: {PRED_ABLATION_DIR}\n"
            "请确认文件命名是否类似图片中的 A0_Full_MGT_seed1_pred_raw.csv。"
        )

    files = _select_files_by_seed(files, seed_mode)
    mats = []
    for f in files:
        mat = read_single_prediction_file(f, file_kind=file_kind)
        mats.append(mat)

    # 检查列一致
    columns0 = mats[0].columns.tolist()
    for mat, f in zip(mats, files):
        if mat.columns.tolist() != columns0:
            raise ValueError(f"{tag}: {f.name} 的股票列与第一个 seed 不一致。")

    # 如果文件带 date 列，要求 date 完全一致；如果没有 date，则后续再由 close matrix 推断。
    has_index_dates = mats[0].index.name == "date"
    if has_index_dates:
        index0 = mats[0].index.tolist()
        for mat, f in zip(mats, files):
            if mat.index.tolist() != index0:
                raise ValueError(f"{tag}: {f.name} 的 date 行与第一个 seed 不一致。")
        mean_values = np.mean(np.stack([m.values for m in mats], axis=0), axis=0)
        pred_wide = pd.DataFrame(mean_values, index=mats[0].index, columns=columns0)
        pred_wide.index.name = "date"
    else:
        mean_values = np.mean(np.stack([m.values for m in mats], axis=0), axis=0)
        pred_wide = pd.DataFrame(mean_values, columns=columns0)

    print(f"[READ] {tag}: kind={file_kind}, seed_mode={seed_mode}, files={[p.name for p in files]}")
    print(f"       pred_wide shape={pred_wide.shape}, date_index={pred_wide.index.name == 'date'}")
    return pred_wide, files, file_kind


def prediction_dates_from_close(close_df: pd.DataFrame, n_rows: int, start_date: str, end_date: str):
    dates = pd.Series(close_df.index, name="date")
    mask = (dates >= start_date) & (dates <= end_date)
    selected = dates.loc[mask].tolist()

    if len(selected) != n_rows:
        raise ValueError(
            "预测矩阵行数与指定日期区间不一致。\n"
            f"  pred rows     = {n_rows}\n"
            f"  selected days = {len(selected)}\n"
            f"  date range    = {start_date} ~ {end_date}\n"
            "解决方法：优先使用带 date 列的 *_pred_raw.csv，或手动调整 TRADE_START/TRADE_END。"
        )
    return selected


def _infer_trade_range_from_generated_csvs(generated_paths):
    starts, ends = [], []
    for tag, path in generated_paths.items():
        if not Path(path).exists():
            continue
        # 直接从对应 pred_raw 读取日期更准确
        try:
            pred_wide, _, _ = read_prediction_wide(tag, seed_mode=PRED_SEED_MODE)
            if pred_wide.index.name == "date":
                starts.append(min(pred_wide.index))
                ends.append(max(pred_wide.index))
        except Exception:
            pass
    if not starts:
        return None, None
    return min(starts), max(ends)


def build_variant_finrl_csv_from_pred(tag: str, seed_mode="mean", start_date=None, end_date=None):
    """把 A*_seed*_pred_raw.csv 转成 FinRL 长表 CSV。"""
    pred_wide, used_files, file_kind = read_prediction_wide(tag, seed_mode=seed_mode)

    if pred_wide.index.name != "date":
        # 只有不带 date 列时才需要用 close matrix 和手工日期区间推断
        close_df, _ = load_close_matrix_and_scaler(required_columns=pred_wide.columns.tolist())
        if start_date is None or end_date is None:
            raise ValueError(f"{tag}: 预测文件没有 date 列，必须手动设置 TRADE_START/TRADE_END。")
        dates = prediction_dates_from_close(close_df, pred_wide.shape[0], start_date, end_date)
        pred_wide.index = dates
        pred_wide.index.name = "date"

    pred_wide = pred_wide.copy()
    pred_wide.index = pd.to_datetime(pred_wide.index).strftime("%Y-%m-%d")
    pred_wide.columns = pred_wide.columns.astype(str)

    pred_long = pred_wide.reset_index().melt(id_vars="date", var_name="tic", value_name="pred_close")
    pred_long["tic"] = pred_long["tic"].astype(str)

    if not BASE_FULL_MGT_CSV.exists():
        raise FileNotFoundError(f"找不到原始 FinRL 长表数据: {BASE_FULL_MGT_CSV}")

    base = pd.read_csv(BASE_FULL_MGT_CSV)
    _check_required_columns(base, BASE_FULL_MGT_CSV)
    base["date"] = pd.to_datetime(base["date"]).dt.strftime("%Y-%m-%d")
    base["tic"] = base["tic"].astype(str)

    # ticker 对齐检查
    base_tickers = set(base["tic"].unique())
    pred_tickers = set(pred_wide.columns)
    missing_in_base = sorted(pred_tickers - base_tickers)
    if missing_in_base:
        raise ValueError(
            f"{tag}: 预测文件 ticker 与 FinRL 长表 ticker 不一致。\n"
            f"预测中有但 base 中没有: {missing_in_base[:20]}"
        )

    # 只替换预测区间内的 close，其余日期保留真实 close，用于训练和构造协方差状态。
    merged = base.merge(pred_long, on=["date", "tic"], how="left")
    replace_mask = merged["pred_close"].notna()
    merged.loc[replace_mask, "close"] = merged.loc[replace_mask, "pred_close"]
    merged = merged.drop(columns=["pred_close"])

    out_csv = generated_finrl_csv_path(tag)
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    merged.to_csv(out_csv, index=False)

    print(f"[OK] {tag}: generated {out_csv}")
    print(f"     kind={file_kind}; used files: {[p.name for p in used_files]}")
    print(f"     replaced close rows: {int(replace_mask.sum())}")
    print(f"     prediction date range: {pred_wide.index.min()} -> {pred_wide.index.max()}")
    return out_csv


def auto_generate_all_variant_finrl_csvs():
    generated = {}
    for tag in ALL_VARIANTS:
        try:
            generated[tag] = build_variant_finrl_csv_from_pred(
                tag=tag,
                seed_mode=PRED_SEED_MODE,
                start_date=TRADE_START,
                end_date=TRADE_END,
            )
        except Exception as e:
            print(f"[WARN] {tag}: cannot generate FinRL CSV -> {e}")
    return generated


if AUTO_GENERATE_VARIANT_FINRL_CSVS:
    print("\nStart auto-generating FinRL CSVs from prediction ablation outputs...")
    generated_paths = auto_generate_all_variant_finrl_csvs()
else:
    generated_paths = {}
    print("AUTO_GENERATE_VARIANT_FINRL_CSVS=False; skip auto generation.")

# 日期设置：方案二使用手动日期，避免 pred.csv 无 date 列导致报错。
if AUTO_DETECT_TRADE_RANGE_FROM_PRED:
    inferred_start, inferred_end = _infer_trade_range_from_generated_csvs(generated_paths)
    if inferred_start is not None:
        TRADE_START = inferred_start
        TRADE_END = inferred_end
        if TRAIN_END is None:
            TRAIN_END = (pd.to_datetime(TRADE_START) - pd.Timedelta(days=1)).strftime("%Y-%m-%d")
        print("\n[DATE AUTO-DETECT]")
        print("TRAIN_START =", TRAIN_START)
        print("TRAIN_END   =", TRAIN_END)
        print("TRADE_START =", TRADE_START)
        print("TRADE_END   =", TRADE_END)
    else:
        raise ValueError("无法从预测文件自动识别交易区间。请检查 *_pred_raw.csv 是否包含 date 列。")
else:
    if TRAIN_END is None or TRADE_START is None or TRADE_END is None:
        raise ValueError(
            "AUTO_DETECT_TRADE_RANGE_FROM_PRED=False 时，必须手动设置 "
            "TRAIN_END、TRADE_START、TRADE_END。"
        )

    print("\n[DATE MANUAL SETTING]")
    print("TRAIN_START =", TRAIN_START)
    print("TRAIN_END   =", TRAIN_END)
    print("TRADE_START =", TRADE_START)
    print("TRADE_END   =", TRADE_END)

# 刷新映射：优先使用刚生成的 finrl_csv；A0 如果没生成，则回退原始 BASE_FULL_MGT_CSV
RL_ABLATION_INPUTS = {tag: resolve_variant_csv(tag) for tag in ALL_VARIANTS}

print("\nRefreshed ablation CSV mapping:")
for tag, path in RL_ABLATION_INPUTS.items():
    print(f"{tag:28s} -> {path} | exists={Path(path).exists()}")

,variant,pred_raw_count,pred_count,true_raw_count,pred_raw_files
0,A0_Full_MGT,0,3,0,
1,A1_Transformer_only,0,3,0,
2,A2_MGNN_only,0,3,0,
3,A3_SH_only,0,3,0,
4,A4_QA_only,0,3,0,
5,A5_KD_only,0,3,0,
6,A6_SH_QA,0,3,0,
7,A7_SH_KD,0,3,0,
8,A8_QA_KD,0,3,0,
9,A9_Fixed_fusion,0,3,0,

Start auto-generating FinRL CSVs from prediction ablation outputs...
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[READ] A0_Full_MGT: kind=pred, seed_mode=mean, files=['A0_Full_MGT_seed1_pred.csv', 'A0_Full_MGT_seed2_pred.csv', 'A0_Full_MGT_seed3_pred.csv']
       pred_wide shape=(242, 15), date_index=False
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[OK] A0_Full_MGT: generated D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A0_Full_MGT.CSV
     kind=pred; used files: ['A0_Full_MGT_seed1_pred.csv', 'A0_Full_MGT_seed2_pred.csv', 'A0_Full_MGT_seed3_pred.csv']
     replaced close rows: 3630
     prediction date range: 2022-01-04 -> 2022-12-30
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[READ] A1_Transformer_only: kind=pred, seed_mode=mean, files=['A1_Transformer_only_seed1_pred.csv', 'A1_Transformer_only_seed2_pred.csv', 'A1_Transformer_only_seed3_pred.csv']
       pred_wide shape=(242, 15), date_index=False
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[OK] A1_Transformer_only: generated D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A1_Transformer_only.CSV
     kind=pred; used files: ['A1_Transformer_only_seed1_pred.csv', 'A1_Transformer_only_seed2_pred.csv', 'A1_Transformer_only_seed3_pred.csv']
     replaced close rows: 3630
     prediction date range: 2022-01-04 -> 2022-12-30
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[READ] A2_MGNN_only: kind=pred, seed_mode=mean, files=['A2_MGNN_only_seed1_pred.csv', 'A2_MGNN_only_seed2_pred.csv', 'A2_MGNN_only_seed3_pred.csv']
       pred_wide shape=(242, 15), date_index=False
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[OK] A2_MGNN_only: generated D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A2_MGNN_only.CSV
     kind=pred; used files: ['A2_MGNN_only_seed1_pred.csv', 'A2_MGNN_only_seed2_pred.csv', 'A2_MGNN_only_seed3_pred.csv']
     replaced close rows: 3630
     prediction date range: 2022-01-04 -> 2022-12-30
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[READ] A3_SH_only: kind=pred, seed_mode=mean, files=['A3_SH_only_seed1_pred.csv', 'A3_SH_only_seed2_pred.csv', 'A3_SH_only_seed3_pred.csv']
       pred_wide shape=(242, 15), date_index=False
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[OK] A3_SH_only: generated D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A3_SH_only.CSV
     kind=pred; used files: ['A3_SH_only_seed1_pred.csv', 'A3_SH_only_seed2_pred.csv', 'A3_SH_only_seed3_pred.csv']
     replaced close rows: 3630
     prediction date range: 2022-01-04 -> 2022-12-30
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[READ] A4_QA_only: kind=pred, seed_mode=mean, files=['A4_QA_only_seed1_pred.csv', 'A4_QA_only_seed2_pred.csv', 'A4_QA_only_seed3_pred.csv']
       pred_wide shape=(242, 15), date_index=False
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[OK] A4_QA_only: generated D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A4_QA_only.CSV
     kind=pred; used files: ['A4_QA_only_seed1_pred.csv', 'A4_QA_only_seed2_pred.csv', 'A4_QA_only_seed3_pred.csv']
     replaced close rows: 3630
     prediction date range: 2022-01-04 -> 2022-12-30
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[READ] A5_KD_only: kind=pred, seed_mode=mean, files=['A5_KD_only_seed1_pred.csv', 'A5_KD_only_seed2_pred.csv', 'A5_KD_only_seed3_pred.csv']
       pred_wide shape=(242, 15), date_index=False
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[OK] A5_KD_only: generated D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A5_KD_only.CSV
     kind=pred; used files: ['A5_KD_only_seed1_pred.csv', 'A5_KD_only_seed2_pred.csv', 'A5_KD_only_seed3_pred.csv']
     replaced close rows: 3630
     prediction date range: 2022-01-04 -> 2022-12-30
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[READ] A6_SH_QA: kind=pred, seed_mode=mean, files=['A6_SH_QA_seed1_pred.csv', 'A6_SH_QA_seed2_pred.csv', 'A6_SH_QA_seed3_pred.csv']
       pred_wide shape=(242, 15), date_index=False
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[OK] A6_SH_QA: generated D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A6_SH_QA.CSV
     kind=pred; used files: ['A6_SH_QA_seed1_pred.csv', 'A6_SH_QA_seed2_pred.csv', 'A6_SH_QA_seed3_pred.csv']
     replaced close rows: 3630
     prediction date range: 2022-01-04 -> 2022-12-30
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[READ] A7_SH_KD: kind=pred, seed_mode=mean, files=['A7_SH_KD_seed1_pred.csv', 'A7_SH_KD_seed2_pred.csv', 'A7_SH_KD_seed3_pred.csv']
       pred_wide shape=(242, 15), date_index=False
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[OK] A7_SH_KD: generated D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A7_SH_KD.CSV
     kind=pred; used files: ['A7_SH_KD_seed1_pred.csv', 'A7_SH_KD_seed2_pred.csv', 'A7_SH_KD_seed3_pred.csv']
     replaced close rows: 3630
     prediction date range: 2022-01-04 -> 2022-12-30
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[READ] A8_QA_KD: kind=pred, seed_mode=mean, files=['A8_QA_KD_seed1_pred.csv', 'A8_QA_KD_seed2_pred.csv', 'A8_QA_KD_seed3_pred.csv']
       pred_wide shape=(242, 15), date_index=False
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[OK] A8_QA_KD: generated D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A8_QA_KD.CSV
     kind=pred; used files: ['A8_QA_KD_seed1_pred.csv', 'A8_QA_KD_seed2_pred.csv', 'A8_QA_KD_seed3_pred.csv']
     replaced close rows: 3630
     prediction date range: 2022-01-04 -> 2022-12-30
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)
[READ] A9_Fixed_fusion: kind=pred, seed_mode=mean, files=['A9_Fixed_fusion_seed1_pred.csv', 'A9_Fixed_fusion_seed2_pred.csv', 'A9_Fixed_fusion_seed3_pred.csv']
       pred_wide shape=(242, 15), date_index=False
Close matrix source = D:\paper\onging\data\bank\bankclose.csv; shape = (1215, 15)

[OK] A9_Fixed_fusion: generated D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV
     kind=pred; used files: ['A9_Fixed_fusion_seed1_pred.csv', 'A9_Fixed_fusion_seed2_pred.csv', 'A9_Fixed_fusion_seed3_pred.csv']
     replaced close rows: 3630
     prediction date range: 2022-01-04 -> 2022-12-30

[DATE MANUAL SETTING]
TRAIN_START = 2018-01-02
TRAIN_END   = 2021-12-31
TRADE_START = 2022-01-04
TRADE_END   = 2022-12-30

Refreshed ablation CSV mapping:
A0_Full_MGT                  -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A0_Full_MGT.CSV | exists=True
A1_Transformer_only          -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A1_Transformer_only.CSV | exists=True
A2_MGNN_only                 -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A2_MGNN_only.CSV | exists=True
A3_SH_only                   -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A3_SH_only.CSV | exists=True
A4_QA_only                   -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A4_QA_only.CSV | exists=True
A5_KD_only                   -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A5_KD_only.CSV | exists=True
A6_SH_QA                     -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A6_SH_QA.CSV | exists=True
A7_SH_KD                     -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A7_SH_KD.CSV | exists=True
A8_QA_KD                     -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A8_QA_KD.CSV | exists=True
A9_Fixed_fusion              -> D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV | exists=True

### 方案二修正说明

本版本针对 Bank 组 `*_pred.csv` 无 `date` 列、列名为 `0,1,...,14` 的情况做了三处修正：

1. `AUTO_DETECT_TRADE_RANGE_FROM_PRED = False`，手动设置 `TRADE_START = "2022-01-04"`、`TRADE_END = "2022-12-30"`。
2. 强制 `PRED_FILE_KIND = "pred"`，读取归一化预测文件并用 `bankclose.csv` 的 scaler 反归一化。
3. 当预测列名是数字位置列时，自动按 `bankclose.csv` 的列顺序映射为真实股票代码，避免 `close matrix 缺少预测文件中的股票列: ['0','1',...]` 报错。

## 4. 修正版 Portfolio Allocation Environment

相对于原 notebook，主要修正：

1. `transaction_cost_pct` 不再是 0，默认使用万分之一；
2. 在 `step()` 中显式计算 turnover 和 transaction cost；
3. 保存 `turnover_memory` 和 `cost_memory`；
4. reward 使用 `portfolio_return * reward_scaling`，避免直接用账户净值导致奖励尺度过大；
5. `save_asset_memory()` 输出 daily return 和 account value。

In [6]:
# ===============================
# 4. Portfolio allocation environment with transaction cost
# ===============================

class StockPortfolioEnv(gym.Env):
    metadata = {"render.modes": ["human"]}

    def __init__(
        self,
        df,
        stock_dim,
        hmax,
        initial_amount,
        transaction_cost_pct,
        reward_scaling,
        state_space,
        action_space,
        tech_indicator_list,
        turbulence_threshold=None,
        lookback=252,
        day=0,
    ):
        self.day = day
        self.lookback = lookback
        self.df = df
        self.stock_dim = stock_dim
        self.hmax = hmax
        self.initial_amount = initial_amount
        self.transaction_cost_pct = transaction_cost_pct
        self.reward_scaling = reward_scaling
        self.state_space = state_space
        self.action_space_dim = action_space
        self.tech_indicator_list = tech_indicator_list
        self.turbulence_threshold = turbulence_threshold

        self.action_space = spaces.Box(low=-1.0, high=1.0, shape=(self.action_space_dim,), dtype=np.float32)
        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(self.state_space + len(self.tech_indicator_list), self.state_space),
            dtype=np.float32,
        )

        self.data = self.df.loc[self.day, :]
        self.covs = self.data["cov_list"].values[0]
        self.state = np.append(
            np.array(self.covs),
            [self.data[tech].values.tolist() for tech in self.tech_indicator_list],
            axis=0,
        )

        self.terminal = False
        self.portfolio_value = self.initial_amount
        self.reward = 0.0

        self.asset_memory = [self.initial_amount]
        self.portfolio_return_memory = [0.0]
        self.actions_memory = [[1 / self.stock_dim] * self.stock_dim]
        self.turnover_memory = [0.0]
        self.cost_memory = [0.0]
        self.date_memory = [self.data.date.unique()[0]]

    def step(self, actions):
        self.terminal = self.day >= len(self.df.index.unique()) - 1

        if self.terminal:
            return self.state.astype(np.float32), self.reward, self.terminal, {}

        # 当前动作 -> long-only simplex 权重
        weights = self.softmax_normalization(actions)
        prev_weights = np.array(self.actions_memory[-1], dtype=float)

        # 当前日价格记忆
        last_day_memory = self.data

        # 进入下一交易日
        self.day += 1
        self.data = self.df.loc[self.day, :]

        self.covs = self.data["cov_list"].values[0]
        self.state = np.append(
            np.array(self.covs),
            [self.data[tech].values.tolist() for tech in self.tech_indicator_list],
            axis=0,
        )

        # 组合收益、换手率和交易成本
        price_relative = self.data.close.values / last_day_memory.close.values
        gross_return = float(np.sum((price_relative - 1.0) * weights))

        turnover = float(np.sum(np.abs(weights - prev_weights)))
        cost = float(self.transaction_cost_pct * turnover)

        portfolio_return = gross_return - cost

        # 更新账户
        new_portfolio_value = self.portfolio_value * (1.0 + portfolio_return)
        self.portfolio_value = new_portfolio_value

        # 保存轨迹
        self.actions_memory.append(weights)
        self.turnover_memory.append(turnover)
        self.cost_memory.append(cost)
        self.portfolio_return_memory.append(portfolio_return)
        self.asset_memory.append(new_portfolio_value)
        self.date_memory.append(self.data.date.unique()[0])

        # 使用收益率作为 reward，避免账户值尺度过大
        self.reward = portfolio_return * self.reward_scaling

        return self.state.astype(np.float32), self.reward, self.terminal, {}

    def reset(self):
        self.asset_memory = [self.initial_amount]
        self.day = 0
        self.data = self.df.loc[self.day, :]

        self.covs = self.data["cov_list"].values[0]
        self.state = np.append(
            np.array(self.covs),
            [self.data[tech].values.tolist() for tech in self.tech_indicator_list],
            axis=0,
        )

        self.portfolio_value = self.initial_amount
        self.reward = 0.0
        self.terminal = False
        self.portfolio_return_memory = [0.0]
        self.actions_memory = [[1 / self.stock_dim] * self.stock_dim]
        self.turnover_memory = [0.0]
        self.cost_memory = [0.0]
        self.date_memory = [self.data.date.unique()[0]]

        return self.state.astype(np.float32)

    def render(self, mode="human"):
        return self.state

    def softmax_normalization(self, actions):
        # SB3/DummyVecEnv may pass actions with shape (1, N); flatten to (N,)
        actions = np.array(actions, dtype=float).reshape(-1)
        actions = actions - np.max(actions)
        numerator = np.exp(actions)
        denominator = np.sum(numerator)
        if denominator == 0 or not np.isfinite(denominator):
            return np.ones(self.stock_dim) / self.stock_dim
        return numerator / denominator

    def save_asset_memory(self):
        return pd.DataFrame({
            "date": self.date_memory,
            "daily_return": self.portfolio_return_memory,
            "account_value": self.asset_memory,
            "turnover": self.turnover_memory,
            "transaction_cost": self.cost_memory,
        })

    def save_action_memory(self):
        df_date = pd.DataFrame(self.date_memory, columns=["date"])
        df_actions = pd.DataFrame(self.actions_memory)
        df_actions.columns = self.data.tic.values
        df_actions.index = df_date.date
        return df_actions

    def _seed(self, seed=None):
        self.np_random, seed = seeding.np_random(seed)
        return [seed]

    def get_sb_env(self):
        e = DummyVecEnv([lambda: self])
        obs = e.reset()
        return e, obs

## 5. 评价指标

输出指标包括：

- CR：累计收益率
- AR：年化收益率
- Vol：年化波动率
- SR：Sharpe ratio
- MDD：最大回撤
- Calmar：Calmar ratio
- Sortino：Sortino ratio
- Omega：Omega ratio
- Turnover：平均换手率
- FinalAccountValue：期末账户价值

In [7]:
# ===============================
# 5. Metrics
# ===============================

def calculate_portfolio_metrics(df_daily_return: pd.DataFrame, df_actions: pd.DataFrame = None):
    r = df_daily_return["daily_return"].astype(float).values

    if len(r) == 0:
        raise ValueError("daily_return is empty.")

    cumulative_return = float(np.prod(1.0 + r) - 1.0)
    annual_return = float((1.0 + cumulative_return) ** (252 / max(len(r), 1)) - 1.0)
    annual_vol = float(np.std(r, ddof=1) * np.sqrt(252)) if len(r) > 1 else np.nan

    sharpe = annual_return / annual_vol if annual_vol and annual_vol != 0 else np.nan

    cumulative_curve = np.cumprod(1.0 + r)
    running_max = np.maximum.accumulate(cumulative_curve)
    drawdown = cumulative_curve / running_max - 1.0
    mdd = float(np.min(drawdown))

    calmar = annual_return / abs(mdd) if mdd != 0 else np.nan

    downside = r[r < 0]
    downside_vol = float(np.std(downside, ddof=1) * np.sqrt(252)) if len(downside) > 1 else np.nan
    sortino = annual_return / downside_vol if downside_vol and downside_vol != 0 else np.nan

    pos_sum = float(np.sum(r[r > 0]))
    neg_sum = float(abs(np.sum(r[r < 0])))
    omega = pos_sum / neg_sum if neg_sum != 0 else np.inf

    if "account_value" in df_daily_return.columns:
        final_account_value = float(df_daily_return["account_value"].iloc[-1])
    else:
        final_account_value = float(cumulative_curve[-1])

    if "turnover" in df_daily_return.columns:
        turnover = float(df_daily_return["turnover"].mean())
    elif df_actions is not None:
        turnover = float(df_actions.diff().abs().sum(axis=1).mean())
    else:
        turnover = np.nan

    return {
        "CR": cumulative_return,
        "AR": annual_return,
        "Vol": annual_vol,
        "SR": sharpe,
        "MDD": mdd,
        "Calmar": calmar,
        "Sortino": sortino,
        "Omega": omega,
        "Turnover": turnover,
        "FinalAccountValue": final_account_value,
    }

In [8]:

# ===============================
# 5.1 Normalize FinRL prediction outputs
# ===============================

def normalize_daily_return_df(df_daily_return):
    """Make returned daily_return dataframe robust across FinRL versions."""
    if isinstance(df_daily_return, list) and len(df_daily_return) > 0:
        df_daily_return = df_daily_return[0]
    df_daily_return = pd.DataFrame(df_daily_return).copy()

    # Some FinRL versions return account_value only
    if "daily_return" not in df_daily_return.columns:
        if "account_value" in df_daily_return.columns:
            df_daily_return["daily_return"] = (
                df_daily_return["account_value"].astype(float).pct_change().fillna(0.0)
            )
        else:
            raise ValueError(
                "df_daily_return must contain daily_return or account_value. "
                f"Columns={df_daily_return.columns.tolist()}"
            )

    if "account_value" not in df_daily_return.columns:
        df_daily_return["account_value"] = (
            INITIAL_AMOUNT * (1.0 + df_daily_return["daily_return"].astype(float)).cumprod()
        )

    if "date" not in df_daily_return.columns:
        df_daily_return.insert(0, "date", np.arange(len(df_daily_return)))

    return df_daily_return


def normalize_action_df(df_actions):
    """Make returned action dataframe robust across FinRL versions."""
    if isinstance(df_actions, list) and len(df_actions) > 0:
        df_actions = df_actions[0]
    df_actions = pd.DataFrame(df_actions).copy()
    return df_actions

## 6. 传统投资基准

这部分用于回应审稿人“缺少 objective investment baselines”的问题。

默认生成：

1. `EqualWeight_Rebalanced`：每日等权再平衡；
2. `BuyHold_EqualInitial`：初始等权买入并持有。

In [9]:
# ===============================
# 6. Objective investment baselines
# ===============================

def equal_weight_rebalanced_baseline(trade_df: pd.DataFrame):
    price = trade_df.pivot_table(index="date", columns="tic", values="close").sort_index()
    asset_ret = price.pct_change().fillna(0.0)
    daily_ret = asset_ret.mean(axis=1)

    df_ret = pd.DataFrame({
        "date": daily_ret.index,
        "daily_return": daily_ret.values,
    })
    df_ret["account_value"] = INITIAL_AMOUNT * (1.0 + df_ret["daily_return"]).cumprod()
    return df_ret

def buy_and_hold_equal_initial_baseline(trade_df: pd.DataFrame):
    price = trade_df.pivot_table(index="date", columns="tic", values="close").sort_index()
    rel_price = price / price.iloc[0]
    portfolio_curve = rel_price.mean(axis=1)
    daily_ret = portfolio_curve.pct_change().fillna(0.0)

    df_ret = pd.DataFrame({
        "date": daily_ret.index,
        "daily_return": daily_ret.values,
    })
    df_ret["account_value"] = INITIAL_AMOUNT * (1.0 + df_ret["daily_return"]).cumprod()
    return df_ret

def run_objective_baselines(trade_df: pd.DataFrame, tag: str):
    rows = []

    baselines = {
        "EqualWeight_Rebalanced": equal_weight_rebalanced_baseline(trade_df),
        "BuyHold_EqualInitial": buy_and_hold_equal_initial_baseline(trade_df),
    }

    for name, df_ret in baselines.items():
        out_path = RL_ABLATION_DIR / f"{tag}_{name}_daily_return.csv"
        df_ret.to_csv(out_path, index=False)

        metrics = calculate_portfolio_metrics(df_ret)
        metrics.update({
            "variant": tag,
            "agent": name,
            "seed": -1,
            "csv_path": "",
        })
        rows.append(metrics)

    return rows

## 7. 单个 RL 消融实验函数

这部分是主函数。

输入一个 FinRL 长表 CSV，训练指定 RL agent，并输出：

- daily return CSV
- action/weight CSV
- 单次实验指标字典

In [10]:
# ===============================
# 7. Run one RL experiment
# ===============================

def build_env_kwargs(train_df: pd.DataFrame):
    stock_dimension = len(train_df.tic.unique())
    state_space = stock_dimension

    env_kwargs = {
        "hmax": 100,
        "initial_amount": INITIAL_AMOUNT,
        "transaction_cost_pct": TRANSACTION_COST_PCT,
        "state_space": state_space,
        "stock_dim": stock_dimension,
        "tech_indicator_list": TECH_INDICATOR_LIST,
        "action_space": stock_dimension,
        "reward_scaling": REWARD_SCALING,
    }
    return env_kwargs

def train_and_trade_one_agent(csv_path, variant_tag, agent_name="a2c", seed=1):
    set_global_seed(seed)
    csv_path = Path(csv_path)

    print(f"\n========== {variant_tag} | {agent_name.upper()} | seed={seed} ==========")
    print("CSV:", csv_path)

    df = load_finrl_data(csv_path, lookback=LOOKBACK, tech_indicator_list=TECH_INDICATOR_LIST)
    train, trade = make_train_trade(df)

    if train.empty:
        raise ValueError(f"{variant_tag}: train 数据为空，请检查日期范围 {TRAIN_START} 到 {TRAIN_END}")
    if trade.empty:
        raise ValueError(f"{variant_tag}: trade 数据为空，请检查日期范围 {TRADE_START} 到 {TRADE_END}")

    env_kwargs = build_env_kwargs(train)

    e_train_gym = StockPortfolioEnv(df=train, **env_kwargs)
    env_train, _ = e_train_gym.get_sb_env()

    agent = DRLAgent(env=env_train)

    params = MODEL_PARAMS.get(agent_name, {}).copy()
    # Stable-Baselines3 大多数算法支持 seed 参数
    params["seed"] = seed

    model = agent.get_model(model_name=agent_name, model_kwargs=params)
    trained_model = agent.train_model(
        model=model,
        tb_log_name=f"{variant_tag}_{agent_name}_seed{seed}",
        total_timesteps=TOTAL_TIMESTEPS[agent_name],
    )

    e_trade_gym = StockPortfolioEnv(df=trade, **env_kwargs)

    df_daily_return, df_actions = DRLAgent.DRL_prediction(
        model=trained_model,
        environment=e_trade_gym,
    )

    # 重要修正：
    # 不要在 DRL_prediction 之后再调用 e_trade_gym.save_asset_memory() 覆盖结果。
    # DummyVecEnv 在 done=True 后可能自动 reset 环境，导致 memory 只剩初始值，
    # 进而出现 A2C 的 CR=0、AR=0、Turnover=0 的假结果。
    df_daily_return = normalize_daily_return_df(df_daily_return)
    df_actions = normalize_action_df(df_actions)

    metrics = calculate_portfolio_metrics(df_daily_return, df_actions)
    metrics.update({
        "variant": variant_tag,
        "agent": agent_name,
        "seed": seed,
        "csv_path": str(csv_path),
    })

    # Save outputs
    daily_path = RL_ABLATION_DIR / f"{variant_tag}_{agent_name}_seed{seed}_daily_return.csv"
    action_path = RL_ABLATION_DIR / f"{variant_tag}_{agent_name}_seed{seed}_actions.csv"

    df_daily_return.to_csv(daily_path, index=False)
    df_actions.to_csv(action_path)

    print("Saved:", daily_path)
    print("Saved:", action_path)
    print(metrics)

    return metrics

## 8. 批量运行 forecast-to-policy 消融实验

默认只运行 `VARIANTS_TO_RUN` 中存在 CSV 的版本。

如果某个 CSV 不存在，会显示 `[SKIP]`，不会报错。

In [11]:
# ===============================
# 8. Batch run RL ablation
# ===============================

all_metrics = []

for variant_tag in VARIANTS_TO_RUN:
    csv_path = RL_ABLATION_INPUTS[variant_tag]

    if not Path(csv_path).exists():
        print(f"[SKIP] {variant_tag}: file not found -> {csv_path}")
        continue

    # 1) 客观投资基准：与 bank 组当前汇总表保持一致，所有 A0--A9 都会生成。
    if RUN_OBJECTIVE_BASELINES:
        try:
            df_for_baseline = load_finrl_data(csv_path, lookback=LOOKBACK, tech_indicator_list=TECH_INDICATOR_LIST)
            _, trade_for_baseline = make_train_trade(df_for_baseline)
            baseline_rows = run_objective_baselines(trade_for_baseline, variant_tag)
            all_metrics.extend(baseline_rows)
        except Exception as e:
            print(f"[Warning] Objective baselines failed for {variant_tag}: {e}")

    # 2) RL forecast-to-policy ablation：如需和完整策略层实验一致，保持 RUN_RL_AGENTS=True。
    if RUN_RL_AGENTS:
        for agent_name in AGENTS_FOR_ABLATION:
            for seed in SEEDS:
                try:
                    metrics = train_and_trade_one_agent(
                        csv_path=csv_path,
                        variant_tag=variant_tag,
                        agent_name=agent_name,
                        seed=seed,
                    )
                    all_metrics.append(metrics)
                except Exception as e:
                    print(f"[ERROR] {variant_tag} | {agent_name} | seed={seed}: {e}")
    else:
        print(f"[INFO] RUN_RL_AGENTS=False; skip RL agents for {variant_tag}")

raw_metrics_df = pd.DataFrame(all_metrics)
raw_metrics_path = RL_ABLATION_DIR / "rl_ablation_raw_results.csv"
raw_metrics_df.to_csv(raw_metrics_path, index=False)

print("Saved raw metrics:", raw_metrics_path)
display(raw_metrics_df)

[banktrademergeGNNtr20241231_A0_Full_MGT.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630

========== A0_Full_MGT | A2C | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A0_Full_MGT.CSV
[banktrademergeGNNtr20241231_A0_Full_MGT.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 10, 'ent_coef': 0.005, 'learning_rate': 0.0004, 'seed': 1}
Using cpu device

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

Logging to tensorboard_log/a2c\A0_Full_MGT_a2c_seed1_7
-------------------------------------
| time/                 |           |
|    fps                | 354       |
|    iterations         | 100       |
|    time_elapsed       | 2         |
|    total_timesteps    | 1000      |
| train/                |           |
|    entropy_loss       | -21.3     |
|    explained_variance | -7.63e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 99        |
|    policy_loss        | 4.24      |
|    std                | 1         |
|    value_loss         | 0.148     |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 372       |
|    iterations         | 200       |
|    time_elapsed       | 5         |
|    total_timesteps    | 2000      |
| train/                |           |
|    entropy_loss       | -21.3     |
|    explained_variance | -1.79e+05 |
|    learning_rate      | 0.0004    |
|    n_updates          | 199       |
|    policy_loss        | 1.53      |
|    std                | 1         |
|    value_loss         | 0.0528    |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 371       |
|    iterations         | 300       |
|    time_elapsed       | 8         |
|    total_timesteps    | 3000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -1.15e+04 |
|    learning_rate      | 0.0004    |
|    n_updates          | 299       |
|    policy_loss        | 1.46      |
|    std                | 1.01      |
|    value_loss         | 0.0541    |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 373       |
|    iterations         | 400       |
|    time_elapsed       | 10        |
|    total_timesteps    | 4000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -2.01e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 399       |
|    policy_loss        | -3.36     |
|    std                | 1.01      |
|    value_loss         | 0.0344    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 369      |
|    iterations         | 500      |
|    time_elapsed       | 13       |
|    total_timesteps    | 5000     |
| train/                |          |
|    entropy_loss       | -21.5    |
|    explained_variance | -85.8    |
|    learning_rate      | 0.0004   |
|    n_updates          | 499      |
|    policy_loss        | -5.51    |
|    std                | 1.01     |
|    value_loss         | 0.0843   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 366       |
|    iterations         | 600       |
|    time_elapsed       | 16        |
|    total_timesteps    | 6000      |
| train/                |           |
|    entropy_loss       | -21.5     |
|    explained_variance | -1.03e+05 |
|    learning_rate      | 0.0004    |
|    n_updates          | 599       |
|    policy_loss        | -0.529    |
|    std                | 1.01      |
|    value_loss         | 0.0152    |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 369       |
|    iterations         | 700       |
|    time_elapsed       | 18        |
|    total_timesteps    | 7000      |
| train/                |           |
|    entropy_loss       | -21.5     |
|    explained_variance | -2.58e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 699       |
|    policy_loss        | -2.15     |
|    std                | 1.02      |
|    value_loss         | 0.0236    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 370      |
|    iterations         | 800      |
|    time_elapsed       | 21       |
|    total_timesteps    | 8000     |
| train/                |          |
|    entropy_loss       | -21.5    |
|    explained_variance | -25.2    |
|    learning_rate      | 0.0004   |
|    n_updates          | 799      |
|    policy_loss        | 5.94     |
|    std                | 1.02     |
|    value_loss         | 0.0773   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 371      |
|    iterations         | 900      |
|    time_elapsed       | 24       |
|    total_timesteps    | 9000     |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -591     |
|    learning_rate      | 0.0004   |
|    n_updates          | 899      |
|    policy_loss        | -0.329   |
|    std                | 1.02     |
|    value_loss         | 0.00817  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 368      |
|    iterations         | 1000     |
|    time_elapsed       | 27       |
|    total_timesteps    | 10000    |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -195     |
|    learning_rate      | 0.0004   |
|    n_updates          | 999      |
|    policy_loss        | 2.63     |
|    std                | 1.02     |
|    value_loss         | 0.0251   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 365      |
|    iterations         | 1100     |
|    time_elapsed       | 30       |
|    total_timesteps    | 11000    |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -93      |
|    learning_rate      | 0.0004   |
|    n_updates          | 1099     |
|    policy_loss        | -3.43    |
|    std                | 1.03     |
|    value_loss         | 0.0286   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 366      |
|    iterations         | 1200     |
|    time_elapsed       | 32       |
|    total_timesteps    | 12000    |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -102     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1199     |
|    policy_loss        | -0.345   |
|    std                | 1.03     |
|    value_loss         | 0.00379  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 363      |
|    iterations         | 1300     |
|    time_elapsed       | 35       |
|    total_timesteps    | 13000    |
| train/                |          |
|    entropy_loss       | -21.8    |
|    explained_variance | -286     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1299     |
|    policy_loss        | 0.463    |
|    std                | 1.04     |
|    value_loss         | 0.00662  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 364      |
|    iterations         | 1400     |
|    time_elapsed       | 38       |
|    total_timesteps    | 14000    |
| train/                |          |
|    entropy_loss       | -21.9    |
|    explained_variance | -916     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1399     |
|    policy_loss        | 0.727    |
|    std                | 1.04     |
|    value_loss         | 0.00765  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 364      |
|    iterations         | 1500     |
|    time_elapsed       | 41       |
|    total_timesteps    | 15000    |
| train/                |          |
|    entropy_loss       | -22      |
|    explained_variance | -83.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 1499     |
|    policy_loss        | -2.6     |
|    std                | 1.05     |
|    value_loss         | 0.0136   |
------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 365      |
|    iterations         | 1600     |
|    time_elapsed       | 43       |
|    total_timesteps    | 16000    |
| train/                |          |
|    entropy_loss       | -22.1    |
|    explained_variance | -54.3    |
|    learning_rate      | 0.0004   |
|    n_updates          | 1599     |
|    policy_loss        | -1.87    |
|    std                | 1.05     |
|    value_loss         | 0.00918  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 363      |
|    iterations         | 1700     |
|    time_elapsed       | 46       |
|    total_timesteps    | 17000    |
| train/                |          |
|    entropy_loss       | -22.2    |
|    explained_variance | -112     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1699     |
|    policy_loss        | 2.68     |
|    std                | 1.06     |
|    value_loss         | 0.0187   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 364      |
|    iterations         | 1800     |
|    time_elapsed       | 49       |
|    total_timesteps    | 18000    |
| train/                |          |
|    entropy_loss       | -22.2    |
|    explained_variance | -44.5    |
|    learning_rate      | 0.0004   |
|    n_updates          | 1799     |
|    policy_loss        | 0.901    |
|    std                | 1.07     |
|    value_loss         | 0.00316  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 364       |
|    iterations         | 1900      |
|    time_elapsed       | 52        |
|    total_timesteps    | 19000     |
| train/                |           |
|    entropy_loss       | -22.3     |
|    explained_variance | -8.15e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 1899      |
|    policy_loss        | -1.16     |
|    std                | 1.07      |
|    value_loss         | 0.00734   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 363      |
|    iterations         | 2000     |
|    time_elapsed       | 55       |
|    total_timesteps    | 20000    |
| train/                |          |
|    entropy_loss       | -22.4    |
|    explained_variance | -358     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1999     |
|    policy_loss        | 0.898    |
|    std                | 1.08     |
|    value_loss         | 0.00318  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 364      |
|    iterations         | 2100     |
|    time_elapsed       | 57       |
|    total_timesteps    | 21000    |
| train/                |          |
|    entropy_loss       | -22.5    |
|    explained_variance | -101     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2099     |
|    policy_loss        | -1.75    |
|    std                | 1.09     |
|    value_loss         | 0.00822  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 363      |
|    iterations         | 2200     |
|    time_elapsed       | 60       |
|    total_timesteps    | 22000    |
| train/                |          |
|    entropy_loss       | -22.6    |
|    explained_variance | -31.8    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2199     |
|    policy_loss        | 0.271    |
|    std                | 1.09     |
|    value_loss         | 0.00159  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 363      |
|    iterations         | 2300     |
|    time_elapsed       | 63       |
|    total_timesteps    | 23000    |
| train/                |          |
|    entropy_loss       | -22.7    |
|    explained_variance | -58.1    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2299     |
|    policy_loss        | -1.29    |
|    std                | 1.1      |
|    value_loss         | 0.00783  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 363      |
|    iterations         | 2400     |
|    time_elapsed       | 66       |
|    total_timesteps    | 24000    |
| train/                |          |
|    entropy_loss       | -22.8    |
|    explained_variance | -132     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2399     |
|    policy_loss        | -0.559   |
|    std                | 1.11     |
|    value_loss         | 0.00397  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 364      |
|    iterations         | 2500     |
|    time_elapsed       | 68       |
|    total_timesteps    | 25000    |
| train/                |          |
|    entropy_loss       | -23      |
|    explained_variance | -184     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2499     |
|    policy_loss        | -1.4     |
|    std                | 1.12     |
|    value_loss         | 0.00639  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 364      |
|    iterations         | 2600     |
|    time_elapsed       | 71       |
|    total_timesteps    | 26000    |
| train/                |          |
|    entropy_loss       | -23.1    |
|    explained_variance | -213     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2599     |
|    policy_loss        | -0.159   |
|    std                | 1.13     |
|    value_loss         | 0.00427  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 364      |
|    iterations         | 2700     |
|    time_elapsed       | 74       |
|    total_timesteps    | 27000    |
| train/                |          |
|    entropy_loss       | -23.2    |
|    explained_variance | -67.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2699     |
|    policy_loss        | -0.229   |
|    std                | 1.13     |
|    value_loss         | 0.00205  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 364      |
|    iterations         | 2800     |
|    time_elapsed       | 76       |
|    total_timesteps    | 28000    |
| train/                |          |
|    entropy_loss       | -23.3    |
|    explained_variance | -243     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2799     |
|    policy_loss        | 0.888    |
|    std                | 1.14     |
|    value_loss         | 0.00235  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 363      |
|    iterations         | 2900     |
|    time_elapsed       | 79       |
|    total_timesteps    | 29000    |
| train/                |          |
|    entropy_loss       | -23.4    |
|    explained_variance | -227     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2899     |
|    policy_loss        | -1.43    |
|    std                | 1.15     |
|    value_loss         | 0.00541  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 363       |
|    iterations         | 3000      |
|    time_elapsed       | 82        |
|    total_timesteps    | 30000     |
| train/                |           |
|    entropy_loss       | -23.5     |
|    explained_variance | -7.02e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 2999      |
|    policy_loss        | -0.223    |
|    std                | 1.16      |
|    value_loss         | 0.00162   |
-------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 364      |
|    iterations         | 3100     |
|    time_elapsed       | 85       |
|    total_timesteps    | 31000    |
| train/                |          |
|    entropy_loss       | -23.6    |
|    explained_variance | -150     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3099     |
|    policy_loss        | 1.39     |
|    std                | 1.17     |
|    value_loss         | 0.00688  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 364      |
|    iterations         | 3200     |
|    time_elapsed       | 87       |
|    total_timesteps    | 32000    |
| train/                |          |
|    entropy_loss       | -23.7    |
|    explained_variance | -372     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3199     |
|    policy_loss        | 0.223    |
|    std                | 1.18     |
|    value_loss         | 0.00375  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 364      |
|    iterations         | 3300     |
|    time_elapsed       | 90       |
|    total_timesteps    | 33000    |
| train/                |          |
|    entropy_loss       | -23.9    |
|    explained_variance | -35.3    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3299     |
|    policy_loss        | 0.647    |
|    std                | 1.19     |
|    value_loss         | 0.00177  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 364      |
|    iterations         | 3400     |
|    time_elapsed       | 93       |
|    total_timesteps    | 34000    |
| train/                |          |
|    entropy_loss       | -24      |
|    explained_variance | -86.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3399     |
|    policy_loss        | -3.5     |
|    std                | 1.2      |
|    value_loss         | 0.0208   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 360       |
|    iterations         | 3500      |
|    time_elapsed       | 97        |
|    total_timesteps    | 35000     |
| train/                |           |
|    entropy_loss       | -24.1     |
|    explained_variance | -1.71e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 3499      |
|    policy_loss        | 0.706     |
|    std                | 1.21      |
|    value_loss         | 0.00246   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 360      |
|    iterations         | 3600     |
|    time_elapsed       | 99       |
|    total_timesteps    | 36000    |
| train/                |          |
|    entropy_loss       | -24.3    |
|    explained_variance | -13      |
|    learning_rate      | 0.0004   |
|    n_updates          | 3599     |
|    policy_loss        | 0.185    |
|    std                | 1.22     |
|    value_loss         | 0.00086  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 360      |
|    iterations         | 3700     |
|    time_elapsed       | 102      |
|    total_timesteps    | 37000    |
| train/                |          |
|    entropy_loss       | -24.4    |
|    explained_variance | -263     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3699     |
|    policy_loss        | -0.393   |
|    std                | 1.23     |
|    value_loss         | 0.00163  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 361      |
|    iterations         | 3800     |
|    time_elapsed       | 105      |
|    total_timesteps    | 38000    |
| train/                |          |
|    entropy_loss       | -24.6    |
|    explained_variance | -336     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3799     |
|    policy_loss        | -1.34    |
|    std                | 1.25     |
|    value_loss         | 0.00401  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 361      |
|    iterations         | 3900     |
|    time_elapsed       | 107      |
|    total_timesteps    | 39000    |
| train/                |          |
|    entropy_loss       | -24.7    |
|    explained_variance | -50.4    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3899     |
|    policy_loss        | 0.769    |
|    std                | 1.26     |
|    value_loss         | 0.00244  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 360      |
|    iterations         | 4000     |
|    time_elapsed       | 110      |
|    total_timesteps    | 40000    |
| train/                |          |
|    entropy_loss       | -24.9    |
|    explained_variance | -54.2    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3999     |
|    policy_loss        | 1.26     |
|    std                | 1.27     |
|    value_loss         | 0.00527  |
------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A0_Full_MGT_a2c_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A0_Full_MGT_a2c_seed1_actions.csv
{'CR': -0.04803342076003403, 'AR': -0.049967853031648635, 'Vol': 0.14181929412016842, 'SR': -0.35233466180778716, 'MDD': -0.14414521786163192, 'Calmar': -0.3466493982451353, 'Sortino': -0.49477722514981803, 'Omega': 0.9482118006036789, 'Turnover': 0.7378876242856033, 'FinalAccountValue': 951966.5792399656, 'variant': 'A0_Full_MGT', 'agent': 'a2c', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A0_Full_MGT.CSV'}

========== A0_Full_MGT | PPO | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A0_Full_MGT.CSV
[banktrademergeGNNtr20241231_A0_Full_MGT.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 2048, 'ent_coef': 0.005, 'learning_rate': 0.001, 'batch_size': 128, 'seed': 1}
Using cpu device
Logging to tensorboard_log/ppo\A0_Full_MGT_ppo_seed1_6

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

-----------------------------
| time/              |      |
|    fps             | 522  |
|    iterations      | 1    |
|    time_elapsed    | 3    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 424         |
|    iterations           | 2           |
|    time_elapsed         | 9           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.047411323 |
|    clip_fraction        | 0.405       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | -46.9       |
|    learning_rate        | 0.001       |
|    loss                 | -0.202      |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0723     |
|    std                  | 0.999       |
|    value_loss           | 0.0354      |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 390         |
|    iterations           | 3           |
|    time_elapsed         | 15          |
|    total_timesteps      | 6144        |
| train/                  |             |
|    approx_kl            | 0.055628944 |
|    clip_fraction        | 0.428       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.2       |
|    explained_variance   | -0.871      |
|    learning_rate        | 0.001       |
|    loss                 | -0.208      |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0686     |
|    std                  | 0.996       |
|    value_loss           | 0.00238     |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 380         |
|    iterations           | 4           |
|    time_elapsed         | 21          |
|    total_timesteps      | 8192        |
| train/                  |             |
|    approx_kl            | 0.062404223 |
|    clip_fraction        | 0.464       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.2       |
|    explained_variance   | 0.508       |
|    learning_rate        | 0.001       |
|    loss                 | -0.183      |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.0595     |
|    std                  | 0.996       |
|    value_loss           | 0.000874    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 378         |
|    iterations           | 5           |
|    time_elapsed         | 27          |
|    total_timesteps      | 10240       |
| train/                  |             |
|    approx_kl            | 0.066075474 |
|    clip_fraction        | 0.477       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.2       |
|    explained_variance   | 0.664       |
|    learning_rate        | 0.001       |
|    loss                 | -0.198      |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0611     |
|    std                  | 0.997       |
|    value_loss           | 0.000589    |
-----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 373       |
|    iterations           | 6         |
|    time_elapsed         | 32        |
|    total_timesteps      | 12288     |
| train/                  |           |
|    approx_kl            | 0.0722509 |
|    clip_fraction        | 0.501     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.2     |
|    explained_variance   | 0.829     |
|    learning_rate        | 0.001     |
|    loss                 | -0.192    |
|    n_updates            | 50        |
|    policy_gradient_loss | -0.0624   |
|    std                  | 0.996     |
|    value_loss           | 0.00034   |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 371        |
|    iterations           | 7          |
|    time_elapsed         | 38         |
|    total_timesteps      | 14336      |
| train/                  |            |
|    approx_kl            | 0.08066017 |
|    clip_fraction        | 0.508      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.841      |
|    learning_rate        | 0.001      |
|    loss                 | -0.178     |
|    n_updates            | 60         |
|    policy_gradient_loss | -0.0571    |
|    std                  | 0.995      |
|    value_loss           | 0.000227   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 371        |
|    iterations           | 8          |
|    time_elapsed         | 44         |
|    total_timesteps      | 16384      |
| train/                  |            |
|    approx_kl            | 0.08725244 |
|    clip_fraction        | 0.525      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.833      |
|    learning_rate        | 0.001      |
|    loss                 | -0.174     |
|    n_updates            | 70         |
|    policy_gradient_loss | -0.055     |
|    std                  | 0.995      |
|    value_loss           | 0.000198   |
----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 372       |
|    iterations           | 9         |
|    time_elapsed         | 49        |
|    total_timesteps      | 18432     |
| train/                  |           |
|    approx_kl            | 0.1080558 |
|    clip_fraction        | 0.562     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.2     |
|    explained_variance   | 0.674     |
|    learning_rate        | 0.001     |
|    loss                 | -0.204    |
|    n_updates            | 80        |
|    policy_gradient_loss | -0.0533   |
|    std                  | 0.999     |
|    value_loss           | 0.000212  |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 369        |
|    iterations           | 10         |
|    time_elapsed         | 55         |
|    total_timesteps      | 20480      |
| train/                  |            |
|    approx_kl            | 0.09933944 |
|    clip_fraction        | 0.543      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.834      |
|    learning_rate        | 0.001      |
|    loss                 | -0.195     |
|    n_updates            | 90         |
|    policy_gradient_loss | -0.0564    |
|    std                  | 0.996      |
|    value_loss           | 0.000151   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 367         |
|    iterations           | 11          |
|    time_elapsed         | 61          |
|    total_timesteps      | 22528       |
| train/                  |             |
|    approx_kl            | 0.111500606 |
|    clip_fraction        | 0.551       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | 0.77        |
|    learning_rate        | 0.001       |
|    loss                 | -0.173      |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.0544     |
|    std                  | 1           |
|    value_loss           | 0.000147    |
-----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 365       |
|    iterations           | 12        |
|    time_elapsed         | 67        |
|    total_timesteps      | 24576     |
| train/                  |           |
|    approx_kl            | 0.0962508 |
|    clip_fraction        | 0.548     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.3     |
|    explained_variance   | 0.756     |
|    learning_rate        | 0.001     |
|    loss                 | -0.184    |
|    n_updates            | 110       |
|    policy_gradient_loss | -0.0492   |
|    std                  | 1         |
|    value_loss           | 0.000123  |
---------------------------------------

---------------------------------------
| time/                   |           |
|    fps                  | 365       |
|    iterations           | 13        |
|    time_elapsed         | 72        |
|    total_timesteps      | 26624     |
| train/                  |           |
|    approx_kl            | 0.1072637 |
|    clip_fraction        | 0.551     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.4     |
|    explained_variance   | 0.858     |
|    learning_rate        | 0.001     |
|    loss                 | -0.193    |
|    n_updates            | 120       |
|    policy_gradient_loss | -0.0507   |
|    std                  | 1.01      |
|    value_loss           | 0.000106  |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 364        |
|    iterations           | 14         |
|    time_elapsed         | 78         |
|    total_timesteps      | 28672      |
| train/                  |            |
|    approx_kl            | 0.10908206 |
|    clip_fraction        | 0.552      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.749      |
|    learning_rate        | 0.001      |
|    loss                 | -0.198     |
|    n_updates            | 130        |
|    policy_gradient_loss | -0.0505    |
|    std                  | 1.01       |
|    value_loss           | 0.000102   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 363        |
|    iterations           | 15         |
|    time_elapsed         | 84         |
|    total_timesteps      | 30720      |
| train/                  |            |
|    approx_kl            | 0.11622736 |
|    clip_fraction        | 0.567      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.717      |
|    learning_rate        | 0.001      |
|    loss                 | -0.202     |
|    n_updates            | 140        |
|    policy_gradient_loss | -0.0485    |
|    std                  | 1.01       |
|    value_loss           | 0.000125   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 362        |
|    iterations           | 16         |
|    time_elapsed         | 90         |
|    total_timesteps      | 32768      |
| train/                  |            |
|    approx_kl            | 0.12862632 |
|    clip_fraction        | 0.569      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.615      |
|    learning_rate        | 0.001      |
|    loss                 | -0.216     |
|    n_updates            | 150        |
|    policy_gradient_loss | -0.0524    |
|    std                  | 1.01       |
|    value_loss           | 0.000108   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 361        |
|    iterations           | 17         |
|    time_elapsed         | 96         |
|    total_timesteps      | 34816      |
| train/                  |            |
|    approx_kl            | 0.13391852 |
|    clip_fraction        | 0.574      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.718      |
|    learning_rate        | 0.001      |
|    loss                 | -0.181     |
|    n_updates            | 160        |
|    policy_gradient_loss | -0.0576    |
|    std                  | 1.01       |
|    value_loss           | 0.000157   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 361        |
|    iterations           | 18         |
|    time_elapsed         | 101        |
|    total_timesteps      | 36864      |
| train/                  |            |
|    approx_kl            | 0.15705493 |
|    clip_fraction        | 0.606      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | -0.191     |
|    learning_rate        | 0.001      |
|    loss                 | -0.166     |
|    n_updates            | 170        |
|    policy_gradient_loss | -0.0502    |
|    std                  | 1.02       |
|    value_loss           | 0.00024    |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 361        |
|    iterations           | 19         |
|    time_elapsed         | 107        |
|    total_timesteps      | 38912      |
| train/                  |            |
|    approx_kl            | 0.15010773 |
|    clip_fraction        | 0.578      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.6      |
|    explained_variance   | 0.0129     |
|    learning_rate        | 0.001      |
|    loss                 | -0.16      |
|    n_updates            | 180        |
|    policy_gradient_loss | -0.0457    |
|    std                  | 1.02       |
|    value_loss           | 0.00051    |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 360        |
|    iterations           | 20         |
|    time_elapsed         | 113        |
|    total_timesteps      | 40960      |
| train/                  |            |
|    approx_kl            | 0.13858297 |
|    clip_fraction        | 0.57       |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.7      |
|    explained_variance   | -1.68      |
|    learning_rate        | 0.001      |
|    loss                 | -0.174     |
|    n_updates            | 190        |
|    policy_gradient_loss | -0.0547    |
|    std                  | 1.03       |
|    value_loss           | 0.000303   |
----------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A0_Full_MGT_ppo_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A0_Full_MGT_ppo_seed1_actions.csv
{'CR': 0.0730873505213363, 'AR': 0.07621982443166186, 'Vol': 0.14603353405842381, 'SR': 0.521933711480053, 'MDD': -0.11768586699190964, 'Calmar': 0.647654866126802, 'Sortino': 0.792600831323923, 'Omega': 1.115833176425899, 'Turnover': 0.7585983523951276, 'FinalAccountValue': 1073087.3505213358, 'variant': 'A0_Full_MGT', 'agent': 'ppo', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A0_Full_MGT.CSV'}

========== A0_Full_MGT | SAC | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A0_Full_MGT.CSV
[banktrademergeGNNtr20241231_A0_Full_MGT.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 128, 'buffer_size': 1000000, 'learning_rate': 0.0001, 'learning_starts': 100, 'ent_coef': 'auto_0.1', 'seed': 1}
Using cpu device
Logging to tensorboard_log/sac\A0_Full_MGT_sac_seed1_6

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 13       |
|    time_elapsed    | 214      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | -9.75    |
|    critic_loss     | 0.0381   |
|    ent_coef        | 0.0753   |
|    ent_coef_loss   | -64.9    |
|    learning_rate   | 0.0001   |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 13       |
|    time_elapsed    | 437      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | -16.5    |
|    critic_loss     | 0.0186   |
|    ent_coef        | 0.0564   |
|    ent_coef_loss   | -72.4    |
|    learning_rate   | 0.0001   |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 13       |
|    time_elapsed    | 663      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | -20.1    |
|    critic_loss     | 0.00873  |
|    ent_coef        | 0.0422   |
|    ent_coef_loss   | -79.9    |
|    learning_rate   | 0.0001   |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 12       |
|    time_elapsed    | 902      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | -21.7    |
|    critic_loss     | 0.0289   |
|    ent_coef        | 0.0316   |
|    ent_coef_loss   | -87.1    |
|    learning_rate   | 0.0001   |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 12       |
|    time_elapsed    | 1149     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | -21.7    |
|    critic_loss     | 0.0317   |
|    ent_coef        | 0.0237   |
|    ent_coef_loss   | -94.3    |
|    learning_rate   | 0.0001   |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 12       |
|    time_elapsed    | 1399     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | -21      |
|    critic_loss     | 0.0195   |
|    ent_coef        | 0.0178   |
|    ent_coef_loss   | -101     |
|    learning_rate   | 0.0001   |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 12       |
|    time_elapsed    | 1648     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | -19.8    |
|    critic_loss     | 0.00659  |
|    ent_coef        | 0.0133   |
|    ent_coef_loss   | -108     |
|    learning_rate   | 0.0001   |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1898     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | -18.2    |
|    critic_loss     | 0.0569   |
|    ent_coef        | 0.00998  |
|    ent_coef_loss   | -115     |
|    learning_rate   | 0.0001   |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2150     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | -15.4    |
|    critic_loss     | 0.017    |
|    ent_coef        | 0.00748  |
|    ent_coef_loss   | -122     |
|    learning_rate   | 0.0001   |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 12       |
|    time_elapsed    | 2402     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | -15      |
|    critic_loss     | 0.0137   |
|    ent_coef        | 0.00561  |
|    ent_coef_loss   | -129     |
|    learning_rate   | 0.0001   |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 12       |
|    time_elapsed    | 2641     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -13      |
|    critic_loss     | 0.00678  |
|    ent_coef        | 0.00421  |
|    ent_coef_loss   | -135     |
|    learning_rate   | 0.0001   |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 11       |
|    time_elapsed    | 2890     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -11.3    |
|    critic_loss     | 0.00384  |
|    ent_coef        | 0.00316  |
|    ent_coef_loss   | -140     |
|    learning_rate   | 0.0001   |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 11       |
|    time_elapsed    | 3138     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -9.74    |
|    critic_loss     | 0.00317  |
|    ent_coef        | 0.00237  |
|    ent_coef_loss   | -145     |
|    learning_rate   | 0.0001   |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 12       |
|    time_elapsed    | 3352     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -8.91    |
|    critic_loss     | 0.00994  |
|    ent_coef        | 0.00178  |
|    ent_coef_loss   | -147     |
|    learning_rate   | 0.0001   |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 12       |
|    time_elapsed    | 3572     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -7.34    |
|    critic_loss     | 0.014    |
|    ent_coef        | 0.00134  |
|    ent_coef_loss   | -151     |
|    learning_rate   | 0.0001   |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 12       |
|    time_elapsed    | 3808     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -6.45    |
|    critic_loss     | 0.0173   |
|    ent_coef        | 0.001    |
|    ent_coef_loss   | -155     |
|    learning_rate   | 0.0001   |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 12       |
|    time_elapsed    | 4039     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -5.42    |
|    critic_loss     | 0.0159   |
|    ent_coef        | 0.000755 |
|    ent_coef_loss   | -154     |
|    learning_rate   | 0.0001   |
|    n_updates       | 48927    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 72       |
|    fps             | 12       |
|    time_elapsed    | 4270     |
|    total_timesteps | 51912    |
| train/             |          |
|    actor_loss      | -4.6     |
|    critic_loss     | 0.0032   |
|    ent_coef        | 0.000569 |
|    ent_coef_loss   | -158     |
|    learning_rate   | 0.0001   |
|    n_updates       | 51811    |
---------------------------------

---------------------------------
| time/              |          |
|    episodes        | 76       |
|    fps             | 12       |
|    time_elapsed    | 4506     |
|    total_timesteps | 54796    |
| train/             |          |
|    actor_loss      | -3.67    |
|    critic_loss     | 0.00759  |
|    ent_coef        | 0.000428 |
|    ent_coef_loss   | -153     |
|    learning_rate   | 0.0001   |
|    n_updates       | 54695    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 80       |
|    fps             | 12       |
|    time_elapsed    | 4738     |
|    total_timesteps | 57680    |
| train/             |          |
|    actor_loss      | -3.2     |
|    critic_loss     | 0.00299  |
|    ent_coef        | 0.000323 |
|    ent_coef_loss   | -142     |
|    learning_rate   | 0.0001   |
|    n_updates       | 57579    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A0_Full_MGT_sac_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A0_Full_MGT_sac_seed1_actions.csv
{'CR': 0.0053848749809382035, 'AR': 0.005608013270934409, 'Vol': 0.1533202370884925, 'SR': 0.03657712365587856, 'MDD': -0.10041707729469174, 'Calmar': 0.055847206690518375, 'Sortino': 0.057249907090121004, 'Omega': 1.0225939763659218, 'Turnover': 0.6562120913638486, 'FinalAccountValue': 1005384.8749809384, 'variant': 'A0_Full_MGT', 'agent': 'sac', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A0_Full_MGT.CSV'}

========== A0_Full_MGT | TD3 | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A0_Full_MGT.CSV
[banktrademergeGNNtr20241231_A0_Full_MGT.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 100, 'buffer_size': 1000000, 'learning_rate': 0.001, 'seed': 1}
Using cpu device
Logging to tensorboard_log/td3\A0_Full_MGT_td3_seed1_5

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 16       |
|    time_elapsed    | 173      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 0.919    |
|    critic_loss     | 0.00735  |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 15       |
|    time_elapsed    | 365      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.928    |
|    critic_loss     | 0.0019   |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 15       |
|    time_elapsed    | 565      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.834    |
|    critic_loss     | 0.0017   |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 14       |
|    time_elapsed    | 775      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.824    |
|    critic_loss     | 0.000284 |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 14       |
|    time_elapsed    | 1010     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.764    |
|    critic_loss     | 0.000801 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 13       |
|    time_elapsed    | 1262     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.643    |
|    critic_loss     | 0.000635 |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 13       |
|    time_elapsed    | 1528     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.645    |
|    critic_loss     | 0.000409 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1811     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.584    |
|    critic_loss     | 0.000361 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2094     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.55     |
|    critic_loss     | 0.000506 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 12       |
|    time_elapsed    | 2393     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.477    |
|    critic_loss     | 0.000215 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A0_Full_MGT_td3_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A0_Full_MGT_td3_seed1_actions.csv
{'CR': 0.07376191981872782, 'AR': 0.07692432816220829, 'Vol': 0.13119001522602136, 'SR': 0.5863581007264831, 'MDD': -0.06886165362197239, 'Calmar': 1.11708511364681, 'Sortino': 0.9201690218630263, 'Omega': 1.1184392307737852, 'Turnover': 0.772282127272828, 'FinalAccountValue': 1073761.9198187257, 'variant': 'A0_Full_MGT', 'agent': 'td3', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A0_Full_MGT.CSV'}

========== A0_Full_MGT | DDPG | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A0_Full_MGT.CSV
[banktrademergeGNNtr20241231_A0_Full_MGT.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'seed': 1}
Using cpu device
Logging to tensorboard_log/ddpg\A0_Full_MGT_ddpg_seed1_4

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 11       |
|    time_elapsed    | 258      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 0.652    |
|    critic_loss     | 0.00086  |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 10       |
|    time_elapsed    | 528      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.509    |
|    critic_loss     | 0.00101  |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 10       |
|    time_elapsed    | 801      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.356    |
|    critic_loss     | 0.000225 |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 10       |
|    time_elapsed    | 1087     |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.277    |
|    critic_loss     | 6.67e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 10       |
|    time_elapsed    | 1373     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.211    |
|    critic_loss     | 7.07e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 10       |
|    time_elapsed    | 1680     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.155    |
|    critic_loss     | 0.000109 |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 10       |
|    time_elapsed    | 1999     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.102    |
|    critic_loss     | 2.68e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 9        |
|    time_elapsed    | 2324     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.0671   |
|    critic_loss     | 1.92e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 9        |
|    time_elapsed    | 2656     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.0358   |
|    critic_loss     | 2.37e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 9        |
|    time_elapsed    | 3003     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.00263  |
|    critic_loss     | 2.25e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 9        |
|    time_elapsed    | 3347     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -0.0204  |
|    critic_loss     | 1.8e-05  |
|    learning_rate   | 0.001    |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 9        |
|    time_elapsed    | 3699     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -0.0486  |
|    critic_loss     | 6.32e-06 |
|    learning_rate   | 0.001    |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 9        |
|    time_elapsed    | 4045     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -0.0712  |
|    critic_loss     | 7.55e-06 |
|    learning_rate   | 0.001    |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 9        |
|    time_elapsed    | 4399     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -0.0875  |
|    critic_loss     | 1.36e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 9        |
|    time_elapsed    | 4764     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -0.114   |
|    critic_loss     | 1.1e-05  |
|    learning_rate   | 0.001    |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 9        |
|    time_elapsed    | 5124     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -0.121   |
|    critic_loss     | 1.04e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 8        |
|    time_elapsed    | 5492     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -0.135   |
|    critic_loss     | 9.82e-06 |
|    learning_rate   | 0.001    |
|    n_updates       | 48927    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A0_Full_MGT_ddpg_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A0_Full_MGT_ddpg_seed1_actions.csv
{'CR': 0.016574265777947295, 'AR': 0.017265032026396954, 'Vol': 0.14686886343792246, 'SR': 0.11755406573085125, 'MDD': -0.10653678216762086, 'Calmar': 0.1620570067456404, 'Sortino': 0.18708240809617316, 'Omega': 1.0353182105227048, 'Turnover': 0.8244295043237938, 'FinalAccountValue': 1016574.2657779461, 'variant': 'A0_Full_MGT', 'agent': 'ddpg', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A0_Full_MGT.CSV'}
[banktrademergeGNNtr20241231_A1_Transformer_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630

========== A1_Transformer_only | A2C | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A1_Transformer_only.CSV
[banktrademergeGNNtr20241231_A1_Transformer_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 10, 'ent_coef': 0.005, 'learning_rate': 0.0004, 'seed': 1}
Using cpu device
Logging to tensorboard_log/a2c\A1_Transformer_only_a2c_seed1_3

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

------------------------------------
| time/                 |          |
|    fps                | 362      |
|    iterations         | 100      |
|    time_elapsed       | 2        |
|    total_timesteps    | 1000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -532     |
|    learning_rate      | 0.0004   |
|    n_updates          | 99       |
|    policy_loss        | 1.11     |
|    std                | 1.01     |
|    value_loss         | 0.0185   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 366      |
|    iterations         | 200      |
|    time_elapsed       | 5        |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -225     |
|    learning_rate      | 0.0004   |
|    n_updates          | 199      |
|    policy_loss        | -6.23    |
|    std                | 1.01     |
|    value_loss         | 0.126    |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 355       |
|    iterations         | 300       |
|    time_elapsed       | 8         |
|    total_timesteps    | 3000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -1.24e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 299       |
|    policy_loss        | 3.94      |
|    std                | 1.01      |
|    value_loss         | 0.0597    |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 361       |
|    iterations         | 400       |
|    time_elapsed       | 11        |
|    total_timesteps    | 4000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -5.82e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 399       |
|    policy_loss        | -3.47     |
|    std                | 1.01      |
|    value_loss         | 0.0511    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 367      |
|    iterations         | 500      |
|    time_elapsed       | 13       |
|    total_timesteps    | 5000     |
| train/                |          |
|    entropy_loss       | -21.5    |
|    explained_variance | -350     |
|    learning_rate      | 0.0004   |
|    n_updates          | 499      |
|    policy_loss        | 2.52     |
|    std                | 1.01     |
|    value_loss         | 0.0312   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 374      |
|    iterations         | 600      |
|    time_elapsed       | 16       |
|    total_timesteps    | 6000     |
| train/                |          |
|    entropy_loss       | -21.5    |
|    explained_variance | -803     |
|    learning_rate      | 0.0004   |
|    n_updates          | 599      |
|    policy_loss        | -2.6     |
|    std                | 1.02     |
|    value_loss         | 0.0233   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 380      |
|    iterations         | 700      |
|    time_elapsed       | 18       |
|    total_timesteps    | 7000     |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -163     |
|    learning_rate      | 0.0004   |
|    n_updates          | 699      |
|    policy_loss        | -5.92    |
|    std                | 1.02     |
|    value_loss         | 0.0874   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 382      |
|    iterations         | 800      |
|    time_elapsed       | 20       |
|    total_timesteps    | 8000     |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -447     |
|    learning_rate      | 0.0004   |
|    n_updates          | 799      |
|    policy_loss        | 3.95     |
|    std                | 1.02     |
|    value_loss         | 0.0362   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 382      |
|    iterations         | 900      |
|    time_elapsed       | 23       |
|    total_timesteps    | 9000     |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -988     |
|    learning_rate      | 0.0004   |
|    n_updates          | 899      |
|    policy_loss        | -1.93    |
|    std                | 1.03     |
|    value_loss         | 0.0197   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 384      |
|    iterations         | 1000     |
|    time_elapsed       | 26       |
|    total_timesteps    | 10000    |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -180     |
|    learning_rate      | 0.0004   |
|    n_updates          | 999      |
|    policy_loss        | 0.755    |
|    std                | 1.03     |
|    value_loss         | 0.00999  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 386      |
|    iterations         | 1100     |
|    time_elapsed       | 28       |
|    total_timesteps    | 11000    |
| train/                |          |
|    entropy_loss       | -21.8    |
|    explained_variance | -217     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1099     |
|    policy_loss        | -1.28    |
|    std                | 1.04     |
|    value_loss         | 0.00845  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 389      |
|    iterations         | 1200     |
|    time_elapsed       | 30       |
|    total_timesteps    | 12000    |
| train/                |          |
|    entropy_loss       | -21.9    |
|    explained_variance | -740     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1199     |
|    policy_loss        | -0.137   |
|    std                | 1.04     |
|    value_loss         | 0.00886  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 391      |
|    iterations         | 1300     |
|    time_elapsed       | 33       |
|    total_timesteps    | 13000    |
| train/                |          |
|    entropy_loss       | -22      |
|    explained_variance | -101     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1299     |
|    policy_loss        | -0.236   |
|    std                | 1.05     |
|    value_loss         | 0.00243  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 393      |
|    iterations         | 1400     |
|    time_elapsed       | 35       |
|    total_timesteps    | 14000    |
| train/                |          |
|    entropy_loss       | -22.1    |
|    explained_variance | -165     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1399     |
|    policy_loss        | 0.524    |
|    std                | 1.05     |
|    value_loss         | 0.00509  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 392      |
|    iterations         | 1500     |
|    time_elapsed       | 38       |
|    total_timesteps    | 15000    |
| train/                |          |
|    entropy_loss       | -22.1    |
|    explained_variance | -147     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1499     |
|    policy_loss        | 0.0101   |
|    std                | 1.06     |
|    value_loss         | 0.00077  |
------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 392      |
|    iterations         | 1600     |
|    time_elapsed       | 40       |
|    total_timesteps    | 16000    |
| train/                |          |
|    entropy_loss       | -22.2    |
|    explained_variance | -63      |
|    learning_rate      | 0.0004   |
|    n_updates          | 1599     |
|    policy_loss        | -2.3     |
|    std                | 1.06     |
|    value_loss         | 0.0143   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 393      |
|    iterations         | 1700     |
|    time_elapsed       | 43       |
|    total_timesteps    | 17000    |
| train/                |          |
|    entropy_loss       | -22.3    |
|    explained_variance | -442     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1699     |
|    policy_loss        | -0.518   |
|    std                | 1.07     |
|    value_loss         | 0.00396  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 394      |
|    iterations         | 1800     |
|    time_elapsed       | 45       |
|    total_timesteps    | 18000    |
| train/                |          |
|    entropy_loss       | -22.4    |
|    explained_variance | -16.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 1799     |
|    policy_loss        | 3.87     |
|    std                | 1.08     |
|    value_loss         | 0.0309   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 394       |
|    iterations         | 1900      |
|    time_elapsed       | 48        |
|    total_timesteps    | 19000     |
| train/                |           |
|    entropy_loss       | -22.5     |
|    explained_variance | -1.47e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 1899      |
|    policy_loss        | 0.215     |
|    std                | 1.08      |
|    value_loss         | 0.00431   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 395      |
|    iterations         | 2000     |
|    time_elapsed       | 50       |
|    total_timesteps    | 20000    |
| train/                |          |
|    entropy_loss       | -22.6    |
|    explained_variance | -152     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1999     |
|    policy_loss        | -2.43    |
|    std                | 1.09     |
|    value_loss         | 0.0139   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 395      |
|    iterations         | 2100     |
|    time_elapsed       | 53       |
|    total_timesteps    | 21000    |
| train/                |          |
|    entropy_loss       | -22.7    |
|    explained_variance | -901     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2099     |
|    policy_loss        | -0.345   |
|    std                | 1.1      |
|    value_loss         | 0.00244  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 394      |
|    iterations         | 2200     |
|    time_elapsed       | 55       |
|    total_timesteps    | 22000    |
| train/                |          |
|    entropy_loss       | -22.8    |
|    explained_variance | -152     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2199     |
|    policy_loss        | 1.41     |
|    std                | 1.1      |
|    value_loss         | 0.00946  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 392      |
|    iterations         | 2300     |
|    time_elapsed       | 58       |
|    total_timesteps    | 23000    |
| train/                |          |
|    entropy_loss       | -22.9    |
|    explained_variance | -16.4    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2299     |
|    policy_loss        | 0.0384   |
|    std                | 1.11     |
|    value_loss         | 0.00153  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 387      |
|    iterations         | 2400     |
|    time_elapsed       | 61       |
|    total_timesteps    | 24000    |
| train/                |          |
|    entropy_loss       | -23      |
|    explained_variance | -597     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2399     |
|    policy_loss        | 1.05     |
|    std                | 1.12     |
|    value_loss         | 0.00623  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 386      |
|    iterations         | 2500     |
|    time_elapsed       | 64       |
|    total_timesteps    | 25000    |
| train/                |          |
|    entropy_loss       | -23.1    |
|    explained_variance | -105     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2499     |
|    policy_loss        | -0.814   |
|    std                | 1.13     |
|    value_loss         | 0.00353  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 384      |
|    iterations         | 2600     |
|    time_elapsed       | 67       |
|    total_timesteps    | 26000    |
| train/                |          |
|    entropy_loss       | -23.2    |
|    explained_variance | -134     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2599     |
|    policy_loss        | 0.198    |
|    std                | 1.13     |
|    value_loss         | 0.00128  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 380      |
|    iterations         | 2700     |
|    time_elapsed       | 70       |
|    total_timesteps    | 27000    |
| train/                |          |
|    entropy_loss       | -23.3    |
|    explained_variance | -573     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2699     |
|    policy_loss        | 0.399    |
|    std                | 1.14     |
|    value_loss         | 0.0067   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 379      |
|    iterations         | 2800     |
|    time_elapsed       | 73       |
|    total_timesteps    | 28000    |
| train/                |          |
|    entropy_loss       | -23.4    |
|    explained_variance | -26.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2799     |
|    policy_loss        | 0.597    |
|    std                | 1.15     |
|    value_loss         | 0.00128  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 378      |
|    iterations         | 2900     |
|    time_elapsed       | 76       |
|    total_timesteps    | 29000    |
| train/                |          |
|    entropy_loss       | -23.6    |
|    explained_variance | -106     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2899     |
|    policy_loss        | -1.73    |
|    std                | 1.16     |
|    value_loss         | 0.00761  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 378      |
|    iterations         | 3000     |
|    time_elapsed       | 79       |
|    total_timesteps    | 30000    |
| train/                |          |
|    entropy_loss       | -23.7    |
|    explained_variance | -802     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2999     |
|    policy_loss        | 1.12     |
|    std                | 1.17     |
|    value_loss         | 0.00393  |
------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 377      |
|    iterations         | 3100     |
|    time_elapsed       | 82       |
|    total_timesteps    | 31000    |
| train/                |          |
|    entropy_loss       | -23.8    |
|    explained_variance | -33.3    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3099     |
|    policy_loss        | -0.341   |
|    std                | 1.18     |
|    value_loss         | 0.00179  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 376      |
|    iterations         | 3200     |
|    time_elapsed       | 84       |
|    total_timesteps    | 32000    |
| train/                |          |
|    entropy_loss       | -23.9    |
|    explained_variance | -102     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3199     |
|    policy_loss        | -0.588   |
|    std                | 1.19     |
|    value_loss         | 0.0024   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 374      |
|    iterations         | 3300     |
|    time_elapsed       | 88       |
|    total_timesteps    | 33000    |
| train/                |          |
|    entropy_loss       | -24.1    |
|    explained_variance | -202     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3299     |
|    policy_loss        | -0.109   |
|    std                | 1.2      |
|    value_loss         | 0.00224  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 373       |
|    iterations         | 3400      |
|    time_elapsed       | 91        |
|    total_timesteps    | 34000     |
| train/                |           |
|    entropy_loss       | -24.2     |
|    explained_variance | -1.15e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 3399      |
|    policy_loss        | 0.473     |
|    std                | 1.21      |
|    value_loss         | 0.000954  |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 373      |
|    iterations         | 3500     |
|    time_elapsed       | 93       |
|    total_timesteps    | 35000    |
| train/                |          |
|    entropy_loss       | -24.3    |
|    explained_variance | -987     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3499     |
|    policy_loss        | -0.0532  |
|    std                | 1.23     |
|    value_loss         | 0.00126  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 373      |
|    iterations         | 3600     |
|    time_elapsed       | 96       |
|    total_timesteps    | 36000    |
| train/                |          |
|    entropy_loss       | -24.5    |
|    explained_variance | -21.3    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3599     |
|    policy_loss        | 0.106    |
|    std                | 1.24     |
|    value_loss         | 0.00126  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 373       |
|    iterations         | 3700      |
|    time_elapsed       | 99        |
|    total_timesteps    | 37000     |
| train/                |           |
|    entropy_loss       | -24.6     |
|    explained_variance | -1.18e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 3699      |
|    policy_loss        | -0.311    |
|    std                | 1.25      |
|    value_loss         | 0.00264   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 372      |
|    iterations         | 3800     |
|    time_elapsed       | 102      |
|    total_timesteps    | 38000    |
| train/                |          |
|    entropy_loss       | -24.8    |
|    explained_variance | -52.3    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3799     |
|    policy_loss        | 1.04     |
|    std                | 1.26     |
|    value_loss         | 0.00309  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 371      |
|    iterations         | 3900     |
|    time_elapsed       | 104      |
|    total_timesteps    | 39000    |
| train/                |          |
|    entropy_loss       | -24.9    |
|    explained_variance | -51.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3899     |
|    policy_loss        | -0.514   |
|    std                | 1.27     |
|    value_loss         | 0.00152  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 371      |
|    iterations         | 4000     |
|    time_elapsed       | 107      |
|    total_timesteps    | 40000    |
| train/                |          |
|    entropy_loss       | -25.1    |
|    explained_variance | -34.3    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3999     |
|    policy_loss        | 0.183    |
|    std                | 1.29     |
|    value_loss         | 0.00189  |
------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A1_Transformer_only_a2c_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A1_Transformer_only_a2c_seed1_actions.csv
{'CR': -0.028502132202560038, 'AR': -0.029662266695985706, 'Vol': 0.03714194364927847, 'SR': -0.7986191292539407, 'MDD': -0.06639045966301094, 'Calmar': -0.4467850779546849, 'Sortino': -1.3092922250328645, 'Omega': 0.8707259349533354, 'Turnover': 0.6784777392642575, 'FinalAccountValue': 971497.8677974411, 'variant': 'A1_Transformer_only', 'agent': 'a2c', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A1_Transformer_only.CSV'}

========== A1_Transformer_only | PPO | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A1_Transformer_only.CSV
[banktrademergeGNNtr20241231_A1_Transformer_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 2048, 'ent_coef': 0.005, 'learning_rate': 0.001, 'batch_size': 128, 'seed': 1}
Using cpu device
Logging to tensorboard_log/ppo\A1_Transformer_only_ppo_seed1_3

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

-----------------------------
| time/              |      |
|    fps             | 536  |
|    iterations      | 1    |
|    time_elapsed    | 3    |
|    total_timesteps | 2048 |
-----------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 432        |
|    iterations           | 2          |
|    time_elapsed         | 9          |
|    total_timesteps      | 4096       |
| train/                  |            |
|    approx_kl            | 0.04596843 |
|    clip_fraction        | 0.404      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | -50.5      |
|    learning_rate        | 0.001      |
|    loss                 | -0.184     |
|    n_updates            | 10         |
|    policy_gradient_loss | -0.0718    |
|    std                  | 1          |
|    value_loss           | 0.0369     |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 398         |
|    iterations           | 3           |
|    time_elapsed         | 15          |
|    total_timesteps      | 6144        |
| train/                  |             |
|    approx_kl            | 0.057741567 |
|    clip_fraction        | 0.438       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | -1.52       |
|    learning_rate        | 0.001       |
|    loss                 | -0.187      |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0671     |
|    std                  | 0.997       |
|    value_loss           | 0.00282     |
-----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 387       |
|    iterations           | 4         |
|    time_elapsed         | 21        |
|    total_timesteps      | 8192      |
| train/                  |           |
|    approx_kl            | 0.0650342 |
|    clip_fraction        | 0.473     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.2     |
|    explained_variance   | 0.396     |
|    learning_rate        | 0.001     |
|    loss                 | -0.171    |
|    n_updates            | 30        |
|    policy_gradient_loss | -0.0655   |
|    std                  | 0.996     |
|    value_loss           | 0.00095   |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 376        |
|    iterations           | 5          |
|    time_elapsed         | 27         |
|    total_timesteps      | 10240      |
| train/                  |            |
|    approx_kl            | 0.07934596 |
|    clip_fraction        | 0.511      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.668      |
|    learning_rate        | 0.001      |
|    loss                 | -0.167     |
|    n_updates            | 40         |
|    policy_gradient_loss | -0.0631    |
|    std                  | 0.998      |
|    value_loss           | 0.000477   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 373        |
|    iterations           | 6          |
|    time_elapsed         | 32         |
|    total_timesteps      | 12288      |
| train/                  |            |
|    approx_kl            | 0.07633846 |
|    clip_fraction        | 0.508      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.787      |
|    learning_rate        | 0.001      |
|    loss                 | -0.189     |
|    n_updates            | 50         |
|    policy_gradient_loss | -0.0657    |
|    std                  | 0.996      |
|    value_loss           | 0.000346   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 376        |
|    iterations           | 7          |
|    time_elapsed         | 38         |
|    total_timesteps      | 14336      |
| train/                  |            |
|    approx_kl            | 0.07520617 |
|    clip_fraction        | 0.492      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.82       |
|    learning_rate        | 0.001      |
|    loss                 | -0.201     |
|    n_updates            | 60         |
|    policy_gradient_loss | -0.0604    |
|    std                  | 1          |
|    value_loss           | 0.000228   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 375         |
|    iterations           | 8           |
|    time_elapsed         | 43          |
|    total_timesteps      | 16384       |
| train/                  |             |
|    approx_kl            | 0.099683166 |
|    clip_fraction        | 0.547       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | 0.875       |
|    learning_rate        | 0.001       |
|    loss                 | -0.192      |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.056      |
|    std                  | 1           |
|    value_loss           | 0.000177    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 377        |
|    iterations           | 9          |
|    time_elapsed         | 48         |
|    total_timesteps      | 18432      |
| train/                  |            |
|    approx_kl            | 0.09620414 |
|    clip_fraction        | 0.522      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.838      |
|    learning_rate        | 0.001      |
|    loss                 | -0.172     |
|    n_updates            | 80         |
|    policy_gradient_loss | -0.053     |
|    std                  | 1.01       |
|    value_loss           | 0.000144   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 378        |
|    iterations           | 10         |
|    time_elapsed         | 54         |
|    total_timesteps      | 20480      |
| train/                  |            |
|    approx_kl            | 0.09968488 |
|    clip_fraction        | 0.533      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.828      |
|    learning_rate        | 0.001      |
|    loss                 | -0.189     |
|    n_updates            | 90         |
|    policy_gradient_loss | -0.0549    |
|    std                  | 1          |
|    value_loss           | 0.000134   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 374        |
|    iterations           | 11         |
|    time_elapsed         | 60         |
|    total_timesteps      | 22528      |
| train/                  |            |
|    approx_kl            | 0.09681736 |
|    clip_fraction        | 0.541      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.835      |
|    learning_rate        | 0.001      |
|    loss                 | -0.206     |
|    n_updates            | 100        |
|    policy_gradient_loss | -0.0575    |
|    std                  | 0.999      |
|    value_loss           | 0.000137   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 373        |
|    iterations           | 12         |
|    time_elapsed         | 65         |
|    total_timesteps      | 24576      |
| train/                  |            |
|    approx_kl            | 0.10770164 |
|    clip_fraction        | 0.56       |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.831      |
|    learning_rate        | 0.001      |
|    loss                 | -0.202     |
|    n_updates            | 110        |
|    policy_gradient_loss | -0.0657    |
|    std                  | 1          |
|    value_loss           | 0.000231   |
----------------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 372        |
|    iterations           | 13         |
|    time_elapsed         | 71         |
|    total_timesteps      | 26624      |
| train/                  |            |
|    approx_kl            | 0.11227764 |
|    clip_fraction        | 0.551      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.367      |
|    learning_rate        | 0.001      |
|    loss                 | -0.188     |
|    n_updates            | 120        |
|    policy_gradient_loss | -0.0544    |
|    std                  | 1.01       |
|    value_loss           | 0.000143   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 369        |
|    iterations           | 14         |
|    time_elapsed         | 77         |
|    total_timesteps      | 28672      |
| train/                  |            |
|    approx_kl            | 0.12087403 |
|    clip_fraction        | 0.562      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.782      |
|    learning_rate        | 0.001      |
|    loss                 | -0.175     |
|    n_updates            | 130        |
|    policy_gradient_loss | -0.054     |
|    std                  | 1.01       |
|    value_loss           | 7.35e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 369        |
|    iterations           | 15         |
|    time_elapsed         | 83         |
|    total_timesteps      | 30720      |
| train/                  |            |
|    approx_kl            | 0.12652272 |
|    clip_fraction        | 0.572      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.833      |
|    learning_rate        | 0.001      |
|    loss                 | -0.189     |
|    n_updates            | 140        |
|    policy_gradient_loss | -0.0525    |
|    std                  | 1.01       |
|    value_loss           | 7.55e-05   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 368         |
|    iterations           | 16          |
|    time_elapsed         | 88          |
|    total_timesteps      | 32768       |
| train/                  |             |
|    approx_kl            | 0.113599315 |
|    clip_fraction        | 0.55        |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.5       |
|    explained_variance   | 0.652       |
|    learning_rate        | 0.001       |
|    loss                 | -0.181      |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.0461     |
|    std                  | 1.02        |
|    value_loss           | 8.27e-05    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 366        |
|    iterations           | 17         |
|    time_elapsed         | 94         |
|    total_timesteps      | 34816      |
| train/                  |            |
|    approx_kl            | 0.13720393 |
|    clip_fraction        | 0.566      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.6      |
|    explained_variance   | 0.774      |
|    learning_rate        | 0.001      |
|    loss                 | -0.168     |
|    n_updates            | 160        |
|    policy_gradient_loss | -0.0538    |
|    std                  | 1.03       |
|    value_loss           | 6.21e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 366        |
|    iterations           | 18         |
|    time_elapsed         | 100        |
|    total_timesteps      | 36864      |
| train/                  |            |
|    approx_kl            | 0.12832616 |
|    clip_fraction        | 0.559      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.6      |
|    explained_variance   | 0.871      |
|    learning_rate        | 0.001      |
|    loss                 | -0.18      |
|    n_updates            | 170        |
|    policy_gradient_loss | -0.0542    |
|    std                  | 1.03       |
|    value_loss           | 5.79e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 366        |
|    iterations           | 19         |
|    time_elapsed         | 106        |
|    total_timesteps      | 38912      |
| train/                  |            |
|    approx_kl            | 0.12565312 |
|    clip_fraction        | 0.558      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.7      |
|    explained_variance   | 0.815      |
|    learning_rate        | 0.001      |
|    loss                 | -0.182     |
|    n_updates            | 180        |
|    policy_gradient_loss | -0.0556    |
|    std                  | 1.03       |
|    value_loss           | 4.83e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 364        |
|    iterations           | 20         |
|    time_elapsed         | 112        |
|    total_timesteps      | 40960      |
| train/                  |            |
|    approx_kl            | 0.11018238 |
|    clip_fraction        | 0.562      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.8      |
|    explained_variance   | 0.819      |
|    learning_rate        | 0.001      |
|    loss                 | -0.216     |
|    n_updates            | 190        |
|    policy_gradient_loss | -0.0489    |
|    std                  | 1.04       |
|    value_loss           | 5.25e-05   |
----------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A1_Transformer_only_ppo_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A1_Transformer_only_ppo_seed1_actions.csv
{'CR': -0.024704393395042934, 'AR': -0.02571200045432387, 'Vol': 0.03294992709246996, 'SR': -0.7803355795649037, 'MDD': -0.05001458665162639, 'Calmar': -0.5140900320424373, 'Sortino': -1.1813239428756168, 'Omega': 0.8759412397973544, 'Turnover': 0.7474776006463311, 'FinalAccountValue': 975295.6066049568, 'variant': 'A1_Transformer_only', 'agent': 'ppo', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A1_Transformer_only.CSV'}

========== A1_Transformer_only | SAC | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A1_Transformer_only.CSV
[banktrademergeGNNtr20241231_A1_Transformer_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 128, 'buffer_size': 1000000, 'learning_rate': 0.0001, 'learning_starts': 100, 'ent_coef': 'auto_0.1', 'seed': 1}
Using cpu device
Logging to tensorboard_log/sac\A1_Transformer_only_sac_seed1_3

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 14       |
|    time_elapsed    | 203      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | -9.78    |
|    critic_loss     | 0.0144   |
|    ent_coef        | 0.0753   |
|    ent_coef_loss   | -64.8    |
|    learning_rate   | 0.0001   |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 13       |
|    time_elapsed    | 414      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | -16.5    |
|    critic_loss     | 0.0332   |
|    ent_coef        | 0.0564   |
|    ent_coef_loss   | -72.5    |
|    learning_rate   | 0.0001   |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 13       |
|    time_elapsed    | 630      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | -20.3    |
|    critic_loss     | 0.0135   |
|    ent_coef        | 0.0422   |
|    ent_coef_loss   | -80      |
|    learning_rate   | 0.0001   |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 13       |
|    time_elapsed    | 861      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | -21.8    |
|    critic_loss     | 0.0164   |
|    ent_coef        | 0.0316   |
|    ent_coef_loss   | -87.2    |
|    learning_rate   | 0.0001   |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 13       |
|    time_elapsed    | 1099     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | -21.8    |
|    critic_loss     | 0.0349   |
|    ent_coef        | 0.0237   |
|    ent_coef_loss   | -94.3    |
|    learning_rate   | 0.0001   |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 12       |
|    time_elapsed    | 1335     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | -21.1    |
|    critic_loss     | 0.0115   |
|    ent_coef        | 0.0178   |
|    ent_coef_loss   | -102     |
|    learning_rate   | 0.0001   |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 12       |
|    time_elapsed    | 1573     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | -19.9    |
|    critic_loss     | 0.0101   |
|    ent_coef        | 0.0133   |
|    ent_coef_loss   | -108     |
|    learning_rate   | 0.0001   |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1813     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | -18.4    |
|    critic_loss     | 0.026    |
|    ent_coef        | 0.00998  |
|    ent_coef_loss   | -116     |
|    learning_rate   | 0.0001   |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2051     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | -15.5    |
|    critic_loss     | 0.0152   |
|    ent_coef        | 0.00748  |
|    ent_coef_loss   | -122     |
|    learning_rate   | 0.0001   |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 12       |
|    time_elapsed    | 2288     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | -15.1    |
|    critic_loss     | 0.00532  |
|    ent_coef        | 0.00561  |
|    ent_coef_loss   | -130     |
|    learning_rate   | 0.0001   |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 12       |
|    time_elapsed    | 2527     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -13      |
|    critic_loss     | 0.00594  |
|    ent_coef        | 0.00421  |
|    ent_coef_loss   | -135     |
|    learning_rate   | 0.0001   |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 12       |
|    time_elapsed    | 2766     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -11.2    |
|    critic_loss     | 0.00534  |
|    ent_coef        | 0.00316  |
|    ent_coef_loss   | -140     |
|    learning_rate   | 0.0001   |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 12       |
|    time_elapsed    | 3003     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -9.78    |
|    critic_loss     | 0.0025   |
|    ent_coef        | 0.00237  |
|    ent_coef_loss   | -147     |
|    learning_rate   | 0.0001   |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 12       |
|    time_elapsed    | 3242     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -8.9     |
|    critic_loss     | 0.0109   |
|    ent_coef        | 0.00178  |
|    ent_coef_loss   | -148     |
|    learning_rate   | 0.0001   |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 12       |
|    time_elapsed    | 3480     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -7.34    |
|    critic_loss     | 0.00322  |
|    ent_coef        | 0.00134  |
|    ent_coef_loss   | -153     |
|    learning_rate   | 0.0001   |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 12       |
|    time_elapsed    | 3716     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -6.53    |
|    critic_loss     | 0.00147  |
|    ent_coef        | 0.001    |
|    ent_coef_loss   | -159     |
|    learning_rate   | 0.0001   |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 12       |
|    time_elapsed    | 3955     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -5.47    |
|    critic_loss     | 0.00415  |
|    ent_coef        | 0.000755 |
|    ent_coef_loss   | -157     |
|    learning_rate   | 0.0001   |
|    n_updates       | 48927    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 72       |
|    fps             | 12       |
|    time_elapsed    | 4188     |
|    total_timesteps | 51912    |
| train/             |          |
|    actor_loss      | -4.56    |
|    critic_loss     | 0.00123  |
|    ent_coef        | 0.000568 |
|    ent_coef_loss   | -155     |
|    learning_rate   | 0.0001   |
|    n_updates       | 51811    |
---------------------------------

---------------------------------
| time/              |          |
|    episodes        | 76       |
|    fps             | 12       |
|    time_elapsed    | 4421     |
|    total_timesteps | 54796    |
| train/             |          |
|    actor_loss      | -3.72    |
|    critic_loss     | 0.00147  |
|    ent_coef        | 0.000428 |
|    ent_coef_loss   | -155     |
|    learning_rate   | 0.0001   |
|    n_updates       | 54695    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 80       |
|    fps             | 12       |
|    time_elapsed    | 4657     |
|    total_timesteps | 57680    |
| train/             |          |
|    actor_loss      | -3.15    |
|    critic_loss     | 0.00269  |
|    ent_coef        | 0.000323 |
|    ent_coef_loss   | -151     |
|    learning_rate   | 0.0001   |
|    n_updates       | 57579    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A1_Transformer_only_sac_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A1_Transformer_only_sac_seed1_actions.csv
{'CR': -0.032789877025341974, 'AR': -0.034121451934221336, 'Vol': 0.03220846693431732, 'SR': -1.0593938545353667, 'MDD': -0.058342625560694694, 'Calmar': -0.5848460127788436, 'Sortino': -1.6412791935927704, 'Omega': 0.8356221537250907, 'Turnover': 0.6597777200011418, 'FinalAccountValue': 967210.1229746584, 'variant': 'A1_Transformer_only', 'agent': 'sac', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A1_Transformer_only.CSV'}

========== A1_Transformer_only | TD3 | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A1_Transformer_only.CSV
[banktrademergeGNNtr20241231_A1_Transformer_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 100, 'buffer_size': 1000000, 'learning_rate': 0.001, 'seed': 1}
Using cpu device
Logging to tensorboard_log/td3\A1_Transformer_only_td3_seed1_3

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 16       |
|    time_elapsed    | 177      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 0.991    |
|    critic_loss     | 0.00497  |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 15       |
|    time_elapsed    | 370      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 1        |
|    critic_loss     | 0.00233  |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 15       |
|    time_elapsed    | 575      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.877    |
|    critic_loss     | 0.00412  |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 14       |
|    time_elapsed    | 794      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.883    |
|    critic_loss     | 0.000808 |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 13       |
|    time_elapsed    | 1030     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.814    |
|    critic_loss     | 0.000251 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 13       |
|    time_elapsed    | 1284     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.679    |
|    critic_loss     | 0.00167  |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 12       |
|    time_elapsed    | 1556     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.698    |
|    critic_loss     | 0.000118 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1836     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.625    |
|    critic_loss     | 0.000185 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2120     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.592    |
|    critic_loss     | 0.000418 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 11       |
|    time_elapsed    | 2414     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.516    |
|    critic_loss     | 0.000136 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A1_Transformer_only_td3_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A1_Transformer_only_td3_seed1_actions.csv
{'CR': -0.043179392952004014, 'AR': -0.044922986158741796, 'Vol': 0.0377336468395563, 'SR': -1.190528610970326, 'MDD': -0.0755502597268376, 'Calmar': -0.5946106118121507, 'Sortino': -1.890440434706248, 'Omega': 0.8198810198814177, 'Turnover': 0.6740265343107829, 'FinalAccountValue': 956820.6070479963, 'variant': 'A1_Transformer_only', 'agent': 'td3', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A1_Transformer_only.CSV'}

========== A1_Transformer_only | DDPG | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A1_Transformer_only.CSV
[banktrademergeGNNtr20241231_A1_Transformer_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'seed': 1}
Using cpu device
Logging to tensorboard_log/ddpg\A1_Transformer_only_ddpg_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 11       |
|    time_elapsed    | 259      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 0.65     |
|    critic_loss     | 0.00293  |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 10       |
|    time_elapsed    | 527      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.54     |
|    critic_loss     | 0.000162 |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 10       |
|    time_elapsed    | 807      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.407    |
|    critic_loss     | 0.000982 |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 10       |
|    time_elapsed    | 1086     |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.318    |
|    critic_loss     | 0.000165 |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 10       |
|    time_elapsed    | 1371     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.25     |
|    critic_loss     | 6.07e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 10       |
|    time_elapsed    | 1676     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.197    |
|    critic_loss     | 7.06e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 10       |
|    time_elapsed    | 1994     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.125    |
|    critic_loss     | 0.000267 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 9        |
|    time_elapsed    | 2316     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.0908   |
|    critic_loss     | 0.00019  |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 9        |
|    time_elapsed    | 2646     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.0498   |
|    critic_loss     | 4.45e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 9        |
|    time_elapsed    | 2991     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.00747  |
|    critic_loss     | 2.23e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 9        |
|    time_elapsed    | 3330     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -0.0151  |
|    critic_loss     | 2.88e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 9        |
|    time_elapsed    | 3673     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -0.0508  |
|    critic_loss     | 1.63e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 9        |
|    time_elapsed    | 4021     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -0.0781  |
|    critic_loss     | 1.85e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 9        |
|    time_elapsed    | 4370     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -0.0977  |
|    critic_loss     | 1.58e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 9        |
|    time_elapsed    | 4731     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -0.13    |
|    critic_loss     | 1.42e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 9        |
|    time_elapsed    | 5089     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -0.135   |
|    critic_loss     | 2.01e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 8        |
|    time_elapsed    | 5447     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -0.149   |
|    critic_loss     | 9.73e-06 |
|    learning_rate   | 0.001    |
|    n_updates       | 48927    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A1_Transformer_only_ddpg_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A1_Transformer_only_ddpg_seed1_actions.csv
{'CR': -0.040624668815856024, 'AR': -0.04226739633569321, 'Vol': 0.03709346212822426, 'SR': -1.1394837232929014, 'MDD': -0.07120325671908234, 'Calmar': -0.5936160547044982, 'Sortino': -1.741871335477195, 'Omega': 0.8192586673114187, 'Turnover': 0.8921694384961181, 'FinalAccountValue': 959375.3311841442, 'variant': 'A1_Transformer_only', 'agent': 'ddpg', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A1_Transformer_only.CSV'}
[banktrademergeGNNtr20241231_A2_MGNN_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630

========== A2_MGNN_only | A2C | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A2_MGNN_only.CSV
[banktrademergeGNNtr20241231_A2_MGNN_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 10, 'ent_coef': 0.005, 'learning_rate': 0.0004, 'seed': 1}
Using cpu device
Logging to tensorboard_log/a2c\A2_MGNN_only_a2c_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

-------------------------------------
| time/                 |           |
|    fps                | 421       |
|    iterations         | 100       |
|    time_elapsed       | 2         |
|    total_timesteps    | 1000      |
| train/                |           |
|    entropy_loss       | -21.3     |
|    explained_variance | -5.82e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 99        |
|    policy_loss        | 6.06      |
|    std                | 1         |
|    value_loss         | 0.141     |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 394       |
|    iterations         | 200       |
|    time_elapsed       | 5         |
|    total_timesteps    | 2000      |
| train/                |           |
|    entropy_loss       | -21.3     |
|    explained_variance | -3.97e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 199       |
|    policy_loss        | -7        |
|    std                | 1         |
|    value_loss         | 0.159     |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 394      |
|    iterations         | 300      |
|    time_elapsed       | 7        |
|    total_timesteps    | 3000     |
| train/                |          |
|    entropy_loss       | -21.3    |
|    explained_variance | -3.9e+03 |
|    learning_rate      | 0.0004   |
|    n_updates          | 299      |
|    policy_loss        | 2.55     |
|    std                | 1        |
|    value_loss         | 0.0659   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 400      |
|    time_elapsed       | 10       |
|    total_timesteps    | 4000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -2e+03   |
|    learning_rate      | 0.0004   |
|    n_updates          | 399      |
|    policy_loss        | -2.01    |
|    std                | 1.01     |
|    value_loss         | 0.0153   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 403      |
|    iterations         | 500      |
|    time_elapsed       | 12       |
|    total_timesteps    | 5000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -178     |
|    learning_rate      | 0.0004   |
|    n_updates          | 499      |
|    policy_loss        | -3.37    |
|    std                | 1.01     |
|    value_loss         | 0.042    |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 407       |
|    iterations         | 600       |
|    time_elapsed       | 14        |
|    total_timesteps    | 6000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -3.36e+05 |
|    learning_rate      | 0.0004    |
|    n_updates          | 599       |
|    policy_loss        | -2.69     |
|    std                | 1.01      |
|    value_loss         | 0.0278    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 409      |
|    iterations         | 700      |
|    time_elapsed       | 17       |
|    total_timesteps    | 7000     |
| train/                |          |
|    entropy_loss       | -21.5    |
|    explained_variance | -159     |
|    learning_rate      | 0.0004   |
|    n_updates          | 699      |
|    policy_loss        | 1.66     |
|    std                | 1.01     |
|    value_loss         | 0.0137   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 408       |
|    iterations         | 800       |
|    time_elapsed       | 19        |
|    total_timesteps    | 8000      |
| train/                |           |
|    entropy_loss       | -21.5     |
|    explained_variance | -1.21e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 799       |
|    policy_loss        | 2.22      |
|    std                | 1.02      |
|    value_loss         | 0.0141    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 403      |
|    iterations         | 900      |
|    time_elapsed       | 22       |
|    total_timesteps    | 9000     |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -574     |
|    learning_rate      | 0.0004   |
|    n_updates          | 899      |
|    policy_loss        | -0.244   |
|    std                | 1.02     |
|    value_loss         | 0.00902  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 404      |
|    iterations         | 1000     |
|    time_elapsed       | 24       |
|    total_timesteps    | 10000    |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -104     |
|    learning_rate      | 0.0004   |
|    n_updates          | 999      |
|    policy_loss        | -3.39    |
|    std                | 1.03     |
|    value_loss         | 0.0343   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 405       |
|    iterations         | 1100      |
|    time_elapsed       | 27        |
|    total_timesteps    | 11000     |
| train/                |           |
|    entropy_loss       | -21.8     |
|    explained_variance | -3.15e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 1099      |
|    policy_loss        | 1.49      |
|    std                | 1.03      |
|    value_loss         | 0.0109    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 406      |
|    iterations         | 1200     |
|    time_elapsed       | 29       |
|    total_timesteps    | 12000    |
| train/                |          |
|    entropy_loss       | -21.8    |
|    explained_variance | -884     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1199     |
|    policy_loss        | 2.14     |
|    std                | 1.04     |
|    value_loss         | 0.0162   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 405      |
|    iterations         | 1300     |
|    time_elapsed       | 32       |
|    total_timesteps    | 13000    |
| train/                |          |
|    entropy_loss       | -21.9    |
|    explained_variance | -161     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1299     |
|    policy_loss        | -0.502   |
|    std                | 1.04     |
|    value_loss         | 0.0047   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 405      |
|    iterations         | 1400     |
|    time_elapsed       | 34       |
|    total_timesteps    | 14000    |
| train/                |          |
|    entropy_loss       | -22      |
|    explained_variance | -323     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1399     |
|    policy_loss        | -3.53    |
|    std                | 1.05     |
|    value_loss         | 0.0266   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 403       |
|    iterations         | 1500      |
|    time_elapsed       | 37        |
|    total_timesteps    | 15000     |
| train/                |           |
|    entropy_loss       | -22.1     |
|    explained_variance | -1.09e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 1499      |
|    policy_loss        | 0.52      |
|    std                | 1.05      |
|    value_loss         | 0.00494   |
-------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 1600     |
|    time_elapsed       | 39       |
|    total_timesteps    | 16000    |
| train/                |          |
|    entropy_loss       | -22.1    |
|    explained_variance | -127     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1599     |
|    policy_loss        | 0.43     |
|    std                | 1.06     |
|    value_loss         | 0.00251  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 402      |
|    iterations         | 1700     |
|    time_elapsed       | 42       |
|    total_timesteps    | 17000    |
| train/                |          |
|    entropy_loss       | -22.2    |
|    explained_variance | -149     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1699     |
|    policy_loss        | 0.263    |
|    std                | 1.07     |
|    value_loss         | 0.003    |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 403      |
|    iterations         | 1800     |
|    time_elapsed       | 44       |
|    total_timesteps    | 18000    |
| train/                |          |
|    entropy_loss       | -22.3    |
|    explained_variance | -46.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 1799     |
|    policy_loss        | 1.8      |
|    std                | 1.07     |
|    value_loss         | 0.00845  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 403      |
|    iterations         | 1900     |
|    time_elapsed       | 47       |
|    total_timesteps    | 19000    |
| train/                |          |
|    entropy_loss       | -22.5    |
|    explained_variance | -434     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1899     |
|    policy_loss        | 1.62     |
|    std                | 1.08     |
|    value_loss         | 0.0094   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 404      |
|    iterations         | 2000     |
|    time_elapsed       | 49       |
|    total_timesteps    | 20000    |
| train/                |          |
|    entropy_loss       | -22.6    |
|    explained_variance | -760     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1999     |
|    policy_loss        | 1.13     |
|    std                | 1.09     |
|    value_loss         | 0.00668  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 403      |
|    iterations         | 2100     |
|    time_elapsed       | 51       |
|    total_timesteps    | 21000    |
| train/                |          |
|    entropy_loss       | -22.6    |
|    explained_variance | -877     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2099     |
|    policy_loss        | -0.452   |
|    std                | 1.09     |
|    value_loss         | 0.00322  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 2200     |
|    time_elapsed       | 54       |
|    total_timesteps    | 22000    |
| train/                |          |
|    entropy_loss       | -22.7    |
|    explained_variance | -27      |
|    learning_rate      | 0.0004   |
|    n_updates          | 2199     |
|    policy_loss        | -2.8     |
|    std                | 1.1      |
|    value_loss         | 0.0161   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 2300     |
|    time_elapsed       | 57       |
|    total_timesteps    | 23000    |
| train/                |          |
|    entropy_loss       | -22.8    |
|    explained_variance | -12.4    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2299     |
|    policy_loss        | -2.45    |
|    std                | 1.11     |
|    value_loss         | 0.0129   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 2400     |
|    time_elapsed       | 59       |
|    total_timesteps    | 24000    |
| train/                |          |
|    entropy_loss       | -23      |
|    explained_variance | -173     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2399     |
|    policy_loss        | 0.968    |
|    std                | 1.12     |
|    value_loss         | 0.00556  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 402      |
|    iterations         | 2500     |
|    time_elapsed       | 62       |
|    total_timesteps    | 25000    |
| train/                |          |
|    entropy_loss       | -23.1    |
|    explained_variance | -14.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2499     |
|    policy_loss        | -0.362   |
|    std                | 1.13     |
|    value_loss         | 0.000591 |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 2600     |
|    time_elapsed       | 64       |
|    total_timesteps    | 26000    |
| train/                |          |
|    entropy_loss       | -23.2    |
|    explained_variance | -344     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2599     |
|    policy_loss        | -0.557   |
|    std                | 1.13     |
|    value_loss         | 0.00221  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 2700     |
|    time_elapsed       | 67       |
|    total_timesteps    | 27000    |
| train/                |          |
|    entropy_loss       | -23.3    |
|    explained_variance | -56.6    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2699     |
|    policy_loss        | -0.61    |
|    std                | 1.14     |
|    value_loss         | 0.00296  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 2800     |
|    time_elapsed       | 69       |
|    total_timesteps    | 28000    |
| train/                |          |
|    entropy_loss       | -23.4    |
|    explained_variance | -442     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2799     |
|    policy_loss        | -0.288   |
|    std                | 1.15     |
|    value_loss         | 0.00235  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 2900     |
|    time_elapsed       | 72       |
|    total_timesteps    | 29000    |
| train/                |          |
|    entropy_loss       | -23.5    |
|    explained_variance | -717     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2899     |
|    policy_loss        | -1.01    |
|    std                | 1.16     |
|    value_loss         | 0.00307  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 3000     |
|    time_elapsed       | 74       |
|    total_timesteps    | 30000    |
| train/                |          |
|    entropy_loss       | -23.6    |
|    explained_variance | -624     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2999     |
|    policy_loss        | -0.925   |
|    std                | 1.17     |
|    value_loss         | 0.00241  |
------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 398      |
|    iterations         | 3100     |
|    time_elapsed       | 77       |
|    total_timesteps    | 31000    |
| train/                |          |
|    entropy_loss       | -23.8    |
|    explained_variance | -39.3    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3099     |
|    policy_loss        | 0.434    |
|    std                | 1.18     |
|    value_loss         | 0.00145  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 398      |
|    iterations         | 3200     |
|    time_elapsed       | 80       |
|    total_timesteps    | 32000    |
| train/                |          |
|    entropy_loss       | -23.9    |
|    explained_variance | -195     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3199     |
|    policy_loss        | -1.14    |
|    std                | 1.19     |
|    value_loss         | 0.00426  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 3300     |
|    time_elapsed       | 82       |
|    total_timesteps    | 33000    |
| train/                |          |
|    entropy_loss       | -24      |
|    explained_variance | -225     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3299     |
|    policy_loss        | 0.525    |
|    std                | 1.2      |
|    value_loss         | 0.00159  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 3400     |
|    time_elapsed       | 85       |
|    total_timesteps    | 34000    |
| train/                |          |
|    entropy_loss       | -24.1    |
|    explained_variance | -312     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3399     |
|    policy_loss        | 2.22     |
|    std                | 1.21     |
|    value_loss         | 0.01     |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 394       |
|    iterations         | 3500      |
|    time_elapsed       | 88        |
|    total_timesteps    | 35000     |
| train/                |           |
|    entropy_loss       | -24.3     |
|    explained_variance | -1.43e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 3499      |
|    policy_loss        | -0.311    |
|    std                | 1.22      |
|    value_loss         | 0.00135   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 394      |
|    iterations         | 3600     |
|    time_elapsed       | 91       |
|    total_timesteps    | 36000    |
| train/                |          |
|    entropy_loss       | -24.4    |
|    explained_variance | -65.1    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3599     |
|    policy_loss        | -0.0921  |
|    std                | 1.23     |
|    value_loss         | 0.00345  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 393       |
|    iterations         | 3700      |
|    time_elapsed       | 93        |
|    total_timesteps    | 37000     |
| train/                |           |
|    entropy_loss       | -24.6     |
|    explained_variance | -2.44e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 3699      |
|    policy_loss        | -0.745    |
|    std                | 1.24      |
|    value_loss         | 0.00183   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 393      |
|    iterations         | 3800     |
|    time_elapsed       | 96       |
|    total_timesteps    | 38000    |
| train/                |          |
|    entropy_loss       | -24.7    |
|    explained_variance | -159     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3799     |
|    policy_loss        | -0.0928  |
|    std                | 1.25     |
|    value_loss         | 0.00152  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 392      |
|    iterations         | 3900     |
|    time_elapsed       | 99       |
|    total_timesteps    | 39000    |
| train/                |          |
|    entropy_loss       | -24.8    |
|    explained_variance | -12.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3899     |
|    policy_loss        | -1.92    |
|    std                | 1.27     |
|    value_loss         | 0.00682  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 390      |
|    iterations         | 4000     |
|    time_elapsed       | 102      |
|    total_timesteps    | 40000    |
| train/                |          |
|    entropy_loss       | -25      |
|    explained_variance | -80.7    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3999     |
|    policy_loss        | -0.186   |
|    std                | 1.28     |
|    value_loss         | 0.00218  |
------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A2_MGNN_only_a2c_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A2_MGNN_only_a2c_seed1_actions.csv
{'CR': 0.07262473299974914, 'AR': 0.07573668854696369, 'Vol': 0.20697669343115319, 'SR': 0.36591892203629217, 'MDD': -0.09033856738444068, 'Calmar': 0.8383649502062845, 'Sortino': 0.5408280486369781, 'Omega': 1.0854092919944474, 'Turnover': 0.7334854645299471, 'FinalAccountValue': 1072624.7329997486, 'variant': 'A2_MGNN_only', 'agent': 'a2c', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A2_MGNN_only.CSV'}

========== A2_MGNN_only | PPO | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A2_MGNN_only.CSV
[banktrademergeGNNtr20241231_A2_MGNN_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 2048, 'ent_coef': 0.005, 'learning_rate': 0.001, 'batch_size': 128, 'seed': 1}
Using cpu device
Logging to tensorboard_log/ppo\A2_MGNN_only_ppo_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

-----------------------------
| time/              |      |
|    fps             | 544  |
|    iterations      | 1    |
|    time_elapsed    | 3    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 453         |
|    iterations           | 2           |
|    time_elapsed         | 9           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.046182048 |
|    clip_fraction        | 0.408       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | -52.7       |
|    learning_rate        | 0.001       |
|    loss                 | -0.196      |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0716     |
|    std                  | 0.998       |
|    value_loss           | 0.0371      |
-----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 426       |
|    iterations           | 3         |
|    time_elapsed         | 14        |
|    total_timesteps      | 6144      |
| train/                  |           |
|    approx_kl            | 0.0600422 |
|    clip_fraction        | 0.438     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.2     |
|    explained_variance   | -1.01     |
|    learning_rate        | 0.001     |
|    loss                 | -0.213    |
|    n_updates            | 20        |
|    policy_gradient_loss | -0.0724   |
|    std                  | 0.998     |
|    value_loss           | 0.00304   |
---------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 410         |
|    iterations           | 4           |
|    time_elapsed         | 19          |
|    total_timesteps      | 8192        |
| train/                  |             |
|    approx_kl            | 0.066132545 |
|    clip_fraction        | 0.466       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | 0.348       |
|    learning_rate        | 0.001       |
|    loss                 | -0.2        |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.0643     |
|    std                  | 0.999       |
|    value_loss           | 0.00116     |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 407        |
|    iterations           | 5          |
|    time_elapsed         | 25         |
|    total_timesteps      | 10240      |
| train/                  |            |
|    approx_kl            | 0.06958614 |
|    clip_fraction        | 0.484      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.687      |
|    learning_rate        | 0.001      |
|    loss                 | -0.197     |
|    n_updates            | 40         |
|    policy_gradient_loss | -0.063     |
|    std                  | 1          |
|    value_loss           | 0.000599   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 407         |
|    iterations           | 6           |
|    time_elapsed         | 30          |
|    total_timesteps      | 12288       |
| train/                  |             |
|    approx_kl            | 0.083893836 |
|    clip_fraction        | 0.52        |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | 0.819       |
|    learning_rate        | 0.001       |
|    loss                 | -0.203      |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.0582     |
|    std                  | 1           |
|    value_loss           | 0.000338    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 402        |
|    iterations           | 7          |
|    time_elapsed         | 35         |
|    total_timesteps      | 14336      |
| train/                  |            |
|    approx_kl            | 0.07869882 |
|    clip_fraction        | 0.512      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.85       |
|    learning_rate        | 0.001      |
|    loss                 | -0.187     |
|    n_updates            | 60         |
|    policy_gradient_loss | -0.0566    |
|    std                  | 1          |
|    value_loss           | 0.000206   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 401         |
|    iterations           | 8           |
|    time_elapsed         | 40          |
|    total_timesteps      | 16384       |
| train/                  |             |
|    approx_kl            | 0.092345424 |
|    clip_fraction        | 0.547       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.4       |
|    explained_variance   | 0.836       |
|    learning_rate        | 0.001       |
|    loss                 | -0.183      |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.053      |
|    std                  | 1.01        |
|    value_loss           | 0.000209    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 401        |
|    iterations           | 9          |
|    time_elapsed         | 45         |
|    total_timesteps      | 18432      |
| train/                  |            |
|    approx_kl            | 0.09477937 |
|    clip_fraction        | 0.521      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.758      |
|    learning_rate        | 0.001      |
|    loss                 | -0.181     |
|    n_updates            | 80         |
|    policy_gradient_loss | -0.0502    |
|    std                  | 1.02       |
|    value_loss           | 0.000177   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 398        |
|    iterations           | 10         |
|    time_elapsed         | 51         |
|    total_timesteps      | 20480      |
| train/                  |            |
|    approx_kl            | 0.10545218 |
|    clip_fraction        | 0.531      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.87       |
|    learning_rate        | 0.001      |
|    loss                 | -0.173     |
|    n_updates            | 90         |
|    policy_gradient_loss | -0.0562    |
|    std                  | 1.01       |
|    value_loss           | 0.000142   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 395        |
|    iterations           | 11         |
|    time_elapsed         | 56         |
|    total_timesteps      | 22528      |
| train/                  |            |
|    approx_kl            | 0.09705283 |
|    clip_fraction        | 0.531      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.789      |
|    learning_rate        | 0.001      |
|    loss                 | -0.166     |
|    n_updates            | 100        |
|    policy_gradient_loss | -0.0548    |
|    std                  | 1.01       |
|    value_loss           | 0.000134   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 395        |
|    iterations           | 12         |
|    time_elapsed         | 62         |
|    total_timesteps      | 24576      |
| train/                  |            |
|    approx_kl            | 0.10718447 |
|    clip_fraction        | 0.55       |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.776      |
|    learning_rate        | 0.001      |
|    loss                 | -0.192     |
|    n_updates            | 110        |
|    policy_gradient_loss | -0.0539    |
|    std                  | 1.02       |
|    value_loss           | 0.000118   |
----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 394         |
|    iterations           | 13          |
|    time_elapsed         | 67          |
|    total_timesteps      | 26624       |
| train/                  |             |
|    approx_kl            | 0.109314814 |
|    clip_fraction        | 0.558       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.6       |
|    explained_variance   | 0.789       |
|    learning_rate        | 0.001       |
|    loss                 | -0.19       |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.0556     |
|    std                  | 1.02        |
|    value_loss           | 0.000124    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 394        |
|    iterations           | 14         |
|    time_elapsed         | 72         |
|    total_timesteps      | 28672      |
| train/                  |            |
|    approx_kl            | 0.11143303 |
|    clip_fraction        | 0.549      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.6      |
|    explained_variance   | 0.664      |
|    learning_rate        | 0.001      |
|    loss                 | -0.153     |
|    n_updates            | 130        |
|    policy_gradient_loss | -0.0522    |
|    std                  | 1.02       |
|    value_loss           | 0.000132   |
----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 393       |
|    iterations           | 15        |
|    time_elapsed         | 78        |
|    total_timesteps      | 30720     |
| train/                  |           |
|    approx_kl            | 0.1050138 |
|    clip_fraction        | 0.541     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.6     |
|    explained_variance   | 0.597     |
|    learning_rate        | 0.001     |
|    loss                 | -0.195    |
|    n_updates            | 140       |
|    policy_gradient_loss | -0.0574   |
|    std                  | 1.03      |
|    value_loss           | 0.000155  |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 387        |
|    iterations           | 16         |
|    time_elapsed         | 84         |
|    total_timesteps      | 32768      |
| train/                  |            |
|    approx_kl            | 0.10646875 |
|    clip_fraction        | 0.553      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.7      |
|    explained_variance   | 0.502      |
|    learning_rate        | 0.001      |
|    loss                 | -0.194     |
|    n_updates            | 150        |
|    policy_gradient_loss | -0.0487    |
|    std                  | 1.03       |
|    value_loss           | 0.000132   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 385        |
|    iterations           | 17         |
|    time_elapsed         | 90         |
|    total_timesteps      | 34816      |
| train/                  |            |
|    approx_kl            | 0.13009354 |
|    clip_fraction        | 0.553      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.7      |
|    explained_variance   | 0.839      |
|    learning_rate        | 0.001      |
|    loss                 | -0.203     |
|    n_updates            | 160        |
|    policy_gradient_loss | -0.0503    |
|    std                  | 1.03       |
|    value_loss           | 9.44e-05   |
----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 384       |
|    iterations           | 18        |
|    time_elapsed         | 95        |
|    total_timesteps      | 36864     |
| train/                  |           |
|    approx_kl            | 0.1008005 |
|    clip_fraction        | 0.547     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.8     |
|    explained_variance   | 0.769     |
|    learning_rate        | 0.001     |
|    loss                 | -0.192    |
|    n_updates            | 170       |
|    policy_gradient_loss | -0.0504   |
|    std                  | 1.04      |
|    value_loss           | 7.59e-05  |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 381        |
|    iterations           | 19         |
|    time_elapsed         | 101        |
|    total_timesteps      | 38912      |
| train/                  |            |
|    approx_kl            | 0.12380214 |
|    clip_fraction        | 0.558      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.8      |
|    explained_variance   | 0.858      |
|    learning_rate        | 0.001      |
|    loss                 | -0.197     |
|    n_updates            | 180        |
|    policy_gradient_loss | -0.0543    |
|    std                  | 1.04       |
|    value_loss           | 5.1e-05    |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 380        |
|    iterations           | 20         |
|    time_elapsed         | 107        |
|    total_timesteps      | 40960      |
| train/                  |            |
|    approx_kl            | 0.11849928 |
|    clip_fraction        | 0.568      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.9      |
|    explained_variance   | 0.791      |
|    learning_rate        | 0.001      |
|    loss                 | -0.201     |
|    n_updates            | 190        |
|    policy_gradient_loss | -0.058     |
|    std                  | 1.04       |
|    value_loss           | 0.000105   |
----------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A2_MGNN_only_ppo_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A2_MGNN_only_ppo_seed1_actions.csv
{'CR': 0.0009017774924928723, 'AR': 0.0009390585161939136, 'Vol': 0.20854484520472036, 'SR': 0.004502909267654525, 'MDD': -0.15285314171308595, 'Calmar': 0.006143534281791733, 'Sortino': 0.006401313172646486, 'Omega': 1.0197840926067725, 'Turnover': 0.7540799006629973, 'FinalAccountValue': 1000901.7774924937, 'variant': 'A2_MGNN_only', 'agent': 'ppo', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A2_MGNN_only.CSV'}

========== A2_MGNN_only | SAC | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A2_MGNN_only.CSV
[banktrademergeGNNtr20241231_A2_MGNN_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 128, 'buffer_size': 1000000, 'learning_rate': 0.0001, 'learning_starts': 100, 'ent_coef': 'auto_0.1', 'seed': 1}
Using cpu device
Logging to tensorboard_log/sac\A2_MGNN_only_sac_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 14       |
|    time_elapsed    | 204      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | -9.84    |
|    critic_loss     | 0.0199   |
|    ent_coef        | 0.0753   |
|    ent_coef_loss   | -64.8    |
|    learning_rate   | 0.0001   |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 13       |
|    time_elapsed    | 417      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | -16.7    |
|    critic_loss     | 0.0278   |
|    ent_coef        | 0.0563   |
|    ent_coef_loss   | -72.4    |
|    learning_rate   | 0.0001   |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 13       |
|    time_elapsed    | 634      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | -20.3    |
|    critic_loss     | 0.0101   |
|    ent_coef        | 0.0422   |
|    ent_coef_loss   | -80.1    |
|    learning_rate   | 0.0001   |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 13       |
|    time_elapsed    | 869      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | -21.9    |
|    critic_loss     | 0.0203   |
|    ent_coef        | 0.0316   |
|    ent_coef_loss   | -87.3    |
|    learning_rate   | 0.0001   |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 13       |
|    time_elapsed    | 1108     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | -21.9    |
|    critic_loss     | 0.025    |
|    ent_coef        | 0.0237   |
|    ent_coef_loss   | -94.3    |
|    learning_rate   | 0.0001   |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 12       |
|    time_elapsed    | 1352     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | -21.2    |
|    critic_loss     | 0.00784  |
|    ent_coef        | 0.0178   |
|    ent_coef_loss   | -102     |
|    learning_rate   | 0.0001   |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 12       |
|    time_elapsed    | 1598     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | -19.9    |
|    critic_loss     | 0.0122   |
|    ent_coef        | 0.0133   |
|    ent_coef_loss   | -108     |
|    learning_rate   | 0.0001   |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1842     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | -18.5    |
|    critic_loss     | 0.00727  |
|    ent_coef        | 0.00998  |
|    ent_coef_loss   | -116     |
|    learning_rate   | 0.0001   |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2093     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | -15.5    |
|    critic_loss     | 0.0163   |
|    ent_coef        | 0.00748  |
|    ent_coef_loss   | -122     |
|    learning_rate   | 0.0001   |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 12       |
|    time_elapsed    | 2338     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | -15.1    |
|    critic_loss     | 0.0167   |
|    ent_coef        | 0.00561  |
|    ent_coef_loss   | -130     |
|    learning_rate   | 0.0001   |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 12       |
|    time_elapsed    | 2578     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -13      |
|    critic_loss     | 0.00992  |
|    ent_coef        | 0.00421  |
|    ent_coef_loss   | -135     |
|    learning_rate   | 0.0001   |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 12       |
|    time_elapsed    | 2824     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -11.3    |
|    critic_loss     | 0.0117   |
|    ent_coef        | 0.00316  |
|    ent_coef_loss   | -141     |
|    learning_rate   | 0.0001   |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 12       |
|    time_elapsed    | 3070     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -9.83    |
|    critic_loss     | 0.00224  |
|    ent_coef        | 0.00237  |
|    ent_coef_loss   | -145     |
|    learning_rate   | 0.0001   |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 12       |
|    time_elapsed    | 3314     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -8.87    |
|    critic_loss     | 0.0168   |
|    ent_coef        | 0.00178  |
|    ent_coef_loss   | -146     |
|    learning_rate   | 0.0001   |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 12       |
|    time_elapsed    | 3547     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -7.3     |
|    critic_loss     | 0.0081   |
|    ent_coef        | 0.00133  |
|    ent_coef_loss   | -156     |
|    learning_rate   | 0.0001   |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 12       |
|    time_elapsed    | 3788     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -6.43    |
|    critic_loss     | 0.00967  |
|    ent_coef        | 0.001    |
|    ent_coef_loss   | -146     |
|    learning_rate   | 0.0001   |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 12       |
|    time_elapsed    | 4025     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -5.41    |
|    critic_loss     | 0.00953  |
|    ent_coef        | 0.000754 |
|    ent_coef_loss   | -157     |
|    learning_rate   | 0.0001   |
|    n_updates       | 48927    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 72       |
|    fps             | 12       |
|    time_elapsed    | 4259     |
|    total_timesteps | 51912    |
| train/             |          |
|    actor_loss      | -4.6     |
|    critic_loss     | 0.00298  |
|    ent_coef        | 0.000568 |
|    ent_coef_loss   | -158     |
|    learning_rate   | 0.0001   |
|    n_updates       | 51811    |
---------------------------------

---------------------------------
| time/              |          |
|    episodes        | 76       |
|    fps             | 12       |
|    time_elapsed    | 4492     |
|    total_timesteps | 54796    |
| train/             |          |
|    actor_loss      | -3.67    |
|    critic_loss     | 0.00537  |
|    ent_coef        | 0.000428 |
|    ent_coef_loss   | -141     |
|    learning_rate   | 0.0001   |
|    n_updates       | 54695    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 80       |
|    fps             | 12       |
|    time_elapsed    | 4710     |
|    total_timesteps | 57680    |
| train/             |          |
|    actor_loss      | -3.18    |
|    critic_loss     | 0.00177  |
|    ent_coef        | 0.000322 |
|    ent_coef_loss   | -153     |
|    learning_rate   | 0.0001   |
|    n_updates       | 57579    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A2_MGNN_only_sac_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A2_MGNN_only_sac_seed1_actions.csv
{'CR': 0.061735618299058936, 'AR': 0.06436710593090589, 'Vol': 0.21623382276120073, 'SR': 0.297673625286596, 'MDD': -0.09591870671288683, 'Calmar': 0.6710589428981331, 'Sortino': 0.41239087074226255, 'Omega': 1.0755281159313406, 'Turnover': 0.6302117105851515, 'FinalAccountValue': 1061735.6182990572, 'variant': 'A2_MGNN_only', 'agent': 'sac', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A2_MGNN_only.CSV'}

========== A2_MGNN_only | TD3 | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A2_MGNN_only.CSV
[banktrademergeGNNtr20241231_A2_MGNN_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 100, 'buffer_size': 1000000, 'learning_rate': 0.001, 'seed': 1}
Using cpu device
Logging to tensorboard_log/td3\A2_MGNN_only_td3_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 16       |
|    time_elapsed    | 180      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 1.06     |
|    critic_loss     | 0.00744  |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 15       |
|    time_elapsed    | 376      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 1.06     |
|    critic_loss     | 0.00274  |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 15       |
|    time_elapsed    | 576      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.952    |
|    critic_loss     | 0.00327  |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 14       |
|    time_elapsed    | 800      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.958    |
|    critic_loss     | 0.000325 |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 13       |
|    time_elapsed    | 1040     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.887    |
|    critic_loss     | 0.000482 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 13       |
|    time_elapsed    | 1298     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.753    |
|    critic_loss     | 0.00285  |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 12       |
|    time_elapsed    | 1570     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.766    |
|    critic_loss     | 0.000166 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1852     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.682    |
|    critic_loss     | 0.000225 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2149     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.648    |
|    critic_loss     | 0.000433 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 11       |
|    time_elapsed    | 2440     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.574    |
|    critic_loss     | 0.00015  |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A2_MGNN_only_td3_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A2_MGNN_only_td3_seed1_actions.csv
{'CR': 0.07250800456068074, 'AR': 0.07561478423990708, 'Vol': 0.19499481676418357, 'SR': 0.3877784317280167, 'MDD': -0.07718853092298394, 'Calmar': 0.979611651313236, 'Sortino': 0.51274888200836, 'Omega': 1.092979981992823, 'Turnover': 0.16846637273686466, 'FinalAccountValue': 1072508.0045606815, 'variant': 'A2_MGNN_only', 'agent': 'td3', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A2_MGNN_only.CSV'}

========== A2_MGNN_only | DDPG | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A2_MGNN_only.CSV
[banktrademergeGNNtr20241231_A2_MGNN_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'seed': 1}
Using cpu device
Logging to tensorboard_log/ddpg\A2_MGNN_only_ddpg_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 11       |
|    time_elapsed    | 253      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 0.695    |
|    critic_loss     | 0.00106  |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 11       |
|    time_elapsed    | 523      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.57     |
|    critic_loss     | 0.00084  |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 10       |
|    time_elapsed    | 799      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.414    |
|    critic_loss     | 0.000295 |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 10       |
|    time_elapsed    | 1084     |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.32     |
|    critic_loss     | 0.000134 |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 10       |
|    time_elapsed    | 1351     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.253    |
|    critic_loss     | 3.09e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 10       |
|    time_elapsed    | 1641     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.191    |
|    critic_loss     | 4.93e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 10       |
|    time_elapsed    | 1961     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.128    |
|    critic_loss     | 0.000104 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 10       |
|    time_elapsed    | 2293     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.0939   |
|    critic_loss     | 0.000154 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 9        |
|    time_elapsed    | 2615     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.0507   |
|    critic_loss     | 2.96e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 9        |
|    time_elapsed    | 2958     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.0126   |
|    critic_loss     | 2.03e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 9        |
|    time_elapsed    | 3300     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -0.0154  |
|    critic_loss     | 5.87e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 9        |
|    time_elapsed    | 3654     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -0.0416  |
|    critic_loss     | 1.78e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 9        |
|    time_elapsed    | 4007     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -0.0667  |
|    critic_loss     | 1.51e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 9        |
|    time_elapsed    | 4363     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -0.0827  |
|    critic_loss     | 2.5e-05  |
|    learning_rate   | 0.001    |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 9        |
|    time_elapsed    | 4720     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -0.11    |
|    critic_loss     | 5.18e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 9        |
|    time_elapsed    | 5079     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -0.115   |
|    critic_loss     | 2.24e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 8        |
|    time_elapsed    | 5448     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -0.124   |
|    critic_loss     | 8.84e-06 |
|    learning_rate   | 0.001    |
|    n_updates       | 48927    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A2_MGNN_only_ddpg_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A2_MGNN_only_ddpg_seed1_actions.csv
{'CR': 0.1623230558899198, 'AR': 0.16957024071541693, 'Vol': 0.23628785654157475, 'SR': 0.7176426380827621, 'MDD': -0.13471251379610916, 'Calmar': 1.258756413469248, 'Sortino': 1.0401240664465004, 'Omega': 1.1617583313308888, 'Turnover': 0.9049410683320882, 'FinalAccountValue': 1162323.055889919, 'variant': 'A2_MGNN_only', 'agent': 'ddpg', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A2_MGNN_only.CSV'}
[banktrademergeGNNtr20241231_A3_SH_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630

========== A3_SH_only | A2C | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A3_SH_only.CSV
[banktrademergeGNNtr20241231_A3_SH_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 10, 'ent_coef': 0.005, 'learning_rate': 0.0004, 'seed': 1}
Using cpu device
Logging to tensorboard_log/a2c\A3_SH_only_a2c_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

------------------------------------
| time/                 |          |
|    fps                | 409      |
|    iterations         | 100      |
|    time_elapsed       | 2        |
|    total_timesteps    | 1000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -643     |
|    learning_rate      | 0.0004   |
|    n_updates          | 99       |
|    policy_loss        | -2.87    |
|    std                | 1.01     |
|    value_loss         | 0.0493   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 414      |
|    iterations         | 200      |
|    time_elapsed       | 4        |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -1.9e+03 |
|    learning_rate      | 0.0004   |
|    n_updates          | 199      |
|    policy_loss        | 0.728    |
|    std                | 1.01     |
|    value_loss         | 0.0119   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 408       |
|    iterations         | 300       |
|    time_elapsed       | 7         |
|    total_timesteps    | 3000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -1.63e+04 |
|    learning_rate      | 0.0004    |
|    n_updates          | 299       |
|    policy_loss        | 3.49      |
|    std                | 1.01      |
|    value_loss         | 0.0675    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 410      |
|    iterations         | 400      |
|    time_elapsed       | 9        |
|    total_timesteps    | 4000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -399     |
|    learning_rate      | 0.0004   |
|    n_updates          | 399      |
|    policy_loss        | 3.07     |
|    std                | 1.01     |
|    value_loss         | 0.0648   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 402      |
|    iterations         | 500      |
|    time_elapsed       | 12       |
|    total_timesteps    | 5000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -695     |
|    learning_rate      | 0.0004   |
|    n_updates          | 499      |
|    policy_loss        | -2.22    |
|    std                | 1.01     |
|    value_loss         | 0.0479   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 403       |
|    iterations         | 600       |
|    time_elapsed       | 14        |
|    total_timesteps    | 6000      |
| train/                |           |
|    entropy_loss       | -21.5     |
|    explained_variance | -1.05e+04 |
|    learning_rate      | 0.0004    |
|    n_updates          | 599       |
|    policy_loss        | -3.98     |
|    std                | 1.01      |
|    value_loss         | 0.0424    |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 405       |
|    iterations         | 700       |
|    time_elapsed       | 17        |
|    total_timesteps    | 7000      |
| train/                |           |
|    entropy_loss       | -21.5     |
|    explained_variance | -3.53e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 699       |
|    policy_loss        | -2.57     |
|    std                | 1.02      |
|    value_loss         | 0.0274    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 407      |
|    iterations         | 800      |
|    time_elapsed       | 19       |
|    total_timesteps    | 8000     |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -506     |
|    learning_rate      | 0.0004   |
|    n_updates          | 799      |
|    policy_loss        | 4.86     |
|    std                | 1.02     |
|    value_loss         | 0.0613   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 407      |
|    iterations         | 900      |
|    time_elapsed       | 22       |
|    total_timesteps    | 9000     |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -825     |
|    learning_rate      | 0.0004   |
|    n_updates          | 899      |
|    policy_loss        | -1.14    |
|    std                | 1.02     |
|    value_loss         | 0.0128   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 409      |
|    iterations         | 1000     |
|    time_elapsed       | 24       |
|    total_timesteps    | 10000    |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -67.1    |
|    learning_rate      | 0.0004   |
|    n_updates          | 999      |
|    policy_loss        | 0.405    |
|    std                | 1.03     |
|    value_loss         | 0.00557  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 404      |
|    iterations         | 1100     |
|    time_elapsed       | 27       |
|    total_timesteps    | 11000    |
| train/                |          |
|    entropy_loss       | -21.8    |
|    explained_variance | -234     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1099     |
|    policy_loss        | 4.42     |
|    std                | 1.03     |
|    value_loss         | 0.0448   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 402      |
|    iterations         | 1200     |
|    time_elapsed       | 29       |
|    total_timesteps    | 12000    |
| train/                |          |
|    entropy_loss       | -21.8    |
|    explained_variance | -510     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1199     |
|    policy_loss        | 0.987    |
|    std                | 1.04     |
|    value_loss         | 0.00641  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 403      |
|    iterations         | 1300     |
|    time_elapsed       | 32       |
|    total_timesteps    | 13000    |
| train/                |          |
|    entropy_loss       | -21.9    |
|    explained_variance | -170     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1299     |
|    policy_loss        | 0.0339   |
|    std                | 1.04     |
|    value_loss         | 0.00467  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 404      |
|    iterations         | 1400     |
|    time_elapsed       | 34       |
|    total_timesteps    | 14000    |
| train/                |          |
|    entropy_loss       | -21.9    |
|    explained_variance | -119     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1399     |
|    policy_loss        | 3.72     |
|    std                | 1.05     |
|    value_loss         | 0.0322   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 405       |
|    iterations         | 1500      |
|    time_elapsed       | 37        |
|    total_timesteps    | 15000     |
| train/                |           |
|    entropy_loss       | -22       |
|    explained_variance | -1.06e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 1499      |
|    policy_loss        | 1.27      |
|    std                | 1.05      |
|    value_loss         | 0.00772   |
-------------------------------------

-------------------------------------
| time/                 |           |
|    fps                | 405       |
|    iterations         | 1600      |
|    time_elapsed       | 39        |
|    total_timesteps    | 16000     |
| train/                |           |
|    entropy_loss       | -22.1     |
|    explained_variance | -1.01e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 1599      |
|    policy_loss        | -0.883    |
|    std                | 1.06      |
|    value_loss         | 0.00609   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 406      |
|    iterations         | 1700     |
|    time_elapsed       | 41       |
|    total_timesteps    | 17000    |
| train/                |          |
|    entropy_loss       | -22.2    |
|    explained_variance | -280     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1699     |
|    policy_loss        | 0.0551   |
|    std                | 1.06     |
|    value_loss         | 0.00524  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 403      |
|    iterations         | 1800     |
|    time_elapsed       | 44       |
|    total_timesteps    | 18000    |
| train/                |          |
|    entropy_loss       | -22.3    |
|    explained_variance | -24.5    |
|    learning_rate      | 0.0004   |
|    n_updates          | 1799     |
|    policy_loss        | 2.39     |
|    std                | 1.07     |
|    value_loss         | 0.0131   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 403      |
|    iterations         | 1900     |
|    time_elapsed       | 47       |
|    total_timesteps    | 19000    |
| train/                |          |
|    entropy_loss       | -22.3    |
|    explained_variance | -588     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1899     |
|    policy_loss        | -2.42    |
|    std                | 1.07     |
|    value_loss         | 0.0161   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 404      |
|    iterations         | 2000     |
|    time_elapsed       | 49       |
|    total_timesteps    | 20000    |
| train/                |          |
|    entropy_loss       | -22.4    |
|    explained_variance | -401     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1999     |
|    policy_loss        | 0.644    |
|    std                | 1.08     |
|    value_loss         | 0.00394  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 2100     |
|    time_elapsed       | 52       |
|    total_timesteps    | 21000    |
| train/                |          |
|    entropy_loss       | -22.5    |
|    explained_variance | -86.8    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2099     |
|    policy_loss        | 0.515    |
|    std                | 1.09     |
|    value_loss         | 0.00314  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 2200     |
|    time_elapsed       | 55       |
|    total_timesteps    | 22000    |
| train/                |          |
|    entropy_loss       | -22.6    |
|    explained_variance | -58.8    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2199     |
|    policy_loss        | -0.885   |
|    std                | 1.09     |
|    value_loss         | 0.00236  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 2300     |
|    time_elapsed       | 58       |
|    total_timesteps    | 23000    |
| train/                |          |
|    entropy_loss       | -22.7    |
|    explained_variance | -31.2    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2299     |
|    policy_loss        | -0.58    |
|    std                | 1.1      |
|    value_loss         | 0.00312  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 395      |
|    iterations         | 2400     |
|    time_elapsed       | 60       |
|    total_timesteps    | 24000    |
| train/                |          |
|    entropy_loss       | -22.8    |
|    explained_variance | -76.6    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2399     |
|    policy_loss        | -0.198   |
|    std                | 1.1      |
|    value_loss         | 0.00193  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 2500     |
|    time_elapsed       | 63       |
|    total_timesteps    | 25000    |
| train/                |          |
|    entropy_loss       | -22.9    |
|    explained_variance | -89.4    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2499     |
|    policy_loss        | -1.61    |
|    std                | 1.11     |
|    value_loss         | 0.00599  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 2600     |
|    time_elapsed       | 65       |
|    total_timesteps    | 26000    |
| train/                |          |
|    entropy_loss       | -23      |
|    explained_variance | -277     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2599     |
|    policy_loss        | -0.355   |
|    std                | 1.12     |
|    value_loss         | 0.0044   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 2700     |
|    time_elapsed       | 67       |
|    total_timesteps    | 27000    |
| train/                |          |
|    entropy_loss       | -23.1    |
|    explained_variance | -161     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2699     |
|    policy_loss        | -0.357   |
|    std                | 1.13     |
|    value_loss         | 0.00228  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 2800     |
|    time_elapsed       | 70       |
|    total_timesteps    | 28000    |
| train/                |          |
|    entropy_loss       | -23.3    |
|    explained_variance | -539     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2799     |
|    policy_loss        | 0.403    |
|    std                | 1.14     |
|    value_loss         | 0.00272  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 398      |
|    iterations         | 2900     |
|    time_elapsed       | 72       |
|    total_timesteps    | 29000    |
| train/                |          |
|    entropy_loss       | -23.4    |
|    explained_variance | -311     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2899     |
|    policy_loss        | 0.521    |
|    std                | 1.15     |
|    value_loss         | 0.00188  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 3000     |
|    time_elapsed       | 75       |
|    total_timesteps    | 30000    |
| train/                |          |
|    entropy_loss       | -23.5    |
|    explained_variance | -150     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2999     |
|    policy_loss        | -0.653   |
|    std                | 1.16     |
|    value_loss         | 0.00186  |
------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 3100     |
|    time_elapsed       | 78       |
|    total_timesteps    | 31000    |
| train/                |          |
|    entropy_loss       | -23.6    |
|    explained_variance | -34.6    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3099     |
|    policy_loss        | 1.88     |
|    std                | 1.17     |
|    value_loss         | 0.00742  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 3200     |
|    time_elapsed       | 80       |
|    total_timesteps    | 32000    |
| train/                |          |
|    entropy_loss       | -23.7    |
|    explained_variance | -111     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3199     |
|    policy_loss        | 0.344    |
|    std                | 1.18     |
|    value_loss         | 0.00244  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 3300     |
|    time_elapsed       | 82       |
|    total_timesteps    | 33000    |
| train/                |          |
|    entropy_loss       | -23.8    |
|    explained_variance | -1.3e+03 |
|    learning_rate      | 0.0004   |
|    n_updates          | 3299     |
|    policy_loss        | 0.0948   |
|    std                | 1.19     |
|    value_loss         | 0.00382  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 398       |
|    iterations         | 3400      |
|    time_elapsed       | 85        |
|    total_timesteps    | 34000     |
| train/                |           |
|    entropy_loss       | -24       |
|    explained_variance | -3.68e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 3399      |
|    policy_loss        | 0.668     |
|    std                | 1.2       |
|    value_loss         | 0.00471   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 398      |
|    iterations         | 3500     |
|    time_elapsed       | 87       |
|    total_timesteps    | 35000    |
| train/                |          |
|    entropy_loss       | -24.1    |
|    explained_variance | -95.1    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3499     |
|    policy_loss        | 1.15     |
|    std                | 1.21     |
|    value_loss         | 0.00272  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 398      |
|    iterations         | 3600     |
|    time_elapsed       | 90       |
|    total_timesteps    | 36000    |
| train/                |          |
|    entropy_loss       | -24.2    |
|    explained_variance | -17.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3599     |
|    policy_loss        | -0.564   |
|    std                | 1.22     |
|    value_loss         | 0.0018   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 3700     |
|    time_elapsed       | 93       |
|    total_timesteps    | 37000    |
| train/                |          |
|    entropy_loss       | -24.3    |
|    explained_variance | -423     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3699     |
|    policy_loss        | 0.084    |
|    std                | 1.23     |
|    value_loss         | 0.00106  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 3800     |
|    time_elapsed       | 95       |
|    total_timesteps    | 38000    |
| train/                |          |
|    entropy_loss       | -24.5    |
|    explained_variance | -143     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3799     |
|    policy_loss        | -0.074   |
|    std                | 1.24     |
|    value_loss         | 0.00125  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 3900     |
|    time_elapsed       | 98       |
|    total_timesteps    | 39000    |
| train/                |          |
|    entropy_loss       | -24.6    |
|    explained_variance | -46.8    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3899     |
|    policy_loss        | -0.21    |
|    std                | 1.25     |
|    value_loss         | 0.00113  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 398      |
|    iterations         | 4000     |
|    time_elapsed       | 100      |
|    total_timesteps    | 40000    |
| train/                |          |
|    entropy_loss       | -24.7    |
|    explained_variance | -32.7    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3999     |
|    policy_loss        | -1.03    |
|    std                | 1.26     |
|    value_loss         | 0.00295  |
------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A3_SH_only_a2c_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A3_SH_only_a2c_seed1_actions.csv
{'CR': -0.0774462629802597, 'AR': -0.08051415625689529, 'Vol': 0.08936052267862021, 'SR': -0.9010036405724667, 'MDD': -0.14727834164322184, 'Calmar': -0.5466802203133089, 'Sortino': -1.4058090505099508, 'Omega': 0.8608737712428405, 'Turnover': 0.650020183697151, 'FinalAccountValue': 922553.737019739, 'variant': 'A3_SH_only', 'agent': 'a2c', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A3_SH_only.CSV'}

========== A3_SH_only | PPO | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A3_SH_only.CSV
[banktrademergeGNNtr20241231_A3_SH_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 2048, 'ent_coef': 0.005, 'learning_rate': 0.001, 'batch_size': 128, 'seed': 1}
Using cpu device
Logging to tensorboard_log/ppo\A3_SH_only_ppo_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

-----------------------------
| time/              |      |
|    fps             | 588  |
|    iterations      | 1    |
|    time_elapsed    | 3    |
|    total_timesteps | 2048 |
-----------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 476       |
|    iterations           | 2         |
|    time_elapsed         | 8         |
|    total_timesteps      | 4096      |
| train/                  |           |
|    approx_kl            | 0.0483507 |
|    clip_fraction        | 0.404     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.3     |
|    explained_variance   | -47.5     |
|    learning_rate        | 0.001     |
|    loss                 | -0.184    |
|    n_updates            | 10        |
|    policy_gradient_loss | -0.0742   |
|    std                  | 0.999     |
|    value_loss           | 0.0356    |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 436        |
|    iterations           | 3          |
|    time_elapsed         | 14         |
|    total_timesteps      | 6144       |
| train/                  |            |
|    approx_kl            | 0.05261921 |
|    clip_fraction        | 0.417      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | -1.22      |
|    learning_rate        | 0.001      |
|    loss                 | -0.204     |
|    n_updates            | 20         |
|    policy_gradient_loss | -0.0683    |
|    std                  | 0.998      |
|    value_loss           | 0.00263    |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 424        |
|    iterations           | 4          |
|    time_elapsed         | 19         |
|    total_timesteps      | 8192       |
| train/                  |            |
|    approx_kl            | 0.06662419 |
|    clip_fraction        | 0.463      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.409      |
|    learning_rate        | 0.001      |
|    loss                 | -0.199     |
|    n_updates            | 30         |
|    policy_gradient_loss | -0.0682    |
|    std                  | 0.995      |
|    value_loss           | 0.000966   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 421        |
|    iterations           | 5          |
|    time_elapsed         | 24         |
|    total_timesteps      | 10240      |
| train/                  |            |
|    approx_kl            | 0.07019425 |
|    clip_fraction        | 0.483      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.707      |
|    learning_rate        | 0.001      |
|    loss                 | -0.191     |
|    n_updates            | 40         |
|    policy_gradient_loss | -0.0634    |
|    std                  | 0.999      |
|    value_loss           | 0.000491   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 412        |
|    iterations           | 6          |
|    time_elapsed         | 29         |
|    total_timesteps      | 12288      |
| train/                  |            |
|    approx_kl            | 0.07551212 |
|    clip_fraction        | 0.502      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.806      |
|    learning_rate        | 0.001      |
|    loss                 | -0.183     |
|    n_updates            | 50         |
|    policy_gradient_loss | -0.058     |
|    std                  | 1          |
|    value_loss           | 0.000344   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 404         |
|    iterations           | 7           |
|    time_elapsed         | 35          |
|    total_timesteps      | 14336       |
| train/                  |             |
|    approx_kl            | 0.085992455 |
|    clip_fraction        | 0.516       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | 0.808       |
|    learning_rate        | 0.001       |
|    loss                 | -0.191      |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.0543     |
|    std                  | 1           |
|    value_loss           | 0.000267    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 403         |
|    iterations           | 8           |
|    time_elapsed         | 40          |
|    total_timesteps      | 16384       |
| train/                  |             |
|    approx_kl            | 0.082781166 |
|    clip_fraction        | 0.526       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.4       |
|    explained_variance   | 0.762       |
|    learning_rate        | 0.001       |
|    loss                 | -0.185      |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.0553     |
|    std                  | 1.01        |
|    value_loss           | 0.000214    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 399        |
|    iterations           | 9          |
|    time_elapsed         | 46         |
|    total_timesteps      | 18432      |
| train/                  |            |
|    approx_kl            | 0.09264069 |
|    clip_fraction        | 0.524      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.838      |
|    learning_rate        | 0.001      |
|    loss                 | -0.182     |
|    n_updates            | 80         |
|    policy_gradient_loss | -0.0536    |
|    std                  | 1.01       |
|    value_loss           | 0.00019    |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 395         |
|    iterations           | 10          |
|    time_elapsed         | 51          |
|    total_timesteps      | 20480       |
| train/                  |             |
|    approx_kl            | 0.098827176 |
|    clip_fraction        | 0.535       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.4       |
|    explained_variance   | 0.808       |
|    learning_rate        | 0.001       |
|    loss                 | -0.197      |
|    n_updates            | 90          |
|    policy_gradient_loss | -0.0601     |
|    std                  | 1.01        |
|    value_loss           | 0.000157    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 395        |
|    iterations           | 11         |
|    time_elapsed         | 56         |
|    total_timesteps      | 22528      |
| train/                  |            |
|    approx_kl            | 0.09377454 |
|    clip_fraction        | 0.522      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.764      |
|    learning_rate        | 0.001      |
|    loss                 | -0.187     |
|    n_updates            | 100        |
|    policy_gradient_loss | -0.0507    |
|    std                  | 1.01       |
|    value_loss           | 0.000119   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 389        |
|    iterations           | 12         |
|    time_elapsed         | 63         |
|    total_timesteps      | 24576      |
| train/                  |            |
|    approx_kl            | 0.10702567 |
|    clip_fraction        | 0.555      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.844      |
|    learning_rate        | 0.001      |
|    loss                 | -0.159     |
|    n_updates            | 110        |
|    policy_gradient_loss | -0.0593    |
|    std                  | 1.01       |
|    value_loss           | 7.98e-05   |
----------------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 389        |
|    iterations           | 13         |
|    time_elapsed         | 68         |
|    total_timesteps      | 26624      |
| train/                  |            |
|    approx_kl            | 0.11110687 |
|    clip_fraction        | 0.531      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.83       |
|    learning_rate        | 0.001      |
|    loss                 | -0.198     |
|    n_updates            | 120        |
|    policy_gradient_loss | -0.0502    |
|    std                  | 1.02       |
|    value_loss           | 0.000103   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 390        |
|    iterations           | 14         |
|    time_elapsed         | 73         |
|    total_timesteps      | 28672      |
| train/                  |            |
|    approx_kl            | 0.10875451 |
|    clip_fraction        | 0.549      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.6      |
|    explained_variance   | 0.794      |
|    learning_rate        | 0.001      |
|    loss                 | -0.209     |
|    n_updates            | 130        |
|    policy_gradient_loss | -0.0548    |
|    std                  | 1.02       |
|    value_loss           | 6.6e-05    |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 388        |
|    iterations           | 15         |
|    time_elapsed         | 79         |
|    total_timesteps      | 30720      |
| train/                  |            |
|    approx_kl            | 0.11029991 |
|    clip_fraction        | 0.565      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.6      |
|    explained_variance   | 0.814      |
|    learning_rate        | 0.001      |
|    loss                 | -0.186     |
|    n_updates            | 140        |
|    policy_gradient_loss | -0.0539    |
|    std                  | 1.03       |
|    value_loss           | 0.000177   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 388        |
|    iterations           | 16         |
|    time_elapsed         | 84         |
|    total_timesteps      | 32768      |
| train/                  |            |
|    approx_kl            | 0.11486842 |
|    clip_fraction        | 0.562      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.7      |
|    explained_variance   | 0.227      |
|    learning_rate        | 0.001      |
|    loss                 | -0.186     |
|    n_updates            | 150        |
|    policy_gradient_loss | -0.0509    |
|    std                  | 1.03       |
|    value_loss           | 0.000207   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 389         |
|    iterations           | 17          |
|    time_elapsed         | 89          |
|    total_timesteps      | 34816       |
| train/                  |             |
|    approx_kl            | 0.114975065 |
|    clip_fraction        | 0.557       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.8       |
|    explained_variance   | 0.72        |
|    learning_rate        | 0.001       |
|    loss                 | -0.182      |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.0568     |
|    std                  | 1.03        |
|    value_loss           | 6.89e-05    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 387        |
|    iterations           | 18         |
|    time_elapsed         | 95         |
|    total_timesteps      | 36864      |
| train/                  |            |
|    approx_kl            | 0.11993738 |
|    clip_fraction        | 0.567      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.8      |
|    explained_variance   | 0.886      |
|    learning_rate        | 0.001      |
|    loss                 | -0.166     |
|    n_updates            | 170        |
|    policy_gradient_loss | -0.0552    |
|    std                  | 1.03       |
|    value_loss           | 4.3e-05    |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 387        |
|    iterations           | 19         |
|    time_elapsed         | 100        |
|    total_timesteps      | 38912      |
| train/                  |            |
|    approx_kl            | 0.15065669 |
|    clip_fraction        | 0.597      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.8      |
|    explained_variance   | 0.843      |
|    learning_rate        | 0.001      |
|    loss                 | -0.191     |
|    n_updates            | 180        |
|    policy_gradient_loss | -0.0473    |
|    std                  | 1.04       |
|    value_loss           | 4.18e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 386        |
|    iterations           | 20         |
|    time_elapsed         | 105        |
|    total_timesteps      | 40960      |
| train/                  |            |
|    approx_kl            | 0.12404729 |
|    clip_fraction        | 0.561      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.9      |
|    explained_variance   | 0.823      |
|    learning_rate        | 0.001      |
|    loss                 | -0.181     |
|    n_updates            | 190        |
|    policy_gradient_loss | -0.0508    |
|    std                  | 1.04       |
|    value_loss           | 5.58e-05   |
----------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A3_SH_only_ppo_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A3_SH_only_ppo_seed1_actions.csv
{'CR': -0.07704906174415327, 'AR': -0.08010191352849783, 'Vol': 0.08905785627938938, 'SR': -0.8994368029385834, 'MDD': -0.14440617690900226, 'Calmar': -0.5546986648567959, 'Sortino': -1.3006933155836045, 'Omega': 0.8599611140920562, 'Turnover': 0.7450605708933806, 'FinalAccountValue': 922950.9382558458, 'variant': 'A3_SH_only', 'agent': 'ppo', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A3_SH_only.CSV'}

========== A3_SH_only | SAC | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A3_SH_only.CSV
[banktrademergeGNNtr20241231_A3_SH_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 128, 'buffer_size': 1000000, 'learning_rate': 0.0001, 'learning_starts': 100, 'ent_coef': 'auto_0.1', 'seed': 1}
Using cpu device
Logging to tensorboard_log/sac\A3_SH_only_sac_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 14       |
|    time_elapsed    | 202      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | -9.8     |
|    critic_loss     | 0.0219   |
|    ent_coef        | 0.0753   |
|    ent_coef_loss   | -64.8    |
|    learning_rate   | 0.0001   |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 13       |
|    time_elapsed    | 417      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | -16.5    |
|    critic_loss     | 0.0314   |
|    ent_coef        | 0.0564   |
|    ent_coef_loss   | -72.4    |
|    learning_rate   | 0.0001   |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 13       |
|    time_elapsed    | 636      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | -20.2    |
|    critic_loss     | 0.022    |
|    ent_coef        | 0.0422   |
|    ent_coef_loss   | -79.9    |
|    learning_rate   | 0.0001   |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 13       |
|    time_elapsed    | 864      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | -21.7    |
|    critic_loss     | 0.0151   |
|    ent_coef        | 0.0316   |
|    ent_coef_loss   | -87.2    |
|    learning_rate   | 0.0001   |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 13       |
|    time_elapsed    | 1093     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | -21.8    |
|    critic_loss     | 0.0206   |
|    ent_coef        | 0.0237   |
|    ent_coef_loss   | -94.3    |
|    learning_rate   | 0.0001   |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 13       |
|    time_elapsed    | 1328     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | -20.9    |
|    critic_loss     | 0.0486   |
|    ent_coef        | 0.0178   |
|    ent_coef_loss   | -101     |
|    learning_rate   | 0.0001   |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 12       |
|    time_elapsed    | 1570     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | -19.8    |
|    critic_loss     | 0.00565  |
|    ent_coef        | 0.0133   |
|    ent_coef_loss   | -108     |
|    learning_rate   | 0.0001   |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1804     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | -18.4    |
|    critic_loss     | 0.00488  |
|    ent_coef        | 0.00998  |
|    ent_coef_loss   | -116     |
|    learning_rate   | 0.0001   |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2038     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | -15.5    |
|    critic_loss     | 0.0046   |
|    ent_coef        | 0.00748  |
|    ent_coef_loss   | -123     |
|    learning_rate   | 0.0001   |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 12       |
|    time_elapsed    | 2277     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | -15      |
|    critic_loss     | 0.0098   |
|    ent_coef        | 0.00561  |
|    ent_coef_loss   | -129     |
|    learning_rate   | 0.0001   |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 12       |
|    time_elapsed    | 2519     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -13      |
|    critic_loss     | 0.00698  |
|    ent_coef        | 0.00421  |
|    ent_coef_loss   | -135     |
|    learning_rate   | 0.0001   |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 12       |
|    time_elapsed    | 2751     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -11.2    |
|    critic_loss     | 0.0196   |
|    ent_coef        | 0.00316  |
|    ent_coef_loss   | -141     |
|    learning_rate   | 0.0001   |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 12       |
|    time_elapsed    | 2987     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -9.73    |
|    critic_loss     | 0.00767  |
|    ent_coef        | 0.00237  |
|    ent_coef_loss   | -145     |
|    learning_rate   | 0.0001   |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 12       |
|    time_elapsed    | 3225     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -8.84    |
|    critic_loss     | 0.0208   |
|    ent_coef        | 0.00178  |
|    ent_coef_loss   | -149     |
|    learning_rate   | 0.0001   |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 12       |
|    time_elapsed    | 3457     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -7.3     |
|    critic_loss     | 0.018    |
|    ent_coef        | 0.00134  |
|    ent_coef_loss   | -151     |
|    learning_rate   | 0.0001   |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 12       |
|    time_elapsed    | 3675     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -6.43    |
|    critic_loss     | 0.0229   |
|    ent_coef        | 0.001    |
|    ent_coef_loss   | -142     |
|    learning_rate   | 0.0001   |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 12       |
|    time_elapsed    | 3899     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -5.43    |
|    critic_loss     | 0.00549  |
|    ent_coef        | 0.000754 |
|    ent_coef_loss   | -155     |
|    learning_rate   | 0.0001   |
|    n_updates       | 48927    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 72       |
|    fps             | 12       |
|    time_elapsed    | 4128     |
|    total_timesteps | 51912    |
| train/             |          |
|    actor_loss      | -4.49    |
|    critic_loss     | 0.0106   |
|    ent_coef        | 0.000569 |
|    ent_coef_loss   | -152     |
|    learning_rate   | 0.0001   |
|    n_updates       | 51811    |
---------------------------------

---------------------------------
| time/              |          |
|    episodes        | 76       |
|    fps             | 12       |
|    time_elapsed    | 4362     |
|    total_timesteps | 54796    |
| train/             |          |
|    actor_loss      | -3.67    |
|    critic_loss     | 0.00639  |
|    ent_coef        | 0.000428 |
|    ent_coef_loss   | -151     |
|    learning_rate   | 0.0001   |
|    n_updates       | 54695    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 80       |
|    fps             | 12       |
|    time_elapsed    | 4595     |
|    total_timesteps | 57680    |
| train/             |          |
|    actor_loss      | -3.2     |
|    critic_loss     | 0.00264  |
|    ent_coef        | 0.000323 |
|    ent_coef_loss   | -148     |
|    learning_rate   | 0.0001   |
|    n_updates       | 57579    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A3_SH_only_sac_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A3_SH_only_sac_seed1_actions.csv
{'CR': -0.04396621484213836, 'AR': -0.04574081439455191, 'Vol': 0.0858879159657365, 'SR': -0.532564026967419, 'MDD': -0.12563521944232292, 'Calmar': -0.36407636805657645, 'Sortino': -0.8703166584605824, 'Omega': 0.9200148113721974, 'Turnover': 0.6485756032692526, 'FinalAccountValue': 956033.7851578614, 'variant': 'A3_SH_only', 'agent': 'sac', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A3_SH_only.CSV'}

========== A3_SH_only | TD3 | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A3_SH_only.CSV
[banktrademergeGNNtr20241231_A3_SH_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 100, 'buffer_size': 1000000, 'learning_rate': 0.001, 'seed': 1}
Using cpu device
Logging to tensorboard_log/td3\A3_SH_only_td3_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 16       |
|    time_elapsed    | 179      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 1.03     |
|    critic_loss     | 0.0101   |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 15       |
|    time_elapsed    | 379      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.952    |
|    critic_loss     | 0.00123  |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 14       |
|    time_elapsed    | 586      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.877    |
|    critic_loss     | 0.00431  |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 14       |
|    time_elapsed    | 800      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.857    |
|    critic_loss     | 0.000647 |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 13       |
|    time_elapsed    | 1032     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.801    |
|    critic_loss     | 0.000336 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 13       |
|    time_elapsed    | 1290     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.673    |
|    critic_loss     | 0.000389 |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 12       |
|    time_elapsed    | 1558     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.7      |
|    critic_loss     | 0.000881 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1849     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.623    |
|    critic_loss     | 0.000388 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2147     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.59     |
|    critic_loss     | 0.000272 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 12       |
|    time_elapsed    | 2318     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.516    |
|    critic_loss     | 0.000204 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A3_SH_only_td3_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A3_SH_only_td3_seed1_actions.csv
{'CR': -0.09304210925476786, 'AR': -0.09669476858111459, 'Vol': 0.09101245425583004, 'SR': -1.0624344697848926, 'MDD': -0.16553974695161455, 'Calmar': -0.5841181369534013, 'Sortino': -1.6309922913561816, 'Omega': 0.8372422899262716, 'Turnover': 0.4062339832139573, 'FinalAccountValue': 906957.8907452307, 'variant': 'A3_SH_only', 'agent': 'td3', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A3_SH_only.CSV'}

========== A3_SH_only | DDPG | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A3_SH_only.CSV
[banktrademergeGNNtr20241231_A3_SH_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'seed': 1}
Using cpu device
Logging to tensorboard_log/ddpg\A3_SH_only_ddpg_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 17       |
|    time_elapsed    | 163      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 0.776    |
|    critic_loss     | 0.00129  |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 18       |
|    time_elapsed    | 312      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.623    |
|    critic_loss     | 0.000958 |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 18       |
|    time_elapsed    | 474      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.451    |
|    critic_loss     | 0.000455 |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 16       |
|    time_elapsed    | 706      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.361    |
|    critic_loss     | 0.000669 |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 16       |
|    time_elapsed    | 867      |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.283    |
|    critic_loss     | 0.000417 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 16       |
|    time_elapsed    | 1040     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.219    |
|    critic_loss     | 0.000139 |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 16       |
|    time_elapsed    | 1204     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.15     |
|    critic_loss     | 9.55e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 17       |
|    time_elapsed    | 1356     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.111    |
|    critic_loss     | 5.88e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 15       |
|    time_elapsed    | 1627     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.0626   |
|    critic_loss     | 3.13e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 14       |
|    time_elapsed    | 1962     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.0263   |
|    critic_loss     | 1.62e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 13       |
|    time_elapsed    | 2309     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | 0.000536 |
|    critic_loss     | 1.56e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 13       |
|    time_elapsed    | 2659     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -0.034   |
|    critic_loss     | 1.77e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 12       |
|    time_elapsed    | 3010     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -0.06    |
|    critic_loss     | 1.91e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 11       |
|    time_elapsed    | 3369     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -0.08    |
|    critic_loss     | 7.4e-06  |
|    learning_rate   | 0.001    |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 11       |
|    time_elapsed    | 3728     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -0.114   |
|    critic_loss     | 3.18e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 11       |
|    time_elapsed    | 4057     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -0.123   |
|    critic_loss     | 1.64e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 11       |
|    time_elapsed    | 4412     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -0.137   |
|    critic_loss     | 3.03e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 48927    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A3_SH_only_ddpg_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A3_SH_only_ddpg_seed1_actions.csv
{'CR': -0.08276235527662401, 'AR': -0.08603085486167938, 'Vol': 0.09396468935626173, 'SR': -0.9155657880749047, 'MDD': -0.16363669002686476, 'Calmar': -0.5257430643919492, 'Sortino': -1.4195642502164996, 'Omega': 0.8589498750048321, 'Turnover': 0.7582459869617147, 'FinalAccountValue': 917237.644723376, 'variant': 'A3_SH_only', 'agent': 'ddpg', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A3_SH_only.CSV'}
[banktrademergeGNNtr20241231_A4_QA_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630

========== A4_QA_only | A2C | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A4_QA_only.CSV
[banktrademergeGNNtr20241231_A4_QA_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 10, 'ent_coef': 0.005, 'learning_rate': 0.0004, 'seed': 1}
Using cpu device
Logging to tensorboard_log/a2c\A4_QA_only_a2c_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

-------------------------------------
| time/                 |           |
|    fps                | 361       |
|    iterations         | 100       |
|    time_elapsed       | 2         |
|    total_timesteps    | 1000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -2.59e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 99        |
|    policy_loss        | 3.54      |
|    std                | 1.01      |
|    value_loss         | 0.0953    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 370      |
|    iterations         | 200      |
|    time_elapsed       | 5        |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -238     |
|    learning_rate      | 0.0004   |
|    n_updates          | 199      |
|    policy_loss        | -1.38    |
|    std                | 1.01     |
|    value_loss         | 0.0241   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 365       |
|    iterations         | 300       |
|    time_elapsed       | 8         |
|    total_timesteps    | 3000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -2.17e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 299       |
|    policy_loss        | 3.83      |
|    std                | 1.01      |
|    value_loss         | 0.0721    |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 365       |
|    iterations         | 400       |
|    time_elapsed       | 10        |
|    total_timesteps    | 4000      |
| train/                |           |
|    entropy_loss       | -21.5     |
|    explained_variance | -1.38e+04 |
|    learning_rate      | 0.0004    |
|    n_updates          | 399       |
|    policy_loss        | 0.673     |
|    std                | 1.01      |
|    value_loss         | 0.025     |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 354      |
|    iterations         | 500      |
|    time_elapsed       | 14       |
|    total_timesteps    | 5000     |
| train/                |          |
|    entropy_loss       | -21.5    |
|    explained_variance | -266     |
|    learning_rate      | 0.0004   |
|    n_updates          | 499      |
|    policy_loss        | -4.52    |
|    std                | 1.02     |
|    value_loss         | 0.0886   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 353      |
|    iterations         | 600      |
|    time_elapsed       | 16       |
|    total_timesteps    | 6000     |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -37.8    |
|    learning_rate      | 0.0004   |
|    n_updates          | 599      |
|    policy_loss        | -6.04    |
|    std                | 1.02     |
|    value_loss         | 0.068    |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 356      |
|    iterations         | 700      |
|    time_elapsed       | 19       |
|    total_timesteps    | 7000     |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -831     |
|    learning_rate      | 0.0004   |
|    n_updates          | 699      |
|    policy_loss        | 0.711    |
|    std                | 1.02     |
|    value_loss         | 0.0039   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 358       |
|    iterations         | 800       |
|    time_elapsed       | 22        |
|    total_timesteps    | 8000      |
| train/                |           |
|    entropy_loss       | -21.6     |
|    explained_variance | -1.67e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 799       |
|    policy_loss        | 1.76      |
|    std                | 1.02      |
|    value_loss         | 0.0149    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 364      |
|    iterations         | 900      |
|    time_elapsed       | 24       |
|    total_timesteps    | 9000     |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -760     |
|    learning_rate      | 0.0004   |
|    n_updates          | 899      |
|    policy_loss        | -0.86    |
|    std                | 1.03     |
|    value_loss         | 0.0133   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 368      |
|    iterations         | 1000     |
|    time_elapsed       | 27       |
|    total_timesteps    | 10000    |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -58.1    |
|    learning_rate      | 0.0004   |
|    n_updates          | 999      |
|    policy_loss        | 1.32     |
|    std                | 1.03     |
|    value_loss         | 0.00698  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 367      |
|    iterations         | 1100     |
|    time_elapsed       | 29       |
|    total_timesteps    | 11000    |
| train/                |          |
|    entropy_loss       | -21.8    |
|    explained_variance | -151     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1099     |
|    policy_loss        | -1.49    |
|    std                | 1.03     |
|    value_loss         | 0.0109   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 368      |
|    iterations         | 1200     |
|    time_elapsed       | 32       |
|    total_timesteps    | 12000    |
| train/                |          |
|    entropy_loss       | -21.9    |
|    explained_variance | -457     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1199     |
|    policy_loss        | -1.66    |
|    std                | 1.04     |
|    value_loss         | 0.0118   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 372      |
|    iterations         | 1300     |
|    time_elapsed       | 34       |
|    total_timesteps    | 13000    |
| train/                |          |
|    entropy_loss       | -21.9    |
|    explained_variance | -110     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1299     |
|    policy_loss        | -0.228   |
|    std                | 1.05     |
|    value_loss         | 0.00427  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 375      |
|    iterations         | 1400     |
|    time_elapsed       | 37       |
|    total_timesteps    | 14000    |
| train/                |          |
|    entropy_loss       | -22      |
|    explained_variance | -945     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1399     |
|    policy_loss        | 0.195    |
|    std                | 1.05     |
|    value_loss         | 0.00937  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 377      |
|    iterations         | 1500     |
|    time_elapsed       | 39       |
|    total_timesteps    | 15000    |
| train/                |          |
|    entropy_loss       | -22.1    |
|    explained_variance | -790     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1499     |
|    policy_loss        | 0.961    |
|    std                | 1.06     |
|    value_loss         | 0.00879  |
------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 379      |
|    iterations         | 1600     |
|    time_elapsed       | 42       |
|    total_timesteps    | 16000    |
| train/                |          |
|    entropy_loss       | -22.2    |
|    explained_variance | -168     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1599     |
|    policy_loss        | -2.29    |
|    std                | 1.07     |
|    value_loss         | 0.0158   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 380      |
|    iterations         | 1700     |
|    time_elapsed       | 44       |
|    total_timesteps    | 17000    |
| train/                |          |
|    entropy_loss       | -22.3    |
|    explained_variance | -234     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1699     |
|    policy_loss        | 0.718    |
|    std                | 1.07     |
|    value_loss         | 0.00603  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 378      |
|    iterations         | 1800     |
|    time_elapsed       | 47       |
|    total_timesteps    | 18000    |
| train/                |          |
|    entropy_loss       | -22.4    |
|    explained_variance | -64.4    |
|    learning_rate      | 0.0004   |
|    n_updates          | 1799     |
|    policy_loss        | 0.975    |
|    std                | 1.08     |
|    value_loss         | 0.00444  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 377       |
|    iterations         | 1900      |
|    time_elapsed       | 50        |
|    total_timesteps    | 19000     |
| train/                |           |
|    entropy_loss       | -22.5     |
|    explained_variance | -1.21e+04 |
|    learning_rate      | 0.0004    |
|    n_updates          | 1899      |
|    policy_loss        | -2.5      |
|    std                | 1.08      |
|    value_loss         | 0.0148    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 378      |
|    iterations         | 2000     |
|    time_elapsed       | 52       |
|    total_timesteps    | 20000    |
| train/                |          |
|    entropy_loss       | -22.6    |
|    explained_variance | -178     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1999     |
|    policy_loss        | -0.226   |
|    std                | 1.09     |
|    value_loss         | 0.00211  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 377      |
|    iterations         | 2100     |
|    time_elapsed       | 55       |
|    total_timesteps    | 21000    |
| train/                |          |
|    entropy_loss       | -22.7    |
|    explained_variance | -75.2    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2099     |
|    policy_loss        | 0.836    |
|    std                | 1.1      |
|    value_loss         | 0.00278  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 377      |
|    iterations         | 2200     |
|    time_elapsed       | 58       |
|    total_timesteps    | 22000    |
| train/                |          |
|    entropy_loss       | -22.8    |
|    explained_variance | -12.3    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2199     |
|    policy_loss        | -3.05    |
|    std                | 1.11     |
|    value_loss         | 0.0183   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 375      |
|    iterations         | 2300     |
|    time_elapsed       | 61       |
|    total_timesteps    | 23000    |
| train/                |          |
|    entropy_loss       | -22.9    |
|    explained_variance | -20.6    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2299     |
|    policy_loss        | -0.0408  |
|    std                | 1.11     |
|    value_loss         | 0.00127  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 374       |
|    iterations         | 2400      |
|    time_elapsed       | 64        |
|    total_timesteps    | 24000     |
| train/                |           |
|    entropy_loss       | -23       |
|    explained_variance | -1.19e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 2399      |
|    policy_loss        | -0.0978   |
|    std                | 1.12      |
|    value_loss         | 0.00671   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 374      |
|    iterations         | 2500     |
|    time_elapsed       | 66       |
|    total_timesteps    | 25000    |
| train/                |          |
|    entropy_loss       | -23.1    |
|    explained_variance | -153     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2499     |
|    policy_loss        | -1.51    |
|    std                | 1.13     |
|    value_loss         | 0.00655  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 374      |
|    iterations         | 2600     |
|    time_elapsed       | 69       |
|    total_timesteps    | 26000    |
| train/                |          |
|    entropy_loss       | -23.2    |
|    explained_variance | -175     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2599     |
|    policy_loss        | -0.514   |
|    std                | 1.14     |
|    value_loss         | 0.00359  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 374      |
|    iterations         | 2700     |
|    time_elapsed       | 72       |
|    total_timesteps    | 27000    |
| train/                |          |
|    entropy_loss       | -23.4    |
|    explained_variance | -55.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2699     |
|    policy_loss        | -1.2     |
|    std                | 1.15     |
|    value_loss         | 0.00395  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 374      |
|    iterations         | 2800     |
|    time_elapsed       | 74       |
|    total_timesteps    | 28000    |
| train/                |          |
|    entropy_loss       | -23.5    |
|    explained_variance | -41.2    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2799     |
|    policy_loss        | -1.27    |
|    std                | 1.16     |
|    value_loss         | 0.00444  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 372      |
|    iterations         | 2900     |
|    time_elapsed       | 77       |
|    total_timesteps    | 29000    |
| train/                |          |
|    entropy_loss       | -23.6    |
|    explained_variance | -336     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2899     |
|    policy_loss        | -0.935   |
|    std                | 1.17     |
|    value_loss         | 0.00266  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 371      |
|    iterations         | 3000     |
|    time_elapsed       | 80       |
|    total_timesteps    | 30000    |
| train/                |          |
|    entropy_loss       | -23.7    |
|    explained_variance | -166     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2999     |
|    policy_loss        | 1.54     |
|    std                | 1.18     |
|    value_loss         | 0.00634  |
------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 371      |
|    iterations         | 3100     |
|    time_elapsed       | 83       |
|    total_timesteps    | 31000    |
| train/                |          |
|    entropy_loss       | -23.8    |
|    explained_variance | -139     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3099     |
|    policy_loss        | 1.63     |
|    std                | 1.19     |
|    value_loss         | 0.00922  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 372      |
|    iterations         | 3200     |
|    time_elapsed       | 85       |
|    total_timesteps    | 32000    |
| train/                |          |
|    entropy_loss       | -23.9    |
|    explained_variance | -220     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3199     |
|    policy_loss        | 0.194    |
|    std                | 1.19     |
|    value_loss         | 0.00233  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 373      |
|    iterations         | 3300     |
|    time_elapsed       | 88       |
|    total_timesteps    | 33000    |
| train/                |          |
|    entropy_loss       | -24      |
|    explained_variance | -50.3    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3299     |
|    policy_loss        | -0.283   |
|    std                | 1.2      |
|    value_loss         | 0.00139  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 374      |
|    iterations         | 3400     |
|    time_elapsed       | 90       |
|    total_timesteps    | 34000    |
| train/                |          |
|    entropy_loss       | -24.2    |
|    explained_variance | -2.3e+03 |
|    learning_rate      | 0.0004   |
|    n_updates          | 3399     |
|    policy_loss        | -0.0411  |
|    std                | 1.22     |
|    value_loss         | 0.00131  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 374      |
|    iterations         | 3500     |
|    time_elapsed       | 93       |
|    total_timesteps    | 35000    |
| train/                |          |
|    entropy_loss       | -24.3    |
|    explained_variance | -350     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3499     |
|    policy_loss        | 1.06     |
|    std                | 1.23     |
|    value_loss         | 0.00286  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 374      |
|    iterations         | 3600     |
|    time_elapsed       | 96       |
|    total_timesteps    | 36000    |
| train/                |          |
|    entropy_loss       | -24.5    |
|    explained_variance | -25.7    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3599     |
|    policy_loss        | -0.0376  |
|    std                | 1.24     |
|    value_loss         | 0.00134  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 374       |
|    iterations         | 3700      |
|    time_elapsed       | 98        |
|    total_timesteps    | 37000     |
| train/                |           |
|    entropy_loss       | -24.6     |
|    explained_variance | -7.88e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 3699      |
|    policy_loss        | -1.77     |
|    std                | 1.25      |
|    value_loss         | 0.0106    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 375      |
|    iterations         | 3800     |
|    time_elapsed       | 101      |
|    total_timesteps    | 38000    |
| train/                |          |
|    entropy_loss       | -24.8    |
|    explained_variance | -189     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3799     |
|    policy_loss        | -1.99    |
|    std                | 1.26     |
|    value_loss         | 0.00673  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 376      |
|    iterations         | 3900     |
|    time_elapsed       | 103      |
|    total_timesteps    | 39000    |
| train/                |          |
|    entropy_loss       | -24.9    |
|    explained_variance | -19.4    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3899     |
|    policy_loss        | -0.0975  |
|    std                | 1.27     |
|    value_loss         | 0.000616 |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 376      |
|    iterations         | 4000     |
|    time_elapsed       | 106      |
|    total_timesteps    | 40000    |
| train/                |          |
|    entropy_loss       | -25      |
|    explained_variance | -35.7    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3999     |
|    policy_loss        | -0.184   |
|    std                | 1.28     |
|    value_loss         | 0.00151  |
------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A4_QA_only_a2c_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A4_QA_only_a2c_seed1_actions.csv
{'CR': -0.0594058649798892, 'AR': -0.06178324055571016, 'Vol': 0.12314538172092225, 'SR': -0.5017097652571836, 'MDD': -0.11619551352632929, 'Calmar': -0.5317179526188024, 'Sortino': -0.8163139930199035, 'Omega': 0.924486623034688, 'Turnover': 0.7242575974794849, 'FinalAccountValue': 940594.1350201109, 'variant': 'A4_QA_only', 'agent': 'a2c', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A4_QA_only.CSV'}

========== A4_QA_only | PPO | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A4_QA_only.CSV
[banktrademergeGNNtr20241231_A4_QA_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 2048, 'ent_coef': 0.005, 'learning_rate': 0.001, 'batch_size': 128, 'seed': 1}
Using cpu device
Logging to tensorboard_log/ppo\A4_QA_only_ppo_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

-----------------------------
| time/              |      |
|    fps             | 493  |
|    iterations      | 1    |
|    time_elapsed    | 4    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 395         |
|    iterations           | 2           |
|    time_elapsed         | 10          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.046932153 |
|    clip_fraction        | 0.405       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | -49.6       |
|    learning_rate        | 0.001       |
|    loss                 | -0.196      |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0721     |
|    std                  | 0.997       |
|    value_loss           | 0.0369      |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 384        |
|    iterations           | 3          |
|    time_elapsed         | 15         |
|    total_timesteps      | 6144       |
| train/                  |            |
|    approx_kl            | 0.05743862 |
|    clip_fraction        | 0.43       |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | -1.03      |
|    learning_rate        | 0.001      |
|    loss                 | -0.189     |
|    n_updates            | 20         |
|    policy_gradient_loss | -0.0661    |
|    std                  | 0.999      |
|    value_loss           | 0.00284    |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 383        |
|    iterations           | 4          |
|    time_elapsed         | 21         |
|    total_timesteps      | 8192       |
| train/                  |            |
|    approx_kl            | 0.07243818 |
|    clip_fraction        | 0.487      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.419      |
|    learning_rate        | 0.001      |
|    loss                 | -0.19      |
|    n_updates            | 30         |
|    policy_gradient_loss | -0.0638    |
|    std                  | 0.996      |
|    value_loss           | 0.000987   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 383         |
|    iterations           | 5           |
|    time_elapsed         | 26          |
|    total_timesteps      | 10240       |
| train/                  |             |
|    approx_kl            | 0.071232446 |
|    clip_fraction        | 0.495       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.2       |
|    explained_variance   | 0.695       |
|    learning_rate        | 0.001       |
|    loss                 | -0.184      |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0582     |
|    std                  | 0.999       |
|    value_loss           | 0.000532    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 383        |
|    iterations           | 6          |
|    time_elapsed         | 32         |
|    total_timesteps      | 12288      |
| train/                  |            |
|    approx_kl            | 0.07568678 |
|    clip_fraction        | 0.508      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.797      |
|    learning_rate        | 0.001      |
|    loss                 | -0.21      |
|    n_updates            | 50         |
|    policy_gradient_loss | -0.0611    |
|    std                  | 0.999      |
|    value_loss           | 0.000349   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 381        |
|    iterations           | 7          |
|    time_elapsed         | 37         |
|    total_timesteps      | 14336      |
| train/                  |            |
|    approx_kl            | 0.07351047 |
|    clip_fraction        | 0.496      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.832      |
|    learning_rate        | 0.001      |
|    loss                 | -0.182     |
|    n_updates            | 60         |
|    policy_gradient_loss | -0.0532    |
|    std                  | 1          |
|    value_loss           | 0.000248   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 382         |
|    iterations           | 8           |
|    time_elapsed         | 42          |
|    total_timesteps      | 16384       |
| train/                  |             |
|    approx_kl            | 0.080353245 |
|    clip_fraction        | 0.497       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.4       |
|    explained_variance   | 0.869       |
|    learning_rate        | 0.001       |
|    loss                 | -0.203      |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.0587     |
|    std                  | 1.01        |
|    value_loss           | 0.00025     |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 383        |
|    iterations           | 9          |
|    time_elapsed         | 48         |
|    total_timesteps      | 18432      |
| train/                  |            |
|    approx_kl            | 0.09755027 |
|    clip_fraction        | 0.547      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.794      |
|    learning_rate        | 0.001      |
|    loss                 | -0.194     |
|    n_updates            | 80         |
|    policy_gradient_loss | -0.0582    |
|    std                  | 1.01       |
|    value_loss           | 0.000174   |
----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 382       |
|    iterations           | 10        |
|    time_elapsed         | 53        |
|    total_timesteps      | 20480     |
| train/                  |           |
|    approx_kl            | 0.1031195 |
|    clip_fraction        | 0.546     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.4     |
|    explained_variance   | 0.856     |
|    learning_rate        | 0.001     |
|    loss                 | -0.166    |
|    n_updates            | 90        |
|    policy_gradient_loss | -0.05     |
|    std                  | 1         |
|    value_loss           | 0.000105  |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 383        |
|    iterations           | 11         |
|    time_elapsed         | 58         |
|    total_timesteps      | 22528      |
| train/                  |            |
|    approx_kl            | 0.10712826 |
|    clip_fraction        | 0.528      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.876      |
|    learning_rate        | 0.001      |
|    loss                 | -0.179     |
|    n_updates            | 100        |
|    policy_gradient_loss | -0.0538    |
|    std                  | 1          |
|    value_loss           | 0.000149   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 382        |
|    iterations           | 12         |
|    time_elapsed         | 64         |
|    total_timesteps      | 24576      |
| train/                  |            |
|    approx_kl            | 0.09882801 |
|    clip_fraction        | 0.53       |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.673      |
|    learning_rate        | 0.001      |
|    loss                 | -0.197     |
|    n_updates            | 110        |
|    policy_gradient_loss | -0.0557    |
|    std                  | 0.998      |
|    value_loss           | 0.000105   |
----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 381         |
|    iterations           | 13          |
|    time_elapsed         | 69          |
|    total_timesteps      | 26624       |
| train/                  |             |
|    approx_kl            | 0.107987754 |
|    clip_fraction        | 0.527       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | 0.872       |
|    learning_rate        | 0.001       |
|    loss                 | -0.187      |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.0494     |
|    std                  | 1           |
|    value_loss           | 7.8e-05     |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 382        |
|    iterations           | 14         |
|    time_elapsed         | 75         |
|    total_timesteps      | 28672      |
| train/                  |            |
|    approx_kl            | 0.11294576 |
|    clip_fraction        | 0.532      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.667      |
|    learning_rate        | 0.001      |
|    loss                 | -0.184     |
|    n_updates            | 130        |
|    policy_gradient_loss | -0.053     |
|    std                  | 1          |
|    value_loss           | 0.000104   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 383         |
|    iterations           | 15          |
|    time_elapsed         | 80          |
|    total_timesteps      | 30720       |
| train/                  |             |
|    approx_kl            | 0.123405874 |
|    clip_fraction        | 0.56        |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | 0.776       |
|    learning_rate        | 0.001       |
|    loss                 | -0.19       |
|    n_updates            | 140         |
|    policy_gradient_loss | -0.0533     |
|    std                  | 1           |
|    value_loss           | 6.36e-05    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 382        |
|    iterations           | 16         |
|    time_elapsed         | 85         |
|    total_timesteps      | 32768      |
| train/                  |            |
|    approx_kl            | 0.12426154 |
|    clip_fraction        | 0.551      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.879      |
|    learning_rate        | 0.001      |
|    loss                 | -0.199     |
|    n_updates            | 150        |
|    policy_gradient_loss | -0.0568    |
|    std                  | 1          |
|    value_loss           | 7.81e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 382        |
|    iterations           | 17         |
|    time_elapsed         | 90         |
|    total_timesteps      | 34816      |
| train/                  |            |
|    approx_kl            | 0.12303289 |
|    clip_fraction        | 0.566      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.733      |
|    learning_rate        | 0.001      |
|    loss                 | -0.176     |
|    n_updates            | 160        |
|    policy_gradient_loss | -0.0507    |
|    std                  | 1          |
|    value_loss           | 7.6e-05    |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 383        |
|    iterations           | 18         |
|    time_elapsed         | 96         |
|    total_timesteps      | 36864      |
| train/                  |            |
|    approx_kl            | 0.13598767 |
|    clip_fraction        | 0.585      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.756      |
|    learning_rate        | 0.001      |
|    loss                 | -0.192     |
|    n_updates            | 170        |
|    policy_gradient_loss | -0.0488    |
|    std                  | 1          |
|    value_loss           | 7.7e-05    |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 383        |
|    iterations           | 19         |
|    time_elapsed         | 101        |
|    total_timesteps      | 38912      |
| train/                  |            |
|    approx_kl            | 0.12104848 |
|    clip_fraction        | 0.554      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.775      |
|    learning_rate        | 0.001      |
|    loss                 | -0.186     |
|    n_updates            | 180        |
|    policy_gradient_loss | -0.0555    |
|    std                  | 1          |
|    value_loss           | 7.23e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 383        |
|    iterations           | 20         |
|    time_elapsed         | 106        |
|    total_timesteps      | 40960      |
| train/                  |            |
|    approx_kl            | 0.13238397 |
|    clip_fraction        | 0.577      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.662      |
|    learning_rate        | 0.001      |
|    loss                 | -0.188     |
|    n_updates            | 190        |
|    policy_gradient_loss | -0.0558    |
|    std                  | 0.998      |
|    value_loss           | 0.000168   |
----------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A4_QA_only_ppo_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A4_QA_only_ppo_seed1_actions.csv
{'CR': -0.061408009534746566, 'AR': -0.06386275725313639, 'Vol': 0.11730580672183097, 'SR': -0.544412583126214, 'MDD': -0.15256658044667593, 'Calmar': -0.4185894254571517, 'Sortino': -0.8796334835755286, 'Omega': 0.9169210217367614, 'Turnover': 0.7383898198180567, 'FinalAccountValue': 938591.9904652529, 'variant': 'A4_QA_only', 'agent': 'ppo', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A4_QA_only.CSV'}

========== A4_QA_only | SAC | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A4_QA_only.CSV
[banktrademergeGNNtr20241231_A4_QA_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 128, 'buffer_size': 1000000, 'learning_rate': 0.0001, 'learning_starts': 100, 'ent_coef': 'auto_0.1', 'seed': 1}
Using cpu device
Logging to tensorboard_log/sac\A4_QA_only_sac_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 14       |
|    time_elapsed    | 197      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | -9.76    |
|    critic_loss     | 0.0207   |
|    ent_coef        | 0.0753   |
|    ent_coef_loss   | -64.8    |
|    learning_rate   | 0.0001   |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 14       |
|    time_elapsed    | 405      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | -16.5    |
|    critic_loss     | 0.024    |
|    ent_coef        | 0.0564   |
|    ent_coef_loss   | -72.4    |
|    learning_rate   | 0.0001   |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 13       |
|    time_elapsed    | 623      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | -20.1    |
|    critic_loss     | 0.0353   |
|    ent_coef        | 0.0422   |
|    ent_coef_loss   | -80.1    |
|    learning_rate   | 0.0001   |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 13       |
|    time_elapsed    | 849      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | -21.7    |
|    critic_loss     | 0.0223   |
|    ent_coef        | 0.0316   |
|    ent_coef_loss   | -87.1    |
|    learning_rate   | 0.0001   |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 13       |
|    time_elapsed    | 1080     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | -21.8    |
|    critic_loss     | 0.0283   |
|    ent_coef        | 0.0237   |
|    ent_coef_loss   | -94.4    |
|    learning_rate   | 0.0001   |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 13       |
|    time_elapsed    | 1321     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | -20.9    |
|    critic_loss     | 0.0347   |
|    ent_coef        | 0.0178   |
|    ent_coef_loss   | -102     |
|    learning_rate   | 0.0001   |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 12       |
|    time_elapsed    | 1562     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | -19.8    |
|    critic_loss     | 0.0069   |
|    ent_coef        | 0.0133   |
|    ent_coef_loss   | -108     |
|    learning_rate   | 0.0001   |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1802     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | -18.4    |
|    critic_loss     | 0.0125   |
|    ent_coef        | 0.00998  |
|    ent_coef_loss   | -116     |
|    learning_rate   | 0.0001   |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2042     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | -15.5    |
|    critic_loss     | 0.00242  |
|    ent_coef        | 0.00748  |
|    ent_coef_loss   | -123     |
|    learning_rate   | 0.0001   |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 12       |
|    time_elapsed    | 2282     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | -15.1    |
|    critic_loss     | 0.0104   |
|    ent_coef        | 0.00561  |
|    ent_coef_loss   | -129     |
|    learning_rate   | 0.0001   |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 12       |
|    time_elapsed    | 2520     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -13      |
|    critic_loss     | 0.00835  |
|    ent_coef        | 0.00421  |
|    ent_coef_loss   | -135     |
|    learning_rate   | 0.0001   |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 12       |
|    time_elapsed    | 2758     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -11.2    |
|    critic_loss     | 0.00203  |
|    ent_coef        | 0.00316  |
|    ent_coef_loss   | -142     |
|    learning_rate   | 0.0001   |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 12       |
|    time_elapsed    | 2997     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -9.71    |
|    critic_loss     | 0.0145   |
|    ent_coef        | 0.00237  |
|    ent_coef_loss   | -146     |
|    learning_rate   | 0.0001   |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 12       |
|    time_elapsed    | 3246     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -8.9     |
|    critic_loss     | 0.00732  |
|    ent_coef        | 0.00178  |
|    ent_coef_loss   | -149     |
|    learning_rate   | 0.0001   |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 12       |
|    time_elapsed    | 3489     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -7.15    |
|    critic_loss     | 0.0334   |
|    ent_coef        | 0.00133  |
|    ent_coef_loss   | -148     |
|    learning_rate   | 0.0001   |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 12       |
|    time_elapsed    | 3734     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -6.49    |
|    critic_loss     | 0.00402  |
|    ent_coef        | 0.001    |
|    ent_coef_loss   | -156     |
|    learning_rate   | 0.0001   |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 12       |
|    time_elapsed    | 3969     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -5.42    |
|    critic_loss     | 0.0018   |
|    ent_coef        | 0.000754 |
|    ent_coef_loss   | -152     |
|    learning_rate   | 0.0001   |
|    n_updates       | 48927    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 72       |
|    fps             | 12       |
|    time_elapsed    | 4206     |
|    total_timesteps | 51912    |
| train/             |          |
|    actor_loss      | -4.56    |
|    critic_loss     | 0.000584 |
|    ent_coef        | 0.000568 |
|    ent_coef_loss   | -162     |
|    learning_rate   | 0.0001   |
|    n_updates       | 51811    |
---------------------------------

---------------------------------
| time/              |          |
|    episodes        | 76       |
|    fps             | 12       |
|    time_elapsed    | 4447     |
|    total_timesteps | 54796    |
| train/             |          |
|    actor_loss      | -3.68    |
|    critic_loss     | 0.00661  |
|    ent_coef        | 0.000427 |
|    ent_coef_loss   | -154     |
|    learning_rate   | 0.0001   |
|    n_updates       | 54695    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 80       |
|    fps             | 12       |
|    time_elapsed    | 4681     |
|    total_timesteps | 57680    |
| train/             |          |
|    actor_loss      | -3.19    |
|    critic_loss     | 0.0035   |
|    ent_coef        | 0.000323 |
|    ent_coef_loss   | -138     |
|    learning_rate   | 0.0001   |
|    n_updates       | 57579    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A4_QA_only_sac_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A4_QA_only_sac_seed1_actions.csv
{'CR': -0.013418067478584206, 'AR': -0.013968642712736679, 'Vol': 0.1252747843907121, 'SR': -0.1115040251769319, 'MDD': -0.12410472431233799, 'Calmar': -0.11255528578897116, 'Sortino': -0.1804675854932018, 'Omega': 0.9912211713361598, 'Turnover': 0.6529476355092434, 'FinalAccountValue': 986581.9325214146, 'variant': 'A4_QA_only', 'agent': 'sac', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A4_QA_only.CSV'}

========== A4_QA_only | TD3 | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A4_QA_only.CSV
[banktrademergeGNNtr20241231_A4_QA_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 100, 'buffer_size': 1000000, 'learning_rate': 0.001, 'seed': 1}
Using cpu device
Logging to tensorboard_log/td3\A4_QA_only_td3_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 16       |
|    time_elapsed    | 175      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 1.01     |
|    critic_loss     | 0.00736  |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 15       |
|    time_elapsed    | 373      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 1.02     |
|    critic_loss     | 0.00126  |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 14       |
|    time_elapsed    | 578      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.927    |
|    critic_loss     | 0.00311  |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 14       |
|    time_elapsed    | 792      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.909    |
|    critic_loss     | 0.00113  |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 14       |
|    time_elapsed    | 1024     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.848    |
|    critic_loss     | 0.000638 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 13       |
|    time_elapsed    | 1277     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.714    |
|    critic_loss     | 0.00146  |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 13       |
|    time_elapsed    | 1547     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.72     |
|    critic_loss     | 0.000625 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1830     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.647    |
|    critic_loss     | 0.000112 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2113     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.619    |
|    critic_loss     | 0.000455 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 11       |
|    time_elapsed    | 2413     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.547    |
|    critic_loss     | 6.8e-05  |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A4_QA_only_td3_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A4_QA_only_td3_seed1_actions.csv
{'CR': -0.01663018650722159, 'AR': -0.017311402181100943, 'Vol': 0.10434239169196255, 'SR': -0.16590957807644766, 'MDD': -0.11303613736262441, 'Calmar': -0.1531492723036464, 'Sortino': -0.2540140393700858, 'Omega': 0.9799686165637034, 'Turnover': 0.42657636064779486, 'FinalAccountValue': 983369.8134927795, 'variant': 'A4_QA_only', 'agent': 'td3', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A4_QA_only.CSV'}

========== A4_QA_only | DDPG | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A4_QA_only.CSV
[banktrademergeGNNtr20241231_A4_QA_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'seed': 1}
Using cpu device
Logging to tensorboard_log/ddpg\A4_QA_only_ddpg_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 11       |
|    time_elapsed    | 259      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 0.587    |
|    critic_loss     | 0.000939 |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 10       |
|    time_elapsed    | 525      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.466    |
|    critic_loss     | 0.00067  |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 10       |
|    time_elapsed    | 792      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.359    |
|    critic_loss     | 0.00033  |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 10       |
|    time_elapsed    | 1074     |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.27     |
|    critic_loss     | 0.000143 |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 10       |
|    time_elapsed    | 1352     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.204    |
|    critic_loss     | 0.000138 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 10       |
|    time_elapsed    | 1652     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.157    |
|    critic_loss     | 1.23e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 10       |
|    time_elapsed    | 1964     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.1      |
|    critic_loss     | 2.44e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 10       |
|    time_elapsed    | 2277     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.0698   |
|    critic_loss     | 1.49e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 9        |
|    time_elapsed    | 2605     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.0375   |
|    critic_loss     | 1.98e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 9        |
|    time_elapsed    | 2946     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.00903  |
|    critic_loss     | 3.04e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 9        |
|    time_elapsed    | 3287     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -0.0123  |
|    critic_loss     | 1.03e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 9        |
|    time_elapsed    | 3634     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -0.0371  |
|    critic_loss     | 1.81e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 9        |
|    time_elapsed    | 3984     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -0.0625  |
|    critic_loss     | 1.09e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 9        |
|    time_elapsed    | 4336     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -0.077   |
|    critic_loss     | 1.13e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 9        |
|    time_elapsed    | 4690     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -0.105   |
|    critic_loss     | 1.84e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 9        |
|    time_elapsed    | 5046     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -0.11    |
|    critic_loss     | 6.03e-06 |
|    learning_rate   | 0.001    |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 9        |
|    time_elapsed    | 5410     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -0.12    |
|    critic_loss     | 7.83e-06 |
|    learning_rate   | 0.001    |
|    n_updates       | 48927    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A4_QA_only_ddpg_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A4_QA_only_ddpg_seed1_actions.csv
{'CR': -0.0052088456632601865, 'AR': -0.0054235025009569116, 'Vol': 0.13694084649742114, 'SR': -0.03960470991435741, 'MDD': -0.18255112007373797, 'Calmar': -0.02970949999521336, 'Sortino': -0.06644167474692254, 'Omega': 1.0051478324942307, 'Turnover': 0.7631201166263752, 'FinalAccountValue': 994791.154336739, 'variant': 'A4_QA_only', 'agent': 'ddpg', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A4_QA_only.CSV'}
[banktrademergeGNNtr20241231_A5_KD_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630

========== A5_KD_only | A2C | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A5_KD_only.CSV
[banktrademergeGNNtr20241231_A5_KD_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 10, 'ent_coef': 0.005, 'learning_rate': 0.0004, 'seed': 1}
Using cpu device
Logging to tensorboard_log/a2c\A5_KD_only_a2c_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

-------------------------------------
| time/                 |           |
|    fps                | 384       |
|    iterations         | 100       |
|    time_elapsed       | 2         |
|    total_timesteps    | 1000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -4.24e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 99        |
|    policy_loss        | 1.4       |
|    std                | 1         |
|    value_loss         | 0.0694    |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 393       |
|    iterations         | 200       |
|    time_elapsed       | 5         |
|    total_timesteps    | 2000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -1.88e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 199       |
|    policy_loss        | -6.01     |
|    std                | 1         |
|    value_loss         | 0.12      |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 400       |
|    iterations         | 300       |
|    time_elapsed       | 7         |
|    total_timesteps    | 3000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -1.49e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 299       |
|    policy_loss        | 2.09      |
|    std                | 1.01      |
|    value_loss         | 0.0398    |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 401       |
|    iterations         | 400       |
|    time_elapsed       | 9         |
|    total_timesteps    | 4000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -4.14e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 399       |
|    policy_loss        | -2.47     |
|    std                | 1.01      |
|    value_loss         | 0.0417    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 405      |
|    iterations         | 500      |
|    time_elapsed       | 12       |
|    total_timesteps    | 5000     |
| train/                |          |
|    entropy_loss       | -21.5    |
|    explained_variance | -393     |
|    learning_rate      | 0.0004   |
|    n_updates          | 499      |
|    policy_loss        | 0.663    |
|    std                | 1.01     |
|    value_loss         | 0.0188   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 404      |
|    iterations         | 600      |
|    time_elapsed       | 14       |
|    total_timesteps    | 6000     |
| train/                |          |
|    entropy_loss       | -21.5    |
|    explained_variance | -101     |
|    learning_rate      | 0.0004   |
|    n_updates          | 599      |
|    policy_loss        | -5.46    |
|    std                | 1.01     |
|    value_loss         | 0.0636   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 700      |
|    time_elapsed       | 17       |
|    total_timesteps    | 7000     |
| train/                |          |
|    entropy_loss       | -21.5    |
|    explained_variance | -908     |
|    learning_rate      | 0.0004   |
|    n_updates          | 699      |
|    policy_loss        | -0.637   |
|    std                | 1.02     |
|    value_loss         | 0.00374  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 800      |
|    time_elapsed       | 20       |
|    total_timesteps    | 8000     |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -71.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 799      |
|    policy_loss        | 5.27     |
|    std                | 1.02     |
|    value_loss         | 0.0672   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 398      |
|    iterations         | 900      |
|    time_elapsed       | 22       |
|    total_timesteps    | 9000     |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -377     |
|    learning_rate      | 0.0004   |
|    n_updates          | 899      |
|    policy_loss        | 0.028    |
|    std                | 1.02     |
|    value_loss         | 0.00578  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 1000     |
|    time_elapsed       | 25       |
|    total_timesteps    | 10000    |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -187     |
|    learning_rate      | 0.0004   |
|    n_updates          | 999      |
|    policy_loss        | 1.02     |
|    std                | 1.03     |
|    value_loss         | 0.0127   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 1100     |
|    time_elapsed       | 27       |
|    total_timesteps    | 11000    |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -519     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1099     |
|    policy_loss        | 3.2      |
|    std                | 1.03     |
|    value_loss         | 0.0224   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 402      |
|    iterations         | 1200     |
|    time_elapsed       | 29       |
|    total_timesteps    | 12000    |
| train/                |          |
|    entropy_loss       | -21.8    |
|    explained_variance | -99.2    |
|    learning_rate      | 0.0004   |
|    n_updates          | 1199     |
|    policy_loss        | -2.68    |
|    std                | 1.04     |
|    value_loss         | 0.0211   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 1300     |
|    time_elapsed       | 32       |
|    total_timesteps    | 13000    |
| train/                |          |
|    entropy_loss       | -21.9    |
|    explained_variance | -88.6    |
|    learning_rate      | 0.0004   |
|    n_updates          | 1299     |
|    policy_loss        | -0.529   |
|    std                | 1.04     |
|    value_loss         | 0.00372  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 398      |
|    iterations         | 1400     |
|    time_elapsed       | 35       |
|    total_timesteps    | 14000    |
| train/                |          |
|    entropy_loss       | -22      |
|    explained_variance | -419     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1399     |
|    policy_loss        | -0.332   |
|    std                | 1.05     |
|    value_loss         | 0.00516  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 1500     |
|    time_elapsed       | 37       |
|    total_timesteps    | 15000    |
| train/                |          |
|    entropy_loss       | -22.1    |
|    explained_variance | -238     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1499     |
|    policy_loss        | -2.47    |
|    std                | 1.05     |
|    value_loss         | 0.0123   |
------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 1600     |
|    time_elapsed       | 39       |
|    total_timesteps    | 16000    |
| train/                |          |
|    entropy_loss       | -22.2    |
|    explained_variance | -392     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1599     |
|    policy_loss        | -0.287   |
|    std                | 1.06     |
|    value_loss         | 0.00328  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 1700     |
|    time_elapsed       | 42       |
|    total_timesteps    | 17000    |
| train/                |          |
|    entropy_loss       | -22.2    |
|    explained_variance | -244     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1699     |
|    policy_loss        | 0.681    |
|    std                | 1.07     |
|    value_loss         | 0.00279  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 402      |
|    iterations         | 1800     |
|    time_elapsed       | 44       |
|    total_timesteps    | 18000    |
| train/                |          |
|    entropy_loss       | -22.3    |
|    explained_variance | -53.3    |
|    learning_rate      | 0.0004   |
|    n_updates          | 1799     |
|    policy_loss        | -1.11    |
|    std                | 1.07     |
|    value_loss         | 0.00532  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 402       |
|    iterations         | 1900      |
|    time_elapsed       | 47        |
|    total_timesteps    | 19000     |
| train/                |           |
|    entropy_loss       | -22.4     |
|    explained_variance | -1.32e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 1899      |
|    policy_loss        | -1.05     |
|    std                | 1.08      |
|    value_loss         | 0.00864   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 2000     |
|    time_elapsed       | 49       |
|    total_timesteps    | 20000    |
| train/                |          |
|    entropy_loss       | -22.5    |
|    explained_variance | -502     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1999     |
|    policy_loss        | -0.744   |
|    std                | 1.08     |
|    value_loss         | 0.0106   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 2100     |
|    time_elapsed       | 52       |
|    total_timesteps    | 21000    |
| train/                |          |
|    entropy_loss       | -22.6    |
|    explained_variance | -449     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2099     |
|    policy_loss        | 0.637    |
|    std                | 1.09     |
|    value_loss         | 0.0035   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 2200     |
|    time_elapsed       | 54       |
|    total_timesteps    | 22000    |
| train/                |          |
|    entropy_loss       | -22.7    |
|    explained_variance | -38.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2199     |
|    policy_loss        | -0.43    |
|    std                | 1.1      |
|    value_loss         | 0.00193  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 402      |
|    iterations         | 2300     |
|    time_elapsed       | 57       |
|    total_timesteps    | 23000    |
| train/                |          |
|    entropy_loss       | -22.8    |
|    explained_variance | -69.4    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2299     |
|    policy_loss        | -3.59    |
|    std                | 1.11     |
|    value_loss         | 0.0315   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 402      |
|    iterations         | 2400     |
|    time_elapsed       | 59       |
|    total_timesteps    | 24000    |
| train/                |          |
|    entropy_loss       | -22.9    |
|    explained_variance | -45.2    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2399     |
|    policy_loss        | -2.47    |
|    std                | 1.12     |
|    value_loss         | 0.0144   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 403       |
|    iterations         | 2500      |
|    time_elapsed       | 62        |
|    total_timesteps    | 25000     |
| train/                |           |
|    entropy_loss       | -23       |
|    explained_variance | -51.7     |
|    learning_rate      | 0.0004    |
|    n_updates          | 2499      |
|    policy_loss        | -0.000998 |
|    std                | 1.12      |
|    value_loss         | 0.0014    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 2600     |
|    time_elapsed       | 64       |
|    total_timesteps    | 26000    |
| train/                |          |
|    entropy_loss       | -23.1    |
|    explained_variance | -307     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2599     |
|    policy_loss        | -0.334   |
|    std                | 1.13     |
|    value_loss         | 0.0038   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 2700     |
|    time_elapsed       | 67       |
|    total_timesteps    | 27000    |
| train/                |          |
|    entropy_loss       | -23.3    |
|    explained_variance | -96.7    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2699     |
|    policy_loss        | -0.675   |
|    std                | 1.14     |
|    value_loss         | 0.00237  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 2800     |
|    time_elapsed       | 69       |
|    total_timesteps    | 28000    |
| train/                |          |
|    entropy_loss       | -23.4    |
|    explained_variance | -27.3    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2799     |
|    policy_loss        | -0.948   |
|    std                | 1.15     |
|    value_loss         | 0.00294  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 2900     |
|    time_elapsed       | 72       |
|    total_timesteps    | 29000    |
| train/                |          |
|    entropy_loss       | -23.5    |
|    explained_variance | -302     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2899     |
|    policy_loss        | 0.79     |
|    std                | 1.16     |
|    value_loss         | 0.00175  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 3000     |
|    time_elapsed       | 75       |
|    total_timesteps    | 30000    |
| train/                |          |
|    entropy_loss       | -23.6    |
|    explained_variance | -293     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2999     |
|    policy_loss        | -0.289   |
|    std                | 1.17     |
|    value_loss         | 0.00247  |
------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 393      |
|    iterations         | 3100     |
|    time_elapsed       | 78       |
|    total_timesteps    | 31000    |
| train/                |          |
|    entropy_loss       | -23.7    |
|    explained_variance | -62.7    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3099     |
|    policy_loss        | -1.41    |
|    std                | 1.18     |
|    value_loss         | 0.00545  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 392      |
|    iterations         | 3200     |
|    time_elapsed       | 81       |
|    total_timesteps    | 32000    |
| train/                |          |
|    entropy_loss       | -23.9    |
|    explained_variance | -163     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3199     |
|    policy_loss        | 1.18     |
|    std                | 1.19     |
|    value_loss         | 0.00419  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 390      |
|    iterations         | 3300     |
|    time_elapsed       | 84       |
|    total_timesteps    | 33000    |
| train/                |          |
|    entropy_loss       | -24      |
|    explained_variance | -19      |
|    learning_rate      | 0.0004   |
|    n_updates          | 3299     |
|    policy_loss        | 0.382    |
|    std                | 1.2      |
|    value_loss         | 0.000713 |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 391      |
|    iterations         | 3400     |
|    time_elapsed       | 86       |
|    total_timesteps    | 34000    |
| train/                |          |
|    entropy_loss       | -24.1    |
|    explained_variance | -660     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3399     |
|    policy_loss        | 2.62     |
|    std                | 1.21     |
|    value_loss         | 0.0141   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 391      |
|    iterations         | 3500     |
|    time_elapsed       | 89       |
|    total_timesteps    | 35000    |
| train/                |          |
|    entropy_loss       | -24.2    |
|    explained_variance | -635     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3499     |
|    policy_loss        | -1.1     |
|    std                | 1.22     |
|    value_loss         | 0.00281  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 392      |
|    iterations         | 3600     |
|    time_elapsed       | 91       |
|    total_timesteps    | 36000    |
| train/                |          |
|    entropy_loss       | -24.3    |
|    explained_variance | -38.6    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3599     |
|    policy_loss        | -1.36    |
|    std                | 1.23     |
|    value_loss         | 0.00513  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 392       |
|    iterations         | 3700      |
|    time_elapsed       | 94        |
|    total_timesteps    | 37000     |
| train/                |           |
|    entropy_loss       | -24.5     |
|    explained_variance | -1.44e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 3699      |
|    policy_loss        | -0.108    |
|    std                | 1.24      |
|    value_loss         | 0.00132   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 391      |
|    iterations         | 3800     |
|    time_elapsed       | 97       |
|    total_timesteps    | 38000    |
| train/                |          |
|    entropy_loss       | -24.6    |
|    explained_variance | -112     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3799     |
|    policy_loss        | -0.663   |
|    std                | 1.25     |
|    value_loss         | 0.00154  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 391      |
|    iterations         | 3900     |
|    time_elapsed       | 99       |
|    total_timesteps    | 39000    |
| train/                |          |
|    entropy_loss       | -24.7    |
|    explained_variance | -31.2    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3899     |
|    policy_loss        | 0.0365   |
|    std                | 1.26     |
|    value_loss         | 0.00108  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 390      |
|    iterations         | 4000     |
|    time_elapsed       | 102      |
|    total_timesteps    | 40000    |
| train/                |          |
|    entropy_loss       | -24.9    |
|    explained_variance | -44.4    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3999     |
|    policy_loss        | -0.362   |
|    std                | 1.27     |
|    value_loss         | 0.00154  |
------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A5_KD_only_a2c_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A5_KD_only_a2c_seed1_actions.csv
{'CR': -0.06846339019685577, 'AR': -0.0711893269730074, 'Vol': 0.062281601345261485, 'SR': -1.143023387892123, 'MDD': -0.11538115271848659, 'Calmar': -0.6169926829098259, 'Sortino': -1.6620050257431103, 'Omega': 0.812393683095185, 'Turnover': 0.7498847560376861, 'FinalAccountValue': 931536.6098031442, 'variant': 'A5_KD_only', 'agent': 'a2c', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A5_KD_only.CSV'}

========== A5_KD_only | PPO | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A5_KD_only.CSV
[banktrademergeGNNtr20241231_A5_KD_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 2048, 'ent_coef': 0.005, 'learning_rate': 0.001, 'batch_size': 128, 'seed': 1}
Using cpu device
Logging to tensorboard_log/ppo\A5_KD_only_ppo_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

-----------------------------
| time/              |      |
|    fps             | 484  |
|    iterations      | 1    |
|    time_elapsed    | 4    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 375         |
|    iterations           | 2           |
|    time_elapsed         | 10          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.050042514 |
|    clip_fraction        | 0.412       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | -52.4       |
|    learning_rate        | 0.001       |
|    loss                 | -0.191      |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.073      |
|    std                  | 0.997       |
|    value_loss           | 0.0359      |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 359         |
|    iterations           | 3           |
|    time_elapsed         | 17          |
|    total_timesteps      | 6144        |
| train/                  |             |
|    approx_kl            | 0.053796202 |
|    clip_fraction        | 0.426       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | -1.2        |
|    learning_rate        | 0.001       |
|    loss                 | -0.217      |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0684     |
|    std                  | 0.999       |
|    value_loss           | 0.00267     |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 361        |
|    iterations           | 4          |
|    time_elapsed         | 22         |
|    total_timesteps      | 8192       |
| train/                  |            |
|    approx_kl            | 0.06674832 |
|    clip_fraction        | 0.485      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.376      |
|    learning_rate        | 0.001      |
|    loss                 | -0.208     |
|    n_updates            | 30         |
|    policy_gradient_loss | -0.0645    |
|    std                  | 0.997      |
|    value_loss           | 0.00101    |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 350        |
|    iterations           | 5          |
|    time_elapsed         | 29         |
|    total_timesteps      | 10240      |
| train/                  |            |
|    approx_kl            | 0.06388508 |
|    clip_fraction        | 0.479      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.654      |
|    learning_rate        | 0.001      |
|    loss                 | -0.199     |
|    n_updates            | 40         |
|    policy_gradient_loss | -0.0605    |
|    std                  | 0.999      |
|    value_loss           | 0.000544   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 351         |
|    iterations           | 6           |
|    time_elapsed         | 34          |
|    total_timesteps      | 12288       |
| train/                  |             |
|    approx_kl            | 0.082897216 |
|    clip_fraction        | 0.52        |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | 0.781       |
|    learning_rate        | 0.001       |
|    loss                 | -0.173      |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.0557     |
|    std                  | 0.999       |
|    value_loss           | 0.000381    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 350         |
|    iterations           | 7           |
|    time_elapsed         | 40          |
|    total_timesteps      | 14336       |
| train/                  |             |
|    approx_kl            | 0.085635975 |
|    clip_fraction        | 0.525       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | 0.822       |
|    learning_rate        | 0.001       |
|    loss                 | -0.191      |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.0527     |
|    std                  | 1           |
|    value_loss           | 0.000234    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 345        |
|    iterations           | 8          |
|    time_elapsed         | 47         |
|    total_timesteps      | 16384      |
| train/                  |            |
|    approx_kl            | 0.10134642 |
|    clip_fraction        | 0.542      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.849      |
|    learning_rate        | 0.001      |
|    loss                 | -0.19      |
|    n_updates            | 70         |
|    policy_gradient_loss | -0.0539    |
|    std                  | 1          |
|    value_loss           | 0.000206   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 345        |
|    iterations           | 9          |
|    time_elapsed         | 53         |
|    total_timesteps      | 18432      |
| train/                  |            |
|    approx_kl            | 0.10586321 |
|    clip_fraction        | 0.551      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.814      |
|    learning_rate        | 0.001      |
|    loss                 | -0.184     |
|    n_updates            | 80         |
|    policy_gradient_loss | -0.0563    |
|    std                  | 1.01       |
|    value_loss           | 0.000143   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 344        |
|    iterations           | 10         |
|    time_elapsed         | 59         |
|    total_timesteps      | 20480      |
| train/                  |            |
|    approx_kl            | 0.09838428 |
|    clip_fraction        | 0.544      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.875      |
|    learning_rate        | 0.001      |
|    loss                 | -0.187     |
|    n_updates            | 90         |
|    policy_gradient_loss | -0.0561    |
|    std                  | 1.01       |
|    value_loss           | 0.000136   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 344        |
|    iterations           | 11         |
|    time_elapsed         | 65         |
|    total_timesteps      | 22528      |
| train/                  |            |
|    approx_kl            | 0.10448003 |
|    clip_fraction        | 0.54       |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.759      |
|    learning_rate        | 0.001      |
|    loss                 | -0.179     |
|    n_updates            | 100        |
|    policy_gradient_loss | -0.0434    |
|    std                  | 1.01       |
|    value_loss           | 0.000213   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 345        |
|    iterations           | 12         |
|    time_elapsed         | 71         |
|    total_timesteps      | 24576      |
| train/                  |            |
|    approx_kl            | 0.10297128 |
|    clip_fraction        | 0.544      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.657      |
|    learning_rate        | 0.001      |
|    loss                 | -0.192     |
|    n_updates            | 110        |
|    policy_gradient_loss | -0.0592    |
|    std                  | 1.01       |
|    value_loss           | 0.00017    |
----------------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 343        |
|    iterations           | 13         |
|    time_elapsed         | 77         |
|    total_timesteps      | 26624      |
| train/                  |            |
|    approx_kl            | 0.11137458 |
|    clip_fraction        | 0.557      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.82       |
|    learning_rate        | 0.001      |
|    loss                 | -0.192     |
|    n_updates            | 120        |
|    policy_gradient_loss | -0.0576    |
|    std                  | 1.01       |
|    value_loss           | 9.99e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 346        |
|    iterations           | 14         |
|    time_elapsed         | 82         |
|    total_timesteps      | 28672      |
| train/                  |            |
|    approx_kl            | 0.13594338 |
|    clip_fraction        | 0.589      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.815      |
|    learning_rate        | 0.001      |
|    loss                 | -0.177     |
|    n_updates            | 130        |
|    policy_gradient_loss | -0.0512    |
|    std                  | 1.01       |
|    value_loss           | 8.34e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 349        |
|    iterations           | 15         |
|    time_elapsed         | 87         |
|    total_timesteps      | 30720      |
| train/                  |            |
|    approx_kl            | 0.12543222 |
|    clip_fraction        | 0.576      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.681      |
|    learning_rate        | 0.001      |
|    loss                 | -0.182     |
|    n_updates            | 140        |
|    policy_gradient_loss | -0.0527    |
|    std                  | 1          |
|    value_loss           | 9.82e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 349        |
|    iterations           | 16         |
|    time_elapsed         | 93         |
|    total_timesteps      | 32768      |
| train/                  |            |
|    approx_kl            | 0.12656613 |
|    clip_fraction        | 0.573      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.82       |
|    learning_rate        | 0.001      |
|    loss                 | -0.205     |
|    n_updates            | 150        |
|    policy_gradient_loss | -0.0563    |
|    std                  | 1.01       |
|    value_loss           | 9.36e-05   |
----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 352       |
|    iterations           | 17        |
|    time_elapsed         | 98        |
|    total_timesteps      | 34816     |
| train/                  |           |
|    approx_kl            | 0.1349479 |
|    clip_fraction        | 0.6       |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.5     |
|    explained_variance   | 0.707     |
|    learning_rate        | 0.001     |
|    loss                 | -0.197    |
|    n_updates            | 160       |
|    policy_gradient_loss | -0.0526   |
|    std                  | 1.01      |
|    value_loss           | 7.51e-05  |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 353        |
|    iterations           | 18         |
|    time_elapsed         | 104        |
|    total_timesteps      | 36864      |
| train/                  |            |
|    approx_kl            | 0.17468162 |
|    clip_fraction        | 0.616      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.831      |
|    learning_rate        | 0.001      |
|    loss                 | -0.167     |
|    n_updates            | 170        |
|    policy_gradient_loss | -0.0459    |
|    std                  | 1.02       |
|    value_loss           | 5.42e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 354        |
|    iterations           | 19         |
|    time_elapsed         | 109        |
|    total_timesteps      | 38912      |
| train/                  |            |
|    approx_kl            | 0.15691055 |
|    clip_fraction        | 0.599      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.7      |
|    explained_variance   | 0.827      |
|    learning_rate        | 0.001      |
|    loss                 | -0.156     |
|    n_updates            | 180        |
|    policy_gradient_loss | -0.0507    |
|    std                  | 1.03       |
|    value_loss           | 6.21e-05   |
----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 356       |
|    iterations           | 20        |
|    time_elapsed         | 114       |
|    total_timesteps      | 40960     |
| train/                  |           |
|    approx_kl            | 0.1587446 |
|    clip_fraction        | 0.594     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.7     |
|    explained_variance   | 0.833     |
|    learning_rate        | 0.001     |
|    loss                 | -0.195    |
|    n_updates            | 190       |
|    policy_gradient_loss | -0.0472   |
|    std                  | 1.03      |
|    value_loss           | 4.45e-05  |
---------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A5_KD_only_ppo_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A5_KD_only_ppo_seed1_actions.csv
{'CR': -0.08428108888047137, 'AR': -0.08760665660222478, 'Vol': 0.05752702779869161, 'SR': -1.52287820098742, 'MDD': -0.11222742517459972, 'Calmar': -0.7806171839541827, 'Sortino': -2.004568669218577, 'Omega': 0.7588703376739125, 'Turnover': 0.7468462907553222, 'FinalAccountValue': 915718.9111195282, 'variant': 'A5_KD_only', 'agent': 'ppo', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A5_KD_only.CSV'}

========== A5_KD_only | SAC | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A5_KD_only.CSV
[banktrademergeGNNtr20241231_A5_KD_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 128, 'buffer_size': 1000000, 'learning_rate': 0.0001, 'learning_starts': 100, 'ent_coef': 'auto_0.1', 'seed': 1}
Using cpu device
Logging to tensorboard_log/sac\A5_KD_only_sac_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 13       |
|    time_elapsed    | 206      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | -9.76    |
|    critic_loss     | 0.0195   |
|    ent_coef        | 0.0753   |
|    ent_coef_loss   | -64.8    |
|    learning_rate   | 0.0001   |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 13       |
|    time_elapsed    | 421      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | -16.4    |
|    critic_loss     | 0.0238   |
|    ent_coef        | 0.0564   |
|    ent_coef_loss   | -72.3    |
|    learning_rate   | 0.0001   |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 13       |
|    time_elapsed    | 640      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | -20.2    |
|    critic_loss     | 0.0173   |
|    ent_coef        | 0.0422   |
|    ent_coef_loss   | -80.1    |
|    learning_rate   | 0.0001   |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 13       |
|    time_elapsed    | 866      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | -21.7    |
|    critic_loss     | 0.0211   |
|    ent_coef        | 0.0316   |
|    ent_coef_loss   | -87.2    |
|    learning_rate   | 0.0001   |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 13       |
|    time_elapsed    | 1103     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | -21.7    |
|    critic_loss     | 0.0104   |
|    ent_coef        | 0.0237   |
|    ent_coef_loss   | -94.3    |
|    learning_rate   | 0.0001   |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 12       |
|    time_elapsed    | 1339     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | -21      |
|    critic_loss     | 0.017    |
|    ent_coef        | 0.0178   |
|    ent_coef_loss   | -101     |
|    learning_rate   | 0.0001   |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 12       |
|    time_elapsed    | 1574     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | -19.8    |
|    critic_loss     | 0.00674  |
|    ent_coef        | 0.0133   |
|    ent_coef_loss   | -108     |
|    learning_rate   | 0.0001   |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1811     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | -18.3    |
|    critic_loss     | 0.0163   |
|    ent_coef        | 0.00998  |
|    ent_coef_loss   | -116     |
|    learning_rate   | 0.0001   |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2047     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | -15.5    |
|    critic_loss     | 0.00495  |
|    ent_coef        | 0.00748  |
|    ent_coef_loss   | -123     |
|    learning_rate   | 0.0001   |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 12       |
|    time_elapsed    | 2284     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | -15      |
|    critic_loss     | 0.00613  |
|    ent_coef        | 0.00561  |
|    ent_coef_loss   | -129     |
|    learning_rate   | 0.0001   |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 12       |
|    time_elapsed    | 2515     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -13      |
|    critic_loss     | 0.00765  |
|    ent_coef        | 0.00421  |
|    ent_coef_loss   | -134     |
|    learning_rate   | 0.0001   |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 12       |
|    time_elapsed    | 2748     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -11.2    |
|    critic_loss     | 0.0142   |
|    ent_coef        | 0.00316  |
|    ent_coef_loss   | -141     |
|    learning_rate   | 0.0001   |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 12       |
|    time_elapsed    | 2986     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -9.74    |
|    critic_loss     | 0.00323  |
|    ent_coef        | 0.00237  |
|    ent_coef_loss   | -146     |
|    learning_rate   | 0.0001   |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 12       |
|    time_elapsed    | 3223     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -8.76    |
|    critic_loss     | 0.0251   |
|    ent_coef        | 0.00178  |
|    ent_coef_loss   | -147     |
|    learning_rate   | 0.0001   |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 12       |
|    time_elapsed    | 3454     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -7.3     |
|    critic_loss     | 0.0191   |
|    ent_coef        | 0.00134  |
|    ent_coef_loss   | -148     |
|    learning_rate   | 0.0001   |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 12       |
|    time_elapsed    | 3695     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -6.49    |
|    critic_loss     | 0.00308  |
|    ent_coef        | 0.001    |
|    ent_coef_loss   | -158     |
|    learning_rate   | 0.0001   |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 12       |
|    time_elapsed    | 3926     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -5.43    |
|    critic_loss     | 0.00315  |
|    ent_coef        | 0.000755 |
|    ent_coef_loss   | -156     |
|    learning_rate   | 0.0001   |
|    n_updates       | 48927    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 72       |
|    fps             | 12       |
|    time_elapsed    | 4158     |
|    total_timesteps | 51912    |
| train/             |          |
|    actor_loss      | -4.57    |
|    critic_loss     | 0.00121  |
|    ent_coef        | 0.000568 |
|    ent_coef_loss   | -160     |
|    learning_rate   | 0.0001   |
|    n_updates       | 51811    |
---------------------------------

---------------------------------
| time/              |          |
|    episodes        | 76       |
|    fps             | 12       |
|    time_elapsed    | 4391     |
|    total_timesteps | 54796    |
| train/             |          |
|    actor_loss      | -3.7     |
|    critic_loss     | 0.00728  |
|    ent_coef        | 0.000428 |
|    ent_coef_loss   | -153     |
|    learning_rate   | 0.0001   |
|    n_updates       | 54695    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 80       |
|    fps             | 12       |
|    time_elapsed    | 4623     |
|    total_timesteps | 57680    |
| train/             |          |
|    actor_loss      | -3.17    |
|    critic_loss     | 0.00071  |
|    ent_coef        | 0.000323 |
|    ent_coef_loss   | -145     |
|    learning_rate   | 0.0001   |
|    n_updates       | 57579    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A5_KD_only_sac_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A5_KD_only_sac_seed1_actions.csv
{'CR': -0.09041530596378844, 'AR': -0.09397027309997208, 'Vol': 0.05452188059043797, 'SR': -1.7235332325725492, 'MDD': -0.11601828824962224, 'Calmar': -0.8099608649438771, 'Sortino': -2.3897241896105568, 'Omega': 0.7358848473427835, 'Turnover': 0.67717208661017, 'FinalAccountValue': 909584.6940362119, 'variant': 'A5_KD_only', 'agent': 'sac', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A5_KD_only.CSV'}

========== A5_KD_only | TD3 | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A5_KD_only.CSV
[banktrademergeGNNtr20241231_A5_KD_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 100, 'buffer_size': 1000000, 'learning_rate': 0.001, 'seed': 1}
Using cpu device
Logging to tensorboard_log/td3\A5_KD_only_td3_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 16       |
|    time_elapsed    | 177      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 1.15     |
|    critic_loss     | 0.00863  |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 15       |
|    time_elapsed    | 373      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 1.1      |
|    critic_loss     | 0.0017   |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 14       |
|    time_elapsed    | 582      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 1        |
|    critic_loss     | 0.00697  |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 14       |
|    time_elapsed    | 800      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.976    |
|    critic_loss     | 0.000259 |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 13       |
|    time_elapsed    | 1043     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.911    |
|    critic_loss     | 0.000499 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 13       |
|    time_elapsed    | 1296     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.762    |
|    critic_loss     | 0.000775 |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 12       |
|    time_elapsed    | 1573     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.778    |
|    critic_loss     | 0.000341 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1863     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.703    |
|    critic_loss     | 0.00135  |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2151     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.672    |
|    critic_loss     | 0.000347 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 11       |
|    time_elapsed    | 2441     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.598    |
|    critic_loss     | 0.000565 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A5_KD_only_td3_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A5_KD_only_td3_seed1_actions.csv
{'CR': -0.07677027120960034, 'AR': -0.0798125611814996, 'Vol': 0.05351521786239044, 'SR': -1.4913993508674561, 'MDD': -0.1133976135207998, 'Calmar': -0.7038292844395715, 'Sortino': -2.0535885026363823, 'Omega': 0.7670198325774246, 'Turnover': 0.21783520186252553, 'FinalAccountValue': 923229.7287903992, 'variant': 'A5_KD_only', 'agent': 'td3', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A5_KD_only.CSV'}

========== A5_KD_only | DDPG | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A5_KD_only.CSV
[banktrademergeGNNtr20241231_A5_KD_only.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'seed': 1}
Using cpu device
Logging to tensorboard_log/ddpg\A5_KD_only_ddpg_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 10       |
|    time_elapsed    | 266      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 0.661    |
|    critic_loss     | 0.00023  |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 10       |
|    time_elapsed    | 531      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.514    |
|    critic_loss     | 0.00018  |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 10       |
|    time_elapsed    | 805      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.378    |
|    critic_loss     | 0.000412 |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 10       |
|    time_elapsed    | 1092     |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.301    |
|    critic_loss     | 5.25e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 10       |
|    time_elapsed    | 1383     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.23     |
|    critic_loss     | 8.23e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 10       |
|    time_elapsed    | 1687     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.184    |
|    critic_loss     | 4.7e-05  |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 10       |
|    time_elapsed    | 2000     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.123    |
|    critic_loss     | 2.28e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 9        |
|    time_elapsed    | 2326     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.0857   |
|    critic_loss     | 2.64e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 9        |
|    time_elapsed    | 2666     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.0493   |
|    critic_loss     | 2.4e-05  |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 9        |
|    time_elapsed    | 3015     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.0147   |
|    critic_loss     | 2.02e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 9        |
|    time_elapsed    | 3361     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -0.0108  |
|    critic_loss     | 2.53e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 9        |
|    time_elapsed    | 3704     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -0.0406  |
|    critic_loss     | 2.3e-05  |
|    learning_rate   | 0.001    |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 9        |
|    time_elapsed    | 4060     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -0.0705  |
|    critic_loss     | 8.78e-06 |
|    learning_rate   | 0.001    |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 9        |
|    time_elapsed    | 4411     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -0.0877  |
|    critic_loss     | 1.92e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 9        |
|    time_elapsed    | 4775     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -0.12    |
|    critic_loss     | 1.54e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 8        |
|    time_elapsed    | 5137     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -0.129   |
|    critic_loss     | 1.79e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 8        |
|    time_elapsed    | 5503     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -0.14    |
|    critic_loss     | 1.48e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 48927    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A5_KD_only_ddpg_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A5_KD_only_ddpg_seed1_actions.csv
{'CR': -0.08311680830932555, 'AR': -0.08639863652065105, 'Vol': 0.06587224245073815, 'SR': -1.3116091589756238, 'MDD': -0.1333769124363805, 'Calmar': -0.6477780520062824, 'Sortino': -1.8728046261657514, 'Omega': 0.7908396424850546, 'Turnover': 0.8373350086698675, 'FinalAccountValue': 916883.1916906737, 'variant': 'A5_KD_only', 'agent': 'ddpg', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A5_KD_only.CSV'}
[banktrademergeGNNtr20241231_A6_SH_QA.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630

========== A6_SH_QA | A2C | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A6_SH_QA.CSV
[banktrademergeGNNtr20241231_A6_SH_QA.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 10, 'ent_coef': 0.005, 'learning_rate': 0.0004, 'seed': 1}
Using cpu device
Logging to tensorboard_log/a2c\A6_SH_QA_a2c_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

------------------------------------
| time/                 |          |
|    fps                | 415      |
|    iterations         | 100      |
|    time_elapsed       | 2        |
|    total_timesteps    | 1000     |
| train/                |          |
|    entropy_loss       | -21.3    |
|    explained_variance | -420     |
|    learning_rate      | 0.0004   |
|    n_updates          | 99       |
|    policy_loss        | -0.611   |
|    std                | 1        |
|    value_loss         | 0.0731   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 405       |
|    iterations         | 200       |
|    time_elapsed       | 4         |
|    total_timesteps    | 2000      |
| train/                |           |
|    entropy_loss       | -21.3     |
|    explained_variance | -6.03e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 199       |
|    policy_loss        | -0.77     |
|    std                | 1         |
|    value_loss         | 0.0909    |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 388       |
|    iterations         | 300       |
|    time_elapsed       | 7         |
|    total_timesteps    | 3000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -1.37e+04 |
|    learning_rate      | 0.0004    |
|    n_updates          | 299       |
|    policy_loss        | 2.19      |
|    std                | 1.01      |
|    value_loss         | 0.0486    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 392      |
|    iterations         | 400      |
|    time_elapsed       | 10       |
|    total_timesteps    | 4000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -421     |
|    learning_rate      | 0.0004   |
|    n_updates          | 399      |
|    policy_loss        | 7.63     |
|    std                | 1.01     |
|    value_loss         | 0.155    |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 500      |
|    time_elapsed       | 12       |
|    total_timesteps    | 5000     |
| train/                |          |
|    entropy_loss       | -21.5    |
|    explained_variance | -497     |
|    learning_rate      | 0.0004   |
|    n_updates          | 499      |
|    policy_loss        | -2.53    |
|    std                | 1.01     |
|    value_loss         | 0.0481   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 399       |
|    iterations         | 600       |
|    time_elapsed       | 15        |
|    total_timesteps    | 6000      |
| train/                |           |
|    entropy_loss       | -21.5     |
|    explained_variance | -2.62e+04 |
|    learning_rate      | 0.0004    |
|    n_updates          | 599       |
|    policy_loss        | -3.82     |
|    std                | 1.01      |
|    value_loss         | 0.0458    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 700      |
|    time_elapsed       | 17       |
|    total_timesteps    | 7000     |
| train/                |          |
|    entropy_loss       | -21.5    |
|    explained_variance | -1.5e+03 |
|    learning_rate      | 0.0004   |
|    n_updates          | 699      |
|    policy_loss        | -0.194   |
|    std                | 1.02     |
|    value_loss         | 0.00645  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 403      |
|    iterations         | 800      |
|    time_elapsed       | 19       |
|    total_timesteps    | 8000     |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -24.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 799      |
|    policy_loss        | 5.39     |
|    std                | 1.02     |
|    value_loss         | 0.0645   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 398      |
|    iterations         | 900      |
|    time_elapsed       | 22       |
|    total_timesteps    | 9000     |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -445     |
|    learning_rate      | 0.0004   |
|    n_updates          | 899      |
|    policy_loss        | 0.16     |
|    std                | 1.02     |
|    value_loss         | 0.013    |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 1000     |
|    time_elapsed       | 25       |
|    total_timesteps    | 10000    |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -174     |
|    learning_rate      | 0.0004   |
|    n_updates          | 999      |
|    policy_loss        | -0.108   |
|    std                | 1.03     |
|    value_loss         | 0.00851  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 1100     |
|    time_elapsed       | 27       |
|    total_timesteps    | 11000    |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -244     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1099     |
|    policy_loss        | 1.08     |
|    std                | 1.03     |
|    value_loss         | 0.00586  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 1200     |
|    time_elapsed       | 29       |
|    total_timesteps    | 12000    |
| train/                |          |
|    entropy_loss       | -21.8    |
|    explained_variance | -193     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1199     |
|    policy_loss        | 2.01     |
|    std                | 1.04     |
|    value_loss         | 0.0114   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 1300     |
|    time_elapsed       | 32       |
|    total_timesteps    | 13000    |
| train/                |          |
|    entropy_loss       | -21.9    |
|    explained_variance | -424     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1299     |
|    policy_loss        | -1.49    |
|    std                | 1.04     |
|    value_loss         | 0.0134   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 1400     |
|    time_elapsed       | 34       |
|    total_timesteps    | 14000    |
| train/                |          |
|    entropy_loss       | -22      |
|    explained_variance | -347     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1399     |
|    policy_loss        | -0.837   |
|    std                | 1.05     |
|    value_loss         | 0.0111   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 1500     |
|    time_elapsed       | 37       |
|    total_timesteps    | 15000    |
| train/                |          |
|    entropy_loss       | -22.1    |
|    explained_variance | -164     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1499     |
|    policy_loss        | -2.39    |
|    std                | 1.05     |
|    value_loss         | 0.0158   |
------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 1600     |
|    time_elapsed       | 40       |
|    total_timesteps    | 16000    |
| train/                |          |
|    entropy_loss       | -22.1    |
|    explained_variance | -326     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1599     |
|    policy_loss        | -2.5     |
|    std                | 1.06     |
|    value_loss         | 0.0176   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 1700     |
|    time_elapsed       | 42       |
|    total_timesteps    | 17000    |
| train/                |          |
|    entropy_loss       | -22.2    |
|    explained_variance | -101     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1699     |
|    policy_loss        | 1.78     |
|    std                | 1.07     |
|    value_loss         | 0.00867  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 1800     |
|    time_elapsed       | 44       |
|    total_timesteps    | 18000    |
| train/                |          |
|    entropy_loss       | -22.3    |
|    explained_variance | -81.1    |
|    learning_rate      | 0.0004   |
|    n_updates          | 1799     |
|    policy_loss        | 1.06     |
|    std                | 1.07     |
|    value_loss         | 0.00691  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 401       |
|    iterations         | 1900      |
|    time_elapsed       | 47        |
|    total_timesteps    | 19000     |
| train/                |           |
|    entropy_loss       | -22.4     |
|    explained_variance | -2.73e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 1899      |
|    policy_loss        | -2.92     |
|    std                | 1.08      |
|    value_loss         | 0.0208    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 2000     |
|    time_elapsed       | 49       |
|    total_timesteps    | 20000    |
| train/                |          |
|    entropy_loss       | -22.5    |
|    explained_variance | -767     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1999     |
|    policy_loss        | 1.82     |
|    std                | 1.08     |
|    value_loss         | 0.0147   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 2100     |
|    time_elapsed       | 52       |
|    total_timesteps    | 21000    |
| train/                |          |
|    entropy_loss       | -22.6    |
|    explained_variance | -407     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2099     |
|    policy_loss        | 0.854    |
|    std                | 1.09     |
|    value_loss         | 0.0041   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 2200     |
|    time_elapsed       | 55       |
|    total_timesteps    | 22000    |
| train/                |          |
|    entropy_loss       | -22.7    |
|    explained_variance | -251     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2199     |
|    policy_loss        | -0.232   |
|    std                | 1.1      |
|    value_loss         | 0.00453  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 2300     |
|    time_elapsed       | 57       |
|    total_timesteps    | 23000    |
| train/                |          |
|    entropy_loss       | -22.8    |
|    explained_variance | -24.5    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2299     |
|    policy_loss        | 0.625    |
|    std                | 1.11     |
|    value_loss         | 0.00233  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 2400     |
|    time_elapsed       | 60       |
|    total_timesteps    | 24000    |
| train/                |          |
|    entropy_loss       | -22.9    |
|    explained_variance | -345     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2399     |
|    policy_loss        | 0.529    |
|    std                | 1.11     |
|    value_loss         | 0.00566  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 2500     |
|    time_elapsed       | 62       |
|    total_timesteps    | 25000    |
| train/                |          |
|    entropy_loss       | -23      |
|    explained_variance | -231     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2499     |
|    policy_loss        | -2.39    |
|    std                | 1.12     |
|    value_loss         | 0.0147   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 2600     |
|    time_elapsed       | 64       |
|    total_timesteps    | 26000    |
| train/                |          |
|    entropy_loss       | -23.1    |
|    explained_variance | -176     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2599     |
|    policy_loss        | 1.35     |
|    std                | 1.13     |
|    value_loss         | 0.00538  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 2700     |
|    time_elapsed       | 67       |
|    total_timesteps    | 27000    |
| train/                |          |
|    entropy_loss       | -23.2    |
|    explained_variance | -114     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2699     |
|    policy_loss        | -0.071   |
|    std                | 1.14     |
|    value_loss         | 0.00519  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 2800     |
|    time_elapsed       | 70       |
|    total_timesteps    | 28000    |
| train/                |          |
|    entropy_loss       | -23.3    |
|    explained_variance | -83.1    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2799     |
|    policy_loss        | -2.07    |
|    std                | 1.14     |
|    value_loss         | 0.0116   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 2900     |
|    time_elapsed       | 72       |
|    total_timesteps    | 29000    |
| train/                |          |
|    entropy_loss       | -23.4    |
|    explained_variance | -143     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2899     |
|    policy_loss        | 0.59     |
|    std                | 1.15     |
|    value_loss         | 0.00142  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 3000     |
|    time_elapsed       | 75       |
|    total_timesteps    | 30000    |
| train/                |          |
|    entropy_loss       | -23.4    |
|    explained_variance | -403     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2999     |
|    policy_loss        | -0.444   |
|    std                | 1.16     |
|    value_loss         | 0.00158  |
------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 3100     |
|    time_elapsed       | 77       |
|    total_timesteps    | 31000    |
| train/                |          |
|    entropy_loss       | -23.6    |
|    explained_variance | -15.8    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3099     |
|    policy_loss        | 0.592    |
|    std                | 1.17     |
|    value_loss         | 0.00125  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 3200     |
|    time_elapsed       | 79       |
|    total_timesteps    | 32000    |
| train/                |          |
|    entropy_loss       | -23.7    |
|    explained_variance | -221     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3199     |
|    policy_loss        | 0.338    |
|    std                | 1.18     |
|    value_loss         | 0.00189  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 3300     |
|    time_elapsed       | 82       |
|    total_timesteps    | 33000    |
| train/                |          |
|    entropy_loss       | -23.8    |
|    explained_variance | -623     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3299     |
|    policy_loss        | -0.428   |
|    std                | 1.18     |
|    value_loss         | 0.00115  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 3400     |
|    time_elapsed       | 84       |
|    total_timesteps    | 34000    |
| train/                |          |
|    entropy_loss       | -23.9    |
|    explained_variance | -812     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3399     |
|    policy_loss        | -0.813   |
|    std                | 1.19     |
|    value_loss         | 0.00284  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 399       |
|    iterations         | 3500      |
|    time_elapsed       | 87        |
|    total_timesteps    | 35000     |
| train/                |           |
|    entropy_loss       | -24.1     |
|    explained_variance | -1.21e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 3499      |
|    policy_loss        | 0.125     |
|    std                | 1.21      |
|    value_loss         | 0.00143   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 398      |
|    iterations         | 3600     |
|    time_elapsed       | 90       |
|    total_timesteps    | 36000    |
| train/                |          |
|    entropy_loss       | -24.2    |
|    explained_variance | -29.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3599     |
|    policy_loss        | 0.886    |
|    std                | 1.22     |
|    value_loss         | 0.00353  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 398      |
|    iterations         | 3700     |
|    time_elapsed       | 92       |
|    total_timesteps    | 37000    |
| train/                |          |
|    entropy_loss       | -24.4    |
|    explained_variance | -210     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3699     |
|    policy_loss        | 1.43     |
|    std                | 1.23     |
|    value_loss         | 0.00539  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 398      |
|    iterations         | 3800     |
|    time_elapsed       | 95       |
|    total_timesteps    | 38000    |
| train/                |          |
|    entropy_loss       | -24.5    |
|    explained_variance | -139     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3799     |
|    policy_loss        | -0.631   |
|    std                | 1.24     |
|    value_loss         | 0.00201  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 398      |
|    iterations         | 3900     |
|    time_elapsed       | 97       |
|    total_timesteps    | 39000    |
| train/                |          |
|    entropy_loss       | -24.6    |
|    explained_variance | -36      |
|    learning_rate      | 0.0004   |
|    n_updates          | 3899     |
|    policy_loss        | 0.544    |
|    std                | 1.25     |
|    value_loss         | 0.00122  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 398      |
|    iterations         | 4000     |
|    time_elapsed       | 100      |
|    total_timesteps    | 40000    |
| train/                |          |
|    entropy_loss       | -24.8    |
|    explained_variance | -37.3    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3999     |
|    policy_loss        | 0.632    |
|    std                | 1.26     |
|    value_loss         | 0.00215  |
------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A6_SH_QA_a2c_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A6_SH_QA_a2c_seed1_actions.csv
{'CR': 0.0036956837835333545, 'AR': 0.0038486914955757623, 'Vol': 0.1478448870013826, 'SR': 0.026031955339380596, 'MDD': -0.08279440012078076, 'Calmar': 0.04648492518770928, 'Sortino': 0.035696205650736175, 'Omega': 1.019266917637461, 'Turnover': 0.6897532408921692, 'FinalAccountValue': 1003695.6837835328, 'variant': 'A6_SH_QA', 'agent': 'a2c', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A6_SH_QA.CSV'}

========== A6_SH_QA | PPO | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A6_SH_QA.CSV
[banktrademergeGNNtr20241231_A6_SH_QA.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 2048, 'ent_coef': 0.005, 'learning_rate': 0.001, 'batch_size': 128, 'seed': 1}
Using cpu device
Logging to tensorboard_log/ppo\A6_SH_QA_ppo_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

-----------------------------
| time/              |      |
|    fps             | 523  |
|    iterations      | 1    |
|    time_elapsed    | 3    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 433         |
|    iterations           | 2           |
|    time_elapsed         | 9           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.043996867 |
|    clip_fraction        | 0.4         |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.2       |
|    explained_variance   | -49.8       |
|    learning_rate        | 0.001       |
|    loss                 | -0.191      |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0714     |
|    std                  | 0.997       |
|    value_loss           | 0.0366      |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 419         |
|    iterations           | 3           |
|    time_elapsed         | 14          |
|    total_timesteps      | 6144        |
| train/                  |             |
|    approx_kl            | 0.049927317 |
|    clip_fraction        | 0.422       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.2       |
|    explained_variance   | -1.18       |
|    learning_rate        | 0.001       |
|    loss                 | -0.212      |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0695     |
|    std                  | 0.995       |
|    value_loss           | 0.00266     |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 414        |
|    iterations           | 4          |
|    time_elapsed         | 19         |
|    total_timesteps      | 8192       |
| train/                  |            |
|    approx_kl            | 0.06561628 |
|    clip_fraction        | 0.461      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.362      |
|    learning_rate        | 0.001      |
|    loss                 | -0.176     |
|    n_updates            | 30         |
|    policy_gradient_loss | -0.0646    |
|    std                  | 0.995      |
|    value_loss           | 0.00102    |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 402        |
|    iterations           | 5          |
|    time_elapsed         | 25         |
|    total_timesteps      | 10240      |
| train/                  |            |
|    approx_kl            | 0.07305339 |
|    clip_fraction        | 0.497      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.654      |
|    learning_rate        | 0.001      |
|    loss                 | -0.193     |
|    n_updates            | 40         |
|    policy_gradient_loss | -0.0649    |
|    std                  | 0.998      |
|    value_loss           | 0.00061    |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 399        |
|    iterations           | 6          |
|    time_elapsed         | 30         |
|    total_timesteps      | 12288      |
| train/                  |            |
|    approx_kl            | 0.07572113 |
|    clip_fraction        | 0.498      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.789      |
|    learning_rate        | 0.001      |
|    loss                 | -0.192     |
|    n_updates            | 50         |
|    policy_gradient_loss | -0.0594    |
|    std                  | 0.999      |
|    value_loss           | 0.000353   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 398         |
|    iterations           | 7           |
|    time_elapsed         | 36          |
|    total_timesteps      | 14336       |
| train/                  |             |
|    approx_kl            | 0.087132744 |
|    clip_fraction        | 0.512       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | 0.827       |
|    learning_rate        | 0.001       |
|    loss                 | -0.187      |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.0575     |
|    std                  | 1           |
|    value_loss           | 0.000221    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 395         |
|    iterations           | 8           |
|    time_elapsed         | 41          |
|    total_timesteps      | 16384       |
| train/                  |             |
|    approx_kl            | 0.090789266 |
|    clip_fraction        | 0.525       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | 0.849       |
|    learning_rate        | 0.001       |
|    loss                 | -0.187      |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.0562     |
|    std                  | 0.999       |
|    value_loss           | 0.000218    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 391        |
|    iterations           | 9          |
|    time_elapsed         | 47         |
|    total_timesteps      | 18432      |
| train/                  |            |
|    approx_kl            | 0.08604607 |
|    clip_fraction        | 0.518      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.8        |
|    learning_rate        | 0.001      |
|    loss                 | -0.187     |
|    n_updates            | 80         |
|    policy_gradient_loss | -0.0511    |
|    std                  | 1          |
|    value_loss           | 0.000166   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 386        |
|    iterations           | 10         |
|    time_elapsed         | 53         |
|    total_timesteps      | 20480      |
| train/                  |            |
|    approx_kl            | 0.09418891 |
|    clip_fraction        | 0.518      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.837      |
|    learning_rate        | 0.001      |
|    loss                 | -0.187     |
|    n_updates            | 90         |
|    policy_gradient_loss | -0.0575    |
|    std                  | 1.01       |
|    value_loss           | 0.000121   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 381        |
|    iterations           | 11         |
|    time_elapsed         | 59         |
|    total_timesteps      | 22528      |
| train/                  |            |
|    approx_kl            | 0.09338331 |
|    clip_fraction        | 0.528      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.836      |
|    learning_rate        | 0.001      |
|    loss                 | -0.177     |
|    n_updates            | 100        |
|    policy_gradient_loss | -0.0518    |
|    std                  | 1.01       |
|    value_loss           | 0.000115   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 378         |
|    iterations           | 12          |
|    time_elapsed         | 64          |
|    total_timesteps      | 24576       |
| train/                  |             |
|    approx_kl            | 0.112636246 |
|    clip_fraction        | 0.576       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.4       |
|    explained_variance   | 0.867       |
|    learning_rate        | 0.001       |
|    loss                 | -0.182      |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.0534     |
|    std                  | 1.01        |
|    value_loss           | 8.11e-05    |
-----------------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 375        |
|    iterations           | 13         |
|    time_elapsed         | 70         |
|    total_timesteps      | 26624      |
| train/                  |            |
|    approx_kl            | 0.11383887 |
|    clip_fraction        | 0.547      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.74       |
|    learning_rate        | 0.001      |
|    loss                 | -0.161     |
|    n_updates            | 120        |
|    policy_gradient_loss | -0.054     |
|    std                  | 1.01       |
|    value_loss           | 0.000137   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 373        |
|    iterations           | 14         |
|    time_elapsed         | 76         |
|    total_timesteps      | 28672      |
| train/                  |            |
|    approx_kl            | 0.10725809 |
|    clip_fraction        | 0.55       |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.792      |
|    learning_rate        | 0.001      |
|    loss                 | -0.203     |
|    n_updates            | 130        |
|    policy_gradient_loss | -0.0576    |
|    std                  | 1.01       |
|    value_loss           | 9.9e-05    |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 371        |
|    iterations           | 15         |
|    time_elapsed         | 82         |
|    total_timesteps      | 30720      |
| train/                  |            |
|    approx_kl            | 0.10908741 |
|    clip_fraction        | 0.537      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.551      |
|    learning_rate        | 0.001      |
|    loss                 | -0.186     |
|    n_updates            | 140        |
|    policy_gradient_loss | -0.0528    |
|    std                  | 1.01       |
|    value_loss           | 8.83e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 369        |
|    iterations           | 16         |
|    time_elapsed         | 88         |
|    total_timesteps      | 32768      |
| train/                  |            |
|    approx_kl            | 0.10648345 |
|    clip_fraction        | 0.544      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.716      |
|    learning_rate        | 0.001      |
|    loss                 | -0.18      |
|    n_updates            | 150        |
|    policy_gradient_loss | -0.0478    |
|    std                  | 1.01       |
|    value_loss           | 8.41e-05   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 369         |
|    iterations           | 17          |
|    time_elapsed         | 94          |
|    total_timesteps      | 34816       |
| train/                  |             |
|    approx_kl            | 0.120718285 |
|    clip_fraction        | 0.557       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.5       |
|    explained_variance   | 0.707       |
|    learning_rate        | 0.001       |
|    loss                 | -0.193      |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.0531     |
|    std                  | 1.02        |
|    value_loss           | 7.91e-05    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 367        |
|    iterations           | 18         |
|    time_elapsed         | 100        |
|    total_timesteps      | 36864      |
| train/                  |            |
|    approx_kl            | 0.11708328 |
|    clip_fraction        | 0.559      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.6      |
|    explained_variance   | 0.799      |
|    learning_rate        | 0.001      |
|    loss                 | -0.176     |
|    n_updates            | 170        |
|    policy_gradient_loss | -0.0537    |
|    std                  | 1.02       |
|    value_loss           | 0.000255   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 366        |
|    iterations           | 19         |
|    time_elapsed         | 106        |
|    total_timesteps      | 38912      |
| train/                  |            |
|    approx_kl            | 0.13055801 |
|    clip_fraction        | 0.567      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.6      |
|    explained_variance   | -0.616     |
|    learning_rate        | 0.001      |
|    loss                 | -0.194     |
|    n_updates            | 180        |
|    policy_gradient_loss | -0.0515    |
|    std                  | 1.02       |
|    value_loss           | 0.000527   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 368        |
|    iterations           | 20         |
|    time_elapsed         | 111        |
|    total_timesteps      | 40960      |
| train/                  |            |
|    approx_kl            | 0.14072175 |
|    clip_fraction        | 0.578      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.6      |
|    explained_variance   | 0.104      |
|    learning_rate        | 0.001      |
|    loss                 | -0.181     |
|    n_updates            | 190        |
|    policy_gradient_loss | -0.0531    |
|    std                  | 1.02       |
|    value_loss           | 0.000135   |
----------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A6_SH_QA_ppo_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A6_SH_QA_ppo_seed1_actions.csv
{'CR': 0.001605971040141263, 'AR': 0.0016723889414260729, 'Vol': 0.14595531274600893, 'SR': 0.011458225877233807, 'MDD': -0.09049997007423127, 'Calmar': 0.01847944192748705, 'Sortino': 0.015389784372508696, 'Omega': 1.0162976807256767, 'Turnover': 0.7426903423891679, 'FinalAccountValue': 1001605.971040143, 'variant': 'A6_SH_QA', 'agent': 'ppo', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A6_SH_QA.CSV'}

========== A6_SH_QA | SAC | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A6_SH_QA.CSV
[banktrademergeGNNtr20241231_A6_SH_QA.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 128, 'buffer_size': 1000000, 'learning_rate': 0.0001, 'learning_starts': 100, 'ent_coef': 'auto_0.1', 'seed': 1}
Using cpu device
Logging to tensorboard_log/sac\A6_SH_QA_sac_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 14       |
|    time_elapsed    | 200      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | -9.74    |
|    critic_loss     | 0.036    |
|    ent_coef        | 0.0753   |
|    ent_coef_loss   | -64.9    |
|    learning_rate   | 0.0001   |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 13       |
|    time_elapsed    | 419      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | -16.5    |
|    critic_loss     | 0.0178   |
|    ent_coef        | 0.0564   |
|    ent_coef_loss   | -72.4    |
|    learning_rate   | 0.0001   |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 13       |
|    time_elapsed    | 635      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | -20.2    |
|    critic_loss     | 0.0201   |
|    ent_coef        | 0.0422   |
|    ent_coef_loss   | -79.9    |
|    learning_rate   | 0.0001   |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 13       |
|    time_elapsed    | 863      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | -21.8    |
|    critic_loss     | 0.0305   |
|    ent_coef        | 0.0316   |
|    ent_coef_loss   | -87.3    |
|    learning_rate   | 0.0001   |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 13       |
|    time_elapsed    | 1101     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | -21.7    |
|    critic_loss     | 0.00986  |
|    ent_coef        | 0.0237   |
|    ent_coef_loss   | -94.2    |
|    learning_rate   | 0.0001   |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 12       |
|    time_elapsed    | 1346     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | -21      |
|    critic_loss     | 0.0169   |
|    ent_coef        | 0.0178   |
|    ent_coef_loss   | -101     |
|    learning_rate   | 0.0001   |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 12       |
|    time_elapsed    | 1586     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | -19.7    |
|    critic_loss     | 0.0115   |
|    ent_coef        | 0.0133   |
|    ent_coef_loss   | -108     |
|    learning_rate   | 0.0001   |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1822     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | -18.4    |
|    critic_loss     | 0.0125   |
|    ent_coef        | 0.00998  |
|    ent_coef_loss   | -116     |
|    learning_rate   | 0.0001   |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2064     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | -15.5    |
|    critic_loss     | 0.00783  |
|    ent_coef        | 0.00748  |
|    ent_coef_loss   | -122     |
|    learning_rate   | 0.0001   |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 12       |
|    time_elapsed    | 2300     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | -15      |
|    critic_loss     | 0.0182   |
|    ent_coef        | 0.00561  |
|    ent_coef_loss   | -127     |
|    learning_rate   | 0.0001   |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 12       |
|    time_elapsed    | 2539     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -13      |
|    critic_loss     | 0.00981  |
|    ent_coef        | 0.00421  |
|    ent_coef_loss   | -135     |
|    learning_rate   | 0.0001   |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 12       |
|    time_elapsed    | 2775     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -11.2    |
|    critic_loss     | 0.00257  |
|    ent_coef        | 0.00316  |
|    ent_coef_loss   | -141     |
|    learning_rate   | 0.0001   |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 12       |
|    time_elapsed    | 3008     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -9.74    |
|    critic_loss     | 0.00221  |
|    ent_coef        | 0.00237  |
|    ent_coef_loss   | -147     |
|    learning_rate   | 0.0001   |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 12       |
|    time_elapsed    | 3242     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -8.85    |
|    critic_loss     | 0.00717  |
|    ent_coef        | 0.00178  |
|    ent_coef_loss   | -147     |
|    learning_rate   | 0.0001   |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 12       |
|    time_elapsed    | 3482     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -7.23    |
|    critic_loss     | 0.00284  |
|    ent_coef        | 0.00134  |
|    ent_coef_loss   | -153     |
|    learning_rate   | 0.0001   |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 12       |
|    time_elapsed    | 3721     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -6.4     |
|    critic_loss     | 0.0193   |
|    ent_coef        | 0.001    |
|    ent_coef_loss   | -151     |
|    learning_rate   | 0.0001   |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 12       |
|    time_elapsed    | 3958     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -5.39    |
|    critic_loss     | 0.0191   |
|    ent_coef        | 0.000755 |
|    ent_coef_loss   | -148     |
|    learning_rate   | 0.0001   |
|    n_updates       | 48927    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 72       |
|    fps             | 12       |
|    time_elapsed    | 4193     |
|    total_timesteps | 51912    |
| train/             |          |
|    actor_loss      | -4.57    |
|    critic_loss     | 0.00238  |
|    ent_coef        | 0.000568 |
|    ent_coef_loss   | -159     |
|    learning_rate   | 0.0001   |
|    n_updates       | 51811    |
---------------------------------

---------------------------------
| time/              |          |
|    episodes        | 76       |
|    fps             | 12       |
|    time_elapsed    | 4423     |
|    total_timesteps | 54796    |
| train/             |          |
|    actor_loss      | -3.67    |
|    critic_loss     | 0.00403  |
|    ent_coef        | 0.000428 |
|    ent_coef_loss   | -158     |
|    learning_rate   | 0.0001   |
|    n_updates       | 54695    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 80       |
|    fps             | 12       |
|    time_elapsed    | 4660     |
|    total_timesteps | 57680    |
| train/             |          |
|    actor_loss      | -3.16    |
|    critic_loss     | 0.000896 |
|    ent_coef        | 0.000323 |
|    ent_coef_loss   | -149     |
|    learning_rate   | 0.0001   |
|    n_updates       | 57579    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A6_SH_QA_sac_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A6_SH_QA_sac_seed1_actions.csv
{'CR': 0.0032798312089976633, 'AR': 0.0034155926243939483, 'Vol': 0.13517155511645207, 'SR': 0.025268575340805767, 'MDD': -0.08865095023925595, 'Calmar': 0.03852855062665164, 'Sortino': 0.03363192533199371, 'Omega': 1.0179229660029545, 'Turnover': 0.6502911008337964, 'FinalAccountValue': 1003279.8312089986, 'variant': 'A6_SH_QA', 'agent': 'sac', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A6_SH_QA.CSV'}

========== A6_SH_QA | TD3 | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A6_SH_QA.CSV
[banktrademergeGNNtr20241231_A6_SH_QA.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 100, 'buffer_size': 1000000, 'learning_rate': 0.001, 'seed': 1}
Using cpu device
Logging to tensorboard_log/td3\A6_SH_QA_td3_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 16       |
|    time_elapsed    | 173      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 1.04     |
|    critic_loss     | 0.0067   |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 15       |
|    time_elapsed    | 367      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.993    |
|    critic_loss     | 0.00391  |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 15       |
|    time_elapsed    | 566      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.902    |
|    critic_loss     | 0.000682 |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 14       |
|    time_elapsed    | 781      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.89     |
|    critic_loss     | 0.00207  |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 14       |
|    time_elapsed    | 1014     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.823    |
|    critic_loss     | 0.000349 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 13       |
|    time_elapsed    | 1270     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.698    |
|    critic_loss     | 0.001    |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 13       |
|    time_elapsed    | 1507     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.705    |
|    critic_loss     | 0.000516 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1786     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.628    |
|    critic_loss     | 0.000529 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2078     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.605    |
|    critic_loss     | 0.000267 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 12       |
|    time_elapsed    | 2371     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.527    |
|    critic_loss     | 0.000423 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A6_SH_QA_td3_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A6_SH_QA_td3_seed1_actions.csv
{'CR': -0.03515206042719876, 'AR': -0.036577735731862626, 'Vol': 0.15258582032198925, 'SR': -0.23971910138619468, 'MDD': -0.1088188899869954, 'Calmar': -0.3361340640051917, 'Sortino': -0.3325652911177258, 'Omega': 0.9694418159893229, 'Turnover': 0.3229542901286103, 'FinalAccountValue': 964847.9395728011, 'variant': 'A6_SH_QA', 'agent': 'td3', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A6_SH_QA.CSV'}

========== A6_SH_QA | DDPG | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A6_SH_QA.CSV
[banktrademergeGNNtr20241231_A6_SH_QA.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'seed': 1}
Using cpu device
Logging to tensorboard_log/ddpg\A6_SH_QA_ddpg_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 11       |
|    time_elapsed    | 260      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 0.657    |
|    critic_loss     | 0.000805 |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 10       |
|    time_elapsed    | 533      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.501    |
|    critic_loss     | 0.000143 |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 10       |
|    time_elapsed    | 806      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.381    |
|    critic_loss     | 0.000315 |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 10       |
|    time_elapsed    | 1079     |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.299    |
|    critic_loss     | 0.000172 |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 10       |
|    time_elapsed    | 1371     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.235    |
|    critic_loss     | 2.79e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 10       |
|    time_elapsed    | 1663     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.177    |
|    critic_loss     | 1.28e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 10       |
|    time_elapsed    | 1978     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.125    |
|    critic_loss     | 6.19e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 9        |
|    time_elapsed    | 2307     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.0804   |
|    critic_loss     | 6.55e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 9        |
|    time_elapsed    | 2634     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.0404   |
|    critic_loss     | 6.38e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 9        |
|    time_elapsed    | 2972     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.00664  |
|    critic_loss     | 2.77e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 9        |
|    time_elapsed    | 3316     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -0.0191  |
|    critic_loss     | 4.88e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 9        |
|    time_elapsed    | 3656     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -0.0546  |
|    critic_loss     | 2.24e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 9        |
|    time_elapsed    | 4015     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -0.0792  |
|    critic_loss     | 1.25e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 9        |
|    time_elapsed    | 4320     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -0.1     |
|    critic_loss     | 3.55e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 9        |
|    time_elapsed    | 4680     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -0.131   |
|    critic_loss     | 1.64e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 9        |
|    time_elapsed    | 5045     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -0.14    |
|    critic_loss     | 1.29e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 9        |
|    time_elapsed    | 5400     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -0.147   |
|    critic_loss     | 1.28e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 48927    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A6_SH_QA_ddpg_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A6_SH_QA_ddpg_seed1_actions.csv
{'CR': -0.0519303286878402, 'AR': -0.05401720136975863, 'Vol': 0.14926708708058625, 'SR': -0.3618828666536237, 'MDD': -0.12809817369055365, 'Calmar': -0.4216859601780725, 'Sortino': -0.5091651306702146, 'Omega': 0.9456990397489745, 'Turnover': 0.8695272544372152, 'FinalAccountValue': 948069.6713121594, 'variant': 'A6_SH_QA', 'agent': 'ddpg', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A6_SH_QA.CSV'}
[banktrademergeGNNtr20241231_A7_SH_KD.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630

========== A7_SH_KD | A2C | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A7_SH_KD.CSV
[banktrademergeGNNtr20241231_A7_SH_KD.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 10, 'ent_coef': 0.005, 'learning_rate': 0.0004, 'seed': 1}
Using cpu device
Logging to tensorboard_log/a2c\A7_SH_KD_a2c_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

-------------------------------------
| time/                 |           |
|    fps                | 354       |
|    iterations         | 100       |
|    time_elapsed       | 2         |
|    total_timesteps    | 1000      |
| train/                |           |
|    entropy_loss       | -21.3     |
|    explained_variance | -1.13e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 99        |
|    policy_loss        | -1.55     |
|    std                | 1         |
|    value_loss         | 0.0821    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 358      |
|    iterations         | 200      |
|    time_elapsed       | 5        |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -348     |
|    learning_rate      | 0.0004   |
|    n_updates          | 199      |
|    policy_loss        | -1.62    |
|    std                | 1.01     |
|    value_loss         | 0.048    |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 363      |
|    iterations         | 300      |
|    time_elapsed       | 8        |
|    total_timesteps    | 3000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -774     |
|    learning_rate      | 0.0004   |
|    n_updates          | 299      |
|    policy_loss        | 3.06     |
|    std                | 1.01     |
|    value_loss         | 0.0533   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 358       |
|    iterations         | 400       |
|    time_elapsed       | 11        |
|    total_timesteps    | 4000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -3.78e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 399       |
|    policy_loss        | 3.86      |
|    std                | 1.01      |
|    value_loss         | 0.0604    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 358      |
|    iterations         | 500      |
|    time_elapsed       | 13       |
|    total_timesteps    | 5000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -319     |
|    learning_rate      | 0.0004   |
|    n_updates          | 499      |
|    policy_loss        | 0.842    |
|    std                | 1.01     |
|    value_loss         | 0.0273   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 362      |
|    iterations         | 600      |
|    time_elapsed       | 16       |
|    total_timesteps    | 6000     |
| train/                |          |
|    entropy_loss       | -21.5    |
|    explained_variance | -451     |
|    learning_rate      | 0.0004   |
|    n_updates          | 599      |
|    policy_loss        | -3.15    |
|    std                | 1.01     |
|    value_loss         | 0.039    |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 365      |
|    iterations         | 700      |
|    time_elapsed       | 19       |
|    total_timesteps    | 7000     |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -656     |
|    learning_rate      | 0.0004   |
|    n_updates          | 699      |
|    policy_loss        | -2.86    |
|    std                | 1.02     |
|    value_loss         | 0.028    |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 368       |
|    iterations         | 800       |
|    time_elapsed       | 21        |
|    total_timesteps    | 8000      |
| train/                |           |
|    entropy_loss       | -21.6     |
|    explained_variance | -8.27e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 799       |
|    policy_loss        | 0.74      |
|    std                | 1.02      |
|    value_loss         | 0.0076    |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 372       |
|    iterations         | 900       |
|    time_elapsed       | 24        |
|    total_timesteps    | 9000      |
| train/                |           |
|    entropy_loss       | -21.7     |
|    explained_variance | -1.11e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 899       |
|    policy_loss        | -0.629    |
|    std                | 1.03      |
|    value_loss         | 0.015     |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 371      |
|    iterations         | 1000     |
|    time_elapsed       | 26       |
|    total_timesteps    | 10000    |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -90.5    |
|    learning_rate      | 0.0004   |
|    n_updates          | 999      |
|    policy_loss        | -0.0586  |
|    std                | 1.03     |
|    value_loss         | 0.00584  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 374       |
|    iterations         | 1100      |
|    time_elapsed       | 29        |
|    total_timesteps    | 11000     |
| train/                |           |
|    entropy_loss       | -21.8     |
|    explained_variance | -1.13e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 1099      |
|    policy_loss        | 2.08      |
|    std                | 1.03      |
|    value_loss         | 0.0135    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 376      |
|    iterations         | 1200     |
|    time_elapsed       | 31       |
|    total_timesteps    | 12000    |
| train/                |          |
|    entropy_loss       | -21.8    |
|    explained_variance | -503     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1199     |
|    policy_loss        | 0.421    |
|    std                | 1.04     |
|    value_loss         | 0.00604  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 380      |
|    iterations         | 1300     |
|    time_elapsed       | 34       |
|    total_timesteps    | 13000    |
| train/                |          |
|    entropy_loss       | -21.9    |
|    explained_variance | -648     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1299     |
|    policy_loss        | 2.09     |
|    std                | 1.04     |
|    value_loss         | 0.021    |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 381      |
|    iterations         | 1400     |
|    time_elapsed       | 36       |
|    total_timesteps    | 14000    |
| train/                |          |
|    entropy_loss       | -22      |
|    explained_variance | -232     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1399     |
|    policy_loss        | 2.98     |
|    std                | 1.05     |
|    value_loss         | 0.0232   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 383      |
|    iterations         | 1500     |
|    time_elapsed       | 39       |
|    total_timesteps    | 15000    |
| train/                |          |
|    entropy_loss       | -22.1    |
|    explained_variance | -241     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1499     |
|    policy_loss        | 0.129    |
|    std                | 1.06     |
|    value_loss         | 0.00273  |
------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 384      |
|    iterations         | 1600     |
|    time_elapsed       | 41       |
|    total_timesteps    | 16000    |
| train/                |          |
|    entropy_loss       | -22.2    |
|    explained_variance | -882     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1599     |
|    policy_loss        | 2.14     |
|    std                | 1.06     |
|    value_loss         | 0.0123   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 385      |
|    iterations         | 1700     |
|    time_elapsed       | 44       |
|    total_timesteps    | 17000    |
| train/                |          |
|    entropy_loss       | -22.3    |
|    explained_variance | -607     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1699     |
|    policy_loss        | -0.0133  |
|    std                | 1.07     |
|    value_loss         | 0.00418  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 386      |
|    iterations         | 1800     |
|    time_elapsed       | 46       |
|    total_timesteps    | 18000    |
| train/                |          |
|    entropy_loss       | -22.3    |
|    explained_variance | -110     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1799     |
|    policy_loss        | -1.09    |
|    std                | 1.07     |
|    value_loss         | 0.00713  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 387       |
|    iterations         | 1900      |
|    time_elapsed       | 49        |
|    total_timesteps    | 19000     |
| train/                |           |
|    entropy_loss       | -22.4     |
|    explained_variance | -1.05e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 1899      |
|    policy_loss        | -0.243    |
|    std                | 1.08      |
|    value_loss         | 0.00633   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 387      |
|    iterations         | 2000     |
|    time_elapsed       | 51       |
|    total_timesteps    | 20000    |
| train/                |          |
|    entropy_loss       | -22.5    |
|    explained_variance | -494     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1999     |
|    policy_loss        | -0.471   |
|    std                | 1.08     |
|    value_loss         | 0.00513  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 389      |
|    iterations         | 2100     |
|    time_elapsed       | 53       |
|    total_timesteps    | 21000    |
| train/                |          |
|    entropy_loss       | -22.6    |
|    explained_variance | -513     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2099     |
|    policy_loss        | -1.6     |
|    std                | 1.09     |
|    value_loss         | 0.0102   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 390      |
|    iterations         | 2200     |
|    time_elapsed       | 56       |
|    total_timesteps    | 22000    |
| train/                |          |
|    entropy_loss       | -22.7    |
|    explained_variance | -105     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2199     |
|    policy_loss        | 1.18     |
|    std                | 1.1      |
|    value_loss         | 0.00559  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 388      |
|    iterations         | 2300     |
|    time_elapsed       | 59       |
|    total_timesteps    | 23000    |
| train/                |          |
|    entropy_loss       | -22.8    |
|    explained_variance | -11.8    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2299     |
|    policy_loss        | -0.0911  |
|    std                | 1.11     |
|    value_loss         | 0.00095  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 389      |
|    iterations         | 2400     |
|    time_elapsed       | 61       |
|    total_timesteps    | 24000    |
| train/                |          |
|    entropy_loss       | -22.9    |
|    explained_variance | -365     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2399     |
|    policy_loss        | -0.524   |
|    std                | 1.12     |
|    value_loss         | 0.00273  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 389      |
|    iterations         | 2500     |
|    time_elapsed       | 64       |
|    total_timesteps    | 25000    |
| train/                |          |
|    entropy_loss       | -23      |
|    explained_variance | -232     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2499     |
|    policy_loss        | 0.72     |
|    std                | 1.12     |
|    value_loss         | 0.00443  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 390      |
|    iterations         | 2600     |
|    time_elapsed       | 66       |
|    total_timesteps    | 26000    |
| train/                |          |
|    entropy_loss       | -23.1    |
|    explained_variance | -20.3    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2599     |
|    policy_loss        | 1.09     |
|    std                | 1.13     |
|    value_loss         | 0.0028   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 391      |
|    iterations         | 2700     |
|    time_elapsed       | 68       |
|    total_timesteps    | 27000    |
| train/                |          |
|    entropy_loss       | -23.2    |
|    explained_variance | -418     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2699     |
|    policy_loss        | -0.42    |
|    std                | 1.14     |
|    value_loss         | 0.00575  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 392      |
|    iterations         | 2800     |
|    time_elapsed       | 71       |
|    total_timesteps    | 28000    |
| train/                |          |
|    entropy_loss       | -23.3    |
|    explained_variance | -164     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2799     |
|    policy_loss        | 0.49     |
|    std                | 1.15     |
|    value_loss         | 0.00175  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 392      |
|    iterations         | 2900     |
|    time_elapsed       | 73       |
|    total_timesteps    | 29000    |
| train/                |          |
|    entropy_loss       | -23.4    |
|    explained_variance | -432     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2899     |
|    policy_loss        | -0.645   |
|    std                | 1.16     |
|    value_loss         | 0.00325  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 392       |
|    iterations         | 3000      |
|    time_elapsed       | 76        |
|    total_timesteps    | 30000     |
| train/                |           |
|    entropy_loss       | -23.6     |
|    explained_variance | -5.45e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 2999      |
|    policy_loss        | -0.892    |
|    std                | 1.17      |
|    value_loss         | 0.00289   |
-------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 392      |
|    iterations         | 3100     |
|    time_elapsed       | 78       |
|    total_timesteps    | 31000    |
| train/                |          |
|    entropy_loss       | -23.7    |
|    explained_variance | -172     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3099     |
|    policy_loss        | 0.0177   |
|    std                | 1.17     |
|    value_loss         | 0.0047   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 393      |
|    iterations         | 3200     |
|    time_elapsed       | 81       |
|    total_timesteps    | 32000    |
| train/                |          |
|    entropy_loss       | -23.8    |
|    explained_variance | -121     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3199     |
|    policy_loss        | -0.997   |
|    std                | 1.19     |
|    value_loss         | 0.00348  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 393      |
|    iterations         | 3300     |
|    time_elapsed       | 83       |
|    total_timesteps    | 33000    |
| train/                |          |
|    entropy_loss       | -23.9    |
|    explained_variance | -269     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3299     |
|    policy_loss        | -0.352   |
|    std                | 1.19     |
|    value_loss         | 0.00201  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 394      |
|    iterations         | 3400     |
|    time_elapsed       | 86       |
|    total_timesteps    | 34000    |
| train/                |          |
|    entropy_loss       | -24.1    |
|    explained_variance | -537     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3399     |
|    policy_loss        | -0.0643  |
|    std                | 1.21     |
|    value_loss         | 0.00149  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 394      |
|    iterations         | 3500     |
|    time_elapsed       | 88       |
|    total_timesteps    | 35000    |
| train/                |          |
|    entropy_loss       | -24.2    |
|    explained_variance | -320     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3499     |
|    policy_loss        | 0.105    |
|    std                | 1.22     |
|    value_loss         | 0.000742 |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 393      |
|    iterations         | 3600     |
|    time_elapsed       | 91       |
|    total_timesteps    | 36000    |
| train/                |          |
|    entropy_loss       | -24.4    |
|    explained_variance | -48.6    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3599     |
|    policy_loss        | -1.37    |
|    std                | 1.23     |
|    value_loss         | 0.00651  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 393      |
|    iterations         | 3700     |
|    time_elapsed       | 93       |
|    total_timesteps    | 37000    |
| train/                |          |
|    entropy_loss       | -24.5    |
|    explained_variance | -188     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3699     |
|    policy_loss        | -0.11    |
|    std                | 1.24     |
|    value_loss         | 0.000868 |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 394      |
|    iterations         | 3800     |
|    time_elapsed       | 96       |
|    total_timesteps    | 38000    |
| train/                |          |
|    entropy_loss       | -24.6    |
|    explained_variance | -128     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3799     |
|    policy_loss        | 1.28     |
|    std                | 1.25     |
|    value_loss         | 0.00514  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 395      |
|    iterations         | 3900     |
|    time_elapsed       | 98       |
|    total_timesteps    | 39000    |
| train/                |          |
|    entropy_loss       | -24.8    |
|    explained_variance | -38.9    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3899     |
|    policy_loss        | 0.149    |
|    std                | 1.26     |
|    value_loss         | 0.000723 |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 395      |
|    iterations         | 4000     |
|    time_elapsed       | 101      |
|    total_timesteps    | 40000    |
| train/                |          |
|    entropy_loss       | -24.9    |
|    explained_variance | -118     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3999     |
|    policy_loss        | -1.7     |
|    std                | 1.28     |
|    value_loss         | 0.0084   |
------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A7_SH_KD_a2c_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A7_SH_KD_a2c_seed1_actions.csv
{'CR': -0.05067514283909569, 'AR': -0.0527129897376416, 'Vol': 0.049175761429538556, 'SR': -1.0719303210621631, 'MDD': -0.09401722050255801, 'Calmar': -0.5606737729095852, 'Sortino': -1.7160312719756101, 'Omega': 0.8289611775777403, 'Turnover': 0.7438541158887141, 'FinalAccountValue': 949324.8571609048, 'variant': 'A7_SH_KD', 'agent': 'a2c', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A7_SH_KD.CSV'}

========== A7_SH_KD | PPO | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A7_SH_KD.CSV
[banktrademergeGNNtr20241231_A7_SH_KD.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 2048, 'ent_coef': 0.005, 'learning_rate': 0.001, 'batch_size': 128, 'seed': 1}
Using cpu device
Logging to tensorboard_log/ppo\A7_SH_KD_ppo_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

-----------------------------
| time/              |      |
|    fps             | 598  |
|    iterations      | 1    |
|    time_elapsed    | 3    |
|    total_timesteps | 2048 |
-----------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 465        |
|    iterations           | 2          |
|    time_elapsed         | 8          |
|    total_timesteps      | 4096       |
| train/                  |            |
|    approx_kl            | 0.04534325 |
|    clip_fraction        | 0.395      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | -50.3      |
|    learning_rate        | 0.001      |
|    loss                 | -0.193     |
|    n_updates            | 10         |
|    policy_gradient_loss | -0.0709    |
|    std                  | 0.997      |
|    value_loss           | 0.0364     |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 439         |
|    iterations           | 3           |
|    time_elapsed         | 13          |
|    total_timesteps      | 6144        |
| train/                  |             |
|    approx_kl            | 0.055790838 |
|    clip_fraction        | 0.435       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | -1.09       |
|    learning_rate        | 0.001       |
|    loss                 | -0.2        |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0718     |
|    std                  | 0.997       |
|    value_loss           | 0.00268     |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 424        |
|    iterations           | 4          |
|    time_elapsed         | 19         |
|    total_timesteps      | 8192       |
| train/                  |            |
|    approx_kl            | 0.06335221 |
|    clip_fraction        | 0.47       |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.402      |
|    learning_rate        | 0.001      |
|    loss                 | -0.189     |
|    n_updates            | 30         |
|    policy_gradient_loss | -0.0663    |
|    std                  | 0.992      |
|    value_loss           | 0.000995   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 400        |
|    iterations           | 5          |
|    time_elapsed         | 25         |
|    total_timesteps      | 10240      |
| train/                  |            |
|    approx_kl            | 0.06916329 |
|    clip_fraction        | 0.486      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.631      |
|    learning_rate        | 0.001      |
|    loss                 | -0.181     |
|    n_updates            | 40         |
|    policy_gradient_loss | -0.0631    |
|    std                  | 0.991      |
|    value_loss           | 0.000569   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 392        |
|    iterations           | 6          |
|    time_elapsed         | 31         |
|    total_timesteps      | 12288      |
| train/                  |            |
|    approx_kl            | 0.07543209 |
|    clip_fraction        | 0.491      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.78       |
|    learning_rate        | 0.001      |
|    loss                 | -0.203     |
|    n_updates            | 50         |
|    policy_gradient_loss | -0.0586    |
|    std                  | 0.992      |
|    value_loss           | 0.000325   |
----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 384       |
|    iterations           | 7         |
|    time_elapsed         | 37        |
|    total_timesteps      | 14336     |
| train/                  |           |
|    approx_kl            | 0.0951343 |
|    clip_fraction        | 0.532     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.2     |
|    explained_variance   | 0.851     |
|    learning_rate        | 0.001     |
|    loss                 | -0.193    |
|    n_updates            | 60        |
|    policy_gradient_loss | -0.0579   |
|    std                  | 0.996     |
|    value_loss           | 0.000239  |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 379        |
|    iterations           | 8          |
|    time_elapsed         | 43         |
|    total_timesteps      | 16384      |
| train/                  |            |
|    approx_kl            | 0.07738673 |
|    clip_fraction        | 0.51       |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.809      |
|    learning_rate        | 0.001      |
|    loss                 | -0.179     |
|    n_updates            | 70         |
|    policy_gradient_loss | -0.0542    |
|    std                  | 1          |
|    value_loss           | 0.000215   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 377        |
|    iterations           | 9          |
|    time_elapsed         | 48         |
|    total_timesteps      | 18432      |
| train/                  |            |
|    approx_kl            | 0.09530979 |
|    clip_fraction        | 0.537      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.84       |
|    learning_rate        | 0.001      |
|    loss                 | -0.199     |
|    n_updates            | 80         |
|    policy_gradient_loss | -0.051     |
|    std                  | 1.01       |
|    value_loss           | 0.000172   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 374        |
|    iterations           | 10         |
|    time_elapsed         | 54         |
|    total_timesteps      | 20480      |
| train/                  |            |
|    approx_kl            | 0.09210859 |
|    clip_fraction        | 0.544      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.769      |
|    learning_rate        | 0.001      |
|    loss                 | -0.181     |
|    n_updates            | 90         |
|    policy_gradient_loss | -0.0609    |
|    std                  | 1.01       |
|    value_loss           | 0.000181   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 369         |
|    iterations           | 11          |
|    time_elapsed         | 60          |
|    total_timesteps      | 22528       |
| train/                  |             |
|    approx_kl            | 0.102289274 |
|    clip_fraction        | 0.53        |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.4       |
|    explained_variance   | 0.696       |
|    learning_rate        | 0.001       |
|    loss                 | -0.172      |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.046      |
|    std                  | 1.01        |
|    value_loss           | 0.000192    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 372        |
|    iterations           | 12         |
|    time_elapsed         | 66         |
|    total_timesteps      | 24576      |
| train/                  |            |
|    approx_kl            | 0.09295266 |
|    clip_fraction        | 0.527      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.764      |
|    learning_rate        | 0.001      |
|    loss                 | -0.215     |
|    n_updates            | 110        |
|    policy_gradient_loss | -0.053     |
|    std                  | 1.01       |
|    value_loss           | 9.29e-05   |
----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 367         |
|    iterations           | 13          |
|    time_elapsed         | 72          |
|    total_timesteps      | 26624       |
| train/                  |             |
|    approx_kl            | 0.097216755 |
|    clip_fraction        | 0.546       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.4       |
|    explained_variance   | 0.87        |
|    learning_rate        | 0.001       |
|    loss                 | -0.179      |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.0547     |
|    std                  | 1.01        |
|    value_loss           | 7.28e-05    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 368        |
|    iterations           | 14         |
|    time_elapsed         | 77         |
|    total_timesteps      | 28672      |
| train/                  |            |
|    approx_kl            | 0.11495459 |
|    clip_fraction        | 0.567      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.775      |
|    learning_rate        | 0.001      |
|    loss                 | -0.192     |
|    n_updates            | 130        |
|    policy_gradient_loss | -0.0491    |
|    std                  | 1.01       |
|    value_loss           | 6.1e-05    |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 370        |
|    iterations           | 15         |
|    time_elapsed         | 82         |
|    total_timesteps      | 30720      |
| train/                  |            |
|    approx_kl            | 0.10603541 |
|    clip_fraction        | 0.555      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.762      |
|    learning_rate        | 0.001      |
|    loss                 | -0.189     |
|    n_updates            | 140        |
|    policy_gradient_loss | -0.049     |
|    std                  | 1.01       |
|    value_loss           | 0.000101   |
----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 372       |
|    iterations           | 16        |
|    time_elapsed         | 88        |
|    total_timesteps      | 32768     |
| train/                  |           |
|    approx_kl            | 0.1156075 |
|    clip_fraction        | 0.564     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.5     |
|    explained_variance   | 0.725     |
|    learning_rate        | 0.001     |
|    loss                 | -0.2      |
|    n_updates            | 150       |
|    policy_gradient_loss | -0.0498   |
|    std                  | 1.02      |
|    value_loss           | 9.25e-05  |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 371        |
|    iterations           | 17         |
|    time_elapsed         | 93         |
|    total_timesteps      | 34816      |
| train/                  |            |
|    approx_kl            | 0.11406073 |
|    clip_fraction        | 0.556      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.6      |
|    explained_variance   | 0.773      |
|    learning_rate        | 0.001      |
|    loss                 | -0.206     |
|    n_updates            | 160        |
|    policy_gradient_loss | -0.0545    |
|    std                  | 1.02       |
|    value_loss           | 6.98e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 372        |
|    iterations           | 18         |
|    time_elapsed         | 99         |
|    total_timesteps      | 36864      |
| train/                  |            |
|    approx_kl            | 0.12972942 |
|    clip_fraction        | 0.577      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.6      |
|    explained_variance   | 0.761      |
|    learning_rate        | 0.001      |
|    loss                 | -0.167     |
|    n_updates            | 170        |
|    policy_gradient_loss | -0.053     |
|    std                  | 1.02       |
|    value_loss           | 7.36e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 372        |
|    iterations           | 19         |
|    time_elapsed         | 104        |
|    total_timesteps      | 38912      |
| train/                  |            |
|    approx_kl            | 0.13177685 |
|    clip_fraction        | 0.585      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.6      |
|    explained_variance   | 0.835      |
|    learning_rate        | 0.001      |
|    loss                 | -0.174     |
|    n_updates            | 180        |
|    policy_gradient_loss | -0.0565    |
|    std                  | 1.02       |
|    value_loss           | 6.38e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 373        |
|    iterations           | 20         |
|    time_elapsed         | 109        |
|    total_timesteps      | 40960      |
| train/                  |            |
|    approx_kl            | 0.13457629 |
|    clip_fraction        | 0.583      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.6      |
|    explained_variance   | 0.771      |
|    learning_rate        | 0.001      |
|    loss                 | -0.193     |
|    n_updates            | 190        |
|    policy_gradient_loss | -0.0549    |
|    std                  | 1.02       |
|    value_loss           | 0.000114   |
----------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A7_SH_KD_ppo_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A7_SH_KD_ppo_seed1_actions.csv
{'CR': -0.06141276513781824, 'AR': -0.06386769641669299, 'Vol': 0.04355255164372901, 'SR': -1.466451310112598, 'MDD': -0.0888872850348007, 'Calmar': -0.7185245492838243, 'Sortino': -2.156995807271545, 'Omega': 0.7760947470285853, 'Turnover': 0.7471434615725855, 'FinalAccountValue': 938587.2348621815, 'variant': 'A7_SH_KD', 'agent': 'ppo', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A7_SH_KD.CSV'}

========== A7_SH_KD | SAC | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A7_SH_KD.CSV
[banktrademergeGNNtr20241231_A7_SH_KD.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 128, 'buffer_size': 1000000, 'learning_rate': 0.0001, 'learning_starts': 100, 'ent_coef': 'auto_0.1', 'seed': 1}
Using cpu device
Logging to tensorboard_log/sac\A7_SH_KD_sac_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 14       |
|    time_elapsed    | 198      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | -9.74    |
|    critic_loss     | 0.0369   |
|    ent_coef        | 0.0753   |
|    ent_coef_loss   | -64.9    |
|    learning_rate   | 0.0001   |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 13       |
|    time_elapsed    | 417      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | -16.6    |
|    critic_loss     | 0.0194   |
|    ent_coef        | 0.0564   |
|    ent_coef_loss   | -72.4    |
|    learning_rate   | 0.0001   |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 13       |
|    time_elapsed    | 634      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | -20.2    |
|    critic_loss     | 0.0133   |
|    ent_coef        | 0.0422   |
|    ent_coef_loss   | -79.9    |
|    learning_rate   | 0.0001   |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 13       |
|    time_elapsed    | 864      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | -21.7    |
|    critic_loss     | 0.0173   |
|    ent_coef        | 0.0316   |
|    ent_coef_loss   | -87.3    |
|    learning_rate   | 0.0001   |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 13       |
|    time_elapsed    | 1096     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | -21.6    |
|    critic_loss     | 0.0332   |
|    ent_coef        | 0.0237   |
|    ent_coef_loss   | -94.1    |
|    learning_rate   | 0.0001   |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 12       |
|    time_elapsed    | 1333     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | -21      |
|    critic_loss     | 0.0189   |
|    ent_coef        | 0.0178   |
|    ent_coef_loss   | -101     |
|    learning_rate   | 0.0001   |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 12       |
|    time_elapsed    | 1577     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | -19.8    |
|    critic_loss     | 0.0168   |
|    ent_coef        | 0.0133   |
|    ent_coef_loss   | -108     |
|    learning_rate   | 0.0001   |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1812     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | -18.4    |
|    critic_loss     | 0.0271   |
|    ent_coef        | 0.00998  |
|    ent_coef_loss   | -115     |
|    learning_rate   | 0.0001   |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2047     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | -15.5    |
|    critic_loss     | 0.00858  |
|    ent_coef        | 0.00748  |
|    ent_coef_loss   | -123     |
|    learning_rate   | 0.0001   |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 12       |
|    time_elapsed    | 2287     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | -15      |
|    critic_loss     | 0.00402  |
|    ent_coef        | 0.00561  |
|    ent_coef_loss   | -128     |
|    learning_rate   | 0.0001   |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 12       |
|    time_elapsed    | 2522     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -12.9    |
|    critic_loss     | 0.00555  |
|    ent_coef        | 0.00421  |
|    ent_coef_loss   | -134     |
|    learning_rate   | 0.0001   |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 12       |
|    time_elapsed    | 2759     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -11.2    |
|    critic_loss     | 0.00823  |
|    ent_coef        | 0.00316  |
|    ent_coef_loss   | -140     |
|    learning_rate   | 0.0001   |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 12       |
|    time_elapsed    | 2999     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -9.73    |
|    critic_loss     | 0.00398  |
|    ent_coef        | 0.00237  |
|    ent_coef_loss   | -148     |
|    learning_rate   | 0.0001   |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 12       |
|    time_elapsed    | 3234     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -8.92    |
|    critic_loss     | 0.00128  |
|    ent_coef        | 0.00178  |
|    ent_coef_loss   | -152     |
|    learning_rate   | 0.0001   |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 12       |
|    time_elapsed    | 3468     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -7.2     |
|    critic_loss     | 0.0266   |
|    ent_coef        | 0.00134  |
|    ent_coef_loss   | -148     |
|    learning_rate   | 0.0001   |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 12       |
|    time_elapsed    | 3704     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -6.46    |
|    critic_loss     | 0.0165   |
|    ent_coef        | 0.001    |
|    ent_coef_loss   | -149     |
|    learning_rate   | 0.0001   |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 12       |
|    time_elapsed    | 3936     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -5.42    |
|    critic_loss     | 0.00162  |
|    ent_coef        | 0.000755 |
|    ent_coef_loss   | -158     |
|    learning_rate   | 0.0001   |
|    n_updates       | 48927    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 72       |
|    fps             | 12       |
|    time_elapsed    | 4170     |
|    total_timesteps | 51912    |
| train/             |          |
|    actor_loss      | -4.55    |
|    critic_loss     | 0.00683  |
|    ent_coef        | 0.000568 |
|    ent_coef_loss   | -157     |
|    learning_rate   | 0.0001   |
|    n_updates       | 51811    |
---------------------------------

---------------------------------
| time/              |          |
|    episodes        | 76       |
|    fps             | 12       |
|    time_elapsed    | 4403     |
|    total_timesteps | 54796    |
| train/             |          |
|    actor_loss      | -3.68    |
|    critic_loss     | 0.00614  |
|    ent_coef        | 0.000428 |
|    ent_coef_loss   | -149     |
|    learning_rate   | 0.0001   |
|    n_updates       | 54695    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 80       |
|    fps             | 12       |
|    time_elapsed    | 4637     |
|    total_timesteps | 57680    |
| train/             |          |
|    actor_loss      | -3.2     |
|    critic_loss     | 0.00416  |
|    ent_coef        | 0.000323 |
|    ent_coef_loss   | -137     |
|    learning_rate   | 0.0001   |
|    n_updates       | 57579    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A7_SH_KD_sac_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A7_SH_KD_sac_seed1_actions.csv
{'CR': -0.04125275008860474, 'AR': -0.042920302649806286, 'Vol': 0.03883244885825965, 'SR': -1.1052690188678933, 'MDD': -0.061138474085487005, 'Calmar': -0.7020178912184312, 'Sortino': -1.5080717874510985, 'Omega': 0.8252214796800669, 'Turnover': 0.5554727520713358, 'FinalAccountValue': 958747.2499113955, 'variant': 'A7_SH_KD', 'agent': 'sac', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A7_SH_KD.CSV'}

========== A7_SH_KD | TD3 | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A7_SH_KD.CSV
[banktrademergeGNNtr20241231_A7_SH_KD.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 100, 'buffer_size': 1000000, 'learning_rate': 0.001, 'seed': 1}
Using cpu device
Logging to tensorboard_log/td3\A7_SH_KD_td3_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 16       |
|    time_elapsed    | 178      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 1.01     |
|    critic_loss     | 0.00812  |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 15       |
|    time_elapsed    | 370      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.974    |
|    critic_loss     | 0.000538 |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 15       |
|    time_elapsed    | 572      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.873    |
|    critic_loss     | 0.00402  |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 14       |
|    time_elapsed    | 784      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.877    |
|    critic_loss     | 0.00297  |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 14       |
|    time_elapsed    | 1022     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.814    |
|    critic_loss     | 0.000654 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 14       |
|    time_elapsed    | 1213     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.692    |
|    critic_loss     | 0.00177  |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 13       |
|    time_elapsed    | 1483     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.685    |
|    critic_loss     | 0.000437 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 13       |
|    time_elapsed    | 1757     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.606    |
|    critic_loss     | 0.000388 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2050     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.593    |
|    critic_loss     | 0.000355 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 12       |
|    time_elapsed    | 2341     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.518    |
|    critic_loss     | 0.000304 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A7_SH_KD_td3_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A7_SH_KD_td3_seed1_actions.csv
{'CR': -0.07836039226445579, 'AR': -0.08146287455617673, 'Vol': 0.050240917157786634, 'SR': -1.62144481360351, 'MDD': -0.11256226321713403, 'Calmar': -0.7237139004484462, 'Sortino': -2.4362721677270733, 'Omega': 0.7541013956032274, 'Turnover': 0.7679240778333013, 'FinalAccountValue': 921639.6077355448, 'variant': 'A7_SH_KD', 'agent': 'td3', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A7_SH_KD.CSV'}

========== A7_SH_KD | DDPG | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A7_SH_KD.CSV
[banktrademergeGNNtr20241231_A7_SH_KD.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'seed': 1}
Using cpu device
Logging to tensorboard_log/ddpg\A7_SH_KD_ddpg_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 11       |
|    time_elapsed    | 257      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 0.679    |
|    critic_loss     | 0.000719 |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 11       |
|    time_elapsed    | 523      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.524    |
|    critic_loss     | 0.00138  |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 10       |
|    time_elapsed    | 800      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.381    |
|    critic_loss     | 0.000283 |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 10       |
|    time_elapsed    | 1074     |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.306    |
|    critic_loss     | 4.68e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 10       |
|    time_elapsed    | 1368     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.228    |
|    critic_loss     | 0.00022  |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 10       |
|    time_elapsed    | 1669     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.17     |
|    critic_loss     | 0.000235 |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 10       |
|    time_elapsed    | 1977     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.116    |
|    critic_loss     | 6.21e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 10       |
|    time_elapsed    | 2301     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.0796   |
|    critic_loss     | 9.11e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 9        |
|    time_elapsed    | 2636     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.0397   |
|    critic_loss     | 3.39e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 9        |
|    time_elapsed    | 2972     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.0055   |
|    critic_loss     | 2.67e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 9        |
|    time_elapsed    | 3320     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -0.0197  |
|    critic_loss     | 1.23e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 9        |
|    time_elapsed    | 3661     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -0.0562  |
|    critic_loss     | 1.5e-05  |
|    learning_rate   | 0.001    |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 9        |
|    time_elapsed    | 4013     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -0.0827  |
|    critic_loss     | 1.08e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 9        |
|    time_elapsed    | 4367     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -0.101   |
|    critic_loss     | 1.8e-05  |
|    learning_rate   | 0.001    |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 9        |
|    time_elapsed    | 4717     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -0.137   |
|    critic_loss     | 1.79e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 9        |
|    time_elapsed    | 5082     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -0.144   |
|    critic_loss     | 1.46e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 9        |
|    time_elapsed    | 5445     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -0.157   |
|    critic_loss     | 1.87e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 48927    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A7_SH_KD_ddpg_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A7_SH_KD_ddpg_seed1_actions.csv
{'CR': -0.06772506366320852, 'AR': -0.07042272835712227, 'Vol': 0.0499400510317274, 'SR': -1.4101453022621468, 'MDD': -0.10616877809683689, 'Calmar': -0.6633092102924032, 'Sortino': -1.9713572662683836, 'Omega': 0.7831772334655984, 'Turnover': 0.8661183295890158, 'FinalAccountValue': 932274.9363367916, 'variant': 'A7_SH_KD', 'agent': 'ddpg', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A7_SH_KD.CSV'}
[banktrademergeGNNtr20241231_A8_QA_KD.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630

========== A8_QA_KD | A2C | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A8_QA_KD.CSV
[banktrademergeGNNtr20241231_A8_QA_KD.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 10, 'ent_coef': 0.005, 'learning_rate': 0.0004, 'seed': 1}
Using cpu device
Logging to tensorboard_log/a2c\A8_QA_KD_a2c_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 100      |
|    time_elapsed       | 2        |
|    total_timesteps    | 1000     |
| train/                |          |
|    entropy_loss       | -21.3    |
|    explained_variance | -861     |
|    learning_rate      | 0.0004   |
|    n_updates          | 99       |
|    policy_loss        | -4.45    |
|    std                | 1        |
|    value_loss         | 0.0775   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 389       |
|    iterations         | 200       |
|    time_elapsed       | 5         |
|    total_timesteps    | 2000      |
| train/                |           |
|    entropy_loss       | -21.3     |
|    explained_variance | -8.59e+04 |
|    learning_rate      | 0.0004    |
|    n_updates          | 199       |
|    policy_loss        | -3.95     |
|    std                | 1         |
|    value_loss         | 0.0566    |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 393       |
|    iterations         | 300       |
|    time_elapsed       | 7         |
|    total_timesteps    | 3000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -4.23e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 299       |
|    policy_loss        | 0.998     |
|    std                | 1.01      |
|    value_loss         | 0.0377    |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 392       |
|    iterations         | 400       |
|    time_elapsed       | 10        |
|    total_timesteps    | 4000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -2.28e+04 |
|    learning_rate      | 0.0004    |
|    n_updates          | 399       |
|    policy_loss        | -3.4      |
|    std                | 1.01      |
|    value_loss         | 0.0384    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 395      |
|    iterations         | 500      |
|    time_elapsed       | 12       |
|    total_timesteps    | 5000     |
| train/                |          |
|    entropy_loss       | -21.5    |
|    explained_variance | -348     |
|    learning_rate      | 0.0004   |
|    n_updates          | 499      |
|    policy_loss        | -1.23    |
|    std                | 1.01     |
|    value_loss         | 0.0185   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 398       |
|    iterations         | 600       |
|    time_elapsed       | 15        |
|    total_timesteps    | 6000      |
| train/                |           |
|    entropy_loss       | -21.5     |
|    explained_variance | -1.67e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 599       |
|    policy_loss        | -0.259    |
|    std                | 1.01      |
|    value_loss         | 0.00562   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 700      |
|    time_elapsed       | 17       |
|    total_timesteps    | 7000     |
| train/                |          |
|    entropy_loss       | -21.5    |
|    explained_variance | -53.3    |
|    learning_rate      | 0.0004   |
|    n_updates          | 699      |
|    policy_loss        | 2.87     |
|    std                | 1.02     |
|    value_loss         | 0.0261   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 396       |
|    iterations         | 800       |
|    time_elapsed       | 20        |
|    total_timesteps    | 8000      |
| train/                |           |
|    entropy_loss       | -21.6     |
|    explained_variance | -2.97e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 799       |
|    policy_loss        | -0.278    |
|    std                | 1.02      |
|    value_loss         | 0.0194    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 900      |
|    time_elapsed       | 22       |
|    total_timesteps    | 9000     |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -891     |
|    learning_rate      | 0.0004   |
|    n_updates          | 899      |
|    policy_loss        | -3.22    |
|    std                | 1.02     |
|    value_loss         | 0.0354   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 1000     |
|    time_elapsed       | 25       |
|    total_timesteps    | 10000    |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -168     |
|    learning_rate      | 0.0004   |
|    n_updates          | 999      |
|    policy_loss        | 1.15     |
|    std                | 1.03     |
|    value_loss         | 0.0122   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 400       |
|    iterations         | 1100      |
|    time_elapsed       | 27        |
|    total_timesteps    | 11000     |
| train/                |           |
|    entropy_loss       | -21.8     |
|    explained_variance | -1.44e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 1099      |
|    policy_loss        | 1.05      |
|    std                | 1.03      |
|    value_loss         | 0.0144    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 1200     |
|    time_elapsed       | 29       |
|    total_timesteps    | 12000    |
| train/                |          |
|    entropy_loss       | -21.8    |
|    explained_variance | -533     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1199     |
|    policy_loss        | 2.68     |
|    std                | 1.04     |
|    value_loss         | 0.0211   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 1300     |
|    time_elapsed       | 32       |
|    total_timesteps    | 13000    |
| train/                |          |
|    entropy_loss       | -21.9    |
|    explained_variance | -151     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1299     |
|    policy_loss        | -0.528   |
|    std                | 1.04     |
|    value_loss         | 0.00318  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 401       |
|    iterations         | 1400      |
|    time_elapsed       | 34        |
|    total_timesteps    | 14000     |
| train/                |           |
|    entropy_loss       | -22       |
|    explained_variance | -1.11e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 1399      |
|    policy_loss        | -1.49     |
|    std                | 1.05      |
|    value_loss         | 0.00903   |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 399       |
|    iterations         | 1500      |
|    time_elapsed       | 37        |
|    total_timesteps    | 15000     |
| train/                |           |
|    entropy_loss       | -22.1     |
|    explained_variance | -1.72e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 1499      |
|    policy_loss        | -0.318    |
|    std                | 1.06      |
|    value_loss         | 0.00814   |
-------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 1600     |
|    time_elapsed       | 40       |
|    total_timesteps    | 16000    |
| train/                |          |
|    entropy_loss       | -22.2    |
|    explained_variance | -314     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1599     |
|    policy_loss        | -1.85    |
|    std                | 1.06     |
|    value_loss         | 0.0116   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 1700     |
|    time_elapsed       | 42       |
|    total_timesteps    | 17000    |
| train/                |          |
|    entropy_loss       | -22.2    |
|    explained_variance | -465     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1699     |
|    policy_loss        | -1.15    |
|    std                | 1.07     |
|    value_loss         | 0.00556  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 1800     |
|    time_elapsed       | 44       |
|    total_timesteps    | 18000    |
| train/                |          |
|    entropy_loss       | -22.3    |
|    explained_variance | -50.1    |
|    learning_rate      | 0.0004   |
|    n_updates          | 1799     |
|    policy_loss        | 1.21     |
|    std                | 1.07     |
|    value_loss         | 0.00526  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 400       |
|    iterations         | 1900      |
|    time_elapsed       | 47        |
|    total_timesteps    | 19000     |
| train/                |           |
|    entropy_loss       | -22.4     |
|    explained_variance | -1.12e+04 |
|    learning_rate      | 0.0004    |
|    n_updates          | 1899      |
|    policy_loss        | 0.197     |
|    std                | 1.08      |
|    value_loss         | 0.00261   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 2000     |
|    time_elapsed       | 50       |
|    total_timesteps    | 20000    |
| train/                |          |
|    entropy_loss       | -22.5    |
|    explained_variance | -586     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1999     |
|    policy_loss        | 1.24     |
|    std                | 1.09     |
|    value_loss         | 0.00558  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 397       |
|    iterations         | 2100      |
|    time_elapsed       | 52        |
|    total_timesteps    | 21000     |
| train/                |           |
|    entropy_loss       | -22.6     |
|    explained_variance | -1.59e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 2099      |
|    policy_loss        | 0.699     |
|    std                | 1.09      |
|    value_loss         | 0.00661   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 2200     |
|    time_elapsed       | 55       |
|    total_timesteps    | 22000    |
| train/                |          |
|    entropy_loss       | -22.7    |
|    explained_variance | -169     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2199     |
|    policy_loss        | 1.51     |
|    std                | 1.1      |
|    value_loss         | 0.00756  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 2300     |
|    time_elapsed       | 57       |
|    total_timesteps    | 23000    |
| train/                |          |
|    entropy_loss       | -22.8    |
|    explained_variance | -31.6    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2299     |
|    policy_loss        | -1.89    |
|    std                | 1.11     |
|    value_loss         | 0.0114   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 2400     |
|    time_elapsed       | 60       |
|    total_timesteps    | 24000    |
| train/                |          |
|    entropy_loss       | -22.9    |
|    explained_variance | -644     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2399     |
|    policy_loss        | -0.663   |
|    std                | 1.11     |
|    value_loss         | 0.00463  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 2500     |
|    time_elapsed       | 62       |
|    total_timesteps    | 25000    |
| train/                |          |
|    entropy_loss       | -23      |
|    explained_variance | -138     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2499     |
|    policy_loss        | 2.16     |
|    std                | 1.12     |
|    value_loss         | 0.0113   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 2600     |
|    time_elapsed       | 64       |
|    total_timesteps    | 26000    |
| train/                |          |
|    entropy_loss       | -23.1    |
|    explained_variance | -321     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2599     |
|    policy_loss        | -0.135   |
|    std                | 1.13     |
|    value_loss         | 0.00132  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 2700     |
|    time_elapsed       | 67       |
|    total_timesteps    | 27000    |
| train/                |          |
|    entropy_loss       | -23.3    |
|    explained_variance | -199     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2699     |
|    policy_loss        | 0.766    |
|    std                | 1.14     |
|    value_loss         | 0.0035   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 2800     |
|    time_elapsed       | 69       |
|    total_timesteps    | 28000    |
| train/                |          |
|    entropy_loss       | -23.4    |
|    explained_variance | -47.5    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2799     |
|    policy_loss        | -0.873   |
|    std                | 1.15     |
|    value_loss         | 0.00253  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 2900     |
|    time_elapsed       | 72       |
|    total_timesteps    | 29000    |
| train/                |          |
|    entropy_loss       | -23.5    |
|    explained_variance | -57.7    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2899     |
|    policy_loss        | -0.605   |
|    std                | 1.16     |
|    value_loss         | 0.00147  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 400       |
|    iterations         | 3000      |
|    time_elapsed       | 74        |
|    total_timesteps    | 30000     |
| train/                |           |
|    entropy_loss       | -23.6     |
|    explained_variance | -2.06e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 2999      |
|    policy_loss        | 0.144     |
|    std                | 1.17      |
|    value_loss         | 0.0023    |
-------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 3100     |
|    time_elapsed       | 77       |
|    total_timesteps    | 31000    |
| train/                |          |
|    entropy_loss       | -23.7    |
|    explained_variance | -141     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3099     |
|    policy_loss        | -1.96    |
|    std                | 1.18     |
|    value_loss         | 0.00947  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 3200     |
|    time_elapsed       | 79       |
|    total_timesteps    | 32000    |
| train/                |          |
|    entropy_loss       | -23.9    |
|    explained_variance | -198     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3199     |
|    policy_loss        | 0.696    |
|    std                | 1.19     |
|    value_loss         | 0.00296  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 3300     |
|    time_elapsed       | 82       |
|    total_timesteps    | 33000    |
| train/                |          |
|    entropy_loss       | -24      |
|    explained_variance | -326     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3299     |
|    policy_loss        | -0.525   |
|    std                | 1.2      |
|    value_loss         | 0.00201  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 399      |
|    iterations         | 3400     |
|    time_elapsed       | 85       |
|    total_timesteps    | 34000    |
| train/                |          |
|    entropy_loss       | -24.2    |
|    explained_variance | -228     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3399     |
|    policy_loss        | 0.895    |
|    std                | 1.21     |
|    value_loss         | 0.00245  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 400       |
|    iterations         | 3500      |
|    time_elapsed       | 87        |
|    total_timesteps    | 35000     |
| train/                |           |
|    entropy_loss       | -24.3     |
|    explained_variance | -1.05e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 3499      |
|    policy_loss        | -0.874    |
|    std                | 1.22      |
|    value_loss         | 0.00577   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 3600     |
|    time_elapsed       | 89       |
|    total_timesteps    | 36000    |
| train/                |          |
|    entropy_loss       | -24.5    |
|    explained_variance | -37.6    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3599     |
|    policy_loss        | 2.16     |
|    std                | 1.24     |
|    value_loss         | 0.0103   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 3700     |
|    time_elapsed       | 92       |
|    total_timesteps    | 37000    |
| train/                |          |
|    entropy_loss       | -24.6    |
|    explained_variance | -160     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3699     |
|    policy_loss        | -0.789   |
|    std                | 1.25     |
|    value_loss         | 0.00251  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 3800     |
|    time_elapsed       | 94       |
|    total_timesteps    | 38000    |
| train/                |          |
|    entropy_loss       | -24.7    |
|    explained_variance | -28.4    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3799     |
|    policy_loss        | 0.582    |
|    std                | 1.26     |
|    value_loss         | 0.00137  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 401      |
|    iterations         | 3900     |
|    time_elapsed       | 97       |
|    total_timesteps    | 39000    |
| train/                |          |
|    entropy_loss       | -24.9    |
|    explained_variance | -97.4    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3899     |
|    policy_loss        | 0.821    |
|    std                | 1.27     |
|    value_loss         | 0.00225  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 400      |
|    iterations         | 4000     |
|    time_elapsed       | 99       |
|    total_timesteps    | 40000    |
| train/                |          |
|    entropy_loss       | -25      |
|    explained_variance | -11.2    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3999     |
|    policy_loss        | 0.866    |
|    std                | 1.28     |
|    value_loss         | 0.00172  |
------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A8_QA_KD_a2c_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A8_QA_KD_a2c_seed1_actions.csv
{'CR': 0.001158353495145814, 'AR': 0.0012062481997279217, 'Vol': 0.1590701561232316, 'SR': 0.007583120738207119, 'MDD': -0.1807878211980446, 'Calmar': 0.006672176210401548, 'Sortino': 0.011215719332077587, 'Omega': 1.0155092730651771, 'Turnover': 0.7583596028012178, 'FinalAccountValue': 1001158.3534951458, 'variant': 'A8_QA_KD', 'agent': 'a2c', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A8_QA_KD.CSV'}

========== A8_QA_KD | PPO | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A8_QA_KD.CSV
[banktrademergeGNNtr20241231_A8_QA_KD.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 2048, 'ent_coef': 0.005, 'learning_rate': 0.001, 'batch_size': 128, 'seed': 1}
Using cpu device
Logging to tensorboard_log/ppo\A8_QA_KD_ppo_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

-----------------------------
| time/              |      |
|    fps             | 462  |
|    iterations      | 1    |
|    time_elapsed    | 4    |
|    total_timesteps | 2048 |
-----------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 401        |
|    iterations           | 2          |
|    time_elapsed         | 10         |
|    total_timesteps      | 4096       |
| train/                  |            |
|    approx_kl            | 0.04731783 |
|    clip_fraction        | 0.408      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | -50.2      |
|    learning_rate        | 0.001      |
|    loss                 | -0.2       |
|    n_updates            | 10         |
|    policy_gradient_loss | -0.0713    |
|    std                  | 0.997      |
|    value_loss           | 0.0361     |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 387        |
|    iterations           | 3          |
|    time_elapsed         | 15         |
|    total_timesteps      | 6144       |
| train/                  |            |
|    approx_kl            | 0.05973628 |
|    clip_fraction        | 0.447      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | -1.23      |
|    learning_rate        | 0.001      |
|    loss                 | -0.195     |
|    n_updates            | 20         |
|    policy_gradient_loss | -0.0705    |
|    std                  | 0.997      |
|    value_loss           | 0.00287    |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 385        |
|    iterations           | 4          |
|    time_elapsed         | 21         |
|    total_timesteps      | 8192       |
| train/                  |            |
|    approx_kl            | 0.05852729 |
|    clip_fraction        | 0.449      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.441      |
|    learning_rate        | 0.001      |
|    loss                 | -0.2       |
|    n_updates            | 30         |
|    policy_gradient_loss | -0.0665    |
|    std                  | 0.992      |
|    value_loss           | 0.000927   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 370         |
|    iterations           | 5           |
|    time_elapsed         | 27          |
|    total_timesteps      | 10240       |
| train/                  |             |
|    approx_kl            | 0.074065186 |
|    clip_fraction        | 0.494       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.2       |
|    explained_variance   | 0.668       |
|    learning_rate        | 0.001       |
|    loss                 | -0.177      |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0628     |
|    std                  | 0.993       |
|    value_loss           | 0.000543    |
-----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 374       |
|    iterations           | 6         |
|    time_elapsed         | 32        |
|    total_timesteps      | 12288     |
| train/                  |           |
|    approx_kl            | 0.0842779 |
|    clip_fraction        | 0.507     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.2     |
|    explained_variance   | 0.742     |
|    learning_rate        | 0.001     |
|    loss                 | -0.173    |
|    n_updates            | 50        |
|    policy_gradient_loss | -0.0557   |
|    std                  | 0.995     |
|    value_loss           | 0.000361  |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 373        |
|    iterations           | 7          |
|    time_elapsed         | 38         |
|    total_timesteps      | 14336      |
| train/                  |            |
|    approx_kl            | 0.07860707 |
|    clip_fraction        | 0.516      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.815      |
|    learning_rate        | 0.001      |
|    loss                 | -0.218     |
|    n_updates            | 60         |
|    policy_gradient_loss | -0.0564    |
|    std                  | 0.996      |
|    value_loss           | 0.000204   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 375        |
|    iterations           | 8          |
|    time_elapsed         | 43         |
|    total_timesteps      | 16384      |
| train/                  |            |
|    approx_kl            | 0.08860432 |
|    clip_fraction        | 0.529      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.869      |
|    learning_rate        | 0.001      |
|    loss                 | -0.204     |
|    n_updates            | 70         |
|    policy_gradient_loss | -0.0573    |
|    std                  | 0.999      |
|    value_loss           | 0.000241   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 377         |
|    iterations           | 9           |
|    time_elapsed         | 48          |
|    total_timesteps      | 18432       |
| train/                  |             |
|    approx_kl            | 0.099895105 |
|    clip_fraction        | 0.527       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | 0.73        |
|    learning_rate        | 0.001       |
|    loss                 | -0.195      |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.0593     |
|    std                  | 1           |
|    value_loss           | 0.00017     |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 376        |
|    iterations           | 10         |
|    time_elapsed         | 54         |
|    total_timesteps      | 20480      |
| train/                  |            |
|    approx_kl            | 0.09791614 |
|    clip_fraction        | 0.535      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.84       |
|    learning_rate        | 0.001      |
|    loss                 | -0.165     |
|    n_updates            | 90         |
|    policy_gradient_loss | -0.0477    |
|    std                  | 1.01       |
|    value_loss           | 0.000108   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 377         |
|    iterations           | 11          |
|    time_elapsed         | 59          |
|    total_timesteps      | 22528       |
| train/                  |             |
|    approx_kl            | 0.095235534 |
|    clip_fraction        | 0.53        |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | 0.87        |
|    learning_rate        | 0.001       |
|    loss                 | -0.202      |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.0538     |
|    std                  | 1           |
|    value_loss           | 9.2e-05     |
-----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 377       |
|    iterations           | 12        |
|    time_elapsed         | 65        |
|    total_timesteps      | 24576     |
| train/                  |           |
|    approx_kl            | 0.0956001 |
|    clip_fraction        | 0.532     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.3     |
|    explained_variance   | 0.855     |
|    learning_rate        | 0.001     |
|    loss                 | -0.15     |
|    n_updates            | 110       |
|    policy_gradient_loss | -0.0548   |
|    std                  | 1         |
|    value_loss           | 9.36e-05  |
---------------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 376        |
|    iterations           | 13         |
|    time_elapsed         | 70         |
|    total_timesteps      | 26624      |
| train/                  |            |
|    approx_kl            | 0.09783408 |
|    clip_fraction        | 0.528      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.857      |
|    learning_rate        | 0.001      |
|    loss                 | -0.174     |
|    n_updates            | 120        |
|    policy_gradient_loss | -0.0536    |
|    std                  | 1          |
|    value_loss           | 8.78e-05   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 376         |
|    iterations           | 14          |
|    time_elapsed         | 76          |
|    total_timesteps      | 28672       |
| train/                  |             |
|    approx_kl            | 0.115433715 |
|    clip_fraction        | 0.58        |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.4       |
|    explained_variance   | 0.791       |
|    learning_rate        | 0.001       |
|    loss                 | -0.193      |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.0509     |
|    std                  | 1.01        |
|    value_loss           | 0.000116    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 376        |
|    iterations           | 15         |
|    time_elapsed         | 81         |
|    total_timesteps      | 30720      |
| train/                  |            |
|    approx_kl            | 0.12664676 |
|    clip_fraction        | 0.568      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.449      |
|    learning_rate        | 0.001      |
|    loss                 | -0.168     |
|    n_updates            | 140        |
|    policy_gradient_loss | -0.0475    |
|    std                  | 1.01       |
|    value_loss           | 0.000152   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 375        |
|    iterations           | 16         |
|    time_elapsed         | 87         |
|    total_timesteps      | 32768      |
| train/                  |            |
|    approx_kl            | 0.12143087 |
|    clip_fraction        | 0.572      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.552      |
|    learning_rate        | 0.001      |
|    loss                 | -0.186     |
|    n_updates            | 150        |
|    policy_gradient_loss | -0.0486    |
|    std                  | 1.01       |
|    value_loss           | 0.000313   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 375        |
|    iterations           | 17         |
|    time_elapsed         | 92         |
|    total_timesteps      | 34816      |
| train/                  |            |
|    approx_kl            | 0.12815152 |
|    clip_fraction        | 0.572      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.0538     |
|    learning_rate        | 0.001      |
|    loss                 | -0.213     |
|    n_updates            | 160        |
|    policy_gradient_loss | -0.0542    |
|    std                  | 1.02       |
|    value_loss           | 0.000202   |
----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 375       |
|    iterations           | 18        |
|    time_elapsed         | 98        |
|    total_timesteps      | 36864     |
| train/                  |           |
|    approx_kl            | 0.1267836 |
|    clip_fraction        | 0.562     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.5     |
|    explained_variance   | 0.679     |
|    learning_rate        | 0.001     |
|    loss                 | -0.178    |
|    n_updates            | 170       |
|    policy_gradient_loss | -0.0509   |
|    std                  | 1.02      |
|    value_loss           | 9.84e-05  |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 375        |
|    iterations           | 19         |
|    time_elapsed         | 103        |
|    total_timesteps      | 38912      |
| train/                  |            |
|    approx_kl            | 0.13332608 |
|    clip_fraction        | 0.577      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.658      |
|    learning_rate        | 0.001      |
|    loss                 | -0.187     |
|    n_updates            | 180        |
|    policy_gradient_loss | -0.0514    |
|    std                  | 1.01       |
|    value_loss           | 5.79e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 376        |
|    iterations           | 20         |
|    time_elapsed         | 108        |
|    total_timesteps      | 40960      |
| train/                  |            |
|    approx_kl            | 0.12287286 |
|    clip_fraction        | 0.554      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.834      |
|    learning_rate        | 0.001      |
|    loss                 | -0.197     |
|    n_updates            | 190        |
|    policy_gradient_loss | -0.0409    |
|    std                  | 1.02       |
|    value_loss           | 4.6e-05    |
----------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A8_QA_KD_ppo_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A8_QA_KD_ppo_seed1_actions.csv
{'CR': -0.17809995557947922, 'AR': -0.18473438062140823, 'Vol': 0.14750997390016257, 'SR': -1.2523517951839638, 'MDD': -0.21942197925902807, 'Calmar': -0.8419137464954181, 'Sortino': -1.688591979932784, 'Omega': 0.7924943776902073, 'Turnover': 0.7466043240971757, 'FinalAccountValue': 821900.044420521, 'variant': 'A8_QA_KD', 'agent': 'ppo', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A8_QA_KD.CSV'}

========== A8_QA_KD | SAC | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A8_QA_KD.CSV
[banktrademergeGNNtr20241231_A8_QA_KD.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 128, 'buffer_size': 1000000, 'learning_rate': 0.0001, 'learning_starts': 100, 'ent_coef': 'auto_0.1', 'seed': 1}
Using cpu device
Logging to tensorboard_log/sac\A8_QA_KD_sac_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 14       |
|    time_elapsed    | 202      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | -9.78    |
|    critic_loss     | 0.0201   |
|    ent_coef        | 0.0753   |
|    ent_coef_loss   | -64.9    |
|    learning_rate   | 0.0001   |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 13       |
|    time_elapsed    | 413      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | -16.5    |
|    critic_loss     | 0.0361   |
|    ent_coef        | 0.0564   |
|    ent_coef_loss   | -72.4    |
|    learning_rate   | 0.0001   |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 13       |
|    time_elapsed    | 634      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | -20.2    |
|    critic_loss     | 0.0111   |
|    ent_coef        | 0.0422   |
|    ent_coef_loss   | -80.1    |
|    learning_rate   | 0.0001   |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 13       |
|    time_elapsed    | 864      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | -21.7    |
|    critic_loss     | 0.017    |
|    ent_coef        | 0.0316   |
|    ent_coef_loss   | -87.3    |
|    learning_rate   | 0.0001   |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 13       |
|    time_elapsed    | 1100     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | -21.8    |
|    critic_loss     | 0.0225   |
|    ent_coef        | 0.0237   |
|    ent_coef_loss   | -94.4    |
|    learning_rate   | 0.0001   |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 12       |
|    time_elapsed    | 1341     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | -21      |
|    critic_loss     | 0.0101   |
|    ent_coef        | 0.0178   |
|    ent_coef_loss   | -101     |
|    learning_rate   | 0.0001   |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 12       |
|    time_elapsed    | 1584     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | -19.7    |
|    critic_loss     | 0.0225   |
|    ent_coef        | 0.0133   |
|    ent_coef_loss   | -108     |
|    learning_rate   | 0.0001   |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1825     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | -18.4    |
|    critic_loss     | 0.0142   |
|    ent_coef        | 0.00998  |
|    ent_coef_loss   | -115     |
|    learning_rate   | 0.0001   |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2066     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | -15.5    |
|    critic_loss     | 0.00358  |
|    ent_coef        | 0.00748  |
|    ent_coef_loss   | -123     |
|    learning_rate   | 0.0001   |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 12       |
|    time_elapsed    | 2307     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | -15      |
|    critic_loss     | 0.00891  |
|    ent_coef        | 0.00561  |
|    ent_coef_loss   | -129     |
|    learning_rate   | 0.0001   |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 12       |
|    time_elapsed    | 2548     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -13      |
|    critic_loss     | 0.00307  |
|    ent_coef        | 0.00421  |
|    ent_coef_loss   | -135     |
|    learning_rate   | 0.0001   |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 12       |
|    time_elapsed    | 2790     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -11.2    |
|    critic_loss     | 0.00909  |
|    ent_coef        | 0.00316  |
|    ent_coef_loss   | -141     |
|    learning_rate   | 0.0001   |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 12       |
|    time_elapsed    | 3026     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -9.75    |
|    critic_loss     | 0.00467  |
|    ent_coef        | 0.00237  |
|    ent_coef_loss   | -147     |
|    learning_rate   | 0.0001   |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 12       |
|    time_elapsed    | 3264     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -8.86    |
|    critic_loss     | 0.0115   |
|    ent_coef        | 0.00178  |
|    ent_coef_loss   | -151     |
|    learning_rate   | 0.0001   |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 12       |
|    time_elapsed    | 3498     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -7.28    |
|    critic_loss     | 0.00405  |
|    ent_coef        | 0.00133  |
|    ent_coef_loss   | -155     |
|    learning_rate   | 0.0001   |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 12       |
|    time_elapsed    | 3739     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -6.46    |
|    critic_loss     | 0.00606  |
|    ent_coef        | 0.001    |
|    ent_coef_loss   | -156     |
|    learning_rate   | 0.0001   |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 12       |
|    time_elapsed    | 3975     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -5.42    |
|    critic_loss     | 0.00341  |
|    ent_coef        | 0.000755 |
|    ent_coef_loss   | -151     |
|    learning_rate   | 0.0001   |
|    n_updates       | 48927    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 72       |
|    fps             | 12       |
|    time_elapsed    | 4207     |
|    total_timesteps | 51912    |
| train/             |          |
|    actor_loss      | -4.55    |
|    critic_loss     | 0.00115  |
|    ent_coef        | 0.000567 |
|    ent_coef_loss   | -159     |
|    learning_rate   | 0.0001   |
|    n_updates       | 51811    |
---------------------------------

---------------------------------
| time/              |          |
|    episodes        | 76       |
|    fps             | 12       |
|    time_elapsed    | 4445     |
|    total_timesteps | 54796    |
| train/             |          |
|    actor_loss      | -3.69    |
|    critic_loss     | 0.0151   |
|    ent_coef        | 0.000427 |
|    ent_coef_loss   | -151     |
|    learning_rate   | 0.0001   |
|    n_updates       | 54695    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 80       |
|    fps             | 12       |
|    time_elapsed    | 4677     |
|    total_timesteps | 57680    |
| train/             |          |
|    actor_loss      | -3.15    |
|    critic_loss     | 0.00213  |
|    ent_coef        | 0.000323 |
|    ent_coef_loss   | -152     |
|    learning_rate   | 0.0001   |
|    n_updates       | 57579    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A8_QA_KD_sac_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A8_QA_KD_sac_seed1_actions.csv
{'CR': -0.15966328480183423, 'AR': -0.16568207202976504, 'Vol': 0.15699785902085958, 'SR': -1.055314212964851, 'MDD': -0.2313010585499915, 'Calmar': -0.7163048585614488, 'Sortino': -1.5108894852009014, 'Omega': 0.8264597798785855, 'Turnover': 0.6584275816450484, 'FinalAccountValue': 840336.7151981652, 'variant': 'A8_QA_KD', 'agent': 'sac', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A8_QA_KD.CSV'}

========== A8_QA_KD | TD3 | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A8_QA_KD.CSV
[banktrademergeGNNtr20241231_A8_QA_KD.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 100, 'buffer_size': 1000000, 'learning_rate': 0.001, 'seed': 1}
Using cpu device
Logging to tensorboard_log/td3\A8_QA_KD_td3_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 15       |
|    time_elapsed    | 181      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 0.97     |
|    critic_loss     | 0.00766  |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 15       |
|    time_elapsed    | 379      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.972    |
|    critic_loss     | 0.00117  |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 14       |
|    time_elapsed    | 582      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.895    |
|    critic_loss     | 0.000698 |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 14       |
|    time_elapsed    | 800      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.883    |
|    critic_loss     | 0.00254  |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 14       |
|    time_elapsed    | 1029     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.816    |
|    critic_loss     | 0.000511 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 13       |
|    time_elapsed    | 1289     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.678    |
|    critic_loss     | 0.000807 |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 12       |
|    time_elapsed    | 1566     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.688    |
|    critic_loss     | 0.000638 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1841     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.614    |
|    critic_loss     | 0.000322 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2136     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.593    |
|    critic_loss     | 0.00091  |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 11       |
|    time_elapsed    | 2430     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.51     |
|    critic_loss     | 9.41e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A8_QA_KD_td3_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A8_QA_KD_td3_seed1_actions.csv
{'CR': -0.07003900290826492, 'AR': -0.07282518923925729, 'Vol': 0.14552179342572613, 'SR': -0.5004418068584829, 'MDD': -0.16167620389962245, 'Calmar': -0.45043851527137047, 'Sortino': -0.7541172098650215, 'Omega': 0.9242651745814001, 'Turnover': 0.4997909336533192, 'FinalAccountValue': 929960.9970917345, 'variant': 'A8_QA_KD', 'agent': 'td3', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A8_QA_KD.CSV'}

========== A8_QA_KD | DDPG | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A8_QA_KD.CSV
[banktrademergeGNNtr20241231_A8_QA_KD.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'seed': 1}
Using cpu device
Logging to tensorboard_log/ddpg\A8_QA_KD_ddpg_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 11       |
|    time_elapsed    | 257      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 0.629    |
|    critic_loss     | 0.000206 |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 10       |
|    time_elapsed    | 536      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.495    |
|    critic_loss     | 0.0004   |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 10       |
|    time_elapsed    | 815      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.383    |
|    critic_loss     | 0.000288 |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 10       |
|    time_elapsed    | 1098     |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.296    |
|    critic_loss     | 0.000187 |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 10       |
|    time_elapsed    | 1394     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.218    |
|    critic_loss     | 0.000143 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 10       |
|    time_elapsed    | 1695     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.159    |
|    critic_loss     | 0.000316 |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 10       |
|    time_elapsed    | 2005     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.103    |
|    critic_loss     | 1.92e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 9        |
|    time_elapsed    | 2338     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.0622   |
|    critic_loss     | 3.54e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 9        |
|    time_elapsed    | 2677     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.0259   |
|    critic_loss     | 2.94e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 9        |
|    time_elapsed    | 3020     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | -0.0116  |
|    critic_loss     | 1.28e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 9        |
|    time_elapsed    | 3367     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -0.0374  |
|    critic_loss     | 2.32e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 9        |
|    time_elapsed    | 3713     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -0.0704  |
|    critic_loss     | 3.84e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 9        |
|    time_elapsed    | 4066     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -0.0966  |
|    critic_loss     | 1.55e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 9        |
|    time_elapsed    | 4426     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -0.114   |
|    critic_loss     | 2.19e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 9        |
|    time_elapsed    | 4776     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -0.148   |
|    critic_loss     | 1.21e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 8        |
|    time_elapsed    | 5134     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -0.153   |
|    critic_loss     | 9.46e-06 |
|    learning_rate   | 0.001    |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 8        |
|    time_elapsed    | 5503     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -0.16    |
|    critic_loss     | 1.19e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 48927    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A8_QA_KD_ddpg_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A8_QA_KD_ddpg_seed1_actions.csv
{'CR': -0.05912840723933832, 'AR': -0.061495046123062114, 'Vol': 0.18581323939147232, 'SR': -0.3309508317300471, 'MDD': -0.20851198642762203, 'Calmar': -0.29492331436978597, 'Sortino': -0.4729994656339616, 'Omega': 0.9543938407665143, 'Turnover': 0.9305314856441204, 'FinalAccountValue': 940871.592760661, 'variant': 'A8_QA_KD', 'agent': 'ddpg', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A8_QA_KD.CSV'}
[banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630

========== A9_Fixed_fusion | A2C | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV
[banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 10, 'ent_coef': 0.005, 'learning_rate': 0.0004, 'seed': 1}
Using cpu device
Logging to tensorboard_log/a2c\A9_Fixed_fusion_a2c_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

-------------------------------------
| time/                 |           |
|    fps                | 397       |
|    iterations         | 100       |
|    time_elapsed       | 2         |
|    total_timesteps    | 1000      |
| train/                |           |
|    entropy_loss       | -21.3     |
|    explained_variance | -1.21e+04 |
|    learning_rate      | 0.0004    |
|    n_updates          | 99        |
|    policy_loss        | 0.112     |
|    std                | 1         |
|    value_loss         | 0.111     |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 381      |
|    iterations         | 200      |
|    time_elapsed       | 5        |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -4.4e+03 |
|    learning_rate      | 0.0004   |
|    n_updates          | 199      |
|    policy_loss        | -5.44    |
|    std                | 1        |
|    value_loss         | 0.112    |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 389      |
|    iterations         | 300      |
|    time_elapsed       | 7        |
|    total_timesteps    | 3000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -1e+03   |
|    learning_rate      | 0.0004   |
|    n_updates          | 299      |
|    policy_loss        | 3.06     |
|    std                | 1.01     |
|    value_loss         | 0.0357   |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 395       |
|    iterations         | 400       |
|    time_elapsed       | 10        |
|    total_timesteps    | 4000      |
| train/                |           |
|    entropy_loss       | -21.4     |
|    explained_variance | -2.15e+04 |
|    learning_rate      | 0.0004    |
|    n_updates          | 399       |
|    policy_loss        | -2.82     |
|    std                | 1.01      |
|    value_loss         | 0.041     |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 500      |
|    time_elapsed       | 12       |
|    total_timesteps    | 5000     |
| train/                |          |
|    entropy_loss       | -21.4    |
|    explained_variance | -296     |
|    learning_rate      | 0.0004   |
|    n_updates          | 499      |
|    policy_loss        | -2.12    |
|    std                | 1.01     |
|    value_loss         | 0.025    |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 398       |
|    iterations         | 600       |
|    time_elapsed       | 15        |
|    total_timesteps    | 6000      |
| train/                |           |
|    entropy_loss       | -21.5     |
|    explained_variance | -2.76e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 599       |
|    policy_loss        | 0.0197    |
|    std                | 1.01      |
|    value_loss         | 0.0049    |
-------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 396       |
|    iterations         | 700       |
|    time_elapsed       | 17        |
|    total_timesteps    | 7000      |
| train/                |           |
|    entropy_loss       | -21.5     |
|    explained_variance | -2.43e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 699       |
|    policy_loss        | -2.85     |
|    std                | 1.02      |
|    value_loss         | 0.0267    |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 393      |
|    iterations         | 800      |
|    time_elapsed       | 20       |
|    total_timesteps    | 8000     |
| train/                |          |
|    entropy_loss       | -21.6    |
|    explained_variance | -259     |
|    learning_rate      | 0.0004   |
|    n_updates          | 799      |
|    policy_loss        | 2.75     |
|    std                | 1.02     |
|    value_loss         | 0.0234   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 391      |
|    iterations         | 900      |
|    time_elapsed       | 22       |
|    total_timesteps    | 9000     |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -831     |
|    learning_rate      | 0.0004   |
|    n_updates          | 899      |
|    policy_loss        | -5.63    |
|    std                | 1.03     |
|    value_loss         | 0.0843   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 394      |
|    iterations         | 1000     |
|    time_elapsed       | 25       |
|    total_timesteps    | 10000    |
| train/                |          |
|    entropy_loss       | -21.7    |
|    explained_variance | -172     |
|    learning_rate      | 0.0004   |
|    n_updates          | 999      |
|    policy_loss        | -0.59    |
|    std                | 1.03     |
|    value_loss         | 0.00968  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 393      |
|    iterations         | 1100     |
|    time_elapsed       | 27       |
|    total_timesteps    | 11000    |
| train/                |          |
|    entropy_loss       | -21.8    |
|    explained_variance | -89.7    |
|    learning_rate      | 0.0004   |
|    n_updates          | 1099     |
|    policy_loss        | 5.39     |
|    std                | 1.04     |
|    value_loss         | 0.062    |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 394      |
|    iterations         | 1200     |
|    time_elapsed       | 30       |
|    total_timesteps    | 12000    |
| train/                |          |
|    entropy_loss       | -21.9    |
|    explained_variance | -36.8    |
|    learning_rate      | 0.0004   |
|    n_updates          | 1199     |
|    policy_loss        | -2.63    |
|    std                | 1.04     |
|    value_loss         | 0.0185   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 393      |
|    iterations         | 1300     |
|    time_elapsed       | 33       |
|    total_timesteps    | 13000    |
| train/                |          |
|    entropy_loss       | -21.9    |
|    explained_variance | -39.1    |
|    learning_rate      | 0.0004   |
|    n_updates          | 1299     |
|    policy_loss        | -1.12    |
|    std                | 1.05     |
|    value_loss         | 0.00668  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 391      |
|    iterations         | 1400     |
|    time_elapsed       | 35       |
|    total_timesteps    | 14000    |
| train/                |          |
|    entropy_loss       | -22      |
|    explained_variance | -109     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1399     |
|    policy_loss        | 4.42     |
|    std                | 1.05     |
|    value_loss         | 0.0458   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 391      |
|    iterations         | 1500     |
|    time_elapsed       | 38       |
|    total_timesteps    | 15000    |
| train/                |          |
|    entropy_loss       | -22.1    |
|    explained_variance | -109     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1499     |
|    policy_loss        | 4.74     |
|    std                | 1.06     |
|    value_loss         | 0.0464   |
------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 393      |
|    iterations         | 1600     |
|    time_elapsed       | 40       |
|    total_timesteps    | 16000    |
| train/                |          |
|    entropy_loss       | -22.2    |
|    explained_variance | -242     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1599     |
|    policy_loss        | 2.27     |
|    std                | 1.06     |
|    value_loss         | 0.0134   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 394      |
|    iterations         | 1700     |
|    time_elapsed       | 43       |
|    total_timesteps    | 17000    |
| train/                |          |
|    entropy_loss       | -22.3    |
|    explained_variance | -578     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1699     |
|    policy_loss        | 1.28     |
|    std                | 1.07     |
|    value_loss         | 0.0136   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 395      |
|    iterations         | 1800     |
|    time_elapsed       | 45       |
|    total_timesteps    | 18000    |
| train/                |          |
|    entropy_loss       | -22.4    |
|    explained_variance | -176     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1799     |
|    policy_loss        | 4.05     |
|    std                | 1.07     |
|    value_loss         | 0.0422   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 395      |
|    iterations         | 1900     |
|    time_elapsed       | 47       |
|    total_timesteps    | 19000    |
| train/                |          |
|    entropy_loss       | -22.4    |
|    explained_variance | -134     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1899     |
|    policy_loss        | -2.99    |
|    std                | 1.08     |
|    value_loss         | 0.0225   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 395      |
|    iterations         | 2000     |
|    time_elapsed       | 50       |
|    total_timesteps    | 20000    |
| train/                |          |
|    entropy_loss       | -22.5    |
|    explained_variance | -848     |
|    learning_rate      | 0.0004   |
|    n_updates          | 1999     |
|    policy_loss        | 2.31     |
|    std                | 1.09     |
|    value_loss         | 0.0138   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 394      |
|    iterations         | 2100     |
|    time_elapsed       | 53       |
|    total_timesteps    | 21000    |
| train/                |          |
|    entropy_loss       | -22.6    |
|    explained_variance | -594     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2099     |
|    policy_loss        | 2.49     |
|    std                | 1.09     |
|    value_loss         | 0.0234   |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 395      |
|    iterations         | 2200     |
|    time_elapsed       | 55       |
|    total_timesteps    | 22000    |
| train/                |          |
|    entropy_loss       | -22.7    |
|    explained_variance | -52      |
|    learning_rate      | 0.0004   |
|    n_updates          | 2199     |
|    policy_loss        | -0.392   |
|    std                | 1.1      |
|    value_loss         | 0.00244  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 2300     |
|    time_elapsed       | 58       |
|    total_timesteps    | 23000    |
| train/                |          |
|    entropy_loss       | -22.9    |
|    explained_variance | -21.7    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2299     |
|    policy_loss        | -1.81    |
|    std                | 1.11     |
|    value_loss         | 0.00812  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 2400     |
|    time_elapsed       | 60       |
|    total_timesteps    | 24000    |
| train/                |          |
|    entropy_loss       | -23      |
|    explained_variance | -169     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2399     |
|    policy_loss        | -0.466   |
|    std                | 1.12     |
|    value_loss         | 0.00283  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 2500     |
|    time_elapsed       | 62       |
|    total_timesteps    | 25000    |
| train/                |          |
|    entropy_loss       | -23.1    |
|    explained_variance | -118     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2499     |
|    policy_loss        | 0.209    |
|    std                | 1.13     |
|    value_loss         | 0.00182  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 2600     |
|    time_elapsed       | 65       |
|    total_timesteps    | 26000    |
| train/                |          |
|    entropy_loss       | -23.2    |
|    explained_variance | -15.8    |
|    learning_rate      | 0.0004   |
|    n_updates          | 2599     |
|    policy_loss        | -0.791   |
|    std                | 1.14     |
|    value_loss         | 0.00161  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 2700     |
|    time_elapsed       | 68       |
|    total_timesteps    | 27000    |
| train/                |          |
|    entropy_loss       | -23.3    |
|    explained_variance | -443     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2699     |
|    policy_loss        | 0.369    |
|    std                | 1.14     |
|    value_loss         | 0.00668  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 2800     |
|    time_elapsed       | 70       |
|    total_timesteps    | 28000    |
| train/                |          |
|    entropy_loss       | -23.4    |
|    explained_variance | -117     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2799     |
|    policy_loss        | -0.315   |
|    std                | 1.15     |
|    value_loss         | 0.00155  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 2900     |
|    time_elapsed       | 73       |
|    total_timesteps    | 29000    |
| train/                |          |
|    entropy_loss       | -23.5    |
|    explained_variance | -423     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2899     |
|    policy_loss        | -0.45    |
|    std                | 1.16     |
|    value_loss         | 0.00161  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 3000     |
|    time_elapsed       | 75       |
|    total_timesteps    | 30000    |
| train/                |          |
|    entropy_loss       | -23.6    |
|    explained_variance | -800     |
|    learning_rate      | 0.0004   |
|    n_updates          | 2999     |
|    policy_loss        | -0.237   |
|    std                | 1.17     |
|    value_loss         | 0.003    |
------------------------------------

------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 3100     |
|    time_elapsed       | 77       |
|    total_timesteps    | 31000    |
| train/                |          |
|    entropy_loss       | -23.7    |
|    explained_variance | -233     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3099     |
|    policy_loss        | 0.17     |
|    std                | 1.18     |
|    value_loss         | 0.00561  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 3200     |
|    time_elapsed       | 80       |
|    total_timesteps    | 32000    |
| train/                |          |
|    entropy_loss       | -23.8    |
|    explained_variance | -91.2    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3199     |
|    policy_loss        | -0.683   |
|    std                | 1.19     |
|    value_loss         | 0.00283  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 396       |
|    iterations         | 3300      |
|    time_elapsed       | 83        |
|    total_timesteps    | 33000     |
| train/                |           |
|    entropy_loss       | -24       |
|    explained_variance | -1.32e+03 |
|    learning_rate      | 0.0004    |
|    n_updates          | 3299      |
|    policy_loss        | -0.638    |
|    std                | 1.2       |
|    value_loss         | 0.00398   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 3400     |
|    time_elapsed       | 85       |
|    total_timesteps    | 34000    |
| train/                |          |
|    entropy_loss       | -24.1    |
|    explained_variance | -173     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3399     |
|    policy_loss        | -1.43    |
|    std                | 1.21     |
|    value_loss         | 0.00456  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 395      |
|    iterations         | 3500     |
|    time_elapsed       | 88       |
|    total_timesteps    | 35000    |
| train/                |          |
|    entropy_loss       | -24.3    |
|    explained_variance | -648     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3499     |
|    policy_loss        | -0.0781  |
|    std                | 1.22     |
|    value_loss         | 0.000646 |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 3600     |
|    time_elapsed       | 90       |
|    total_timesteps    | 36000    |
| train/                |          |
|    entropy_loss       | -24.4    |
|    explained_variance | -39.2    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3599     |
|    policy_loss        | -0.341   |
|    std                | 1.23     |
|    value_loss         | 0.00243  |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 396       |
|    iterations         | 3700      |
|    time_elapsed       | 93        |
|    total_timesteps    | 37000     |
| train/                |           |
|    entropy_loss       | -24.5     |
|    explained_variance | -1.19e+04 |
|    learning_rate      | 0.0004    |
|    n_updates          | 3699      |
|    policy_loss        | -0.289    |
|    std                | 1.24      |
|    value_loss         | 0.00194   |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 397      |
|    iterations         | 3800     |
|    time_elapsed       | 95       |
|    total_timesteps    | 38000    |
| train/                |          |
|    entropy_loss       | -24.6    |
|    explained_variance | -105     |
|    learning_rate      | 0.0004   |
|    n_updates          | 3799     |
|    policy_loss        | 0.343    |
|    std                | 1.25     |
|    value_loss         | 0.00332  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 3900     |
|    time_elapsed       | 98       |
|    total_timesteps    | 39000    |
| train/                |          |
|    entropy_loss       | -24.8    |
|    explained_variance | -51.1    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3899     |
|    policy_loss        | -0.108   |
|    std                | 1.26     |
|    value_loss         | 0.00133  |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 396      |
|    iterations         | 4000     |
|    time_elapsed       | 100      |
|    total_timesteps    | 40000    |
| train/                |          |
|    entropy_loss       | -24.9    |
|    explained_variance | -79.4    |
|    learning_rate      | 0.0004   |
|    n_updates          | 3999     |
|    policy_loss        | -0.275   |
|    std                | 1.28     |
|    value_loss         | 0.0025   |
------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A9_Fixed_fusion_a2c_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A9_Fixed_fusion_a2c_seed1_actions.csv
{'CR': 0.03879238438795629, 'AR': 0.04042735828838673, 'Vol': 0.19675877619964618, 'SR': 0.2054666077378226, 'MDD': -0.11359020096701478, 'Calmar': 0.3559053328915788, 'Sortino': 0.2525014845718921, 'Omega': 1.0676860062647002, 'Turnover': 0.6588105356053215, 'FinalAccountValue': 1038792.3843879548, 'variant': 'A9_Fixed_fusion', 'agent': 'a2c', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV'}

========== A9_Fixed_fusion | PPO | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV
[banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'n_steps': 2048, 'ent_coef': 0.005, 'learning_rate': 0.001, 'batch_size': 128, 'seed': 1}
Using cpu device
Logging to tensorboard_log/ppo\A9_Fixed_fusion_ppo_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

-----------------------------
| time/              |      |
|    fps             | 466  |
|    iterations      | 1    |
|    time_elapsed    | 4    |
|    total_timesteps | 2048 |
-----------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 431        |
|    iterations           | 2          |
|    time_elapsed         | 9          |
|    total_timesteps      | 4096       |
| train/                  |            |
|    approx_kl            | 0.04652728 |
|    clip_fraction        | 0.417      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | -50.8      |
|    learning_rate        | 0.001      |
|    loss                 | -0.197     |
|    n_updates            | 10         |
|    policy_gradient_loss | -0.0746    |
|    std                  | 0.997      |
|    value_loss           | 0.0368     |
----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 416       |
|    iterations           | 3         |
|    time_elapsed         | 14        |
|    total_timesteps      | 6144      |
| train/                  |           |
|    approx_kl            | 0.0563858 |
|    clip_fraction        | 0.443     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.2     |
|    explained_variance   | -0.904    |
|    learning_rate        | 0.001     |
|    loss                 | -0.201    |
|    n_updates            | 20        |
|    policy_gradient_loss | -0.0702   |
|    std                  | 0.995     |
|    value_loss           | 0.00267   |
---------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 390         |
|    iterations           | 4           |
|    time_elapsed         | 20          |
|    total_timesteps      | 8192        |
| train/                  |             |
|    approx_kl            | 0.061484218 |
|    clip_fraction        | 0.463       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.2       |
|    explained_variance   | 0.45        |
|    learning_rate        | 0.001       |
|    loss                 | -0.196      |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.0637     |
|    std                  | 0.996       |
|    value_loss           | 0.00105     |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 388        |
|    iterations           | 5          |
|    time_elapsed         | 26         |
|    total_timesteps      | 10240      |
| train/                  |            |
|    approx_kl            | 0.06831105 |
|    clip_fraction        | 0.479      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.2      |
|    explained_variance   | 0.685      |
|    learning_rate        | 0.001      |
|    loss                 | -0.176     |
|    n_updates            | 40         |
|    policy_gradient_loss | -0.0634    |
|    std                  | 0.998      |
|    value_loss           | 0.000581   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 388        |
|    iterations           | 6          |
|    time_elapsed         | 31         |
|    total_timesteps      | 12288      |
| train/                  |            |
|    approx_kl            | 0.08231043 |
|    clip_fraction        | 0.513      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.78       |
|    learning_rate        | 0.001      |
|    loss                 | -0.196     |
|    n_updates            | 50         |
|    policy_gradient_loss | -0.0577    |
|    std                  | 1          |
|    value_loss           | 0.000313   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 383        |
|    iterations           | 7          |
|    time_elapsed         | 37         |
|    total_timesteps      | 14336      |
| train/                  |            |
|    approx_kl            | 0.07935436 |
|    clip_fraction        | 0.5        |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.872      |
|    learning_rate        | 0.001      |
|    loss                 | -0.195     |
|    n_updates            | 60         |
|    policy_gradient_loss | -0.0538    |
|    std                  | 1          |
|    value_loss           | 0.000232   |
----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 384       |
|    iterations           | 8         |
|    time_elapsed         | 42        |
|    total_timesteps      | 16384     |
| train/                  |           |
|    approx_kl            | 0.0893839 |
|    clip_fraction        | 0.527     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.3     |
|    explained_variance   | 0.832     |
|    learning_rate        | 0.001     |
|    loss                 | -0.187    |
|    n_updates            | 70        |
|    policy_gradient_loss | -0.0564   |
|    std                  | 1         |
|    value_loss           | 0.000192  |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 385        |
|    iterations           | 9          |
|    time_elapsed         | 47         |
|    total_timesteps      | 18432      |
| train/                  |            |
|    approx_kl            | 0.08768507 |
|    clip_fraction        | 0.512      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.881      |
|    learning_rate        | 0.001      |
|    loss                 | -0.172     |
|    n_updates            | 80         |
|    policy_gradient_loss | -0.056     |
|    std                  | 1.01       |
|    value_loss           | 0.000132   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 381         |
|    iterations           | 10          |
|    time_elapsed         | 53          |
|    total_timesteps      | 20480       |
| train/                  |             |
|    approx_kl            | 0.092050105 |
|    clip_fraction        | 0.529       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | 0.874       |
|    learning_rate        | 0.001       |
|    loss                 | -0.192      |
|    n_updates            | 90          |
|    policy_gradient_loss | -0.0542     |
|    std                  | 1           |
|    value_loss           | 0.000145    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 380        |
|    iterations           | 11         |
|    time_elapsed         | 59         |
|    total_timesteps      | 22528      |
| train/                  |            |
|    approx_kl            | 0.09662326 |
|    clip_fraction        | 0.519      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.3      |
|    explained_variance   | 0.817      |
|    learning_rate        | 0.001      |
|    loss                 | -0.185     |
|    n_updates            | 100        |
|    policy_gradient_loss | -0.0553    |
|    std                  | 1          |
|    value_loss           | 0.000143   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 376         |
|    iterations           | 12          |
|    time_elapsed         | 65          |
|    total_timesteps      | 24576       |
| train/                  |             |
|    approx_kl            | 0.100189686 |
|    clip_fraction        | 0.531       |
|    clip_range           | 0.2         |
|    entropy_loss         | -21.3       |
|    explained_variance   | 0.862       |
|    learning_rate        | 0.001       |
|    loss                 | -0.193      |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.0565     |
|    std                  | 1.01        |
|    value_loss           | 7.64e-05    |
-----------------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 373        |
|    iterations           | 13         |
|    time_elapsed         | 71         |
|    total_timesteps      | 26624      |
| train/                  |            |
|    approx_kl            | 0.11745536 |
|    clip_fraction        | 0.551      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.727      |
|    learning_rate        | 0.001      |
|    loss                 | -0.187     |
|    n_updates            | 120        |
|    policy_gradient_loss | -0.0489    |
|    std                  | 1.01       |
|    value_loss           | 0.000127   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 372        |
|    iterations           | 14         |
|    time_elapsed         | 76         |
|    total_timesteps      | 28672      |
| train/                  |            |
|    approx_kl            | 0.11427395 |
|    clip_fraction        | 0.556      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.4      |
|    explained_variance   | 0.352      |
|    learning_rate        | 0.001      |
|    loss                 | -0.182     |
|    n_updates            | 130        |
|    policy_gradient_loss | -0.0461    |
|    std                  | 1.01       |
|    value_loss           | 0.000145   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 371        |
|    iterations           | 15         |
|    time_elapsed         | 82         |
|    total_timesteps      | 30720      |
| train/                  |            |
|    approx_kl            | 0.11885722 |
|    clip_fraction        | 0.553      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.565      |
|    learning_rate        | 0.001      |
|    loss                 | -0.172     |
|    n_updates            | 140        |
|    policy_gradient_loss | -0.0515    |
|    std                  | 1.02       |
|    value_loss           | 9.57e-05   |
----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 370       |
|    iterations           | 16        |
|    time_elapsed         | 88        |
|    total_timesteps      | 32768     |
| train/                  |           |
|    approx_kl            | 0.1222974 |
|    clip_fraction        | 0.549     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.5     |
|    explained_variance   | 0.835     |
|    learning_rate        | 0.001     |
|    loss                 | -0.187    |
|    n_updates            | 150       |
|    policy_gradient_loss | -0.0531   |
|    std                  | 1.01      |
|    value_loss           | 3.99e-05  |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 366        |
|    iterations           | 17         |
|    time_elapsed         | 95         |
|    total_timesteps      | 34816      |
| train/                  |            |
|    approx_kl            | 0.12391141 |
|    clip_fraction        | 0.566      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.5      |
|    explained_variance   | 0.885      |
|    learning_rate        | 0.001      |
|    loss                 | -0.206     |
|    n_updates            | 160        |
|    policy_gradient_loss | -0.0519    |
|    std                  | 1.02       |
|    value_loss           | 4.93e-05   |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 364        |
|    iterations           | 18         |
|    time_elapsed         | 101        |
|    total_timesteps      | 36864      |
| train/                  |            |
|    approx_kl            | 0.11837921 |
|    clip_fraction        | 0.568      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.6      |
|    explained_variance   | 0.88       |
|    learning_rate        | 0.001      |
|    loss                 | -0.187     |
|    n_updates            | 170        |
|    policy_gradient_loss | -0.0547    |
|    std                  | 1.02       |
|    value_loss           | 8.21e-05   |
----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 365       |
|    iterations           | 19        |
|    time_elapsed         | 106       |
|    total_timesteps      | 38912     |
| train/                  |           |
|    approx_kl            | 0.1285129 |
|    clip_fraction        | 0.564     |
|    clip_range           | 0.2       |
|    entropy_loss         | -21.7     |
|    explained_variance   | 0.678     |
|    learning_rate        | 0.001     |
|    loss                 | -0.184    |
|    n_updates            | 180       |
|    policy_gradient_loss | -0.0545   |
|    std                  | 1.03      |
|    value_loss           | 8.72e-05  |
---------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 364        |
|    iterations           | 20         |
|    time_elapsed         | 112        |
|    total_timesteps      | 40960      |
| train/                  |            |
|    approx_kl            | 0.12679191 |
|    clip_fraction        | 0.576      |
|    clip_range           | 0.2        |
|    entropy_loss         | -21.7      |
|    explained_variance   | 0.681      |
|    learning_rate        | 0.001      |
|    loss                 | -0.189     |
|    n_updates            | 190        |
|    policy_gradient_loss | -0.0563    |
|    std                  | 1.03       |
|    value_loss           | 0.000104   |
----------------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A9_Fixed_fusion_ppo_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A9_Fixed_fusion_ppo_seed1_actions.csv
{'CR': -0.04608995437051988, 'AR': -0.0479481053666857, 'Vol': 0.18420379314188706, 'SR': -0.2602992291790246, 'MDD': -0.12261697793369264, 'Calmar': -0.391039692664865, 'Sortino': -0.34493353627955703, 'Omega': 0.9644768031505354, 'Turnover': 0.7446492369113284, 'FinalAccountValue': 953910.0456294806, 'variant': 'A9_Fixed_fusion', 'agent': 'ppo', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV'}

========== A9_Fixed_fusion | SAC | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV
[banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 128, 'buffer_size': 1000000, 'learning_rate': 0.0001, 'learning_starts': 100, 'ent_coef': 'auto_0.1', 'seed': 1}
Using cpu device
Logging to tensorboard_log/sac\A9_Fixed_fusion_sac_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 14       |
|    time_elapsed    | 200      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | -9.78    |
|    critic_loss     | 0.0157   |
|    ent_coef        | 0.0753   |
|    ent_coef_loss   | -64.8    |
|    learning_rate   | 0.0001   |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 13       |
|    time_elapsed    | 414      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | -16.5    |
|    critic_loss     | 0.0162   |
|    ent_coef        | 0.0564   |
|    ent_coef_loss   | -72.4    |
|    learning_rate   | 0.0001   |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 13       |
|    time_elapsed    | 636      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | -20.3    |
|    critic_loss     | 0.0213   |
|    ent_coef        | 0.0422   |
|    ent_coef_loss   | -80      |
|    learning_rate   | 0.0001   |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 13       |
|    time_elapsed    | 867      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | -21.8    |
|    critic_loss     | 0.012    |
|    ent_coef        | 0.0316   |
|    ent_coef_loss   | -87.3    |
|    learning_rate   | 0.0001   |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 13       |
|    time_elapsed    | 1100     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | -21.8    |
|    critic_loss     | 0.0439   |
|    ent_coef        | 0.0237   |
|    ent_coef_loss   | -94.4    |
|    learning_rate   | 0.0001   |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 12       |
|    time_elapsed    | 1339     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | -21.1    |
|    critic_loss     | 0.0106   |
|    ent_coef        | 0.0178   |
|    ent_coef_loss   | -101     |
|    learning_rate   | 0.0001   |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 12       |
|    time_elapsed    | 1581     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | -19.7    |
|    critic_loss     | 0.0279   |
|    ent_coef        | 0.0133   |
|    ent_coef_loss   | -108     |
|    learning_rate   | 0.0001   |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1818     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | -18.4    |
|    critic_loss     | 0.0223   |
|    ent_coef        | 0.00998  |
|    ent_coef_loss   | -116     |
|    learning_rate   | 0.0001   |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2057     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | -15.5    |
|    critic_loss     | 0.00525  |
|    ent_coef        | 0.00748  |
|    ent_coef_loss   | -123     |
|    learning_rate   | 0.0001   |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 12       |
|    time_elapsed    | 2292     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | -15.1    |
|    critic_loss     | 0.00437  |
|    ent_coef        | 0.00561  |
|    ent_coef_loss   | -129     |
|    learning_rate   | 0.0001   |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 12       |
|    time_elapsed    | 2544     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -13      |
|    critic_loss     | 0.00563  |
|    ent_coef        | 0.00421  |
|    ent_coef_loss   | -133     |
|    learning_rate   | 0.0001   |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 12       |
|    time_elapsed    | 2789     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -11.3    |
|    critic_loss     | 0.00341  |
|    ent_coef        | 0.00316  |
|    ent_coef_loss   | -141     |
|    learning_rate   | 0.0001   |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 12       |
|    time_elapsed    | 3023     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -9.79    |
|    critic_loss     | 0.00598  |
|    ent_coef        | 0.00237  |
|    ent_coef_loss   | -147     |
|    learning_rate   | 0.0001   |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 12       |
|    time_elapsed    | 3251     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -8.93    |
|    critic_loss     | 0.00903  |
|    ent_coef        | 0.00178  |
|    ent_coef_loss   | -146     |
|    learning_rate   | 0.0001   |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 12       |
|    time_elapsed    | 3484     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -7.29    |
|    critic_loss     | 0.00578  |
|    ent_coef        | 0.00134  |
|    ent_coef_loss   | -155     |
|    learning_rate   | 0.0001   |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 12       |
|    time_elapsed    | 3723     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -6.5     |
|    critic_loss     | 0.0115   |
|    ent_coef        | 0.001    |
|    ent_coef_loss   | -155     |
|    learning_rate   | 0.0001   |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 12       |
|    time_elapsed    | 3961     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -5.42    |
|    critic_loss     | 0.00292  |
|    ent_coef        | 0.000754 |
|    ent_coef_loss   | -159     |
|    learning_rate   | 0.0001   |
|    n_updates       | 48927    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 72       |
|    fps             | 12       |
|    time_elapsed    | 4195     |
|    total_timesteps | 51912    |
| train/             |          |
|    actor_loss      | -4.56    |
|    critic_loss     | 0.00223  |
|    ent_coef        | 0.000568 |
|    ent_coef_loss   | -156     |
|    learning_rate   | 0.0001   |
|    n_updates       | 51811    |
---------------------------------

---------------------------------
| time/              |          |
|    episodes        | 76       |
|    fps             | 12       |
|    time_elapsed    | 4425     |
|    total_timesteps | 54796    |
| train/             |          |
|    actor_loss      | -3.7     |
|    critic_loss     | 0.00639  |
|    ent_coef        | 0.000428 |
|    ent_coef_loss   | -145     |
|    learning_rate   | 0.0001   |
|    n_updates       | 54695    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 80       |
|    fps             | 12       |
|    time_elapsed    | 4657     |
|    total_timesteps | 57680    |
| train/             |          |
|    actor_loss      | -3.17    |
|    critic_loss     | 0.00186  |
|    ent_coef        | 0.000323 |
|    ent_coef_loss   | -149     |
|    learning_rate   | 0.0001   |
|    n_updates       | 57579    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A9_Fixed_fusion_sac_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A9_Fixed_fusion_sac_seed1_actions.csv
{'CR': -0.04627463283973299, 'AR': -0.048140039803555634, 'Vol': 0.19570960109794225, 'SR': -0.24597689399746978, 'MDD': -0.18985586973389612, 'Calmar': -0.25356097691911866, 'Sortino': -0.30409862513919367, 'Omega': 0.9675569538112481, 'Turnover': 0.6874024070727424, 'FinalAccountValue': 953725.3671602667, 'variant': 'A9_Fixed_fusion', 'agent': 'sac', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV'}

========== A9_Fixed_fusion | TD3 | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV
[banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'batch_size': 100, 'buffer_size': 1000000, 'learning_rate': 0.001, 'seed': 1}
Using cpu device
Logging to tensorboard_log/td3\A9_Fixed_fusion_td3_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 16       |
|    time_elapsed    | 172      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 1.03     |
|    critic_loss     | 0.00936  |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 15       |
|    time_elapsed    | 369      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.969    |
|    critic_loss     | 0.000742 |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 15       |
|    time_elapsed    | 573      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.916    |
|    critic_loss     | 0.00628  |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 14       |
|    time_elapsed    | 788      |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.874    |
|    critic_loss     | 0.00124  |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 14       |
|    time_elapsed    | 1011     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.81     |
|    critic_loss     | 0.000558 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 13       |
|    time_elapsed    | 1270     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.679    |
|    critic_loss     | 0.00092  |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 13       |
|    time_elapsed    | 1544     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.684    |
|    critic_loss     | 0.000281 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 12       |
|    time_elapsed    | 1824     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.623    |
|    critic_loss     | 0.000501 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 12       |
|    time_elapsed    | 2110     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.583    |
|    critic_loss     | 7.54e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 11       |
|    time_elapsed    | 2410     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | 0.516    |
|    critic_loss     | 0.000165 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A9_Fixed_fusion_td3_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A9_Fixed_fusion_td3_seed1_actions.csv
{'CR': 0.06408123947472388, 'AR': 0.06681581908873979, 'Vol': 0.19714183730935664, 'SR': 0.3389225747343109, 'MDD': -0.0974292332416189, 'Calmar': 0.6857882061233141, 'Sortino': 0.4973744239202338, 'Omega': 1.1023253819854766, 'Turnover': 0.48490877944707556, 'FinalAccountValue': 1064081.2394747215, 'variant': 'A9_Fixed_fusion', 'agent': 'td3', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV'}

========== A9_Fixed_fusion | DDPG | seed=1 ==========
CSV: D:\paper\onging\ablation\finrl_csv_bank_best_policy\banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV
[banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV] Missing technical indicators ['macd', 'rsi_30', 'cci_30', 'dx_30']; running FeatureEngineer...

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(
C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\finrl\preprocessing\preprocessors.py:82: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(

Successfully added technical indicators
train dates: 2019-01-15 -> 2021-12-31 | rows=10815
trade dates: 2022-01-04 -> 2022-12-30 | rows=3630
{'seed': 1}
Using cpu device
Logging to tensorboard_log/ddpg\A9_Fixed_fusion_ddpg_seed1_2

C:\Users\perfe\.conda\envs\finrl-meta\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 11       |
|    time_elapsed    | 255      |
|    total_timesteps | 2884     |
| train/             |          |
|    actor_loss      | 0.702    |
|    critic_loss     | 0.000317 |
|    learning_rate   | 0.001    |
|    n_updates       | 2783     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 10       |
|    time_elapsed    | 530      |
|    total_timesteps | 5768     |
| train/             |          |
|    actor_loss      | 0.539    |
|    critic_loss     | 0.000358 |
|    learning_rate   | 0.001    |
|    n_updates       | 5667     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 10       |
|    time_elapsed    | 804      |
|    total_timesteps | 8652     |
| train/             |          |
|    actor_loss      | 0.383    |
|    critic_loss     | 0.00011  |
|    learning_rate   | 0.001    |
|    n_updates       | 8551     |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 10       |
|    time_elapsed    | 1082     |
|    total_timesteps | 11536    |
| train/             |          |
|    actor_loss      | 0.292    |
|    critic_loss     | 0.000224 |
|    learning_rate   | 0.001    |
|    n_updates       | 11435    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 10       |
|    time_elapsed    | 1365     |
|    total_timesteps | 14420    |
| train/             |          |
|    actor_loss      | 0.22     |
|    critic_loss     | 3.25e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 14319    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 24       |
|    fps             | 10       |
|    time_elapsed    | 1666     |
|    total_timesteps | 17304    |
| train/             |          |
|    actor_loss      | 0.169    |
|    critic_loss     | 1.45e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 17203    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 28       |
|    fps             | 10       |
|    time_elapsed    | 1979     |
|    total_timesteps | 20188    |
| train/             |          |
|    actor_loss      | 0.105    |
|    critic_loss     | 5.99e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 20087    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 10       |
|    time_elapsed    | 2300     |
|    total_timesteps | 23072    |
| train/             |          |
|    actor_loss      | 0.0705   |
|    critic_loss     | 2.25e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 22971    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 36       |
|    fps             | 9        |
|    time_elapsed    | 2617     |
|    total_timesteps | 25956    |
| train/             |          |
|    actor_loss      | 0.0306   |
|    critic_loss     | 3.26e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 25855    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 9        |
|    time_elapsed    | 2948     |
|    total_timesteps | 28840    |
| train/             |          |
|    actor_loss      | -0.00718 |
|    critic_loss     | 6.77e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 28739    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 44       |
|    fps             | 9        |
|    time_elapsed    | 3284     |
|    total_timesteps | 31724    |
| train/             |          |
|    actor_loss      | -0.0287  |
|    critic_loss     | 1.5e-05  |
|    learning_rate   | 0.001    |
|    n_updates       | 31623    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 48       |
|    fps             | 9        |
|    time_elapsed    | 3636     |
|    total_timesteps | 34608    |
| train/             |          |
|    actor_loss      | -0.0641  |
|    critic_loss     | 1.71e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 34507    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 52       |
|    fps             | 9        |
|    time_elapsed    | 3933     |
|    total_timesteps | 37492    |
| train/             |          |
|    actor_loss      | -0.0866  |
|    critic_loss     | 7.86e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 37391    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 56       |
|    fps             | 9        |
|    time_elapsed    | 4284     |
|    total_timesteps | 40376    |
| train/             |          |
|    actor_loss      | -0.111   |
|    critic_loss     | 4.01e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 40275    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 60       |
|    fps             | 9        |
|    time_elapsed    | 4629     |
|    total_timesteps | 43260    |
| train/             |          |
|    actor_loss      | -0.142   |
|    critic_loss     | 1.84e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 43159    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 64       |
|    fps             | 9        |
|    time_elapsed    | 4974     |
|    total_timesteps | 46144    |
| train/             |          |
|    actor_loss      | -0.15    |
|    critic_loss     | 1.48e-05 |
|    learning_rate   | 0.001    |
|    n_updates       | 46043    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 68       |
|    fps             | 9        |
|    time_elapsed    | 5336     |
|    total_timesteps | 49028    |
| train/             |          |
|    actor_loss      | -0.161   |
|    critic_loss     | 7.44e-06 |
|    learning_rate   | 0.001    |
|    n_updates       | 48927    |
---------------------------------
hit end!
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A9_Fixed_fusion_ddpg_seed1_daily_return.csv
Saved: D:\paper\onging\ablation\rl_bank_best_policy\A9_Fixed_fusion_ddpg_seed1_actions.csv
{'CR': -0.1708684802360776, 'AR': -0.1772635149182027, 'Vol': 0.271115661508194, 'SR': -0.6538298596698561, 'MDD': -0.21990816759386345, 'Calmar': -0.8060797234488404, 'Sortino': -0.7594798439030482, 'Omega': 0.8681465858804415, 'Turnover': 0.8999202991472182, 'FinalAccountValue': 829131.5197639226, 'variant': 'A9_Fixed_fusion', 'agent': 'ddpg', 'seed': 1, 'csv_path': 'D:\\paper\\onging\\ablation\\finrl_csv_bank_best_policy\\banktrademergeGNNtr20241231_A9_Fixed_fusion.CSV'}
Saved raw metrics: D:\paper\onging\ablation\rl_bank_best_policy\rl_ablation_raw_results.csv

,CR,AR,Vol,SR,MDD,Calmar,Sortino,Omega,Turnover,FinalAccountValue,variant,agent,seed,csv_path
0,0.067378,0.070258,0.134722,0.521504,-0.081513,0.861924,0.834250,1.114313,NaN,1.067378e+06,A0_Full_MGT,EqualWeight_Rebalanced,-1,
1,0.032440,0.033803,0.134256,0.251783,-0.094951,0.356008,0.391118,1.061263,NaN,1.032440e+06,A0_Full_MGT,BuyHold_EqualInitial,-1,
2,-0.048033,-0.049968,0.141819,-0.352335,-0.144145,-0.346649,-0.494777,0.948212,0.737888,9.519666e+05,A0_Full_MGT,a2c,1,D:\paper\onging\ablation\finrl_csv_bank_best_p...
3,0.073087,0.076220,0.146034,0.521934,-0.117686,0.647655,0.792601,1.115833,0.758598,1.073087e+06,A0_Full_MGT,ppo,1,D:\paper\onging\ablation\finrl_csv_bank_best_p...
4,0.005385,0.005608,0.153320,0.036577,-0.100417,0.055847,0.057250,1.022594,0.656212,1.005385e+06,A0_Full_MGT,sac,1,D:\paper\onging\ablation\finrl_csv_bank_best_p...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,0.038792,0.040427,0.196759,0.205467,-0.113590,0.355905,0.252501,1.067686,0.658811,1.038792e+06,A9_Fixed_fusion,a2c,1,D:\paper\onging\ablation\finrl_csv_bank_best_p...
66,-0.046090,-0.047948,0.184204,-0.260299,-0.122617,-0.391040,-0.344934,0.964477,0.744649,9.539100e+05,A9_Fixed_fusion,ppo,1,D:\paper\onging\ablation\finrl_csv_bank_best_p...
67,-0.046275,-0.048140,0.195710,-0.245977,-0.189856,-0.253561,-0.304099,0.967557,0.687402,9.537254e+05,A9_Fixed_fusion,sac,1,D:\paper\onging\ablation\finrl_csv_bank_best_p...
68,0.064081,0.066816,0.197142,0.338923,-0.097429,0.685788,0.497374,1.102325,0.484909,1.064081e+06,A9_Fixed_fusion,td3,1,D:\paper\onging\ablation\finrl_csv_bank_best_p...
69,-0.170868,-0.177264,0.271116,-0.653830,-0.219908,-0.806080,-0.759480,0.868147,0.899920,8.291315e+05,A9_Fixed_fusion,ddpg,1,D:\paper\onging\ablation\finrl_csv_bank_best_p...

## 9. 汇总结果表

生成论文中可用的 `mean ± std` 汇总表。

In [12]:
# ===============================
# 9. Summary and paper tables
# ===============================

if len(raw_metrics_df) == 0:
    print("No results. Please check prediction files, generated FinRL CSVs, and date settings.")
else:
    metric_cols = ["CR", "AR", "Vol", "SR", "MDD", "Calmar", "Sortino", "Omega", "Turnover", "FinalAccountValue"]
    agent_order = ["BuyHold_EqualInitial", "EqualWeight_Rebalanced"] + AGENTS_FOR_ABLATION

    # mean/std summary for repeated seeds
    summary_df = raw_metrics_df.groupby(["variant", "agent"], sort=False)[metric_cols].agg(["mean", "std"])
    summary_path = RL_ABLATION_DIR / "rl_ablation_summary_mean_std.csv"
    summary_df.to_csv(summary_path)

    # Paper table: one row for each variant-agent, using mean across seeds.
    paper_table = raw_metrics_df.groupby(["variant", "agent"], sort=False)[metric_cols].mean(numeric_only=True).reset_index()
    paper_table["variant"] = pd.Categorical(paper_table["variant"], categories=ALL_VARIANTS, ordered=True)
    paper_table["agent"] = pd.Categorical(paper_table["agent"], categories=agent_order, ordered=True)
    paper_table = paper_table.sort_values(["variant", "agent"]).reset_index(drop=True)
    paper_table["variant"] = paper_table["variant"].astype(str)
    paper_table["agent"] = paper_table["agent"].astype(str)

    paper_path = RL_ABLATION_DIR / "rl_ablation_paper_table.csv"
    paper_table.to_csv(paper_path, index=False)

    # Best agent by variant: choose highest FinalAccountValue / CR.
    best_agent = (
        paper_table.sort_values(["variant", "FinalAccountValue"], ascending=[True, False])
        .groupby("variant", sort=False)
        .head(1)
        .reset_index(drop=True)
    )
    best_path = RL_ABLATION_DIR / "best_agent_by_variant.csv"
    best_agent.to_csv(best_path, index=False)

    # Pivots consistent with bank group outputs
    pivot_final = paper_table.pivot(index="variant", columns="agent", values="FinalAccountValue").reset_index()
    pivot_final_path = RL_ABLATION_DIR / "pivot_final_account_value_A0_A9_agents.csv"
    pivot_final.to_csv(pivot_final_path, index=False)

    pivot_sharpe = paper_table.pivot(index="variant", columns="agent", values="SR").reset_index()
    pivot_sharpe_path = RL_ABLATION_DIR / "pivot_sharpe_A0_A9_agents.csv"
    pivot_sharpe.to_csv(pivot_sharpe_path, index=False)

    # LaTeX table for paper draft
    latex_path = RL_ABLATION_DIR / "rl_ablation_paper_table.tex"
    paper_table.to_latex(latex_path, index=False, float_format="%.4f", escape=False)

    print("Saved summary:", summary_path)
    print("Saved paper table:", paper_path)
    print("Saved best-agent table:", best_path)
    print("Saved pivot final value:", pivot_final_path)
    print("Saved pivot Sharpe:", pivot_sharpe_path)
    print("Saved LaTeX table:", latex_path)

    display(paper_table)
    print("\nBest agent by variant:")
    display(best_agent)

Saved summary: D:\paper\onging\ablation\rl_bank_best_policy\rl_ablation_summary_mean_std.csv
Saved paper table: D:\paper\onging\ablation\rl_bank_best_policy\rl_ablation_paper_table.csv
Saved best-agent table: D:\paper\onging\ablation\rl_bank_best_policy\best_agent_by_variant.csv
Saved pivot final value: D:\paper\onging\ablation\rl_bank_best_policy\pivot_final_account_value_A0_A9_agents.csv
Saved pivot Sharpe: D:\paper\onging\ablation\rl_bank_best_policy\pivot_sharpe_A0_A9_agents.csv
Saved LaTeX table: D:\paper\onging\ablation\rl_bank_best_policy\rl_ablation_paper_table.tex

C:\Users\perfe\AppData\Local\Temp\ipykernel_23092\2625305587.py:48: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  paper_table.to_latex(latex_path, index=False, float_format="%.4f", escape=False)

,variant,agent,CR,AR,Vol,SR,MDD,Calmar,Sortino,Omega,Turnover,FinalAccountValue
0,A0_Full_MGT,BuyHold_EqualInitial,0.032440,0.033803,0.134256,0.251783,-0.094951,0.356008,0.391118,1.061263,NaN,1.032440e+06
1,A0_Full_MGT,EqualWeight_Rebalanced,0.067378,0.070258,0.134722,0.521504,-0.081513,0.861924,0.834250,1.114313,NaN,1.067378e+06
2,A0_Full_MGT,a2c,-0.048033,-0.049968,0.141819,-0.352335,-0.144145,-0.346649,-0.494777,0.948212,0.737888,9.519666e+05
3,A0_Full_MGT,ppo,0.073087,0.076220,0.146034,0.521934,-0.117686,0.647655,0.792601,1.115833,0.758598,1.073087e+06
4,A0_Full_MGT,sac,0.005385,0.005608,0.153320,0.036577,-0.100417,0.055847,0.057250,1.022594,0.656212,1.005385e+06
...,...,...,...,...,...,...,...,...,...,...,...,...
65,A9_Fixed_fusion,a2c,0.038792,0.040427,0.196759,0.205467,-0.113590,0.355905,0.252501,1.067686,0.658811,1.038792e+06
66,A9_Fixed_fusion,ppo,-0.046090,-0.047948,0.184204,-0.260299,-0.122617,-0.391040,-0.344934,0.964477,0.744649,9.539100e+05
67,A9_Fixed_fusion,sac,-0.046275,-0.048140,0.195710,-0.245977,-0.189856,-0.253561,-0.304099,0.967557,0.687402,9.537254e+05
68,A9_Fixed_fusion,td3,0.064081,0.066816,0.197142,0.338923,-0.097429,0.685788,0.497374,1.102325,0.484909,1.064081e+06
69,A9_Fixed_fusion,ddpg,-0.170868,-0.177264,0.271116,-0.653830,-0.219908,-0.806080,-0.759480,0.868147,0.899920,8.291315e+05

Best agent by variant:

,variant,agent,CR,AR,Vol,SR,MDD,Calmar,Sortino,Omega,Turnover,FinalAccountValue
0,A0_Full_MGT,td3,0.073762,0.076924,0.131190,0.586358,-0.068862,1.117085,0.920169,1.118439,0.772282,1.073762e+06
1,A1_Transformer_only,EqualWeight_Rebalanced,-0.018385,-0.019137,0.032308,-0.592338,-0.051036,-0.374974,-0.936791,0.907433,NaN,9.816151e+05
2,A2_MGNN_only,ddpg,0.162323,0.169570,0.236288,0.717643,-0.134713,1.258756,1.040124,1.161758,0.904941,1.162323e+06
3,A3_SH_only,sac,-0.043966,-0.045741,0.085888,-0.532564,-0.125635,-0.364076,-0.870317,0.920015,0.648576,9.560338e+05
4,A4_QA_only,ddpg,-0.005209,-0.005424,0.136941,-0.039605,-0.182551,-0.029709,-0.066442,1.005148,0.763120,9.947912e+05
5,A5_KD_only,EqualWeight_Rebalanced,-0.058042,-0.060367,0.054897,-1.099647,-0.097382,-0.619900,-1.543529,0.824704,NaN,9.419577e+05
6,A6_SH_QA,a2c,0.003696,0.003849,0.147845,0.026032,-0.082794,0.046485,0.035696,1.019267,0.689753,1.003696e+06
7,A7_SH_KD,EqualWeight_Rebalanced,-0.041240,-0.042907,0.043301,-0.990912,-0.074147,-0.578678,-1.505132,0.847008,NaN,9.587599e+05
8,A8_QA_KD,a2c,0.001158,0.001206,0.159070,0.007583,-0.180788,0.006672,0.011216,1.015509,0.758360,1.001158e+06
9,A9_Fixed_fusion,td3,0.064081,0.066816,0.197142,0.338923,-0.097429,0.685788,0.497374,1.102325,0.484909,1.064081e+06

In [13]:
# ===============================
# 9.1 Best-policy paper table for Bank sector
#     Same format as Healthcare innovation sector table
# ===============================

import math

AGENT_DISPLAY = {
    "a2c": "A2C",
    "ppo": "PPO",
    "sac": "SAC",
    "td3": "TD3",
    "ddpg": "DDPG",
    "BuyHold_EqualInitial": "Buy-and-Hold",
    "EqualWeight_Rebalanced": "Equal Weight",
}


def _fmt4(x):
    if pd.isna(x):
        return "--"
    return f"{float(x):.4f}"


def _fmt_money(x):
    if pd.isna(x):
        return "--"
    return f"{int(round(float(x))):,}"


def make_best_policy_table_for_paper(paper_table: pd.DataFrame):
    """Select best downstream RL policy for each A0--A9 variant by FinalAccountValue."""
    # Healthcare 表格只在五个 RL policies 中选择 best policy，不把 Buy-and-Hold / Equal Weight 纳入选择。
    rl_only = paper_table[paper_table["agent"].isin(AGENTS_FOR_ABLATION)].copy()
    if rl_only.empty:
        raise ValueError("没有找到 RL agent 结果。请确认 RUN_RL_AGENTS=True，并且五个 agent 已经运行完成。")

    best = (
        rl_only.sort_values(["variant", "FinalAccountValue"], ascending=[True, False])
        .groupby("variant", sort=False)
        .head(1)
        .reset_index(drop=True)
    )
    best["Method"] = best["variant"].map(DISPLAY_NAMES)
    best["Best policy"] = best["agent"].map(AGENT_DISPLAY).fillna(best["agent"].astype(str).str.upper())
    best = best[["Method", "Best policy", "CR", "AR", "SR", "MDD", "Calmar", "Sortino", "FinalAccountValue"]]
    best = best.rename(columns={"FinalAccountValue": "Final value"})

    # 保存 CSV
    out_csv = RL_ABLATION_DIR / "bank_forecast_to_policy_best_policy_table.csv"
    best.to_csv(out_csv, index=False)

    # 找每列最优值。MDD 越接近 0 越好，所以取最大值。
    metric_cols = ["CR", "AR", "SR", "MDD", "Calmar", "Sortino", "Final value"]
    best_values = {col: best[col].max() for col in metric_cols}

    def bold_if_best(col, x, text):
        try:
            if np.isclose(float(x), float(best_values[col]), rtol=1e-9, atol=1e-9):
                return r"\textbf{" + text + "}"
        except Exception:
            pass
        return text

    lines = []
    lines.append(r"\begin{table*}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{Forecast-to-policy ablation results on the banking sector.}")
    lines.append(r"\label{tab:bank_forecast_policy_ablation}")
    lines.append(r"\resizebox{\textwidth}{!}{")
    lines.append(r"\begin{tabular}{llccccccc}")
    lines.append(r"\toprule")
    lines.append(r"Method & Best policy & CR & AR & SR & MDD & Calmar & Sortino & Final value \\")
    lines.append(r"\midrule")

    for _, row in best.iterrows():
        vals = {
            "CR": _fmt4(row["CR"]),
            "AR": _fmt4(row["AR"]),
            "SR": _fmt4(row["SR"]),
            "MDD": _fmt4(row["MDD"]),
            "Calmar": _fmt4(row["Calmar"]),
            "Sortino": _fmt4(row["Sortino"]),
            "Final value": _fmt_money(row["Final value"]),
        }
        vals = {col: bold_if_best(col, row[col], vals[col]) for col in vals}
        lines.append(
            f"{row['Method']} & {row['Best policy']} & "
            f"{vals['CR']} & {vals['AR']} & {vals['SR']} & {vals['MDD']} & "
            f"{vals['Calmar']} & {vals['Sortino']} & {vals['Final value']} \\\\" 
        )

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"}")
    lines.append(r"\vspace{1mm}")
    lines.append(r"\parbox{\textwidth}{\footnotesize Note: For each ablation variant, the reported row corresponds to the best downstream allocation policy according to final account value. CR, AR, SR, MDD, Calmar, and Sortino denote cumulative return, annualized return, Sharpe ratio, maximum drawdown, Calmar ratio, and Sortino ratio, respectively. For MDD, a value closer to zero indicates a smaller drawdown.}")
    lines.append(r"\end{table*}")
    latex = "\n".join(lines)

    out_tex = RL_ABLATION_DIR / "bank_forecast_to_policy_best_policy_table.tex"
    out_tex.write_text(latex, encoding="utf-8")

    print("Saved Bank best-policy table CSV:", out_csv)
    print("Saved Bank best-policy table LaTeX:", out_tex)
    display(best)
    print(latex)
    return best, latex


if 'paper_table' in globals() and len(paper_table) > 0:
    bank_best_policy_table, bank_best_policy_latex = make_best_policy_table_for_paper(paper_table)
else:
    print("paper_table 不存在。请先运行上一单元生成 rl_ablation_paper_table.csv。")

Saved Bank best-policy table CSV: D:\paper\onging\ablation\rl_bank_best_policy\bank_forecast_to_policy_best_policy_table.csv
Saved Bank best-policy table LaTeX: D:\paper\onging\ablation\rl_bank_best_policy\bank_forecast_to_policy_best_policy_table.tex

,Method,Best policy,CR,AR,SR,MDD,Calmar,Sortino,Final value
0,A0 Full MGT,TD3,0.073762,0.076924,0.586358,-0.068862,1.117085,0.920169,1.073762e+06
1,A1 Transformer-only,PPO,-0.024704,-0.025712,-0.780336,-0.050015,-0.514090,-1.181324,9.752956e+05
2,A2 MGNN-only,DDPG,0.162323,0.169570,0.717643,-0.134713,1.258756,1.040124,1.162323e+06
3,A3 SH-only,SAC,-0.043966,-0.045741,-0.532564,-0.125635,-0.364076,-0.870317,9.560338e+05
4,A4 QA-only,DDPG,-0.005209,-0.005424,-0.039605,-0.182551,-0.029709,-0.066442,9.947912e+05
5,A5 KD-only,A2C,-0.068463,-0.071189,-1.143023,-0.115381,-0.616993,-1.662005,9.315366e+05
6,A6 SH+QA,A2C,0.003696,0.003849,0.026032,-0.082794,0.046485,0.035696,1.003696e+06
7,A7 SH+KD,SAC,-0.041253,-0.042920,-1.105269,-0.061138,-0.702018,-1.508072,9.587472e+05
8,A8 QA+KD,A2C,0.001158,0.001206,0.007583,-0.180788,0.006672,0.011216,1.001158e+06
9,A9 Fixed-fusion,TD3,0.064081,0.066816,0.338923,-0.097429,0.685788,0.497374,1.064081e+06

\begin{table*}[t]
\centering
\caption{Forecast-to-policy ablation results on the banking sector.}
\label{tab:bank_forecast_policy_ablation}
\resizebox{\textwidth}{!}{
\begin{tabular}{llccccccc}
\toprule
Method & Best policy & CR & AR & SR & MDD & Calmar & Sortino & Final value \\
\midrule
A0 Full MGT & TD3 & 0.0738 & 0.0769 & 0.5864 & -0.0689 & 1.1171 & 0.9202 & 1,073,762 \\
A1 Transformer-only & PPO & -0.0247 & -0.0257 & -0.7803 & \textbf{-0.0500} & -0.5141 & -1.1813 & 975,296 \\
A2 MGNN-only & DDPG & \textbf{0.1623} & \textbf{0.1696} & \textbf{0.7176} & -0.1347 & \textbf{1.2588} & \textbf{1.0401} & \textbf{1,162,323} \\
A3 SH-only & SAC & -0.0440 & -0.0457 & -0.5326 & -0.1256 & -0.3641 & -0.8703 & 956,034 \\
A4 QA-only & DDPG & -0.0052 & -0.0054 & -0.0396 & -0.1826 & -0.0297 & -0.0664 & 994,791 \\
A5 KD-only & A2C & -0.0685 & -0.0712 & -1.1430 & -0.1154 & -0.6170 & -1.6620 & 931,537 \\
A6 SH+QA & A2C & 0.0037 & 0.0038 & 0.0260 & -0.0828 & 0.0465 & 0.0357 & 1,003,696 \\
A7 SH+KD & SAC & -0.0413 & -0.0429 & -1.1053 & -0.0611 & -0.7020 & -1.5081 & 958,747 \\
A8 QA+KD & A2C & 0.0012 & 0.0012 & 0.0076 & -0.1808 & 0.0067 & 0.0112 & 1,001,158 \\
A9 Fixed-fusion & TD3 & 0.0641 & 0.0668 & 0.3389 & -0.0974 & 0.6858 & 0.4974 & 1,064,081 \\
\bottomrule
\end{tabular}
}
\vspace{1mm}
\parbox{\textwidth}{\footnotesize Note: For each ablation variant, the reported row corresponds to the best downstream allocation policy according to final account value. CR, AR, SR, MDD, Calmar, and Sortino denote cumulative return, annualized return, Sharpe ratio, maximum drawdown, Calmar ratio, and Sortino ratio, respectively. For MDD, a value closer to zero indicates a smaller drawdown.}
\end{table*}

## 10. 画累计收益曲线

生成用于论文的 SVG 图：

```text
D:/paper/onging/ablation/rl/rl_ablation_cumulative_return.svg
```

建议放在 `Ablation study on forecast-driven portfolio allocation` 小节。

In [14]:
# ===============================
# 10. Plot cumulative return curves
# ===============================

def plot_cumulative_return_curves(results_dir=RL_ABLATION_DIR):
    results_dir = Path(results_dir)
    files = sorted(results_dir.glob("*_daily_return.csv"))

    if not files:
        print("No daily_return files found.")
        return

    plt.figure(figsize=(10, 5))

    for file in files:
        df_ret = pd.read_csv(file)
        if "daily_return" not in df_ret.columns:
            continue

        label = file.stem.replace("_daily_return", "")
        curve = (1.0 + df_ret["daily_return"].astype(float)).cumprod() - 1.0
        plt.plot(curve.values, label=label, linewidth=1.2)

    plt.xlabel("Trading day")
    plt.ylabel("Cumulative return")
    plt.legend(fontsize=6, ncol=2)
    plt.tight_layout()

    out_path = results_dir / "rl_ablation_cumulative_return.svg"
    png_path = results_dir / "rl_ablation_cumulative_return.png"
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.savefig(png_path, dpi=300, bbox_inches="tight")
    plt.show()

    print("Saved:", out_path)
    print("Saved:", png_path)

plot_cumulative_return_curves()

Saved: D:\paper\onging\ablation\rl_bank_best_policy\rl_ablation_cumulative_return.svg
Saved: D:\paper\onging\ablation\rl_bank_best_policy\rl_ablation_cumulative_return.png

C:\Users\perfe\AppData\Local\Temp\ipykernel_23092\994057022.py:33: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

## 11. 可选：完整 RL agent 比较

如果你要做完整策略比较，可以把下面的 `RUN_FULL_AGENT_COMPARISON` 改成 `True`。

这部分只建议对 `A0_Full_MGT` 运行 PPO/A2C/SAC/TD3/DDPG，不建议所有消融版本都跑五个 agent，计算量太大。

In [15]:
# ===============================
# 11. Optional full-agent comparison
# ===============================

RUN_FULL_AGENT_COMPARISON = False

if RUN_FULL_AGENT_COMPARISON:
    full_agent_metrics = []
    variant_tag = "A0_Full_MGT"
    csv_path = RL_ABLATION_INPUTS[variant_tag]

    FULL_AGENTS = ["a2c", "ppo", "sac", "td3", "ddpg"]

    for agent_name in FULL_AGENTS:
        for seed in SEEDS:
            metrics = train_and_trade_one_agent(
                csv_path=csv_path,
                variant_tag=variant_tag,
                agent_name=agent_name,
                seed=seed,
            )
            full_agent_metrics.append(metrics)

    full_agent_df = pd.DataFrame(full_agent_metrics)
    full_agent_path = RL_ABLATION_DIR / "full_agent_comparison_raw_results.csv"
    full_agent_df.to_csv(full_agent_path, index=False)

    print("Saved:", full_agent_path)
    display(full_agent_df)
else:
    print("RUN_FULL_AGENT_COMPARISON = False; skip full PPO/A2C/SAC/TD3/DDPG comparison.")

RUN_FULL_AGENT_COMPARISON = False; skip full PPO/A2C/SAC/TD3/DDPG comparison.

## 12. 可选：从第一个预测消融结果生成 FinRL 长表 CSV 的辅助函数

如果第一个 notebook 输出的是 `A*_pred.csv` 预测矩阵，而不是 FinRL 长表 CSV，可以用下面函数把预测 close 合并回原始 OHLCV 长表中。

注意：

1. 预测矩阵必须已经反归一化到真实价格尺度；
2. 预测矩阵的列顺序必须与 `base_trade_csv` 中的 ticker 顺序一致，或者直接带有 ticker 列名；
3. 预测行数必须与指定日期范围内的交易日数量一致。

如果你的预测 CSV 仍然是 MinMaxScaler 后的 `[-1, 1]` 数值，必须先反归一化，否则不能用于回测。

In [16]:
# ===============================
# 12. Optional helper: merge predicted close into FinRL long table
# ===============================

def merge_predicted_close_to_finrl_csv(
    base_trade_csv,
    pred_matrix_csv,
    output_csv,
    start_date=TRADE_START,
    end_date=TRADE_END,
    tickers=None,
    pred_is_real_price=True,
):
    if not pred_is_real_price:
        raise ValueError("预测矩阵仍是归一化值，必须先反归一化到真实价格尺度。")

    base_trade_csv = Path(base_trade_csv)
    pred_matrix_csv = Path(pred_matrix_csv)
    output_csv = Path(output_csv)

    base = pd.read_csv(base_trade_csv)
    _check_required_columns(base, base_trade_csv)

    base["date"] = pd.to_datetime(base["date"]).dt.strftime("%Y-%m-%d")
    date_mask = (base["date"] >= start_date) & (base["date"] <= end_date)

    if tickers is None:
        tickers = sorted(base["tic"].unique().tolist())

    dates = sorted(base.loc[date_mask, "date"].unique().tolist())

    pred = pd.read_csv(pred_matrix_csv)

    # 如果预测 CSV 多了一列 unnamed index，则删除
    unnamed = [c for c in pred.columns if str(c).lower().startswith("unnamed")]
    if unnamed:
        pred = pred.drop(columns=unnamed)

    if pred.shape[1] == len(tickers):
        pred.columns = tickers
    else:
        missing = set(tickers) - set(pred.columns)
        if missing:
            raise ValueError(
                f"预测矩阵列数/列名与 ticker 不匹配。pred shape={pred.shape}, "
                f"num tickers={len(tickers)}, missing={missing}"
            )
        pred = pred[tickers]

    if len(pred) != len(dates):
        raise ValueError(
            f"预测矩阵行数 {len(pred)} 与日期数量 {len(dates)} 不一致。"
            f"请检查 start_date/end_date 或预测输出区间。"
        )

    pred = pred.copy()
    pred["date"] = dates
    pred_long = pred.melt(id_vars="date", var_name="tic", value_name="pred_close")

    merged = base.merge(pred_long, on=["date", "tic"], how="left")
    replace_mask = merged["pred_close"].notna()

    merged.loc[replace_mask, "close"] = merged.loc[replace_mask, "pred_close"]
    merged = merged.drop(columns=["pred_close"])

    output_csv.parent.mkdir(parents=True, exist_ok=True)
    merged.to_csv(output_csv, index=False)

    print("Saved merged FinRL CSV:", output_csv)
    print("Replaced close rows:", int(replace_mask.sum()))

    return merged

# 示例，不自动运行：
# merge_predicted_close_to_finrl_csv(
#     base_trade_csv=BASE_FULL_MGT_CSV,
#     pred_matrix_csv=ABLATION_ROOT / "A1_Transformer_only_seed1_pred_real_price.csv",
#     output_csv=GRAPH_DATA_DIR / "banktrademergeGNNtr20241231_A1_Transformer_only.CSV",
#     start_date=TRADE_START,
#     end_date=TRADE_END,
# )

## 13. 论文中放置位置

本 notebook 产生的结果建议替换原来的 Table 7 / Table 8，放在：

```latex
\subsection{Ablation study on forecast-driven portfolio allocation}
```

banking sector 对应表格可命名为：

```latex
Table X. Forecast-to-policy ablation results on the healthcare innovation sector.
```

核心输出文件位于：

```text
D:/paper/onging/ablation/rl/rl_ablation_paper_table.csv
D:/paper/onging/ablation/rl/best_agent_by_variant.csv
D:/paper/onging/ablation/rl/pivot_final_account_value_A0_A9_agents.csv
D:/paper/onging/ablation/rl/pivot_sharpe_A0_A9_agents.csv
D:/paper/onging/ablation/rl/rl_ablation_cumulative_return.svg
```

如果某个 A0--A9 版本被跳过，优先检查：

```text
D:/paper/onging/ablation/A*_seed*_pred_raw.csv
```

是否完整生成，且文件中是否包含 `date` 列。